/**
 * ウクライナの都市と路線(35件)。
 *
 * 地方区分は6つ。
 *   `ky`   キーウとその周辺(4)
 *   `pl`   ポリッシャ(北部。7。チェルニーヒウ・ジトームィル・チョルノービリ他)
 *   `west` 西部・カルパチア(9。リヴィウ・イヴァノ=フランキウシク・
 *          チェルニウツィー・ザカルパッチャ他)
 *   `cen`  中部(6。ヴィーンヌィツャ・チェルカースィ・ポルタヴァ他)
 *   `south`南部・黒海/ドナウ沿岸(5。オデーサ・ミコライウ・イズマイール他)
 *   `east` 東部(4。ハルキウ・ドニプロ・ザポリッジャ・スーミ)
 *
 * ## 都市を選ぶ物差し(team-lead との相談で確定)
 *
 * 「占領されているか」ではなく、**いま人が普通に暮らし、鉄道が普通に
 * 走っている町か**を基準にした。ヘルソン市は解放後もドニプロ川越しに
 * 連日砲撃を受けている土地のため、占領地ではないが外している。
 * 同じ理由でアスカニア・ノヴァ(実際には2022年からヘルソン州の
 * 占領地域にある)、ソレダール(ドネツク州、2023年に激戦地)も外した。
 *
 * ## 占領地域・戦災地に都市を置かないことについて
 *
 * 争いのある土地・戦地を遊びの止まりマスにしないという方針から、
 * 次の地域には都市を置かない: クリミア半島全域、ドネツク州・
 * ルハンシク州の(現に占領されている)東部、マリウポリ、メリトポリ、
 * ヘルソン州のドニプロ川左岸(ヘルソン市より南東)。国境線・海岸線
 * そのものは `geography.mjs` の通り、国際的に認められたウクライナの
 * 領土のまま描く(クリミアも陸地として輪郭に含める)。
 *
 * また、2022年以降の戦闘で市街の大半が破壊された町(バフムート・
 * マリウポリ・アウディーイウカなど)は、何事もなかったような観光案内に
 * ならないよう外している。ハルキウのように前線に近い大都市は、
 * 現在の戦況には立ち入らず、歴史・建築・大学都市としての性格を書いている。
 *
 * チョルノービリは項目に含めた。ウクライナ語表記(「チェルノブイリ」は
 * ロシア語形)を使い、1986年の事故を史実として落ち着いた調子で書き、
 * 「肝試しスポット」のような扱いにはしていない。
 *
 * 都市名はウクライナ語からの転写を使う(Kyiv であって Kiev ではない、
 * Odesa・Lviv・Kharkiv・Chornobyl。日本語も「キーウ」「オデーサ」
 * 「リヴィウ」「ハルキウ」「チョルノービリ」)。
 *
 * ## `mark`(21種。`bg` はほぼ同じキーを共有する)
 *
 * | キー | 描くもの | 受け持つ町 |
 * |---|---|---|
 * | `cathedral`      | 黄金のドームを持つ聖堂 | キーウ |
 * | `oldtown`        | 市場広場を囲む石造りの町並み | リヴィウ |
 * | `port`           | 起重機と船、海への大階段 | オデーサ・ミコライウ・イズマイール |
 * | `memorial`(bg=`zone`) | 新安全閉じ込め施設のアーチ | チョルノービリ |
 * | `constructivist` | 空中回廊で結ばれた無機質な塔 | ハルキウ |
 * | `fortress`       | 石垣と塔 | カムヤネツィ=ポジーリシキー・ビルホロド=ドニストロウシキー・ルーツィク・テルノーピリ |
 * | `hutsul`         | フツル地方の山と木造教会 | イヴァノ=フランキウシク・コロミヤ・ウージュホロド |
 * | `spa`            | 温泉水を汲む東屋 | トゥルスカヴェツィ |
 * | `canal`          | 高床の家と小舟 | ヴィルコヴェ |
 * | `onion`          | 正教会の小さな玉ねぎ屋根 | チェルニーヒウ・スーミ |
 * | `park`           | 貴族庭園の噴水と並木 | ビラ・ツェールクヴァ・ウマーニ |
 * | `folkmuseum`     | 移築された茅葺き民家 | ペレヤスラウ |
 * | `relic`          | 先史時代の環状土器住居 | トリピッリャ |
 * | `tunnel`         | 緑のトンネルと小さな貨物列車 | クレヴァニ |
 * | `planned`        | 各共和国様式の集合住宅 | スラウーティチ |
 * | `residence`      | 装飾的な府主教館 | チェルニウツィー |
 * | `cossack`        | 見張り塔と葦原 | チェルカースィ・ザポリッジャ |
 * | `theatre`        | 仮面と緞帳 | クロピヴニツィクィイ |
 * | `industry`       | 煙突と線路 | クレメンチューク・コロステーニ |
 * | `rocket`         | ロケットの尾翼 | ドニプロ |
 * | `fountain`       | 噴水と放射状の並木道 | ヴィーンヌィツャ・ポルタヴァ |
 */
import { city, prop } from "../../content-overrides/city-helpers.mjs";

export const UKRAINE_CITIES = {
  kyiv: city(
    "Kyiv|Kyiv|Kyiv|キーウ",
    30.5234, 50.4501, "ky", "cathedral", "capital", "r",
    "A thousand-year city under a wall said to be unbreakable|Una ciudad milenaria bajo un muro que dicen indestructible|Une ville millénaire sous un mur que l'on dit indestructible|壊れない壁を戴く、千年の都",
    "Inside St Sophia's Cathedral, built in 1037 under Yaroslav the Wise, an 11th-century mosaic of the Virgin at prayer is known as the Indestructible Wall, because the section of wall it covers has come through fire, Mongol sack and Soviet anti-religious campaigns without a crack, and legend holds that the city stands as long as it does. The cathedral and the nearby Kyiv-Pechersk Lavra, a monastery honeycombed with catacombs the monks began digging in 1051, became Ukraine's first UNESCO World Heritage Site in 1990.|Dentro de la catedral de Santa Sofía, construida en 1037 bajo Yaroslav el Sabio, un mosaico del siglo XI de la Virgen orante es conocido como el Muro Indestructible: la sección de muro que cubre ha resistido incendios, el saqueo mongol y las campañas antirreligiosas soviéticas sin una sola grieta, y la leyenda dice que la ciudad se mantendrá en pie mientras el muro aguante. La catedral y el cercano Monasterio de las Cuevas de Kyiv, horadado por catacumbas que los monjes empezaron a excavar en 1051, se convirtieron en 1990 en el primer Patrimonio de la Humanidad de la UNESCO en Ucrania.|Dans la cathédrale Sainte-Sophie, bâtie en 1037 sous Iaroslav le Sage, une mosaïque du XIe siècle représentant la Vierge en prière est appelée le Mur indestructible : la portion de mur qu'elle recouvre a traversé incendies, sac mongol et campagnes antireligieuses soviétiques sans une seule fissure, et la légende veut que la ville tienne tant que ce mur tient. La cathédrale et la laure des Grottes de Kyiv toute proche, un monastère creusé de catacombes que les moines commencèrent à percer en 1051, sont devenues en 1990 le premier site ukrainien inscrit au patrimoine mondial de l'UNESCO.|1037年、賢公ヤロスラフの時代に建てられた聖ソフィア大聖堂の内部には、祈る聖母を描いた11世紀のモザイク画があり、「壊れない壁」と呼ばれている。それを覆う壁の部分は火災もモンゴルの略奪もソ連の宗教弾圧も亀裂ひとつなく耐え抜いており、この壁が立っている限り都も立ち続けると語り継がれている。大聖堂と、近くにある1051年に修道士たちが掘り始めた洞窟修道院ペチェールシク大修道院は、1990年にウクライナで最初のユネスコ世界遺産となった。",
    [prop("St Sophia's Golden Domes|Las cúpulas doradas de Santa Sofía|Les coupoles dorées de Sainte-Sophie|聖ソフィアの黄金のドーム", 2800, 578),
     prop("Andriyivskyy Descent Studios|Los estudios de la bajada Andriivskyi|Les ateliers de la descente Andriïvskyi|アンドリーイウシクィイ坂の工房", 1200, 248)],
  ),

  // ---------------------------------------------------------------------
  // ky — キーウとその周辺
  // ---------------------------------------------------------------------
  bilaTserkva: city(
    "Bila Tserkva|Bila Tserkva|Bila Tserkva|ビラ・ツェールクヴァ",
    30.1121, 49.7950, "ky", "park", "park", "l",
    "A count's garden that swallowed a whole river valley|El jardín de un conde que se tragó todo un valle fluvial|Le jardin d'un comte qui engloutit toute une vallée fluviale|伯爵の庭園が呑み込んだ谷ひとつぶん",
    "Oleksandriya Park was laid out from 1793 by Count Franciszek Ksawery Branicki for his wife Alexandra, damming a stream into a chain of ponds and importing rare trees along paths that still wind across more than 200 hectares — one of Europe's largest surviving landscape parks of its kind. It is also one of the very few in Ukraine to keep almost its entire original layout after being nationalised in 1919.|El parque Oleksandriya se trazó a partir de 1793 por el conde Franciszek Ksawery Branicki para su esposa Alexandra, represando un arroyo en una cadena de estanques e importando árboles raros junto a senderos que aún serpentean por más de 200 hectáreas: uno de los mayores parques paisajísticos de su tipo que sobreviven en Europa. Es también uno de los pocos en Ucrania que conserva casi todo su trazado original tras ser nacionalizado en 1919.|Le parc Oleksandriya fut aménagé à partir de 1793 par le comte Franciszek Ksawery Branicki pour son épouse Alexandra, retenant un ruisseau en une chaîne d'étangs et important des arbres rares le long d'allées qui serpentent encore sur plus de 200 hectares — l'un des plus grands parcs paysagers de ce genre subsistant en Europe. C'est aussi l'un des rares en Ukraine à avoir gardé presque tout son tracé d'origine après sa nationalisation en 1919.|オレクサンドリヤ公園は1793年、ブラニツィ伯爵フランツィシェク・クサヴェルィが妻アレクサンドラのために造り始めた。小川をせき止めて連なる池をつくり、珍しい木々を運び込んで200ヘクタール以上に及ぶ小径を巡らせた、ヨーロッパでも屈指の規模を誇る現存する風景式庭園である。1919年に国有化されたのちも、ほぼ元の設計をそのまま保っているウクライナでも数少ない庭園のひとつでもある。",
    [prop("Oleksandriya Park Grotto|La gruta del parque Oleksandriya|La grotte du parc Oleksandriya|オレクサンドリヤ公園の洞窟", 480, 99),
     prop("Ros River Watermill|El molino de agua del río Ros|Le moulin à eau de la Ros|ロース川の水車小屋", 220, 45)],
  ),
  pereiaslav: city(
    "Pereiaslav|Pereiaslav|Pereiaslav|ペレヤスラウ",
    31.4467, 50.0667, "ky", "folkmuseum", "folkmuseum", "r",
    "A treaty town turned into an open-air museum of everyday things|Una ciudad de tratados convertida en museo al aire libre de objetos cotidianos|Une ville de traité devenue musée en plein air des objets du quotidien|条約の町は日用品の野外博物館になった",
    "The 1654 Pereiaslav Council, where Cossack hetman Bohdan Khmelnytsky swore an alliance with the Russian tsar, is still argued over by historians as to what exactly it promised either side. The town today holds some two dozen small museums built from real relocated buildings, including entire collections devoted to nothing but Ukrainian pottery, folk dress and antique bicycles.|El Consejo de Pereyáslav de 1654, donde el hetman cosaco Bohdán Jmelnitski juró una alianza con el zar ruso, sigue siendo motivo de debate entre historiadores sobre lo que en realidad prometía a cada bando. La ciudad conserva hoy una veintena de pequeños museos construidos con edificios reales trasladados, incluidas colecciones enteras dedicadas solo a la cerámica ucraniana, el traje popular y las bicicletas antiguas.|Le Conseil de Pereïaslav de 1654, où l'hetman cosaque Bohdan Khmelnytsky jura une alliance avec le tsar russe, fait toujours débat chez les historiens quant à ce qu'il promettait réellement à chaque partie. La ville abrite aujourd'hui une vingtaine de petits musées bâtis à partir de vrais édifices déplacés, dont des collections entières consacrées uniquement à la céramique ukrainienne, au costume populaire et aux bicyclettes anciennes.|1654年のペレヤスラウ会議で、コサックのヘーチマン、ボフダン・フメリニツィクィイはロシア皇帝との同盟を誓ったが、それが実際に双方に何を約束したものだったのかは、いまも歴史家のあいだで論争が続いている。町にはいま、実際に移築された建物を使った小さな博物館が二十数館あり、ウクライナの陶器だけを集めた館、民族衣装だけの館、アンティーク自転車だけの館まである。",
    [prop("Treaty Hall Courtyard|El patio de la sala del tratado|La cour de la salle du traité|条約の間の中庭", 320, 66),
     prop("Folk Pottery Museum Shed|El cobertizo del museo de cerámica popular|La remise du musée de la poterie populaire|民芸陶器博物館の小屋", 200, 41)],
  ),
  trypillia: city(
    "Trypillia|Trypillia|Trypillia|トリピッリャ",
    30.6206, 49.9153, "ky", "relic", "relic", "l",
    "A village that gave its name to towns 4,000 years older than it|Un pueblo que dio nombre a ciudades 4.000 años más antiguas que él|Un village qui donna son nom à des villes vieilles de 4 000 ans de plus que lui|自分より4千年古い町に名を貸した村",
    "Excavations near here in 1897 turned up the remains of settlements built around 4800–3000 BCE, some housing several thousand people in concentric rings of clay houses — among the largest settlements anywhere in the world at that time, long before Kyiv or any city on this river existed. Archaeologists still argue over why entire towns were deliberately burned and abandoned every 60 to 80 years, whole and furnished, as if by custom rather than disaster.|Unas excavaciones cercanas en 1897 sacaron a la luz restos de asentamientos construidos hacia 4800–3000 a.C., algunos con varios miles de habitantes en anillos concéntricos de casas de barro: entre los mayores asentamientos del mundo en su época, mucho antes de que existieran Kýiv o cualquier ciudad de este río. Los arqueólogos siguen debatiendo por qué pueblos enteros eran quemados y abandonados deliberadamente cada 60 u 80 años, completos y amueblados, como por costumbre y no por desastre.|Des fouilles menées ici en 1897 ont mis au jour les vestiges d'établissements bâtis vers 4800–3000 av. J.-C., certains abritant plusieurs milliers d'habitants en anneaux concentriques de maisons d'argile — parmi les plus grands établissements au monde à l'époque, bien avant que Kyiv ou toute ville de ce fleuve n'existe. Les archéologues débattent encore pour savoir pourquoi des villes entières étaient délibérément brûlées et abandonnées tous les 60 à 80 ans, intactes et meublées, comme par coutume plutôt que par désastre.|1897年にこの近くで行われた発掘調査で、紀元前4800年から3000年頃に築かれた集落の跡が見つかった。粘土の家々を同心円状に並べた集落には数千人が暮らしたものもあり、キーウはおろかこの川沿いのどんな町よりも古い、当時世界でも屈指の規模の集落だった。町全体が60年から80年おきに、家財ごとまるまる焼かれて放棄されていた理由については、災害ではなく習わしだったとする説も含め、考古学者のあいだでいまも議論が続いている。",
    [prop("Trypillia Clay-House Ring|El anillo de casas de barro de Trypillia|L'anneau de maisons d'argile de Trypillia|トリピッリャの環状土器住居", 260, 54),
     prop("Riverside Dig Site Shelter|El refugio del yacimiento junto al río|L'abri du site de fouilles au bord du fleuve|川辺の発掘現場の待避所", 180, 37)],
  ),
  lviv: city(
    "Lviv|Lviv|Lviv|リヴィウ",
    24.0297, 49.8397, "west", "oldtown", "oldtown", "l",
    "A city that changed rulers eight times and never lost its coffee|Una ciudad que cambió de dueño ocho veces y nunca perdió su café|Une ville qui changea huit fois de maître sans jamais perdre son café|統治者が幾度も変わっても、珈琲だけは絶やさなかった町",
    "Lviv's Rynok Square kept its Renaissance and Baroque façades through a twentieth century that handed the city between Austria-Hungary, Poland, the Soviet Union and Nazi occupation without ever flattening it, which is rare enough among historic centres in this part of Europe that UNESCO listed the whole old town in 1998. A local legend, doubted outside the city, credits a Lviv-born merchant with opening Vienna's first coffeehouse after 1683 using beans left behind by a retreating Ottoman army — true or not, Lviv's own café culture needs no borrowed reputation.|La plaza del Mercado de Lviv conservó sus fachadas renacentistas y barrocas a lo largo de un siglo XX que hizo pasar la ciudad de Austria-Hungría a Polonia, a la Unión Soviética y a la ocupación nazi sin llegar nunca a arrasarla, algo bastante raro entre los cascos históricos de esta parte de Europa como para que la UNESCO declarase todo el casco antiguo en 1998. Una leyenda local, puesta en duda fuera de la ciudad, atribuye a un comerciante nacido en Lviv la apertura del primer café de Viena después de 1683 con granos dejados por un ejército otomano en retirada; sea cierto o no, la propia cultura cafetera de la ciudad no necesita fama prestada.|La place du Marché de Lviv a gardé ses façades Renaissance et baroques tout au long d'un XXe siècle qui fit passer la ville de l'Autriche-Hongrie à la Pologne, à l'Union soviétique puis à l'occupation nazie sans jamais la raser, une rareté suffisante parmi les centres historiques de cette partie de l'Europe pour que l'UNESCO classe toute la vieille ville en 1998. Une légende locale, mise en doute hors de la ville, attribue à un marchand né à Lviv l'ouverture du premier café de Vienne après 1683 avec des grains laissés par une armée ottomane en retraite ; vraie ou non, la propre culture du café de Lviv n'a pas besoin d'une réputation empruntée.|リヴィウの市場広場は、20世紀を通じてオーストリア=ハンガリー、ポーランド、ソ連、ナチス占領下と幾度も統治者が入れ替わったにもかかわらず、一度も焼け野原にされることなくルネサンスとバロックの街並みを保ち続けた。この地域の歴史的な中心街としては珍しいことで、1998年には旧市街全体がユネスコ世界遺産に登録された。地元の言い伝えでは、1683年以降にウィーン最初の珈琲店を開いたのはリヴィウ出身の商人で、退却するオスマン軍が残した豆を使ったとされる――真偽は町の外では疑われているが、リヴィウ自身の珈琲文化は借り物の評判を必要としない。",
    [prop("Rynok Square Café Corner|El rincón cafetero de la plaza del Mercado|Le coin café de la place du Marché|市場広場の珈琲店の一角", 1600, 330),
     prop("Lychakiv Cemetery Gate|La puerta del cementerio de Lychakiv|La porte du cimetière de Lytchakiv|リチャキウ墓地の門", 480, 99)],
  ),

  // ---------------------------------------------------------------------
  // west — 西部・カルパチア
  // ---------------------------------------------------------------------
  ivanoFrankivsk: city(
    "Ivano-Frankivsk|Ivano-Frankivsk|Ivano-Frankivsk|イヴァノ=フランキウシク",
    24.7111, 48.9226, "west", "hutsul", "hutsul", "l",
    "A fortress town renamed for a poet it never met|Una ciudad fortaleza rebautizada por un poeta al que nunca conoció|Une ville fortifiée rebaptisée pour un poète qu'elle ne connut jamais|会ったこともない詩人の名を与えられた城塞町",
    "Founded in 1662 as a private fortress for the Potocki family, the city spent three centuries under the name Stanyslaviv before being renamed in 1962 for Ivan Franko, a writer who never actually lived there but whose name was judged safer to honour than the Polish magnate who built it. Its Armenian church and the wooden domes nearby mark it as a crossing point where Polish, Armenian, Jewish and Hutsul traditions once shared the same market square.|Fundada en 1662 como fortaleza privada de la familia Potocki, la ciudad pasó tres siglos con el nombre de Stanislavov antes de ser rebautizada en 1962 en honor a Iván Franko, un escritor que nunca vivió allí pero cuyo nombre se juzgó más seguro de honrar que el del magnate polaco que la construyó. Su iglesia armenia y las cúpulas de madera cercanas la señalan como un cruce donde las tradiciones polaca, armenia, judía y hutsul compartieron antaño la misma plaza de mercado.|Fondée en 1662 comme forteresse privée de la famille Potocki, la ville porta trois siècles durant le nom de Stanyslaviv avant d'être rebaptisée en 1962 en l'honneur d'Ivan Franko, un écrivain qui n'y vécut jamais mais dont le nom parut plus sûr à honorer que celui du magnat polonais qui la bâtit. Son église arménienne et les coupoles de bois voisines en font un carrefour où les traditions polonaise, arménienne, juive et houtsoule partagèrent jadis la même place de marché.|1662年にポトツキ家の私設要塞として築かれたこの町は、300年にわたりスタニスラヴィウの名で呼ばれたのち、1962年に作家イヴァン・フランコにちなんで改名された。フランコ自身はこの町に住んだことはなかったが、町を築いたポーランド貴族の名を残すより安全だと判断されたためである。アルメニア教会と近郊の木造教会のドームは、かつてポーランド・アルメニア・ユダヤ・フツルの各文化が同じ市場広場を共有していた交差点であったことを物語る。",
    [prop("Potocki Fortress Bastion|El baluarte de la fortaleza Potocki|Le bastion de la forteresse Potocki|ポトツキ家の城砦稜堡", 620, 128),
     prop("Armenian Church Courtyard|El patio de la iglesia armenia|La cour de l'église arménienne|アルメニア教会の中庭", 340, 70)],
  ),
  chernivtsi: city(
    "Chernivtsi|Chernivtsi|Tchernivtsi|チェルニウツィー",
    25.9403, 48.2921, "west", "residence", "residence", "r",
    "A university built to look like it belonged to no single faith|Una universidad construida para no parecer que pertenecía a una sola fe|Une université bâtie pour ne sembler appartenir à aucune foi unique|一つの信仰にも属さないよう建てられた大学",
    "The Residence of Bukovinian Metropolitans, finished in 1882 and now the heart of Chernivtsi National University, mixes Byzantine mosaics, Moorish tilework and Gothic vaulting in a single courtyard on the deliberate instructions of its Czech architect, who wanted no single religious community to see the building as purely its own. The city was long remembered locally as a place where several languages could be heard on one café terrace, a coexistence the twentieth century's wars scattered along with most of its Jewish and German-speaking population.|La Residencia de los Metropolitanos de Bucovina, terminada en 1882 y hoy corazón de la Universidad Nacional de Chernivtsi, mezcla mosaicos bizantinos, azulejos morunos y bóvedas góticas en un mismo patio por instrucción deliberada de su arquitecto checo, que no quería que ninguna comunidad religiosa viera el edificio como exclusivamente suyo. La ciudad se recordaba localmente como un lugar donde se oían varias lenguas en una misma terraza de café, una convivencia que las guerras del siglo XX dispersaron junto con la mayor parte de su población judía y de habla alemana.|La Résidence des métropolites de Bucovine, achevée en 1882 et aujourd'hui cœur de l'Université nationale de Tchernivtsi, mêle mosaïques byzantines, carrelages mauresques et voûtes gothiques dans une même cour sur instruction délibérée de son architecte tchèque, qui ne voulait qu'aucune communauté religieuse ne voie le bâtiment comme sien exclusivement. La ville resta longtemps connue localement comme un lieu où plusieurs langues se mêlaient sur une même terrasse de café, une coexistence que les guerres du XXe siècle dispersèrent avec la plus grande partie de sa population juive et germanophone.|1882年に完成し、いまはチェルニウツィー国立大学の中心となっている府主教館は、ビザンツ風モザイク、ムーア風タイル、ゴシック風の丸天井を一つの中庭に混ぜ合わせている。設計を手がけたチェコ人建築家が、どの宗教共同体にもこの建物を自分たちだけのものだと思わせないよう意図的にそう仕立てたためである。この町は長らく、一つのカフェのテラスで幾つもの言語が飛び交う場所として語られてきたが、その共存は20世紀の戦争によって、ユダヤ系・ドイツ語話者の住民の多くとともに散り散りになった。",
    [prop("Metropolitan Residence Courtyard|El patio de la Residencia Metropolitana|La cour de la Résidence métropolitaine|府主教館の中庭", 780, 161),
     prop("Kobylianska Street Café Terrace|La terraza de café de la calle Kobylianska|La terrasse de café de la rue Kobylianska|コビリャンシカ通りのカフェテラス", 400, 83)],
  ),
  uzhhorod: city(
    "Uzhhorod|Uzhhorod|Oujhorod|ウージュホロド",
    22.2979, 48.6208, "west", "hutsul", "hutsul", "l",
    "A castle town where the vineyards start at the city limits|Una ciudad de castillo donde los viñedos empiezan en el límite urbano|Une ville-château où les vignobles commencent à la limite de la ville|市境からぶどう畑が始まる城の町",
    "Uzhhorod's fourteenth-century castle looks down on one of Europe's longest linden-tree promenades along the Uzh river, planted in stages from the 1920s and now shading cafés that serve wine grown on the terraced hillsides visible from the ramparts. Sitting at the western tip of the country, where Hungarian, Slovak, Rusyn and Ukrainian have long been spoken within walking distance of each other, the city changed hands among four different states between 1918 and 1945 without its castle walls ever taking direct damage.|El castillo del siglo XIV de Uzhhorod domina uno de los paseos de tilos más largos de Europa junto al río Uzh, plantado por etapas desde la década de 1920 y hoy da sombra a cafés que sirven vino cultivado en las laderas en terrazas visibles desde las murallas. Situada en la punta occidental del país, donde húngaro, eslovaco, rusino y ucraniano llevan mucho tiempo oyéndose a poca distancia entre sí, la ciudad cambió de manos entre cuatro estados distintos entre 1918 y 1945 sin que las murallas de su castillo sufrieran jamás daño directo.|Le château du XIVe siècle d'Oujhorod domine l'une des plus longues promenades de tilleuls d'Europe le long de l'Uzh, plantée par étapes depuis les années 1920 et ombrageant aujourd'hui des cafés servant un vin cultivé sur les coteaux en terrasses visibles depuis les remparts. Située à la pointe occidentale du pays, où hongrois, slovaque, rusyne et ukrainien se sont longtemps côtoyés à quelques pas les uns des autres, la ville changea de mains entre quatre États différents entre 1918 et 1945 sans que les murs de son château ne subissent jamais de dommage direct.|14世紀に築かれたウージュホロド城は、ウージ川沿いに続くヨーロッパでも屈指の長さの菩提樹並木を見下ろす。1920年代から段階的に植えられたこの並木道は、城壁から見える段々畑で育てられたぶどうのワインを出すカフェに木陰を作っている。ハンガリー語・スロヴァキア語・ルシン語・ウクライナ語が長く隣り合って話されてきたこの国の最西端に位置し、1918年から1945年にかけて四つの異なる国のあいだで持ち主が変わったが、城壁が直接の被害を受けたことは一度もない。",
    [prop("Castle Rampart Vineyard Terrace|La terraza de viñedo de la muralla del castillo|La terrasse viticole du rempart du château|城壁のぶどう畑テラス", 700, 145),
     prop("Linden Promenade Wine Cellar|La bodega del paseo de los tilos|La cave à vin de la promenade des tilleuls|菩提樹並木のワイン蔵", 380, 78)],
  ),
  ternopil: city(
    "Ternopil|Ternopil|Ternopil|テルノーピリ",
    25.5948, 49.5535, "west", "fortress", "fortress", "l",
    "A castle that gave its lake to the whole town|Un castillo que le dio su lago a toda la ciudad|Un château qui offrit son lac à toute la ville|自らの湖を町全体に与えた城",
    "Ternopil's sixteenth-century castle was built beside a dam across the Seret river specifically to create the lake that still fills the middle of the city, an artificial water feature old enough that most residents no longer think of it as artificial at all. The lakeside promenade was among the first major reconstructions after the city was heavily damaged in fighting during 1944, rebuilt slowly enough that some of its older buildings were only fully restored after independence in 1991.|El castillo del siglo XVI de Ternopil se construyó junto a una presa en el río Seret precisamente para crear el lago que aún llena el centro de la ciudad, un elemento acuático artificial tan antiguo que la mayoría de los vecinos ya ni lo consideran artificial. El paseo junto al lago fue una de las primeras grandes reconstrucciones tras los graves daños sufridos por la ciudad en los combates de 1944, restaurada con tal lentitud que algunos de sus edificios más antiguos no quedaron del todo reparados hasta después de la independencia en 1991.|Le château du XVIe siècle de Ternopil fut bâti à côté d'un barrage sur la Séret précisément pour créer le lac qui remplit encore le centre de la ville, un plan d'eau artificiel si ancien que la plupart des habitants ne le considèrent plus comme tel. La promenade au bord du lac fut l'une des premières grandes reconstructions après les lourds dégâts subis par la ville lors des combats de 1944, restaurée si lentement que certains de ses bâtiments plus anciens ne furent pleinement rénovés qu'après l'indépendance de 1991.|16世紀に築かれたテルノーピリ城は、セレト川をせき止めるダムのすぐそばに、いまも町の中心を満たす湖を作る目的で建てられた。あまりに古くからある人工の水辺のため、住民の多くはもはやそれを人工物とは思っていない。湖畔の遊歩道は、1944年の戦闘で町が大きな被害を受けたのちの主要な再建事業の一つで、古い建物のいくつかは1991年の独立後にようやく修復が完了するほど、ゆっくりと再建が進んだ。",
    [prop("Castle Lake Promenade|El paseo del lago del castillo|La promenade du lac du château|城湖の遊歩道", 520, 107),
     prop("Seret Dam Fishing Pier|El muelle de pesca de la presa del Seret|La jetée de pêche du barrage du Seret|セレト川ダムの釣り桟橋", 260, 54)],
  ),
  lutsk: city(
    "Lutsk|Lutsk|Loutsk|ルーツィク",
    25.3254, 50.7472, "west", "fortress", "fortress", "r",
    "A castle where kings once tried to found an empire by committee|Un castillo donde unos reyes intentaron fundar un imperio en comité|Un château où des rois tentèrent jadis de fonder un empire en comité|王たちが合議で帝国を建てようとした城",
    "Lubart's Castle hosted a 1429 congress where the Grand Duke of Lithuania gathered the Holy Roman Emperor, the King of Poland, the last Byzantine claimant and assorted dukes to discuss crowning him emperor of a new state stretching from the Baltic to the Black Sea — a plan that collapsed within months when rival nobles intercepted the imperial crown before it arrived. The castle's thick brick towers, unusual for a region that mostly built in stone, still ring each summer with a festival of medieval music performed on reconstructed instruments.|El castillo de Lubart acogió en 1429 un congreso donde el gran duque de Lituania reunió al emperador del Sacro Imperio, al rey de Polonia, al último pretendiente bizantino y a varios duques para debatir su coronación como emperador de un nuevo estado que se extendería del Báltico al mar Negro, un plan que se vino abajo en meses cuando nobles rivales interceptaron la corona imperial antes de que llegara. Las gruesas torres de ladrillo del castillo, poco habituales en una región que construía sobre todo en piedra, aún resuenan cada verano con un festival de música medieval interpretada con instrumentos reconstruidos.|Le château de Lubart accueillit en 1429 un congrès où le grand-duc de Lituanie réunit l'empereur du Saint-Empire, le roi de Pologne, le dernier prétendant byzantin et divers ducs pour discuter de son couronnement en empereur d'un nouvel État s'étendant de la Baltique à la mer Noire — un projet qui s'effondra en quelques mois lorsque des nobles rivaux interceptèrent la couronne impériale avant son arrivée. Les épaisses tours de brique du château, inhabituelles dans une région qui bâtissait surtout en pierre, résonnent encore chaque été d'un festival de musique médiévale joué sur instruments reconstitués.|ルバルト城では1429年、リトアニア大公が神聖ローマ皇帝、ポーランド王、最後のビザンツ帝位請求者、そして幾人もの公たちを集め、バルト海から黒海まで広がる新たな国家の皇帝として大公を戴冠させる案を協議する会議が開かれた。しかしこの計画は数か月のうちに、対立する貴族たちが帝冠を途中で奪ったことで潰えた。石造りが主流だったこの地方では珍しい厚い煉瓦造りの塔は、いまも毎年夏、復元楽器による中世音楽祭で鳴り響く。",
    [prop("Lubart's Castle Congress Hall|El salón del congreso del castillo de Lubart|La salle du congrès du château de Lubart|ルバルト城の会議の間", 660, 136),
     prop("Old Town Brick Tower Stair|La escalera de la torre de ladrillo del casco antiguo|L'escalier de la tour de brique de la vieille ville|旧市街レンガ塔の階段", 280, 58)],
  ),
  kamianetsPodilskyi: city(
    "Kamianets-Podilskyi|Kamianets-Podilskyi|Kamianets-Podilskyi|カムヤネツィ=ポジーリシキー",
    26.5807, 48.6816, "west", "fortress", "fortress", "b",
    "A fortress town built inside its own moat by a river|Una ciudad fortaleza construida dentro de su propio foso fluvial|Une ville fortifiée bâtie à l'intérieur de son propre fossé fluvial|自らの堀の中に築かれた要塞町",
    "The old town sits on a rock island almost entirely encircled by a loop of the Smotrych river, so sheer-walled on all sides that its Ottoman-and-Polish fortress needed only a single narrow bridge as its real weak point across four centuries of sieges. A tightrope walker crossed the 190-metre gorge between the fortress and the town on a wire in 2009, marking the anniversary of a similar stunt performed by a French acrobat in the 1860s.|El casco antiguo se asienta sobre una isla rocosa casi por completo rodeada por un meandro del río Smotrych, con paredes tan verticales por todos lados que su fortaleza otomano-polaca solo tenía un estrecho puente como verdadero punto débil a lo largo de cuatro siglos de asedios. Un funambulista cruzó en 2009 el desfiladero de 190 metros entre la fortaleza y la ciudad sobre un cable, en homenaje a una hazaña similar de un acróbata francés en la década de 1860.|La vieille ville se dresse sur une île rocheuse presque entièrement cernée par une boucle de la Smotrytch, aux parois si abruptes de tous côtés que sa forteresse ottomane puis polonaise n'eut qu'un étroit pont pour seul véritable point faible durant quatre siècles de sièges. Un funambule traversa en 2009 sur un fil les 190 mètres du gouffre entre la forteresse et la ville, marquant l'anniversaire d'une prouesse similaire accomplie par un acrobate français dans les années 1860.|旧市街は、スモトリチ川がほぼ一周する形で取り囲む岩の島の上にあり、四方が切り立った崖であるため、オスマン・ポーランド両時代の要塞は四百年にわたる包囲戦を通じて、細い一本の橋だけを本当の弱点として抱えていた。2009年には綱渡り師が、要塞と町を隔てる幅190メートルの峡谷をワイヤー一本で渡った。1860年代にフランス人の軽業師が行った同様の芸を記念してのことだった。",
    [prop("Fortress Bridge Gatehouse|La casa de guardia del puente de la fortaleza|Le corps de garde du pont de la forteresse|要塞橋の門衛所", 900, 186),
     prop("Smotrych Canyon Rim Path|El sendero del borde del cañón del Smotrych|Le sentier de la crête du canyon du Smotrych|スモトリチ渓谷縁の小道", 360, 74)],
  ),
  truskavets: city(
    "Truskavets|Truskavets|Trouskavets|トゥルスカヴェツィ",
    23.5089, 49.2775, "west", "spa", "spa", "l",
    "A spa town that bottles its own smell|Un balneario que embotella su propio olor|Une ville d'eaux qui embouteille sa propre odeur|自らの匂いを瓶詰めにする湯治町",
    "Truskavets built its reputation on Naftusya, a mineral spring water that genuinely smells faintly of crude oil because it seeps through the same shale the region once drilled for it, and the pump rooms still dispense it warm in ceramic cups on a doctor's prescribed schedule rather than sold freely like ordinary bottled water. Its spa culture dates to the 1820s under Habsburg rule, old enough that some of its sanatoria have been treating the same handful of ailments, mostly kidney and liver complaints, for six generations of the same families.|Truskavets forjó su fama con Naftusya, un agua mineral que huele en verdad ligeramente a petróleo crudo porque brota a través de la misma pizarra que la región llegó a perforar en busca de él, y sus salas de bombeo aún la sirven tibia en tazas de cerámica según una pauta médica prescrita, en vez de venderse libremente como agua embotellada corriente. Su cultura balnearia se remonta a la década de 1820 bajo el dominio de los Habsburgo, lo bastante antigua como para que algunos de sus sanatorios lleven seis generaciones de las mismas familias tratando el mismo puñado de dolencias, sobre todo renales y hepáticas.|Truskavets bâtit sa réputation sur la Naftoussia, une eau minérale qui sent véritablement un peu le pétrole brut car elle suinte à travers le même schiste que la région a jadis foré pour l'extraire, et les salles de pompage la servent encore tiède dans des tasses en céramique selon un horaire prescrit par un médecin plutôt que vendue librement comme une eau en bouteille ordinaire. Sa culture thermale remonte aux années 1820 sous domination des Habsbourg, assez ancienne pour que certains de ses sanatoriums traitent depuis six générations les mêmes familles pour la même poignée de maux, surtout rénaux et hépatiques.|トゥルスカヴェツィは「ナフトゥーシャ」という、原油を掘っていたのと同じ頁岩を通って湧くために本当にかすかに石油の匂いがする鉱泉水で名を上げた。汲み上げ場ではいまも、ふつうの瓶入り水のように自由に売るのではなく、医師の処方に従って陶器のカップで温めて出す。その温泉文化は1820年代のハプスブルク統治下に遡り、いくつかのサナトリウムは主に腎臓と肝臓の疾患という同じ数種の症状を、同じ家系の六世代にわたって診てきたほど古い。",
    [prop("Naftusya Pump Room|La sala de bombeo de Naftusya|La salle de pompage de Naftoussia|ナフトゥーシャ汲み上げ室", 460, 95),
     prop("Sanatorium Colonnade Bench|El banco de la columnata del sanatorio|Le banc de la colonnade du sanatorium|サナトリウム回廊のベンチ", 220, 45)],
  ),
  kolomyia: city(
    "Kolomyia|Kolomyia|Kolomyia|コロミヤ",
    25.0350, 48.5285, "west", "hutsul", "hutsul", "r",
    "A museum shaped like the eggs inside it|Un museo con la forma de los huevos que guarda|Un musée en forme des œufs qu'il abrite|中にある卵と同じ形をした博物館",
    "The Pysanka Museum, built in 1987 in the shape of a giant painted Easter egg, holds several thousand examples of the wax-resist dyeing technique that turns a plain egg into a miniature map of protective symbols, one family's patterns often kept secret and passed down only by watching, never written. Kolomyia sits at the edge of Hutsul country, where the same wax-and-dye tools historically decorated more than eggs — cloth, leather and the carved wooden pipes still sold in the town's Saturday market.|El Museo de la Pysanka, construido en 1987 con forma de un gigantesco huevo de Pascua pintado, guarda varios miles de ejemplos de la técnica de teñido con cera que convierte un huevo liso en un mapa en miniatura de símbolos protectores, cuyos motivos familiares a menudo se guardaban en secreto y se transmitían solo observando, nunca por escrito. Kolomyia se halla al borde del país hutsul, donde las mismas herramientas de cera y tinte decoraban históricamente algo más que huevos: telas, cuero y las pipas de madera talladas que aún se venden en el mercado de los sábados.|Le musée de la Pysanka, bâti en 1987 en forme d'un gigantesque œuf de Pâques peint, conserve plusieurs milliers d'exemples de cette technique de teinture à la cire qui transforme un œuf ordinaire en carte miniature de symboles protecteurs, des motifs familiaux souvent gardés secrets et transmis seulement par l'observation, jamais par écrit. Kolomyia se trouve à la lisière du pays houtsoule, où les mêmes outils de cire et de teinture décoraient jadis bien plus que des œufs : tissus, cuir et pipes de bois sculptées encore vendues au marché du samedi.|1987年、巨大な彩色イースターエッグの形に建てられたピサンカ博物館には、蝋を使う防染技法の作例が数千点収められている。この技法は無地の卵を、魔除けの文様を刻んだ小さな地図のようなものに変える。文様は一家ごとの秘伝であることが多く、文字に残さず見て覚えるだけで受け継がれてきた。コロミヤはフツル地方の縁にあり、同じ蝋染めの道具は歴史的に卵だけでなく、布や革、そしていまも土曜市で売られている彫刻入りの木製パイプの装飾にも使われてきた。",
    [prop("Giant Pysanka Museum Hall|La sala del museo de la pysanka gigante|La salle du musée de la pysanka géante|巨大ピサンカ博物館の展示室", 400, 83),
     prop("Hutsul Saturday Market Stall|El puesto del mercado hutsul de los sábados|L'étal du marché houtsoule du samedi|フツル土曜市の露店", 210, 43)],
  ),

  // ---------------------------------------------------------------------
  // south — 南部・黒海/ドナウ沿岸
  // ---------------------------------------------------------------------
  odesa: city(
    "Odesa|Odesa|Odesa|オデーサ",
    30.7233, 46.4825, "south", "port", "port", "r",
    "A staircase built to trick the eye from the sea|Una escalinata construida para engañar al ojo desde el mar|Un escalier bâti pour tromper l'œil depuis la mer|海から見た目を欺くために造られた大階段",
    "The Potemkin Steps, built between 1837 and 1841, use a forced-perspective trick: the treads widen almost imperceptibly from top to bottom while the balustrades narrow, so a ship arriving in the harbour sees a staircase that looks perfectly straight-sided rather than tapering away. The grand street at the top is named for José de Ribas, the Spanish-Neapolitan admiral who helped Catherine the Great plan the city in 1794 on the ruins of an Ottoman fortress, which is why so much of central Odesa still reads as more Mediterranean than Slavic.|La Escalinata Potemkin, construida entre 1837 y 1841, usa un truco de perspectiva forzada: los peldaños se ensanchan de forma casi imperceptible de arriba abajo mientras las balaustradas se estrechan, de modo que un barco que llega al puerto ve una escalera de lados perfectamente rectos en vez de una que se afina en la distancia. La gran avenida de arriba lleva el nombre de José de Ribas, el almirante hispano-napolitano que ayudó a Catalina la Grande a planificar la ciudad en 1794 sobre las ruinas de una fortaleza otomana, razón por la que buena parte del centro de Odesa se lee más mediterránea que eslava.|L'escalier Potemkine, bâti entre 1837 et 1841, joue sur une perspective forcée : les marches s'élargissent presque imperceptiblement de haut en bas tandis que les balustrades se resserrent, si bien qu'un navire arrivant au port voit un escalier aux côtés parfaitement droits plutôt que rétréci par la distance. La grande avenue du sommet porte le nom de José de Ribas, l'amiral hispano-napolitain qui aida Catherine la Grande à planifier la ville en 1794 sur les ruines d'une forteresse ottomane, ce qui explique pourquoi une bonne partie du centre d'Odesa se lit plus méditerranéenne que slave.|1837年から1841年にかけて造られたポチョムキン階段には、遠近感をごまかす仕掛けがある。段差は上から下へいくにつれてほとんど気づかないほど広がり、手すりはわずかに狭まっていくため、港に入る船からはすぼまって見えるはずの階段が、まっすぐな形に見える。頂上の大通りは、1794年にエカチェリーナ2世のもとでオスマン帝国の要塞跡にこの町の都市計画を手がけたスペイン系ナポリ人の提督ホセ・デ・リバスの名にちなむ。オデーサの中心街の多くがスラブ的というより地中海的な表情を持つのはそのためである。",
    [prop("Potemkin Steps Landing|El descansillo de la Escalinata Potemkin|Le palier de l'escalier Potemkine|ポチョムキン階段の踊り場", 2200, 454),
     prop("Deribasivska Street Kiosk|El quiosco de la calle Deribasivska|Le kiosque de la rue Deribassivska|デリバシフスカ通りの売店", 620, 128)],
  ),
  mykolaiv: city(
    "Mykolaiv|Mykolaiv|Mykolaïv|ミコライウ",
    32.0000, 46.9750, "south", "port", "port", "l",
    "A shipyard town that also bottled the world's cooking oil|Un pueblo astillero que también embotelló el aceite de cocina del mundo|Une ville de chantiers navals qui a aussi mis en bouteille l'huile de cuisine du monde|世界の食用油も瓶詰めにした造船の町",
    "Mykolaiv was founded in 1789 specifically as a naval shipyard on the estuary where the Southern Bug meets the Dnipro, and its yards have launched everything from Black Sea Fleet battleships to Soviet aircraft carriers built too wide to pass back through the Bosphorus once finished. In 1833, a local agronomist named Danylo Bokariov worked out how to press useful quantities of oil from sunflower seeds, an industrial method that turned a decorative garden flower into one of the country's defining crops.|Mykolaiv se fundó en 1789 específicamente como astillero naval en el estuario donde el Bug Meridional se une al Dniéper, y sus astilleros han botado de todo, desde acorazados de la Flota del Mar Negro hasta portaaviones soviéticos construidos demasiado anchos para volver a pasar por el Bósforo una vez terminados. En 1833, un agrónomo local llamado Danylo Bokariov descubrió cómo prensar cantidades útiles de aceite de las semillas de girasol, un método industrial que convirtió una flor decorativa de jardín en uno de los cultivos que definen al país.|Mykolaïv fut fondée en 1789 spécifiquement comme chantier naval militaire à l'estuaire où le Boug méridional rejoint le Dniepr, et ses chantiers ont lancé de tout, des cuirassés de la flotte de la mer Noire aux porte-avions soviétiques construits trop larges pour repasser le Bosphore une fois achevés. En 1833, un agronome local nommé Danylo Bokariov mit au point un procédé pour presser des quantités utiles d'huile à partir de graines de tournesol, une méthode industrielle qui fit d'une fleur de jardin décorative l'une des cultures phares du pays.|ミコライウは1789年、南ブーフ川がドニプロ川と合流する河口に、海軍の造船所として建設された町である。ここの造船台からは黒海艦隊の戦艦から、完成後にボスポラス海峡を通り抜けるには幅が広すぎたソ連の空母まで、あらゆる艦船が進水してきた。1833年には地元の農学者ダヌィーロ・ボカリョウが、ひまわりの種から実用的な量の油を搾る方法を編み出し、この工業的な製法が観賞用の庭の花を国を代表する作物のひとつに変えた。",
    [prop("Shipyard Dry Dock Overlook|El mirador del dique seco del astillero|Le belvédère de la cale sèche du chantier naval|造船所ドライドックの見晴らし所", 780, 161),
     prop("Sunflower Press Museum Room|La sala del museo de la prensa de girasol|La salle du musée du pressoir à tournesol|ひまわり搾油博物館の一室", 320, 66)],
  ),
  bilhorodDnistrovskyi: city(
    "Bilhorod-Dnistrovskyi|Bilhorod-Dnistrovskyi|Bilhorod-Dnistrovskyi|ビルホロド=ドニストロウシキー",
    30.3453, 46.1875, "south", "fortress", "fortress", "r",
    "A fortress that outgrew four different names|Una fortaleza que superó cuatro nombres distintos|Une forteresse qui survécut à quatre noms différents|四つの名を乗り越えてきた要塞",
    "Akkerman Fortress, begun by Genoese traders in the thirteenth century and expanded by Moldavian princes and then the Ottoman Empire, is one of the largest surviving medieval fortresses in Europe, its walls enclosing enough space that a small town once lived entirely within them. The settlement itself has answered to Tyras in Greek, Cetatea Albă in Romanian and Akkerman in Turkish before its current Ukrainian name, each conqueror renaming rather than replacing what the last one had built.|La fortaleza de Akkerman, iniciada por mercaderes genoveses en el siglo XIII y ampliada por príncipes moldavos y después por el Imperio otomano, es una de las mayores fortalezas medievales que se conservan en Europa, con murallas que encierran espacio suficiente para que un pequeño pueblo viviera antaño enteramente dentro de ellas. El propio asentamiento respondió a Tyras en griego, Cetatea Albă en rumano y Akkerman en turco antes de su actual nombre ucraniano, cada conquistador renombrando en vez de sustituir lo que el anterior había construido.|La forteresse d'Akkerman, entamée par des marchands génois au XIIIe siècle puis agrandie par des princes moldaves et enfin l'Empire ottoman, est l'une des plus grandes forteresses médiévales subsistant en Europe, ses murs enfermant assez d'espace pour qu'une petite ville y ait jadis vécu tout entière. L'agglomération elle-même a répondu à Tyras en grec, Cetatea Albă en roumain puis Akkerman en turc avant son nom ukrainien actuel, chaque conquérant renommant plutôt que remplaçant ce que le précédent avait bâti.|13世紀にジェノヴァ商人が築き始め、モルダヴィア公国、続いてオスマン帝国が拡張したアッケルマン要塞は、ヨーロッパに現存する中世要塞でも屈指の規模を誇り、城壁の内側にはかつて小さな町がまるごと収まるほどの広さがある。この町自体も、ギリシャ語でテュラス、ルーマニア語でチェタテア・アルバ、トルコ語でアッケルマンと呼ばれてから現在のウクライナ語名に至っており、征服者はそのたびに前の建設を壊すのではなく、名を変えるだけにとどめてきた。",
    [prop("Akkerman Fortress Inner Courtyard|El patio interior de la fortaleza de Akkerman|La cour intérieure de la forteresse d'Akkerman|アッケルマン要塞の内庭", 720, 149),
     prop("Genoese Watchtower Stair|La escalera de la torre genovesa|L'escalier de la tour génoise|ジェノヴァ人の見張り塔の階段", 320, 66)],
  ),
  izmail: city(
    "Izmail|Izmail|Izmaïl|イズマイール",
    28.8419, 45.3519, "south", "port", "port", "b",
    "A river port that measures its trade in barges, not trains|Un puerto fluvial que mide su comercio en barcazas, no en trenes|Un port fluvial qui mesure son commerce en péniches, pas en trains|貨物を鉄道ではなく川船で量る川港",
    "Izmail's port sits on the Danube itself rather than the Black Sea, work its docks have done in some form since Ottoman times when a fortress here guarded the river mouth, and in recent years barge traffic upriver toward the wider Danube network has grown busier than at any point in decades. The town's small history museum keeps a case of river-worn Ottoman cannonballs still being turned up by dredgers working the same channel two centuries later.|El puerto de Izmail se asienta sobre el propio Danubio y no sobre el mar Negro, un trabajo que sus muelles realizan de una forma u otra desde época otomana, cuando una fortaleza aquí custodiaba la desembocadura del río, y en los últimos años el tráfico de barcazas río arriba hacia la red danubiana más amplia se ha vuelto más intenso que en décadas. El pequeño museo de historia de la ciudad guarda una vitrina de balas de cañón otomanas desgastadas por el río que las dragas siguen sacando del mismo canal dos siglos después.|Le port d'Izmaïl se trouve sur le Danube lui-même plutôt que sur la mer Noire, un travail que ses quais accomplissent sous une forme ou une autre depuis l'époque ottomane, quand une forteresse gardait ici l'embouchure du fleuve, et ces dernières années le trafic de péniches remontant vers le vaste réseau danubien s'est fait plus dense qu'à aucun moment depuis des décennies. Le petit musée d'histoire de la ville conserve une vitrine de boulets de canon ottomans usés par le fleuve, que les dragues continuent de remonter du même chenal deux siècles plus tard.|イズマイールの港は黒海ではなくドナウ川そのものに面しており、この地の要塞が河口を守っていたオスマン時代から何らかの形で続いてきた仕事である。近年は、ドナウ川の広い水運網へ上流に向かうはしけの往来が、ここ数十年で最も活発になっている。町の小さな郷土博物館には、二百年たったいまも浚渫船が同じ水路から引き上げ続ける、川に磨かれたオスマン軍の砲弾が展示ケースに収められている。",
    [prop("Danube Barge Quay|El muelle de barcazas del Danubio|Le quai des péniches du Danube|ドナウ川はしけ埠頭", 380, 78),
     prop("Ottoman Cannonball Display Case|La vitrina de balas de cañón otomanas|La vitrine des boulets de canon ottomans|オスマン砲弾の展示ケース", 200, 41)],
  ),
  vylkove: city(
    "Vylkove|Vylkove|Vylkove|ヴィルコヴェ",
    29.5975, 45.4025, "south", "canal", "canal", "l",
    "A town where the streets are canals and the taxis are boats|Un pueblo donde las calles son canales y los taxis son barcas|Une ville où les rues sont des canaux et les taxis des bateaux|通りが運河で、タクシーが小舟の町",
    "Vylkove was settled in the eighteenth century by Old Believers fleeing religious persecution in Russia, who built houses on stilts along the Danube delta's silt-laden channels rather than filling them in, and many residents still travel between houses by narrow flat-bottomed boat rather than by road. The delta beyond the town is one of Europe's largest wetlands, and its reed beds and fish-rich channels support pelicans, herons and one of the continent's few reliable colonies of wild swans.|Vylkove fue poblada en el siglo XVIII por viejos creyentes que huían de la persecución religiosa en Rusia, quienes construyeron casas sobre pilotes a lo largo de los canales cargados de limo del delta del Danubio en vez de rellenarlos, y muchos vecinos aún se desplazan entre casas en barca estrecha y de fondo plano en lugar de por carretera. El delta más allá del pueblo es uno de los mayores humedales de Europa, y sus cañaverales y canales ricos en peces sostienen pelícanos, garzas y una de las pocas colonias fiables de cisnes salvajes del continente.|Vylkove fut peuplée au XVIIIe siècle par des vieux-croyants fuyant les persécutions religieuses en Russie, qui bâtirent des maisons sur pilotis le long des chenaux limoneux du delta du Danube plutôt que de les combler, et beaucoup d'habitants se déplacent encore d'une maison à l'autre en barque étroite à fond plat plutôt que par la route. Le delta au-delà de la ville est l'une des plus grandes zones humides d'Europe, et ses roselières et chenaux poissonneux abritent pélicans, hérons et l'une des rares colonies fiables de cygnes sauvages du continent.|ヴィルコヴェは18世紀、ロシアでの宗教弾圧を逃れた古儀式派の人々が住み着いた町で、彼らはドナウ・デルタの泥の堆積する水路を埋め立てるのではなく、その上に高床の家を建てた。いまも多くの住民は道路ではなく、底の平たい細長い舟で家々のあいだを行き来する。町の先に広がるデルタはヨーロッパ有数の湿地帯で、葦原と魚の豊かな水路はペリカンやサギ、そしてヨーロッパでも数少ない野生のハクチョウの安定したコロニーを支えている。",
    [prop("Delta Canal Boat Landing|El embarcadero del canal del delta|Le débarcadère du canal du delta|デルタ運河の船着場", 260, 54),
     prop("Old Believer Stilt House|La casa sobre pilotes de los viejos creyentes|La maison sur pilotis des vieux-croyants|古儀式派の高床の家", 180, 37)],
  ),

  // ---------------------------------------------------------------------
  // cen — 中部
  // ---------------------------------------------------------------------
  vinnytsia: city(
    "Vinnytsia|Vinnytsia|Vinnytsia|ヴィーンヌィツャ",
    28.4682, 49.2331, "cen", "fountain", "fountain", "l",
    "A river that dances to a schedule on the hour|Un río que baila según un horario cada hora|Un fleuve qui danse selon un horaire, à l'heure pile|時報に合わせて踊る川",
    "The Roshen Fountain, floating on pontoons across the Southern Bug, is Europe's largest of its kind, choreographing jets up to 60 metres high to recorded music each evening from a control room that resets automatically after every performance. The riverside promenade around it was largely rebuilt in the 2010s, funded in part by the confectionery company whose fountain now draws more evening visitors downtown than any single museum in the city.|La fuente Roshen, flotando sobre pontones a través del Bug Meridional, es la mayor de su tipo en Europa, coreografiando chorros de hasta 60 metros de altura al son de música grabada cada noche desde una sala de control que se reinicia sola tras cada función. El paseo ribereño que la rodea se reconstruyó en gran parte en la década de 2010, financiado en parte por la empresa de dulces cuya fuente atrae hoy al centro más visitantes nocturnos que cualquier museo de la ciudad.|La fontaine Rochen, flottant sur des pontons à travers le Boug méridional, est la plus grande de son genre en Europe, chorégraphiant des jets montant jusqu'à 60 mètres sur une musique enregistrée chaque soir depuis une salle de contrôle qui se réinitialise automatiquement après chaque représentation. La promenade riveraine qui l'entoure fut en grande partie reconstruite dans les années 2010, financée en partie par l'entreprise de confiserie dont la fontaine attire aujourd'hui en soirée plus de visiteurs au centre-ville qu'aucun musée de la ville.|南ブーフ川に浮橋で浮かぶロシェン噴水は、この種のものとしてはヨーロッパ最大で、毎晩、録音された音楽に合わせて最高60メートルの高さまで噴き上げる演出を行い、制御室は上演のたびに自動で初期状態に戻る。周囲の川辺の遊歩道は2010年代に大きく整備され、費用の一部はこの噴水を運営する菓子メーカーが負担した。いまではこの噴水が、市内のどの博物館よりも多くの夜間の来街者を中心部に集めている。",
    [prop("Roshen Fountain Viewing Deck|La plataforma de observación de la fuente Roshen|La plate-forme d'observation de la fontaine Rochen|ロシェン噴水の展望デッキ", 560, 116),
     prop("Pyrohiv Bridge Promenade|El paseo del puente Pyrohiv|La promenade du pont Pyrohiv|ピロヒウ橋の遊歩道", 300, 62)],
  ),
  cherkasy: city(
    "Cherkasy|Cherkasy|Tcherkassy|チェルカースィ",
    32.0598, 49.4444, "cen", "cossack", "cossack", "r",
    "A city that moved uphill to make room for a lake|Una ciudad que se trasladó cuesta arriba para dejar sitio a un lago|Une ville qui se déplaça en hauteur pour faire place à un lac|湖に道を譲るため高台へ移った町",
    "Much of old Cherkasy was flooded in the 1960s when a dam downstream on the Dnipro raised the river into the Kremenchuk reservoir, so the modern centre sits noticeably higher and further back than the original riverside town it replaced. The surrounding steppe was Cossack country in the sixteenth and seventeenth centuries, and the reed-lined shallows the reservoir left behind now draw more herons than the fishing boats that once worked the same water.|Buena parte del viejo Cherkasy quedó inundada en los años sesenta cuando una presa río abajo en el Dniéper elevó el cauce hasta formar el embalse de Kremenchuk, de modo que el centro moderno se alza notablemente más alto y más retirado que la antigua ciudad ribereña a la que sustituyó. La estepa circundante fue tierra cosaca en los siglos XVI y XVII, y los bajíos bordeados de cañas que dejó el embalse atraen hoy a más garzas que a las barcas de pesca que antaño faenaban en la misma agua.|Une bonne partie du vieux Tcherkassy fut inondée dans les années 1960 lorsqu'un barrage en aval sur le Dniepr éleva le fleuve pour former le réservoir de Kremenchouk, si bien que le centre moderne se trouve nettement plus haut et plus en retrait que l'ancienne ville riveraine qu'il remplaça. La steppe environnante fut terre cosaque aux XVIe et XVIIe siècles, et les hauts-fonds bordés de roseaux laissés par le réservoir attirent aujourd'hui plus de hérons que les barques de pêche qui travaillaient jadis la même eau.|旧チェルカースィの多くは1960年代、下流のドニプロ川に造られたダムが川を堰き止めてクレメンチューク貯水池を生んだ際に水没した。そのため現在の中心部は、置き換えられた元の川沿いの町よりも明らかに高く、川から離れた場所に位置している。周囲のステップは16〜17世紀にはコサックの土地であり、貯水池が残した葦の茂る浅瀬には、かつて同じ水域で働いていた漁船よりも多くのサギが集まる。",
    [prop("Reservoir Shoreline Promenade|El paseo de la orilla del embalse|La promenade du bord du réservoir|貯水池湖岸の遊歩道", 420, 87),
     prop("Cossack Watchtower Overlook|El mirador de la atalaya cosaca|Le belvédère de la tour de guet cosaque|コサック監視塔の展望台", 240, 50)],
  ),
  poltava: city(
    "Poltava|Poltava|Poltava|ポルタヴァ",
    34.5514, 49.5883, "cen", "fountain", "fountain", "b",
    "A battlefield that redrew the whole city as a compass rose|Un campo de batalla que rediseñó toda la ciudad como una rosa de los vientos|Un champ de bataille qui redessina toute la ville en rose des vents|全市を方位図に描き直した古戦場",
    "After Peter I defeated Charles XII of Sweden and hetman Ivan Mazepa's forces here in 1709, a battle that shifted the balance of power across northern Europe for a century, the city was later rebuilt around a circular square from which eight streets radiate outward like the points of a compass. The Rotunda of Friendship of Nations, added in the 1960s, now anchors the ring park that traces the old fortress line the battle was originally fought to defend.|Después de que Pedro I derrotara aquí en 1709 a Carlos XII de Suecia y a las fuerzas del hetman Iván Mazepa, una batalla que desplazó el equilibrio de poder en el norte de Europa durante un siglo, la ciudad se reconstruyó más tarde en torno a una plaza circular de la que parten ocho calles como los puntos de una rosa de los vientos. La Rotonda de la Amistad de los Pueblos, añadida en los años sesenta, ancla hoy el parque anular que traza la vieja línea de la fortaleza que la batalla se libró originalmente por defender.|Après que Pierre Ier eut vaincu ici en 1709 Charles XII de Suède et les forces de l'hetman Ivan Mazepa, une bataille qui déplaça l'équilibre des pouvoirs en Europe du Nord pour tout un siècle, la ville fut reconstruite autour d'une place circulaire d'où rayonnent huit rues comme les pointes d'une rose des vents. La Rotonde de l'amitié des peuples, ajoutée dans les années 1960, ancre aujourd'hui le parc en anneau qui trace la vieille ligne de forteresse que la bataille visait à l'origine à défendre.|1709年、ピョートル1世がスウェーデン王カール12世とヘーチマン、イヴァン・マゼーパの軍をここで破った戦いは、その後一世紀にわたり北欧の勢力図を塗り替えた。この地はのちに、八本の通りが方位図の針のように放射状に伸びる円形広場を中心に再建された。1960年代に加えられた「諸民族友好のロトンダ」は、いまや戦いがもともと守ろうとした旧要塞線をなぞる環状公園の要となっている。",
    [prop("Compass Square Rotunda|La rotonda de la plaza compás|La rotonde de la place-boussole|コンパス広場のロトンダ", 680, 140),
     prop("Battlefield Ring Park Bench|El banco del parque anular del campo de batalla|Le banc du parc annulaire du champ de bataille|古戦場環状公園のベンチ", 320, 66)],
  ),
  kropyvnytskyi: city(
    "Kropyvnytskyi|Kropyvnytskyi|Kropyvnytskyi|クロピヴニツィクィイ",
    32.2597, 48.5079, "cen", "theatre", "theatre", "l",
    "The town where Ukrainian theatre first got a stage of its own|El pueblo donde el teatro ucraniano tuvo por primera vez escenario propio|La ville où le théâtre ukrainien obtint pour la première fois une scène bien à lui|ウクライナ演劇が初めて自前の舞台を得た町",
    "In 1882, the writer and actor Marko Kropyvnytskyi founded the first professional Ukrainian-language theatre troupe here, at a time when tsarist decree banned Ukrainian-language stage plays outright and performances survived only by disguising themselves as folk entertainment between other acts. The city has changed its own name five times since then, most recently in 2016, but kept the theatre building and the annual festival named for the man who defied the ban.|En 1882, el escritor y actor Marko Kropyvnytskyi fundó aquí la primera compañía teatral profesional en lengua ucraniana, en una época en que un decreto zarista prohibía sin más las obras en ucraniano, y las representaciones sobrevivían solo disfrazándose de espectáculo popular entre otros números. La ciudad ha cambiado de nombre cinco veces desde entonces, la última en 2016, pero conservó el edificio del teatro y el festival anual que lleva el nombre del hombre que desafió la prohibición.|En 1882, l'écrivain et acteur Marko Kropyvnytskyi fonda ici la première troupe théâtrale professionnelle en langue ukrainienne, à une époque où un décret tsariste interdisait purement et simplement les pièces en ukrainien, et les représentations ne survivaient qu'en se déguisant en spectacle populaire entre d'autres numéros. La ville a changé de nom cinq fois depuis lors, la dernière en 2016, mais a conservé le bâtiment du théâtre et le festival annuel nommé d'après l'homme qui brava l'interdiction.|1882年、作家で俳優のマルコ・クロピヴニツィクィイはここで最初のウクライナ語による職業劇団を旗揚げした。当時は帝政ロシアの布告でウクライナ語の舞台劇そのものが禁じられており、上演は他の出し物の合間に民俗芸能を装うことでかろうじて生き延びていた。町はそれ以来五度も名前を変え、最近では2016年にも改称されたが、劇場の建物と、その禁令に逆らった人物の名を冠した毎年の演劇祭は残された。",
    [prop("Kropyvnytskyi Theatre Balcony|El balcón del teatro Kropyvnytskyi|Le balcon du théâtre Kropyvnytskyi|クロピヴニツィクィイ劇場のバルコニー", 440, 91),
     prop("Backstage Costume Workshop|El taller de vestuario entre bastidores|L'atelier de costumes en coulisses|舞台裏の衣装工房", 240, 50)],
  ),
  uman: city(
    "Uman|Uman|Ouman|ウマーニ",
    30.2223, 48.7484, "cen", "park", "park", "r",
    "A garden built for a wife, a grave visited by strangers|Un jardín para una esposa, una tumba visitada por desconocidos|Un jardin bâti pour une épouse, une tombe visitée par des inconnus|妻のために造られた庭園と、見知らぬ人々が訪れる墓",
    "Sofiyivka Park was laid out from 1796 by Count Stanisław Szczęsny Potocki as a gift to his wife Zofia, its grottoes, waterfalls and an underground river built almost entirely by hand over decades and named for figures from Greek mythology rather than the family that paid for it. Every autumn the city's population swells briefly by tens of thousands as Hasidic pilgrims travel from around the world to the grave of Rabbi Nachman of Breslov for Rosh Hashanah, a pilgrimage held every year since his death in 1810.|El parque Sofiyivka se trazó a partir de 1796 por el conde Stanisław Szczęsny Potocki como regalo para su esposa Zofia, con grutas, cascadas y un río subterráneo construidos casi enteramente a mano a lo largo de décadas y bautizados con figuras de la mitología griega y no con el nombre de la familia que los pagó. Cada otoño la población de la ciudad crece brevemente en decenas de miles cuando peregrinos jasídicos viajan desde todo el mundo hasta la tumba del rabino Najman de Breslev para el Rosh Hashaná, una peregrinación celebrada cada año desde su muerte en 1810.|Le parc Sofiyivka fut aménagé à partir de 1796 par le comte Stanisław Szczęsny Potocki en cadeau pour son épouse Zofia, ses grottes, cascades et une rivière souterraine bâties presque entièrement à la main sur des décennies et nommées d'après des figures de la mythologie grecque plutôt que d'après la famille qui les paya. Chaque automne, la population de la ville gonfle brièvement de dizaines de milliers d'habitants lorsque des pèlerins hassidiques viennent du monde entier jusqu'à la tombe du rabbin Nahman de Breslev pour Roch Hachana, un pèlerinage tenu chaque année depuis sa mort en 1810.|ソフィイウカ公園は1796年、ポトツキ伯爵スタニスワフ・シチェンスヌィが妻ゾフィヤへの贈り物として造り始めた。洞窟や滝、地下を流れる川は数十年かけてほぼすべて手作業で築かれ、費用を出した一族の名ではなくギリシャ神話の登場人物にちなんで名付けられている。毎秋、この町の人口は一時的に数万人規模で膨れ上がる。ハシディズムの巡礼者たちが世界中からロシュ・ハシャナの祭日に合わせ、ラビ・ナフマン・ミブレスラフの墓を訪れるためで、彼が1810年に没して以来毎年続く巡礼である。",
    [prop("Sofiyivka Park Grotto|La gruta del parque Sofiyivka|La grotte du parc Sofiyivka|ソフィイウカ公園の洞窟", 620, 128),
     prop("Rabbi Nachman Pilgrim Courtyard|El patio de peregrinos del rabino Najman|La cour des pèlerins du rabbi Nahman|ナフマン・ラビ巡礼の中庭", 300, 62)],
  ),
  kremenchuk: city(
    "Kremenchuk|Kremenchuk|KremenTchouk|クレメンチューク",
    33.4247, 49.0670, "cen", "industry", "industry", "l",
    "A truck factory town that also holds back a sea|Un pueblo de fábrica de camiones que también contiene un mar|Une ville-usine de camions qui retient aussi une mer|海をせき止めるトラック工場の町",
    "The Kremenchuk hydroelectric dam, completed in 1960, backs up the Dnipro into a reservoir large enough that locals call it the Kremenchuk Sea, and its turbines still supply power to the KrAZ truck factory whose heavy-duty trucks have hauled cargo across the region since 1959. The reservoir's shoreline hides the drowned outline of villages relocated before the flooding, some of whose former residents still gather each summer at the waterline nearest their old address.|La presa hidroeléctrica de Kremenchuk, terminada en 1960, embalsa el Dniéper en un depósito tan grande que la gente del lugar lo llama el Mar de Kremenchuk, y sus turbinas aún alimentan la fábrica de camiones KrAZ, cuyos vehículos pesados transportan carga por la región desde 1959. La orilla del embalse oculta el contorno anegado de aldeas trasladadas antes de la inundación, y algunos de sus antiguos vecinos aún se reúnen cada verano en la línea de agua más cercana a su antigua dirección.|Le barrage hydroélectrique de Kremenchouk, achevé en 1960, retient le Dniepr dans un réservoir si vaste que les habitants l'appellent la mer de Kremenchouk, et ses turbines alimentent encore l'usine de camions KrAZ, dont les poids lourds transportent du fret dans la région depuis 1959. La rive du réservoir cache le contour englouti de villages relogés avant la mise en eau, dont certains anciens habitants se retrouvent encore chaque été sur la ligne d'eau la plus proche de leur ancienne adresse.|1960年に完成したクレメンチューク水力発電ダムはドニプロ川をせき止め、地元では「クレメンチューク海」と呼ばれるほど大きな貯水池を作った。そのタービンはいまも、1959年から地域一帯へ貨物を運んできた大型トラック、クラズのトラック工場に電力を供給している。貯水池の岸辺には、水没前に移転させられた村々の水に沈んだ輪郭が隠れており、かつての住民の一部は、いまも毎年夏、自分の元の住所にいちばん近い水際に集まる。",
    [prop("Kremenchuk Sea Shoreline|La orilla del Mar de Kremenchuk|Le rivage de la mer de Kremenchouk|クレメンチューク海の岸辺", 460, 95),
     prop("KrAZ Factory Gate|La puerta de la fábrica KrAZ|La porte de l'usine KrAZ|クラズ工場の門", 260, 54)],
  ),

  // ---------------------------------------------------------------------
  // pl — ポリッシャ(北部)
  // ---------------------------------------------------------------------
  chornobyl: city(
    "Chornobyl|Chornobyl|Chornobyl|チョルノービリ",
    30.2219, 51.2763, "pl", "memorial", "zone", "l",
    "A forest that grew back where a city could not|Un bosque que volvió a crecer donde una ciudad ya no pudo|Une forêt qui a repoussé là où une ville ne le pouvait plus|町の代わりに森が戻ってきた場所",
    "On 26 April 1986, a botched safety test at the nuclear plant here released more radioactive material than any accident before or since, and the nearby city of Pripyat was evacuated within two days and never resettled. Wolves, lynx and Przewalski's horses reintroduced in 1998 now live across the exclusion zone in numbers rarely seen this close to the rest of Europe, and scientists still study the area as an accidental case study in what land looks like once people leave it alone.|El 26 de abril de 1986, una prueba de seguridad fallida en la central nuclear de aquí liberó más material radiactivo que cualquier accidente anterior o posterior, y la cercana ciudad de Prípiat fue evacuada en dos días y nunca volvió a poblarse. Lobos, linces y caballos de Przewalski reintroducidos en 1998 viven hoy por toda la zona de exclusión en números raramente vistos tan cerca del resto de Europa, y los científicos siguen estudiando la zona como un caso accidental de cómo queda un territorio cuando la gente lo deja en paz.|Le 26 avril 1986, un essai de sécurité raté à la centrale nucléaire d'ici a libéré plus de matières radioactives qu'aucun accident avant ou depuis, et la ville voisine de Pripiat fut évacuée en deux jours et jamais repeuplée. Loups, lynx et chevaux de Przewalski réintroduits en 1998 vivent aujourd'hui dans toute la zone d'exclusion en nombre rarement vu d'aussi près ailleurs en Europe, et les scientifiques y étudient encore, comme un cas d'école accidentel, ce à quoi ressemble un territoire une fois que les hommes le laissent tranquille.|1986年4月26日、この地の原子力発電所で行われた安全試験の失敗により、それまでにもその後にも例のない量の放射性物質が放出され、近くのプリピャチの町は2日以内に避難させられたまま二度と人が住むことはなかった。1998年に再導入されたオオカミ、オオヤマネコ、プルジェヴァリスキーウマは、いまやヨーロッパの他のどこよりも高い密度で立入禁止区域全体に生息しており、科学者たちはこの土地を、人が去った後に何が起こるかを示す図らずもの実験場として研究し続けている。",
    [prop("Duga Radar Overlook|El mirador del radar Duga|Le belvédère du radar Duga|ドゥーガ・レーダーの展望地点", 640, 132),
     prop("Exclusion Zone Ranger Post|El puesto de guardabosques de la zona de exclusión|Le poste de garde de la zone d'exclusion|立入禁止区域のレンジャー詰所", 260, 54)],
  ),
  chernihiv: city(
    "Chernihiv|Chernihiv|Chernihiv|チェルニーヒウ",
    31.2893, 51.4982, "pl", "onion", "onion", "l",
    "A city older than Kyiv's own written history|Una ciudad más antigua que la propia historia escrita de Kýiv|Une ville plus vieille que l'histoire écrite de Kyiv elle-même|キーウの文献史よりも古い町",
    "Chernihiv is first named in the 907 treaty between Kyivan Rus and Byzantium, making it one of the oldest continuously recorded cities in the region, and its eleventh-century Transfiguration Cathedral is one of the very few Kyivan Rus stone churches still standing largely as built. The freestanding bell tower beside it was climbed for centuries by pilgrims counting the eight bells cast at different times across four hundred years, each with its own name and voice.|Chernihiv aparece nombrada por primera vez en el tratado de 907 entre la Rus de Kýiv y Bizancio, lo que la convierte en una de las ciudades más antiguas registradas sin interrupción en la región, y su catedral de la Transfiguración del siglo XI es una de las pocas iglesias de piedra de la Rus de Kýiv que aún se mantienen en gran parte como se construyeron. El campanario exento de al lado fue subido durante siglos por peregrinos que contaban las ocho campanas fundidas en distintas épocas a lo largo de cuatrocientos años, cada una con su propio nombre y voz.|Tchernihiv est mentionnée pour la première fois dans le traité de 907 entre la Rus' de Kyiv et Byzance, ce qui en fait l'une des plus anciennes villes attestées sans interruption dans la région, et sa cathédrale de la Transfiguration du XIe siècle est l'une des rares églises de pierre de la Rus' de Kyiv encore debout à peu près telle qu'elle fut bâtie. Le clocher indépendant qui la jouxte fut gravi pendant des siècles par des pèlerins comptant les huit cloches coulées à des époques différentes sur quatre cents ans, chacune avec son propre nom et sa propre voix.|チェルニーヒウの名が初めて記されるのは907年、キーウ・ルーシとビザンツ帝国の間の条約で、この地域で途切れず記録され続けている都市の中でも屈指の古さを誇る。11世紀に建てられた生神女大聖堂は、キーウ・ルーシ時代の石造教会でほぼ建設当時のまま残る数少ない一つである。隣に独立して立つ鐘楼には、四百年にわたり異なる時期に鋳造された八つの鐘があり、それぞれに固有の名と音色を持つ。巡礼者たちは何世紀ものあいだ塔に登ってその数を数えてきた。",
    [prop("Transfiguration Cathedral Bell Tower|El campanario de la catedral de la Transfiguración|Le clocher de la cathédrale de la Transfiguration|生神女大聖堂の鐘楼", 900, 186),
     prop("Antoniy Caves Candle Stall|El puesto de velas de las cuevas de Antoniy|L'étal de bougies des grottes d'Antoniy|アントニイ洞窟のろうそく売り場", 300, 62)],
  ),
  zhytomyr: city(
    "Zhytomyr|Zhytomyr|Jytomyr|ジトームィル",
    28.6587, 50.2547, "pl", "industry", "industry", "r",
    "The gateway town that trained its own rocket scientist|La ciudad frontera que formó a su propio ingeniero de cohetes|La ville-porte qui forma son propre ingénieur des fusées|自前のロケット技師を育てた玄関町",
    "Serhii Korolev, later chief designer of the Soviet space programme and the engineer behind Sputnik and Gagarin's flight, was born here in 1907 in a small wooden house that now holds a museum devoted mostly to model rockets built by local schoolchildren. Long before that, Zhytomyr made its living as the gateway between the forests of Polissia and the farmland further south, and its old Polish quarter still shows the stone townhouses of merchants who traded between the two.|Serguéi Koroliov, después diseñador jefe del programa espacial soviético e ingeniero tras el Sputnik y el vuelo de Gagarin, nació aquí en 1907 en una pequeña casa de madera que hoy alberga un museo dedicado sobre todo a maquetas de cohetes construidas por escolares locales. Mucho antes, Zhytomyr se ganaba la vida como puerta entre los bosques de Polesia y las tierras de labranza más al sur, y su antiguo barrio polaco aún muestra las casas de piedra de los mercaderes que comerciaban entre ambos.|Sergueï Korolev, futur ingénieur en chef du programme spatial soviétique et cerveau derrière Spoutnik et le vol de Gagarine, naquit ici en 1907 dans une petite maison de bois qui abrite aujourd'hui un musée consacré surtout aux maquettes de fusées construites par des écoliers locaux. Bien avant cela, Jytomyr vivait de son rôle de porte entre les forêts de Polésie et les terres agricoles plus au sud, et son vieux quartier polonais montre encore les maisons de pierre des marchands qui commerçaient entre les deux.|のちにソ連宇宙計画の主任設計者となり、スプートニクとガガーリンの飛行を手がけた技師セルヒイ・コロリョウは、1907年にここの小さな木造家屋で生まれた。いまその家は、主に地元の子どもたちが作った模型ロケットを展示する博物館になっている。それよりずっと前から、ジトームィルはポリッシャの森と南に広がる農地を結ぶ玄関町として生計を立ててきた。古いポーランド人街には、両者の間で商いをした商人たちの石造りの町家がいまも残る。",
    [prop("Korolev's Childhood House|La casa de infancia de Koroliov|La maison d'enfance de Korolev|コロリョウの生家", 420, 87),
     prop("Polissia Timber Yard|El almacén de madera de Polesia|Le dépôt de bois de Polésie|ポリッシャ材木置き場", 240, 50)],
  ),
  rivne: city(
    "Rivne|Rivne|Rivne|リヴネ",
    26.2516, 50.6199, "pl", "onion", "onion", "l",
    "A lake town built where two rivers refused to meet cleanly|Una ciudad lacustre alzada donde dos ríos se negaron a unirse sin más|Une ville lacustre bâtie où deux rivières refusèrent de se rejoindre simplement|二つの川が素直に合わさらなかった湖の町",
    "Rivne grew up on marshland where the Ustya river splits around an island before joining the wider basin, and the old town still keeps a small artificial lake at its centre that freezes solid enough most winters for skating rinks to be marked out on the ice by hand. The regional philharmonic building, a nineteenth-century former Polish theatre, has survived three changes of national ownership without ever losing its original stage floor.|Rivne creció sobre una marisma donde el río Ustia se divide en torno a una isla antes de unirse a la cuenca más amplia, y el casco antiguo conserva aún un pequeño lago artificial en su centro que la mayoría de los inviernos se hiela lo bastante como para trazar a mano pistas de patinaje sobre el hielo. El edificio de la filarmónica regional, un antiguo teatro polaco del siglo XIX, ha sobrevivido a tres cambios de soberanía nacional sin perder nunca su tarima original.|Rivne s'est développée sur un marécage où l'Ustia se divise autour d'une île avant de rejoindre le bassin plus large, et la vieille ville garde en son centre un petit lac artificiel qui gèle assez solidement la plupart des hivers pour qu'on y trace à la main des patinoires sur la glace. Le bâtiment de la philharmonie régionale, un ancien théâtre polonais du XIXe siècle, a survécu à trois changements de souveraineté nationale sans jamais perdre son plancher de scène d'origine.|リヴネは、ウスチャ川が島を挟んで二つに分かれてから広い流域に合流する湿地の上に育った町で、旧市街の中心にはいまも小さな人工湖があり、たいていの冬はしっかり凍ってスケートリンクが手作業で線を引かれるほどになる。19世紀にポーランド劇場として建てられた州フィルハーモニーの建物は、国の帰属が三度変わってもなお、当初の舞台の床を失わずに残している。",
    [prop("Rivne Lake Skating Patch|La pista de patinaje del lago de Rivne|La patinoire du lac de Rivne|リヴネ湖のスケート場", 280, 58),
     prop("Old Theatre Stage Floor|El escenario del viejo teatro|Le plancher de scène du vieux théâtre|旧劇場の舞台床", 340, 70)],
  ),
  korosten: city(
    "Korosten|Korosten|Korosten|コロステーニ",
    28.6367, 50.9508, "pl", "industry", "industry", "b",
    "A junction where four railway lines and one legend meet|Un nudo donde se cruzan cuatro líneas ferroviarias y una leyenda|Un carrefour où se croisent quatre lignes ferroviaires et une légende|4本の鉄路と1つの伝説が交わる分岐点",
    "Korosten sits where four main rail lines cross, a knot the Soviet army fortified so heavily in 1943 that some of its concrete pillboxes are still climbed over by children on the way to school, and the granite quarried nearby has floored buildings as far away as Moscow's metro. Local tradition places the tenth-century death of Prince Ihor of Kyiv here, killed by the Drevlian tribe for demanding tribute twice — a story his widow Olga is said to have answered with a revenge involving pigeons and burning thatch.|Korosten se asienta donde se cruzan cuatro líneas ferroviarias principales, un nudo que el ejército soviético fortificó tanto en 1943 que algunos de sus búnkeres de hormigón siguen siendo trepados por niños de camino al colegio, y el granito extraído cerca ha pavimentado edificios tan lejanos como el metro de Moscú. La tradición local sitúa aquí la muerte en el siglo X del príncipe Ígor de Kýiv, asesinado por la tribu drevliana por exigir tributo dos veces, historia a la que su viuda Olga habría respondido con una venganza que incluía palomas y paja en llamas.|Korosten se trouve au croisement de quatre grandes lignes ferroviaires, un nœud que l'armée soviétique fortifia si lourdement en 1943 que certains de ses blockhaus en béton sont encore escaladés par des enfants sur le chemin de l'école, et le granit extrait à proximité a pavé des bâtiments aussi lointains que le métro de Moscou. La tradition locale y situe la mort au Xe siècle du prince Igor de Kyiv, tué par la tribu des Drevlianes pour avoir exigé deux fois le tribut — une histoire à laquelle sa veuve Olga aurait répondu par une vengeance impliquant des pigeons et de la paille enflammée.|コロステーニは4本の主要鉄道路線が交わる町で、1943年にソ連軍がこの結節点を徹底的に要塞化したため、当時のコンクリート製トーチカのいくつかは、いまも通学途中の子どもたちがよじ登るほど身近に残っている。近郊で採れる花崗岩は、遠くモスクワの地下鉄の床にまで使われた。地元の言い伝えでは、10世紀にキーウ公イーホルが、二度も貢物を求めたことでドレヴリャーネ族に殺されたのがこの地とされ、妻オーリハは鳩と燃える藁を使った復讐で応じたと語られる。",
    [prop("Rail Junction Signal Post|El poste de señales del nudo ferroviario|Le poste de signalisation du nœud ferroviaire|鉄道分岐点の信号所", 260, 54),
     prop("Granite Quarry Overlook|El mirador de la cantera de granito|Le belvédère de la carrière de granit|花崗岩採石場の展望所", 190, 39)],
  ),
  klevan: city(
    "Klevan|Klevan|Klevan|クレヴァニ",
    26.1667, 50.7333, "pl", "tunnel", "tunnel", "l",
    "A hedge of trees that only opened for a train|Un seto de árboles que solo se abría para un tren|Une haie d'arbres qui ne s'ouvrait que pour un train|列車のためだけに開く木々の垣根",
    "Klevan's so-called Tunnel of Love is not a tourist folly but a working freight spur, laid to carry timber to a fibreboard factory a few times a day, and the arch of trees over the tracks grew thick simply because nothing but the passing trains ever trims it back. Couples now walk its two-kilometre length making wishes, a custom that appears to be no older than the photographs that made the tunnel famous online in the early 2010s.|El llamado Túnel del Amor de Klevan no es un capricho turístico, sino un ramal de mercancías en funcionamiento, tendido para llevar madera a una fábrica de tableros unas pocas veces al día, y el arco de árboles sobre las vías creció espeso simplemente porque nada salvo los trenes que pasan lo recorta jamás. Las parejas recorren hoy sus dos kilómetros pidiendo deseos, una costumbre que no parece más antigua que las fotografías que hicieron famoso al túnel en internet a principios de la década de 2010.|Le prétendu Tunnel de l'Amour de Klevan n'est pas une folie touristique mais un embranchement de fret bien réel, posé pour acheminer du bois vers une usine de panneaux de fibres quelques fois par jour, et la voûte d'arbres au-dessus des rails a poussé dense simplement parce que rien à part les trains qui passent ne la taille jamais. Des couples parcourent aujourd'hui ses deux kilomètres en faisant des vœux, une coutume qui ne semble pas plus ancienne que les photos qui ont rendu le tunnel célèbre en ligne au début des années 2010.|クレヴァニの「愛のトンネル」は観光用に造られた奇観ではなく、実際に稼働している貨物線の側線で、1日に数回、繊維板工場へ木材を運ぶために敷かれている。線路の上を覆う木々のアーチが濃く茂ったのは、通り過ぎる列車以外に誰も剪定しないからにすぎない。いまではカップルたちが2キロの道のりを願いごとをしながら歩くが、この習わし自体は、2010年代初めにこのトンネルをネットで有名にした写真より古いものではないようだ。",
    [prop("Tunnel of Love Footpath|El sendero del Túnel del Amor|Le sentier du Tunnel de l'Amour|愛のトンネルの遊歩道", 320, 66),
     prop("Fibreboard Factory Siding|El apartadero de la fábrica de tableros|La voie de garage de l'usine de panneaux|繊維板工場の側線", 200, 41)],
  ),
  slavutych: city(
    "Slavutych|Slavutych|Slavoutytch|スラウーティチ",
    30.7442, 51.5228, "pl", "planned", "planned", "r",
    "A town where every district was built by a different country|Una ciudad donde cada barrio lo construyó un país distinto|Une ville où chaque quartier fut bâti par un pays différent|区画ごとに違う国が建てた町",
    "Slavutych was raised in under two years to rehouse the Chornobyl plant's workers after Pripyat was evacuated, and eight Soviet republics each designed one of its residential districts in their own regional style, so a walk across town passes from Baltic brick to Georgian arcades to Central Asian tilework within a few blocks. Nobody who was not already a plant employee was allowed to move in during its first years, and the town's yearly half-marathon still runs partly along the road built for the original 1986 evacuation convoys.|Slavutych se levantó en menos de dos años para realojar a los trabajadores de la central de Chornóbil tras evacuarse Prípiat, y ocho repúblicas soviéticas diseñaron cada una un barrio residencial en su propio estilo regional, de modo que un paseo por la ciudad pasa del ladrillo báltico a las arcadas georgianas y los azulejos centroasiáticos en pocas manzanas. Nadie que no fuera ya empleado de la central pudo mudarse allí en sus primeros años, y la media maratón anual de la ciudad aún recorre en parte la carretera construida para los convoyes de evacuación de 1986.|Slavoutytch fut bâtie en moins de deux ans pour reloger les travailleurs de la centrale de Tchornobyl après l'évacuation de Prypiat, et huit républiques soviétiques conçurent chacune l'un de ses quartiers résidentiels dans son propre style régional, si bien qu'une promenade en ville passe de la brique balte aux arcades géorgiennes puis au carrelage d'Asie centrale en quelques rues. Nul qui n'était pas déjà employé de la centrale ne put s'y installer durant ses premières années, et le semi-marathon annuel de la ville emprunte encore en partie la route bâtie pour les convois d'évacuation de 1986.|スラウーティチは、プリピャチが避難させられたあとチョルノービリ原発の職員を住まわせるため、2年足らずで築かれた町である。ソ連の八つの共和国がそれぞれ自国の様式で一区画ずつ設計したため、町を歩くとバルト風の煉瓦造りからグルジア風の回廊、中央アジア風のタイル張りへと、数区画ごとに表情が変わる。開設から数年は原発職員以外の入居が認められず、いまも毎年開かれるハーフマラソンの一部は、1986年の避難隊列のために敷かれた道をたどる。",
    [prop("Tallinn District Courtyard|El patio del distrito de Tallin|La cour du quartier de Tallinn|タリン地区の中庭", 360, 74),
     prop("Worker Shuttle Platform|El andén de la lanzadera de trabajadores|Le quai de la navette des travailleurs|通勤シャトルのホーム", 240, 50)],
  ),

  // ---------------------------------------------------------------------
  // east — 東部
  // ---------------------------------------------------------------------
  kharkiv: city(
    "Kharkiv|Kharkiv|Kharkiv|ハルキウ",
    36.2304, 49.9935, "east", "constructivist", "constructivist", "r",
    "A university city that once built the future in concrete|Una ciudad universitaria que una vez construyó el futuro en hormigón|Une ville universitaire qui bâtit jadis l'avenir en béton|コンクリートで未来を築いた大学都市",
    "Derzhprom, the State Industry Building completed in 1928, was among the first constructivist skyscrapers built anywhere, its interlinked concrete towers and sky bridges engineered to flex rather than crack over the old mine workings beneath the square. It anchored Freedom Square, at 11.9 hectares one of the largest city squares in Europe, built while Kharkiv served as the capital of Soviet Ukraine from 1919 to 1934 — a role the much older university founded here in 1804 has already outlasted by two centuries and counting.|El Derzhprom, el Edificio de la Industria Estatal terminado en 1928, fue uno de los primeros rascacielos constructivistas construidos en el mundo, con torres de hormigón interconectadas y pasarelas aéreas diseñadas para flexionar en vez de agrietarse sobre las antiguas galerías mineras bajo la plaza. Ancló la plaza de la Libertad, con 11,9 hectáreas una de las mayores plazas urbanas de Europa, construida mientras Kharkiv fue capital de la Ucrania soviética entre 1919 y 1934, un papel que la universidad, mucho más antigua, fundada aquí en 1804, ya ha superado por dos siglos y sigue sumando.|Le Derzhprom, l'Immeuble de l'industrie d'État achevé en 1928, fut l'un des tout premiers gratte-ciel constructivistes au monde, ses tours de béton reliées par des passerelles suspendues conçues pour fléchir plutôt que se fissurer au-dessus d'anciennes galeries minières sous la place. Il ancrait la place de la Liberté, avec ses 11,9 hectares l'une des plus grandes places urbaines d'Europe, bâtie alors que Kharkiv fut la capitale de l'Ukraine soviétique de 1919 à 1934 — un rôle que l'université, bien plus ancienne, fondée ici en 1804, a déjà dépassé de deux siècles et continue de dépasser.|1928年に完成した国家産業ビル(デルジプロム)は、世界でも最初期のコンストラクティビズム様式の高層建築の一つで、広場の地下に残る旧坑道の上でひび割れずにたわむよう設計された、空中回廊で結ばれた複数のコンクリート塔からなる。この建物は11.9haという、ヨーロッパでも屈指の広さを持つ自由広場の核となった。広場が造られたのは、ハルキウが1919年から1934年までソヴィエト・ウクライナの首都だった時期のことだが、1804年に創立されたこの町の大学はその役割よりすでに二世紀も長く続いている。",
    [prop("Derzhprom Sky Bridge|La pasarela aérea del Derzhprom|La passerelle suspendue du Derzhprom|デルジプロムの空中回廊", 1400, 289),
     prop("Freedom Square Tram Stop|La parada de tranvía de la plaza de la Libertad|L'arrêt de tram de la place de la Liberté|自由広場の路面電車停留所", 360, 74)],
  ),
  dnipro: city(
    "Dnipro|Dnipro|Dnipro|ドニプロ",
    35.0462, 48.4647, "east", "rocket", "rocket", "l",
    "A closed city that once built the rockets nobody could name|Una ciudad cerrada que una vez construyó los cohetes que nadie podía nombrar|Une ville fermée qui bâtit jadis les fusées que nul ne pouvait nommer|誰もその名を口にできなかったロケットを造った閉ざされた町",
    "Until 1991, Dnipro (then Dnipropetrovsk) was closed to foreigners entirely because the Yuzhmash factory here built the Soviet Union's intercontinental ballistic missiles alongside civilian rockets, work so secret that the city was left off ordinary maps for decades. Yuzhmash later built pieces of the International Space Station and satellites still in orbit today, and the city's long embankment along the Dnipro, one of the longest continuous river promenades in Europe, was largely landscaped only after the Soviet-era secrecy finally lifted.|Hasta 1991, Dnipro (entonces Dnipropetrovsk) estuvo cerrada por completo a los extranjeros porque la fábrica Yuzhmash de aquí construía los misiles balísticos intercontinentales de la Unión Soviética junto a cohetes civiles, un trabajo tan secreto que la ciudad quedó fuera de los mapas corrientes durante décadas. Yuzhmash construyó después piezas de la Estación Espacial Internacional y satélites aún en órbita hoy, y el largo malecón de la ciudad junto al Dniéper, uno de los paseos fluviales continuos más largos de Europa, se ajardinó en gran parte solo después de que se levantara por fin el secretismo de la era soviética.|Jusqu'en 1991, Dnipro (alors Dnipropetrovsk) fut entièrement fermée aux étrangers car l'usine Ioujmach y construisait les missiles balistiques intercontinentaux de l'Union soviétique aux côtés de fusées civiles, un travail si secret que la ville resta absente des cartes ordinaires pendant des décennies. Ioujmach construisit plus tard des éléments de la Station spatiale internationale et des satellites encore en orbite aujourd'hui, et le long quai de la ville le long du Dniepr, l'une des plus longues promenades fluviales continues d'Europe, ne fut largement aménagé qu'après la levée du secret de l'ère soviétique.|1991年まで、ドニプロ(当時のドニプロペトロウシク)は外国人の立ち入りが全面的に禁じられていた。ここのユージュマシュ工場がソ連の大陸間弾道ミサイルを民生用ロケットと並行して製造しており、その秘密は徹底していて、この町は何十年もふつうの地図から外されていたほどだった。ユージュマシュはのちに国際宇宙ステーションの部品や、いまも軌道上にある人工衛星を手がけるようになった。ヨーロッパでも屈指の長さを誇るドニプロ川沿いの遊歩道が本格的に整備されたのも、ソ連時代の秘匿がようやく解かれてからのことである。",
    [prop("Yuzhmash Museum Rocket Hall|La sala de cohetes del museo Yuzhmash|La salle des fusées du musée Ioujmach|ユージュマシュ博物館のロケット展示室", 1000, 206),
     prop("Long Embankment River Bench|El banco del largo malecón|Le banc de la longue promenade fluviale|長い河岸遊歩道のベンチ", 340, 70)],
  ),
  zaporizhzhia: city(
    "Zaporizhzhia|Zaporizhzhia|Zaporijjia|ザポリッジャ",
    35.1396, 47.8388, "east", "cossack", "cossack", "r",
    "An island fortress that trained an army with no permanent address|Una isla fortaleza que entrenó a un ejército sin dirección fija|Une île forteresse qui forma une armée sans adresse fixe|定まった住所を持たない軍を鍛えた島の砦",
    "Khortytsia Island, the largest river island in Europe, was the site of the Zaporozhian Sich, a fortified Cossack camp that moved several times between the sixteenth and eighteenth centuries and admitted no women, kept no hereditary titles and elected its own leaders — an arrangement historians still cite as an unusually early experiment in military democracy. A reconstructed wooden Sich now stands on the island, built in the 1990s using the same joinery methods the original camps would have used, since none of the originals survived being repeatedly abandoned and rebuilt elsewhere.|La isla de Jortytsia, la mayor isla fluvial de Europa, fue el emplazamiento de la Sich zaporoga, un campamento cosaco fortificado que se trasladó varias veces entre los siglos XVI y XVIII, no admitía mujeres, no reconocía títulos hereditarios y elegía a sus propios líderes: un régimen que los historiadores aún citan como un experimento inusualmente temprano de democracia militar. En la isla se alza hoy una Sich de madera reconstruida, levantada en los años noventa con las mismas técnicas de ensamblaje que habrían usado los campamentos originales, ya que ninguno de estos sobrevivió a ser abandonado y reconstruido en otro lugar una y otra vez.|L'île de Khortytsia, la plus grande île fluviale d'Europe, fut le site de la Sitch zaporogue, un camp cosaque fortifié qui se déplaça plusieurs fois entre les XVIe et XVIIIe siècles, n'admettait aucune femme, ne reconnaissait aucun titre héréditaire et élisait ses propres chefs — un dispositif que les historiens citent encore comme une expérience précoce et singulière de démocratie militaire. Une Sitch de bois reconstituée se dresse aujourd'hui sur l'île, bâtie dans les années 1990 selon les mêmes méthodes d'assemblage que les camps d'origine, dont aucun n'a survécu à ces abandons et reconstructions répétés ailleurs.|ヨーロッパ最大の川中島であるホルティツャ島は、ザポロージャ・シーチの所在地だった。この要塞化されたコサックの陣営は16世紀から18世紀のあいだに何度も移動し、女人禁制で世襲の称号もなく、指導者は選挙で選ばれた。歴史家はいまもこれを、軍事的民主主義の異例に早い実験例として挙げる。島にはいま1990年代に復元された木造のシーチが立つ。当時と同じ木組みの技法で建てられているのは、幾度も放棄され別の場所に再建されたために、当時の建物が一つも現存していないからである。",
    [prop("Khortytsia Sich Palisade Gate|La puerta de la empalizada de la Sich de Jortytsia|La porte de la palissade de la Sitch de Khortytsia|ホルティツャ・シーチの柵門", 640, 132),
     prop("Dnipro Rapids Overlook|El mirador de los rápidos del Dniéper|Le belvédère des rapides du Dniepr|ドニプロ急流の展望所", 300, 62)],
  ),
  sumy: city(
    "Sumy|Sumy|Soumy|スーミ",
    34.7981, 50.9077, "east", "onion", "onion", "b",
    "A merchant's fortune, built almost entirely out of hemp rope|La fortuna de un mercader, hecha casi por entero de cuerda de cáñamo|La fortune d'un marchand, bâtie presque entièrement en corde de chanvre|麻縄でほぼ築かれた商人の財",
    "Sumy grew rich in the nineteenth century supplying hemp rope and rigging to the Russian Imperial Navy, and the fortune of one merchant family, the Kharitonenkos, paid for the ornate Transfiguration Cathedral that still dominates the skyline as well as a sugar-refining business that made them among the wealthiest commoners in the empire. The city's Roman Catholic church, built by the same wave of merchant money, was converted into a philharmonic concert hall in Soviet times and never fully returned to religious use.|Sumy se enriqueció en el siglo XIX suministrando cuerda y jarcia de cáñamo a la Armada Imperial rusa, y la fortuna de una familia de mercaderes, los Kharitonenko, pagó la ornamentada catedral de la Transfiguración que aún domina el perfil de la ciudad, así como un negocio azucarero que los convirtió en unos de los plebeyos más ricos del imperio. La iglesia católica romana de la ciudad, construida con la misma ola de dinero mercantil, se convirtió en sala de conciertos filarmónica en época soviética y nunca volvió del todo al uso religioso.|Sumy s'enrichit au XIXe siècle en fournissant corde et gréement de chanvre à la marine impériale russe, et la fortune d'une famille de marchands, les Kharitonenko, finança l'imposante cathédrale de la Transfiguration qui domine encore la ville, ainsi qu'une affaire de raffinage de sucre qui en fit l'une des familles roturières les plus riches de l'empire. L'église catholique romaine de la ville, bâtie grâce à la même vague d'argent marchand, fut transformée en salle de concert philharmonique à l'époque soviétique et ne retrouva jamais pleinement son usage religieux.|スーミは19世紀、ロシア帝国海軍に麻縄や索具を供給して富を築いた町で、ハリトネンコという一商人一族の財産が、いまも町並みを圧する華麗な生神女大聖堂と、彼らを帝国でも屈指の富裕な平民に押し上げた製糖業を支えた。同じ商人の資金の波で建てられた町のローマ・カトリック教会は、ソ連時代にフィルハーモニーのコンサートホールへと転用され、いまも宗教施設としては完全には戻っていない。",
    [prop("Transfiguration Cathedral Steps|Los escalones de la catedral de la Transfiguración|Les marches de la cathédrale de la Transfiguration|生神女大聖堂の階段", 520, 107),
     prop("Former Church Concert Hall Seat|El asiento de la sala de conciertos de la antigua iglesia|Un fauteuil de la salle de concert de l'ancienne église|旧教会コンサートホールの客席", 260, 54)],
  ),
};

/**
 * 路線(49本)。ウクルザリズニツャ(УЗ)の実在の幹線・支線にならい、
 * キーウを中心に放射状に組んである(実際の路線網もキーウ中心)。
 */
export const UKRAINE_EDGES = [
  // --- ky キーウとその周辺 ---
  ["kyiv", "bilaTserkva"],
  ["kyiv", "pereiaslav"],
  ["kyiv", "trypillia"],
  ["kyiv", "chornobyl"],
  ["kyiv", "zhytomyr"],
  ["kyiv", "chernihiv"],
  ["kyiv", "cherkasy"],
  ["bilaTserkva", "uman"],
  // --- pl ポリッシャ(北部) ---
  ["zhytomyr", "vinnytsia"],
  ["zhytomyr", "korosten"],
  ["korosten", "rivne"],
  ["korosten", "chernihiv"],
  ["rivne", "klevan"],
  ["rivne", "lutsk"],
  ["chernihiv", "slavutych"],
  // --- west 西部・カルパチア ---
  ["lviv", "ternopil"],
  ["lviv", "lutsk"],
  ["lviv", "truskavets"],
  ["lviv", "uzhhorod"],
  ["ternopil", "ivanoFrankivsk"],
  ["ternopil", "kamianetsPodilskyi"],
  ["ivanoFrankivsk", "chernivtsi"],
  ["ivanoFrankivsk", "kolomyia"],
  ["ivanoFrankivsk", "uzhhorod"],
  ["kamianetsPodilskyi", "chernivtsi"],
  ["kamianetsPodilskyi", "vinnytsia"],
  // --- cen 中部 ---
  ["vinnytsia", "uman"],
  ["vinnytsia", "odesa"],
  ["uman", "cherkasy"],
  ["uman", "kropyvnytskyi"],
  ["cherkasy", "poltava"],
  ["poltava", "kharkiv"],
  ["poltava", "kremenchuk"],
  ["poltava", "sumy"],
  ["kremenchuk", "kropyvnytskyi"],
  ["kremenchuk", "dnipro"],
  ["kropyvnytskyi", "odesa"],
  // --- south 南部・黒海/ドナウ沿岸 ---
  ["odesa", "mykolaiv"],
  ["odesa", "bilhorodDnistrovskyi"],
  ["bilhorodDnistrovskyi", "izmail"],
  ["izmail", "vylkove"],
  // --- east 東部 ---
  ["dnipro", "zaporizhzhia"],
  ["dnipro", "kharkiv"],
  ["dnipro", "poltava"],
  ["zaporizhzhia", "mykolaiv"],
  // --- 地方をまたぐ補助線(移動の選択肢を増やす) ---
  ["chernihiv", "sumy"],
  ["lutsk", "zhytomyr"],
  ["mykolaiv", "kropyvnytskyi"],
  ["chernivtsi", "vinnytsia"],
];
