/**
 * アフリカ大陸盤面の都市と路線(いまは5都市の見本のみ)。
 *
 * 大陸盤面の主題は「国をまたぐ話」。すでにモロッコとガーナの盤面があるので、
 * 同じ都市を選ぶ場合でも中身は変える(このファイルでは同じ都市はまだ選んでいない)。
 * この盤面固有の主題は「大陸を貫く鉄路がついに一本につながらなかったこと」——
 * 軌間が国ごとにバラバラ(1067mm/1000mm/1435mm)で、路線の大半は内陸の資源を
 * 港へ運ぶためだけに敷かれ、隣国とはもともと繋がる設計になっていない。
 * ケープ〜カイロ構想は完成せず、いま新しく敷かれている線(電化標準軌)は
 * その古い構図をようやく書き換え始めている、という筋。
 *
 * 地方区分(暫定、7つ。このファイルではまだ eaf/saf/hoa/caf/gof の5つしか
 * 使っていない): `mag` マグレブ・ナイル / `sah` サヘル・西アフリカ内陸 /
 * `gof` ギニア湾岸 / `caf` 中部アフリカ・コンゴ盆地 / `hoa` アフリカの角 /
 * `eaf` 東アフリカ・大湖地方 / `saf` 南部アフリカ。
 *
 * 経度・緯度は実際の値。投影の範囲は今後 geography.mjs で定義する
 * (団体側の見積りでは経度-17〜51度・緯度37〜-35度、都市1つあたり約90k px²
 * 目標なら BW≈2258×BH≈2391 前後になる見込み。都市総数が決まってから確定する)。
 *
 * ## この5都市で選んだ角度
 *
 * - ダルエスサラーム(`eaf`): タンザニア自前の鉄道(ドイツ・イギリスが敷いた
 *   メーターゲージ1000mm)と、中国が建設したタンザン鉄道TAZARA(ケープゲージ
 *   1067mm)が同じ市内の別々のターミナルに着き、いまも物理的につながっていない。
 *   「軌間の断絶」を都市の中の断絶として書く。
 * - カピリンポシ(`saf`): TAZARAのザンビア側終点。あえてザンビア既存網と
 *   同じ軌間で敷かれた点(ダルエスサラームとは対照的に軌間は揃っている)と、
 *   「白人少数支配のローデシア/南アフリカを通らずに銅を運ぶ」という
 *   建設そのものの政治的動機を書く。理想が薄れたあとの赤字も隠さない。
 * - ジブチ(`hoa`): 1917年開通のフランス製メーターゲージ線が朽ちて止まり、
 *   2018年の中国製電化標準軌線がそれに置き換わった。エリトリア戦争で
 *   陸封国エチオピアがこの港にいっそう依存するようになった経緯も書く。
 *   「いま新しく敷かれている線」の代表例。
 * - ルブンバシ(`caf`): カタンガの銅を運ぶために競合した3本の植民地鉄道
 *   (ベルギー領コンゴ川水系・イギリス領ローデシア経由・ポルトガル領
 *   アンゴラのベンゲラ鉄道)。どれも隣国を結ぶためではなく、資源を
 *   最短で港へ運ぶためだけに敷かれたという主題そのもの。
 * - ダカール(`gof`): ダカール〜ニジェール鉄道(1907〜1923年)は、内陸の
 *   交易をイギリス領ガンビア/シエラレオネの港へ逃がさないための線。
 *   国際旅客が途絶えたあと、2021年開通のTERは国境を越えない都市内路線
 *   になった——「植民地時代の線」と「いまの新線」を1都市で対比させる。
 *
 * モロッコとガーナの盤面にある都市は、この5都市では選んでいない。
 */
import { city, prop } from "../../content-overrides/city-helpers.mjs";

export const AFRICA_CITIES = {
  // ---------------------------------------------------------------------
  // eaf — 東アフリカ・大湖地方
  // ---------------------------------------------------------------------
  daressalaam: city(
    "Dar es Salaam|Dar es Salam|Dar es-Salaam|ダルエスサラーム",
    39.2083, -6.7924, "eaf", "gauge", "portrail", "l",
    "A port where two railways still don't touch tracks|Un puerto donde dos anchos de vía todavía no se tocan|Un port où deux écartements ne se touchent toujours pas|二つの軌間がいまも触れ合わない港",
    "Tanzania's own railway, built to metre gauge (1,000mm) by German and British colonizers from 1905, reaches the harbour at Dar es Salaam from one side of downtown; the Tanzania–Zambia Railway (TAZARA), opened in 1975 on the wider Cape gauge (1,067mm) with Chinese financing and around 50,000 Chinese engineers and labourers over the course of construction, reaches it from a separate terminal on the other side. The two networks have never been physically linked, so freight switching between them is trucked across the city instead of simply rolled from one gauge onto the other.|La red ferroviaria propia de Tanzania, tendida con ancho métrico (1.000 mm) por los colonizadores alemanes y británicos desde 1905, llega al puerto de Dar es Salaam desde un lado del centro; el Ferrocarril Tanzania-Zambia (TAZARA), inaugurado en 1975 con el ancho Cabo más amplio (1.067 mm), financiado por China y construido por unos 50.000 ingenieros y obreros chinos a lo largo de la obra, llega a él desde una terminal aparte al otro lado. Las dos redes nunca se han conectado físicamente, así que la carga que cambia de una a otra se transporta en camión a través de la ciudad en vez de simplemente rodar de un ancho al otro.|Le réseau ferroviaire propre à la Tanzanie, posé à l'écartement métrique (1 000 mm) par les colonisateurs allemands puis britanniques à partir de 1905, atteint le port de Dar es Salaam d'un côté du centre-ville ; le chemin de fer Tanzanie-Zambie (TAZARA), ouvert en 1975 à l'écartement Cap plus large (1 067 mm), financé par la Chine et construit par environ 50 000 ingénieurs et ouvriers chinois au fil du chantier, l'atteint depuis un terminus séparé de l'autre côté. Les deux réseaux n'ont jamais été physiquement reliés, si bien que le fret changeant de l'un à l'autre est transporté en camion à travers la ville plutôt que simplement roulé d'un écartement à l'autre.|ドイツとイギリスの植民地当局が1905年から敷いたタンザニア自前の鉄道網は、軌間1000mm(メーターゲージ)で市街の一方からダルエスサラームの港に達する。中国の資金援助と、のべ約5万人の中国人技術者・労働者によって1975年に開通したタンザン鉄道(TAZARA)は、より広い軌間1067mm(ケープゲージ)で市の反対側の別のターミナルから港に達する。二つの鉄道網はいまも物理的につながっておらず、貨物の積み替えは軌間を履き替えるのではなく、トラックで市内を横切って運ばれる。",
    [prop("TAZARA Terminus Platform|Andén de la terminal de TAZARA|Quai du terminus du TAZARA|タンザン鉄道ターミナルのホーム", 900, 185),
     prop("Central Line Break-of-Gauge Yard|Patio de cambio de ancho de la Línea Central|Cour de changement d'écartement de la ligne centrale|セントラル線の軌間境界操車場", 500, 103)],
  ),
  zanzibar: city(
    "Zanzibar|Zanzíbar|Zanzibar|ザンジバル",
    39.1975, -6.1659, "eaf", "dhow", "swahilicoast", "l",
    "An island whose only rail line served a sultan, not the public|Una isla cuya única línea férrea servía a un sultán, no al público|Une île dont l'unique ligne ferroviaire servait un sultan, pas le public|唯一の鉄道が公衆ではなくスルタンに仕えた島",
    "Zanzibar's Sultan Barghash built a short private railway in the early 1880s to link his palace to a summer retreat, one of the earliest railways anywhere in East Africa and one of the few built anywhere on the continent never meant to carry ordinary passengers or freight to a port at all; it fell out of use not long after his death in 1888, and nothing of it survives above ground today. The island's economy still runs partly on the clove trade that made Zanzibar one of the wealthiest sultanates on the Swahili coast, and its only fixed link to the mainland remains the ferry — no bridge or causeway has ever been built across the strait.|El sultán Barghash de Zanzíbar construyó un breve ferrocarril privado a principios de la década de 1880 para unir su palacio con un retiro de verano, uno de los primeros ferrocarriles de África Oriental y uno de los pocos construidos en el continente que nunca estuvo pensado para llevar pasajeros o mercancías corrientes hasta un puerto; cayó en desuso poco después de su muerte en 1888, y hoy no queda nada de él sobre el terreno. La economía de la isla todavía se apoya en parte en el comercio del clavo que hizo de Zanzíbar uno de los sultanatos más ricos de la costa suajili, y su único enlace fijo con el continente sigue siendo el ferry: nunca se ha construido un puente o calzada sobre el estrecho.|Le sultan Barghash de Zanzibar fit construire au début des années 1880 un court chemin de fer privé reliant son palais à une résidence d'été, l'un des tout premiers chemins de fer d'Afrique de l'Est et l'un des rares construits sur le continent jamais destinés à transporter passagers ou marchandises ordinaires vers un port ; il tomba en désuétude peu après sa mort en 1888, et il n'en subsiste rien en surface aujourd'hui. L'économie de l'île repose encore en partie sur le commerce du clou de girofle qui fit de Zanzibar l'un des sultanats les plus riches de la côte swahilie, et son seul lien fixe avec le continent reste le ferry : aucun pont ni chaussée n'a jamais été construit sur le détroit.|ザンジバルのスルタン、バルガシュは1880年代初め、自らの宮殿と避暑の別邸を結ぶ短い私設鉄道を敷いた。東アフリカでも最初期の鉄道の一つでありながら、大陸のどこでも珍しく、一般の旅客や貨物を港へ運ぶためのものではなかった。1888年に彼が没するとほどなく使われなくなり、いまは地上に何も残っていない。島の経済はいまも、ザンジバルをスワヒリ海岸有数の富裕なスルタン国にしたクローブ交易にいくらか支えられている。本土との唯一の固定的な結びつきはいまもフェリーであり、海峡に橋や堤道が架けられたことは一度も無い。",
    [prop("Mtoni Palace Rail Trace|Traza ferroviaria del palacio de Mtoni|Trace ferroviaire du palais de Mtoni|ムトニ宮殿の鉄道跡", 620, 128),
     prop("Stone Town Clove Warehouse|Almacén de clavo de Stone Town|Entrepôt à clous de girofle de Stone Town|ストーンタウンのクローブ倉庫", 480, 99)],
  ),
  kigoma: city(
    "Kigoma|Kigoma|Kigoma|キゴマ",
    29.6267, -4.8766, "eaf", "riverport", "rivercrossing", "r",
    "Where the railway stops and a lake ferry takes over|Donde el ferrocarril se detiene y un ferry de lago toma el relevo|Où le chemin de fer s'arrête et où un ferry lacustre prend le relais|鉄道が尽き、湖の渡し船が引き継ぐ場所",
    "The German-built Central Line reached Kigoma on the shore of Lake Tanganyika in 1914, giving landlocked Burundi and eastern Congo their shortest route to the Indian Ocean: goods travelled by lake steamer to Kigoma, then by rail to Dar es Salaam, a combination that still runs today aboard the MV Liemba, a German warship built in 1913, scuttled during the First World War, then raised and refitted as a civilian ferry that has sailed the lake since 1927 — one of the oldest passenger ships still in regular service anywhere in the world. No railway has ever continued past Kigoma into Congo or Burundi; the lake itself remains the only link.|La Línea Central, construida por Alemania, llegó a Kigoma, a orillas del lago Tanganica, en 1914, dando a Burundi y al este del Congo, ambos sin salida al mar, su ruta más corta hacia el océano Índico: las mercancías viajaban en vapor lacustre hasta Kigoma y luego en tren hasta Dar es Salaam, una combinación que sigue funcionando hoy a bordo del MV Liemba, un buque de guerra alemán construido en 1913, hundido durante la Primera Guerra Mundial y luego reflotado y adaptado como ferry civil que navega el lago desde 1927, uno de los buques de pasajeros más antiguos aún en servicio regular en el mundo. Ningún ferrocarril ha continuado nunca más allá de Kigoma hacia el Congo o Burundi; el lago sigue siendo el único enlace.|La Ligne centrale, construite par les Allemands, atteignit Kigoma, sur les rives du lac Tanganyika, en 1914, donnant au Burundi et à l'est du Congo, tous deux enclavés, leur route la plus courte vers l'océan Indien : les marchandises voyageaient par vapeur lacustre jusqu'à Kigoma, puis par rail jusqu'à Dar es Salaam, une combinaison qui fonctionne encore aujourd'hui à bord du MV Liemba, un navire de guerre allemand construit en 1913, sabordé pendant la Première Guerre mondiale, puis renfloué et transformé en ferry civil naviguant sur le lac depuis 1927 — l'un des plus anciens navires à passagers encore en service régulier au monde. Aucun chemin de fer n'a jamais continué au-delà de Kigoma vers le Congo ou le Burundi ; le lac reste l'unique lien.|ドイツが建設したセントラル線は1914年、タンガニーカ湖畔のキゴマに達し、内陸国ブルンジとコンゴ東部にとってインド洋への最短路を与えた。貨物は湖の汽船でキゴマまで運ばれ、そこから鉄道でダルエスサラームへ向かう。この組み合わせはいまもMVリエンバ号によって続いている。1913年建造のドイツの軍艦として生まれ、第一次世界大戦中に自沈させられたのち引き揚げられて民間フェリーに改装され、1927年からこの湖を航行している、世界でもまだ定期運航を続ける最古級の旅客船である。キゴマの先へコンゴやブルンジまで続いた鉄道は一度も無く、いまも湖そのものが唯一の連絡路である。",
    [prop("Kigoma Central Line Terminus|Terminal de la Línea Central de Kigoma|Terminus de la Ligne centrale de Kigoma|キゴマ・セントラル線の終着駅", 500, 103),
     prop("MV Liemba Ferry Berth|Atracadero del ferry MV Liemba|Poste d'amarrage du ferry MV Liemba|MVリエンバ号の発着桟橋", 380, 78)],
  ),
  nairobi: city(
    "Nairobi|Nairobi|Nairobi|ナイロビ",
    36.8219, -1.2921, "eaf", "wildlife", "savannah", "l",
    "A railway supply camp that was never meant to become a capital|Un campamento de suministro ferroviario que nunca debía ser capital|Un camp d'approvisionnement ferroviaire qui ne devait jamais devenir une capitale|首都になるはずではなかった鉄道の補給基地",
    "Nairobi did not exist before 1899, when British engineers building the Uganda Railway from Mombasa chose the site — flat, well-watered, roughly halfway to Lake Victoria — purely as a supply depot and railhead, not as anywhere anyone planned to live permanently. British newspapers mocked the whole project as the 'Lunatic Express' for its enormous cost and the workers killed by disease, accidents and lions during construction, yet the railway camp grew into East Africa's largest city and, in 2017, got a new standard-gauge line built by China running roughly alongside the old one.|Nairobi no existía antes de 1899, cuando los ingenieros británicos que construían el Ferrocarril de Uganda desde Mombasa eligieron el emplazamiento —llano, bien regado, casi a medio camino del lago Victoria— solo como depósito de suministros y cabecera de línea, no como un lugar donde nadie planeara vivir de forma permanente. Los periódicos británicos ridiculizaron todo el proyecto llamándolo el 'Expreso Lunático' por su enorme coste y los trabajadores muertos por enfermedad, accidentes y leones durante la construcción, pero el campamento ferroviario creció hasta convertirse en la mayor ciudad de África Oriental y, en 2017, obtuvo una nueva línea de ancho estándar construida por China que discurre casi junto a la antigua.|Nairobi n'existait pas avant 1899, quand les ingénieurs britanniques construisant le chemin de fer de l'Ouganda depuis Mombasa choisirent le site — plat, bien arrosé, à peu près à mi-chemin du lac Victoria — uniquement comme dépôt de ravitaillement et tête de ligne, et non comme un lieu où quiconque prévoyait de s'installer durablement. La presse britannique tourna tout le projet en dérision, le surnommant l'« Express du Fou » pour son coût énorme et les ouvriers tués par la maladie, les accidents et les lions pendant la construction, mais le camp ferroviaire devint la plus grande ville d'Afrique de l'Est et obtint en 2017 une nouvelle ligne à écartement standard construite par la Chine, courant à peu près à côté de l'ancienne.|ナイロビは1899年以前には存在しなかった。モンバサから延びるウガンダ鉄道を建設していたイギリス人技師たちが、平らで水に恵まれ、ヴィクトリア湖までのほぼ中間にあるこの土地を、誰かが住み着くための場所としてではなく、単なる補給基地・起点として選んだのが始まりである。イギリスの新聞は莫大な費用と、建設中に病気・事故・ライオンで命を落とした労働者たちを揶揄して、この事業全体を「ルナティック・エクスプレス(狂人急行)」と呼んだ。それでもこの鉄道の宿営地は東アフリカ最大の都市へと育ち、2017年には中国建設の新標準軌線が旧線とほぼ並んで開通した。",
    [prop("Nairobi Railway Museum Yard|Patio del Museo Ferroviario de Nairobi|Cour du musée du chemin de fer de Nairobi|ナイロビ鉄道博物館の車両基地", 700, 144),
     prop("SGR Terminus Concourse|Vestíbulo de la terminal del SGR|Hall du terminus du SGR|SGR新線ターミナルのコンコース", 1200, 248)],
  ),
  mombasa: city(
    "Mombasa|Mombasa|Mombasa|モンバサ",
    39.6682, -4.0435, "eaf", "port", "swahilicoast", "l",
    "The port where a colonial railway began, and a modern debt story too|El puerto donde empezó un ferrocarril colonial, y también una historia de deuda moderna|Le port où débuta un chemin de fer colonial, et une histoire de dette moderne aussi|植民地鉄道が始まり、現代の債務の物語も始まった港",
    "Mombasa was the starting point of the Uganda Railway, begun in 1896 with crews that included around 32,000 indentured labourers brought from British India, several thousand of whom died before the line reached Lake Victoria in 1901; many of their descendants form the Indian communities still prominent in Mombasa and Nairobi today. In 2017 Mombasa became the starting point of a new standard-gauge line again, this time built with Chinese loans so large and opaque that a leaked 2018 audit report raised fears the port itself could be seized as collateral if Kenya defaulted, a controversy that made headlines far beyond East Africa even after officials denied it.|Mombasa fue el punto de partida del Ferrocarril de Uganda, iniciado en 1896 con cuadrillas que incluían a unos 32.000 trabajadores contratados traídos de la India británica, varios miles de los cuales murieron antes de que la línea llegara al lago Victoria en 1901; muchos de sus descendientes forman las comunidades indias todavía destacadas hoy en Mombasa y Nairobi. En 2017 Mombasa volvió a ser el punto de partida de una nueva línea de ancho estándar, esta vez construida con préstamos chinos tan grandes y opacos que un informe de auditoría filtrado en 2018 despertó temores de que el propio puerto pudiera embargarse como garantía si Kenia incumplía, una polémica que fue noticia mucho más allá de África Oriental incluso después de que las autoridades lo negaran.|Mombasa fut le point de départ du chemin de fer de l'Ouganda, entamé en 1896 avec des équipes comptant environ 32 000 travailleurs sous contrat venus des Indes britanniques, dont plusieurs milliers moururent avant que la ligne n'atteigne le lac Victoria en 1901 ; nombre de leurs descendants forment les communautés indiennes encore importantes aujourd'hui à Mombasa et Nairobi. En 2017, Mombasa redevint le point de départ d'une nouvelle ligne à écartement standard, cette fois construite avec des prêts chinois si importants et opaques qu'un rapport d'audit divulgué en 2018 fit craindre que le port lui-même puisse être saisi en garantie en cas de défaut du Kenya, une controverse qui fit la une bien au-delà de l'Afrique de l'Est même après les démentis officiels.|モンバサはウガンダ鉄道の起点であり、1896年に始まった建設にはイギリス領インドから連れてこられた契約労働者約3万2000人が加わり、そのうち数千人が1901年にヴィクトリア湖へ路線が達するまでに命を落とした。彼らの子孫の多くは、いまもモンバサやナイロビで存在感を持つインド系コミュニティを形成している。2017年、モンバサは再び新標準軌線の起点となったが、今度は中国からの融資があまりに巨額かつ不透明だったため、2018年に流出した監査報告書がケニアの債務不履行時に港そのものが担保として差し押さえられかねないとの懸念を呼び、当局が否定したあとも東アフリカを越えて大きく報じられる論争になった。",
    [prop("1896 Railway Survey Camp Site|Emplazamiento del campamento de estudio ferroviario de 1896|Site du camp d'étude ferroviaire de 1896|1896年鉄道測量基地跡", 550, 113),
     prop("SGR Container Terminal|Terminal de contenedores del SGR|Terminal à conteneurs du SGR|SGRコンテナターミナル", 1050, 216)],
  ),
  voi: city(
    "Voi|Voi|Voi|ヴォイ",
    38.5561, -3.3961, "eaf", "wildlife", "savannah", "r",
    "The junction where lions stopped a railway for nine months|El empalme donde unos leones detuvieron un ferrocarril durante nueve meses|La jonction où des lions ont arrêté un chemin de fer pendant neuf mois|ライオンが9か月間、鉄道を止めた分岐点",
    "Construction of the Uganda Railway stalled for about nine months in 1898 near Voi and the Tsavo River when two male lions killed an estimated 28 to 35 Indian and African workers, dragging some out of their tents at night; the bridge engineer who eventually shot both lions later wrote a bestselling account that turned the incident into one of colonial Africa's most famous animal stories. Voi grew up as the junction where a branch line splits off toward Taveta and the Tanzanian border, on the edge of the Tsavo National Parks the same railway helped open up to hunting and, later, tourism.|La construcción del Ferrocarril de Uganda se estancó unos nueve meses en 1898 cerca de Voi y el río Tsavo cuando dos leones machos mataron a entre 28 y 35 trabajadores indios y africanos, arrastrando a algunos fuera de sus tiendas por la noche; el ingeniero del puente que finalmente abatió a ambos leones escribió después un relato superventas que convirtió el incidente en una de las historias animales más famosas del África colonial. Voi creció como el empalme donde un ramal se desvía hacia Taveta y la frontera con Tanzania, al borde de los parques nacionales de Tsavo que el mismo ferrocarril ayudó a abrir a la caza y, después, al turismo.|La construction du chemin de fer de l'Ouganda s'arrêta environ neuf mois en 1898 près de Voi et de la rivière Tsavo, quand deux lions mâles tuèrent entre 28 et 35 ouvriers indiens et africains selon les estimations, en traînant certains hors de leurs tentes la nuit ; l'ingénieur du pont qui finit par abattre les deux lions écrivit ensuite un récit à succès qui fit de l'incident l'une des plus célèbres histoires animalières de l'Afrique coloniale. Voi grandit comme la jonction où un embranchement part vers Taveta et la frontière tanzanienne, en bordure des parcs nationaux de Tsavo que ce même chemin de fer contribua à ouvrir à la chasse puis au tourisme.|1898年、ウガンダ鉄道の建設はヴォイとツァボ川付近で約9か月間止まった。二頭の雄ライオンが推定28〜35人のインド人・アフリカ人労働者を殺し、夜にはテントから引きずり出すこともあったからである。最終的に両方のライオンを仕留めた橋梁技師は、のちにベストセラーとなる手記を著し、この出来事は植民地時代のアフリカで最も有名な動物にまつわる話の一つになった。ヴォイは、タヴェタとタンザニア国境へ向かう支線が分かれる分岐点として育ち、同じ鉄道が狩猟、のちに観光のために切り開いたツァボ国立公園群のすぐそばにある。",
    [prop("Tsavo Bridge Overlook|Mirador del puente sobre el Tsavo|Belvédère du pont sur le Tsavo|ツァボ橋の展望台", 460, 95),
     prop("Voi–Taveta Branch Platform|Andén del ramal Voi-Taveta|Quai de l'embranchement Voi-Taveta|ヴォイ―タヴェタ支線のホーム", 260, 54)],
  ),
  kampala: city(
    "Kampala|Kampala|Kampala|カンパラ",
    32.5825, 0.3476, "eaf", "capital", "capitalcity", "l",
    "The capital the railway named after it took thirty years longer to reach|La capital que el ferrocarril con su nombre tardó treinta años más en alcanzar|La capitale que le chemin de fer censé la desservir mit trente ans de plus à atteindre|自分の名を冠した鉄道が三十年遅れて届いた首都",
    "The Uganda Railway, despite its name, took until 1931 to actually reach Kampala, more than thirty years after the line began at Mombasa in 1896 — for most of that time it stopped well short, at Kisumu on Lake Victoria, and goods and passengers finished the journey to Uganda by lake steamer. A newer standard-gauge extension meant to finally link Kampala directly to Mombasa without the steamer leg has been under discussion and partial construction for years without being completed.|El Ferrocarril de Uganda, pese a su nombre, tardó hasta 1931 en llegar de verdad a Kampala, más de treinta años después de que la línea empezara en Mombasa en 1896; durante la mayor parte de ese tiempo se detenía mucho antes, en Kisumu, a orillas del lago Victoria, y las mercancías y pasajeros terminaban el trayecto a Uganda en vapor lacustre. Una nueva ampliación de ancho estándar pensada para por fin unir Kampala directamente con Mombasa sin el tramo en barco lleva años en discusión y construcción parcial sin completarse.|Le chemin de fer de l'Ouganda, malgré son nom, mit jusqu'en 1931 à atteindre réellement Kampala, plus de trente ans après le début de la ligne à Mombasa en 1896 — pendant la majeure partie de cette période, il s'arrêtait bien avant, à Kisumu sur le lac Victoria, et marchandises et voyageurs achevaient le trajet vers l'Ouganda par vapeur lacustre. Une nouvelle extension à écartement standard censée enfin relier Kampala directement à Mombasa sans le tronçon fluvial est en discussion et en construction partielle depuis des années sans avoir été achevée.|ウガンダ鉄道は、その名にもかかわらず、実際にカンパラへ達するまで1931年までかかった。1896年にモンバサで着工してから三十年以上が経っていた。その大半の期間、路線はヴィクトリア湖畔のキスムでいったん止まっており、貨物も旅客も湖の汽船でウガンダへの残りの行程を終えていた。蒸気船の区間を経ずにカンパラをモンバサへ直接結ぶはずの新しい標準軌延伸は、何年も議論と部分的な建設が続いたまま完成していない。",
    [prop("1931 Kampala Extension Terminus|Terminal de la ampliación de Kampala de 1931|Terminus de l'extension de Kampala de 1931|1931年カンパラ延伸線の終着駅", 780, 161),
     prop("Lake Victoria Steamer Quay|Muelle del vapor del lago Victoria|Quai du vapeur du lac Victoria|ヴィクトリア湖汽船の埠頭", 420, 87)],
  ),
  tororo: city(
    "Tororo|Tororo|Tororo|トロロ",
    34.1811, 0.6928, "eaf", "junction", "railjunction", "r",
    "A junction where one line splits toward two different lakes|Un empalme donde una línea se divide hacia dos lagos distintos|Une jonction où une ligne se scinde vers deux lacs différents|一本の線が二つの湖へ分かれる分岐点",
    "Tororo grew around the point where the railway from Kenya forks in Uganda: one branch continues to Jinja and on to Kampala near Lake Victoria, the other runs north toward Lira and eventually Gulu and Pakwach, a line completed in stages through the mid-20th century, following limestone deposits that still support a large cement works beside the tracks today. The town's single distinctive hill, Tororo Rock, rises straight out of the flat plain the railway had to cross to reach it, a rare vertical landmark on an otherwise featureless stretch of line.|Tororo creció en torno al punto donde el ferrocarril procedente de Kenia se bifurca en Uganda: un ramal sigue hacia Jinja y luego Kampala, cerca del lago Victoria; el otro va al norte hacia Lira y, con el tiempo, Gulu y Pakwach, una línea completada por etapas a mediados del siglo XX, siguiendo los yacimientos de caliza que todavía sostienen una gran fábrica de cemento junto a las vías. La única colina distintiva del pueblo, Tororo Rock, se alza justo en medio de la llanura que el ferrocarril tuvo que cruzar para llegar hasta ella, un raro hito vertical en un tramo por lo demás sin rasgos.|Tororo grandit autour du point où le chemin de fer venu du Kenya se divise en Ouganda : un embranchement continue vers Jinja puis Kampala, près du lac Victoria ; l'autre part vers le nord en direction de Lira puis, à terme, Gulu et Pakwach, une ligne achevée par étapes au milieu du XXe siècle, suivant des gisements de calcaire qui font encore vivre aujourd'hui une grande cimenterie près des voies. L'unique colline remarquable de la ville, Tororo Rock, surgit tout droit de la plaine plate que le chemin de fer dut traverser pour l'atteindre, rare repère vertical sur un tronçon par ailleurs sans relief.|トロロは、ケニアから来る鉄道がウガンダで分岐する地点を中心に育った町である。一方の支線はジンジャを経てヴィクトリア湖に近いカンパラへ、もう一方は北へリラ、やがてグルとパクワチへ向かい、20世紀半ばにかけて段階的に完成した。この北への路線は石灰岩の鉱床沿いに敷かれ、いまも線路脇の大きなセメント工場を支えている。町の目立つ唯一の丘、トロロ・ロックは、鉄道がそこへ達するために横切らねばならなかった平坦な平原からまっすぐそびえ立ち、それ以外は特徴のない路線区間の中で数少ない目印となっている。",
    [prop("Tororo Cement Rail Siding|Vía muerta de la cementera de Tororo|Voie de garage de la cimenterie de Tororo|トロロ・セメント工場の側線", 480, 99),
     prop("Tororo Rock Junction Platform|Andén del empalme de Tororo Rock|Quai de la jonction de Tororo Rock|トロロ・ロック分岐駅のホーム", 300, 62)],
  ),
  kigali: city(
    "Kigali|Kigali|Kigali|キガリ",
    30.0619, -1.9441, "eaf", "capital", "capitalcity", "l",
    "A capital the railway still hasn't reached|Una capital a la que el ferrocarril aún no ha llegado|Une capitale que le chemin de fer n'a toujours pas atteinte|鉄道がいまだ届いていない首都",
    "Rwanda has never had a single kilometre of railway; everything that reaches Kigali still comes by road from ports in Kenya, Tanzania or Mozambique hundreds of kilometres away, a gap that makes landlocked Rwanda's freight costs among the highest in East Africa. A standard-gauge line meant to finally connect Kigali to the Tanzanian port of Dar es Salaam or the inland hub of Isaka has been planned, delayed and re-planned since the 2010s, so for now the closest railway to the capital is still in a neighbouring country.|Ruanda nunca ha tenido ni un kilómetro de ferrocarril; todo lo que llega a Kigali sigue viniendo por carretera desde puertos de Kenia, Tanzania o Mozambique a cientos de kilómetros de distancia, una carencia que hace que los costes de flete de Ruanda, sin salida al mar, estén entre los más altos de África Oriental. Una línea de ancho estándar pensada para por fin conectar Kigali con el puerto tanzano de Dar es Salaam o con el nudo interior de Isaka lleva planeándose, retrasándose y replaneándose desde la década de 2010, así que por ahora el ferrocarril más cercano a la capital sigue estando en un país vecino.|Le Rwanda n'a jamais eu le moindre kilomètre de chemin de fer ; tout ce qui arrive à Kigali vient encore par la route depuis des ports au Kenya, en Tanzanie ou au Mozambique, à des centaines de kilomètres, un manque qui rend les coûts de fret du Rwanda enclavé parmi les plus élevés d'Afrique de l'Est. Une ligne à écartement standard censée enfin relier Kigali au port tanzanien de Dar es Salaam ou au nœud intérieur d'Isaka est planifiée, retardée et replanifiée depuis les années 2010, si bien que pour l'instant le chemin de fer le plus proche de la capitale se trouve encore dans un pays voisin.|ルワンダには鉄道が一キロメートルたりとも存在したことがない。キガリに届くものはすべて、数百キロ離れたケニア・タンザニア・モザンビークの港からいまも道路で運ばれており、この空白のせいで内陸国ルワンダの貨物輸送費は東アフリカでも屈指の高さになっている。キガリをタンザニアのダルエスサラーム港、あるいは内陸の結節点イサカへついに結ぶはずの標準軌新線は、2010年代からずっと計画・延期・再計画が繰り返されており、いまのところ首都に最も近い鉄道はいまだ隣国にある。",
    [prop("Gikondo Dry Port Yard|Patio del puerto seco de Gikondo|Cour du port sec de Gikondo|ギコンド・ドライポート操車場", 550, 113),
     prop("Kigali Road Freight Depot|Depósito de carga por carretera de Kigali|Dépôt de fret routier de Kigali|キガリ道路貨物基地", 380, 78)],
  ),
  antananarivo: city(
    "Antananarivo|Antananarivo|Antananarivo|アンタナナリボ",
    47.5079, -18.8792, "eaf", "riverport", "sahara", "r",
    "An island network that never touched the mainland, and mostly stopped anyway|Una red isleña que nunca tocó el continente, y aun así casi se detuvo del todo|Un réseau insulaire qui n'a jamais touché le continent, et qui s'est presque arrêté quand même|大陸に触れないまま、それでもほぼ止まってしまった島の鉄道網",
    "Madagascar's railways, begun by the French in 1901, were always going to serve only the island's own ports, since Madagascar sits hundreds of kilometres from the African mainland across the Mozambique Channel; even the island's own two rail networks were never connected to each other, and after independence much of the network around the capital fell into disrepair, with passenger service suspended for long stretches since the 2000s. The separate narrow-gauge FCE line, running from Fianarantsoa to Manakara on the east coast, survives mainly as a freight and tourist run through rainforest too steep and roadless for trucks to reach as easily.|Los ferrocarriles de Madagascar, iniciados por Francia en 1901, siempre estuvieron destinados a servir solo a los propios puertos de la isla, ya que Madagascar se encuentra a cientos de kilómetros del continente africano al otro lado del canal de Mozambique; ni siquiera las dos redes ferroviarias propias de la isla llegaron a conectarse entre sí, y tras la independencia buena parte de la red en torno a la capital se deterioró, con el servicio de pasajeros suspendido por largos periodos desde la década de 2000. La línea aparte de vía estrecha FCE, que va de Fianarantsoa a Manakara en la costa este, sobrevive sobre todo como recorrido de carga y turístico por una selva demasiado empinada y sin carreteras para que los camiones lleguen con la misma facilidad.|Les chemins de fer de Madagascar, entamés par les Français en 1901, n'ont toujours été destinés qu'à desservir les propres ports de l'île, Madagascar se trouvant à des centaines de kilomètres du continent africain de l'autre côté du canal du Mozambique ; même les deux réseaux ferroviaires propres à l'île n'ont jamais été reliés entre eux, et après l'indépendance, une grande partie du réseau autour de la capitale se dégrada, le service voyageurs étant suspendu de longues périodes depuis les années 2000. La ligne à voie étroite distincte du FCE, allant de Fianarantsoa à Manakara sur la côte est, survit surtout comme liaison de fret et touristique à travers une forêt tropicale trop abrupte et sans routes pour que les camions y accèdent aussi facilement.|マダガスカルの鉄道は1901年にフランスによって始められたが、モザンビーク海峡を挟んでアフリカ大陸から数百キロ離れているため、もとから島内の港に仕えるだけの存在だった。島に二つあった鉄道網どうしですら一度もつながったことがなく、独立後は首都周辺の路線網の多くが荒廃し、2000年代以降は旅客サービスが長期にわたって止まったままの区間もある。フィアナランツォアから東海岸のマナカラまで走る別系統の狭軌線FCEは、トラックが同じようには入り込めない急峻で道路の無い熱帯雨林を抜ける貨物・観光用の路線として、おもに生き残っている。",
    [prop("Soarano Station Concourse|Vestíbulo de la estación de Soarano|Hall de la gare de Soarano|ソアラノ駅のコンコース", 620, 128),
     prop("Manakara Rainforest Rail Halt|Apeadero ferroviario de la selva de Manakara|Halte ferroviaire de la forêt de Manakara|マナカラ熱帯雨林の停車場", 340, 70)],
  ),
  // ---------------------------------------------------------------------
  kapirimposhi: city(
    "New Kapiri Mposhi|Nueva Kapiri Mposhi|New Kapiri Mposhi|ニューカピリンポシ",
    28.6833, -13.9667, "saf", "junction", "railjunction", "r",
    "A junction chosen so Zambia's copper could avoid two countries|Un empalme elegido para que el cobre de Zambia evitara dos países|Une jonction choisie pour que le cuivre zambien évite deux pays|ザンビアの銅が二つの国を避けるために選ばれた分岐点",
    "When Zambia's government looked for a copper export route that touched neither white-minority-ruled Rhodesia nor apartheid South Africa, China agreed to build TAZARA, laying it deliberately to the same 1,067mm gauge as Zambia's own network so wagons could roll straight from one system onto the other. New Kapiri Mposhi, a stop 200km north of Lusaka with little else to distinguish it, became the line's Zambian terminus when it opened in 1975; once white-minority rule ended in both neighbouring countries during the 1980s and 1990s, cheaper southern routes drew most of the copper traffic back, and TAZARA has run at a loss for decades since.|Cuando el gobierno de Zambia buscó una ruta de exportación de cobre que no tocara ni la Rodesia gobernada por la minoría blanca ni la Sudáfrica del apartheid, China aceptó construir el TAZARA, tendido deliberadamente con el mismo ancho de 1.067 mm que la propia red zambiana para que los vagones pudieran pasar directamente de un sistema a otro. Nueva Kapiri Mposhi, una parada 200 km al norte de Lusaka sin nada más que la distinguiera, se convirtió en la terminal zambiana de la línea cuando esta abrió en 1975; una vez que el gobierno de la minoría blanca terminó en los dos países vecinos durante los años ochenta y noventa, las rutas del sur, más baratas, recuperaron la mayor parte del tráfico de cobre, y el TAZARA lleva décadas operando con pérdidas.|Quand le gouvernement zambien a cherché une route d'exportation du cuivre qui ne touche ni la Rhodésie dirigée par la minorité blanche ni l'Afrique du Sud de l'apartheid, la Chine a accepté de construire le TAZARA, posé délibérément au même écartement de 1 067 mm que le réseau zambien lui-même afin que les wagons puissent rouler directement d'un système à l'autre. New Kapiri Mposhi, un arrêt à 200 km au nord de Lusaka sans rien d'autre pour le distinguer, devint le terminus zambien de la ligne à son ouverture en 1975 ; une fois le pouvoir de la minorité blanche tombé dans les deux pays voisins durant les années 1980 et 1990, des routes méridionales moins chères ont récupéré l'essentiel du trafic de cuivre, et le TAZARA fonctionne à perte depuis des décennies.|ザンビア政府が、白人少数支配下のローデシアにもアパルトヘイト下の南アフリカにも触れない銅の輸出路を探していたとき、中国はザンビア自前の鉄道網と同じ軌間1067mmであえて敷いたタンザン鉄道の建設を引き受けた。これにより貨車は一方の路線からもう一方へそのまま乗り入れられる。ルサカの北200kmにある、それ以外は特に目立たない駅だったニューカピリンポシは、1975年の開通時にこの路線のザンビア側終点となった。しかし1980〜90年代に両隣国の白人少数支配が終わると、より安価な南回りの経路が銅の輸送の大半を取り戻し、タンザン鉄道はそれ以来数十年にわたって赤字を続けている。",
    [prop("New Kapiri Mposhi Terminus Hall|Sala de la terminal de Nueva Kapiri Mposhi|Salle du terminus de New Kapiri Mposhi|ニューカピリンポシ駅の待合ホール", 400, 82),
     prop("Zambia Railways Interchange Sidings|Vías de enlace de Zambia Railways|Voies de raccordement de Zambia Railways|ザンビア鉄道の連絡側線", 260, 54)],
  ),

  // ---------------------------------------------------------------------
  // hoa — アフリカの角
  // ---------------------------------------------------------------------
  djibouti: city(
    "Djibouti|Yibuti|Djibouti|ジブチ",
    43.1456, 11.5885, "hoa", "electric", "desertport", "l",
    "The port that outlived its railway, then got a faster one|El puerto que sobrevivió a su ferrocarril, y luego tuvo uno más rápido|Le port qui a survécu à son chemin de fer, puis en a eu un plus rapide|自らの鉄道より長生きし、やがてより速い鉄道を得た港",
    "The French-built, metre-gauge Djibouti–Addis Ababa railway opened in 1917 as Ethiopia's only rail link to the sea and stayed the country's main outside connection for most of the 20th century, before decades of poor maintenance slowed it to a crawl and it stopped running altogether in the 2000s. Ethiopia lost access to Eritrea's ports after a 1998–2000 border war, making Djibouti's harbour even more essential, and in 2018 a new Chinese-built, electrified standard-gauge line reopened the same route at speeds the old one never came close to; it now carries over 90% of landlocked Ethiopia's trade.|El ferrocarril Djibouti-Adís Abeba, construido por Francia con ancho métrico, se inauguró en 1917 como el único enlace ferroviario de Etiopía con el mar y siguió siendo la principal conexión exterior del país durante casi todo el siglo XX, hasta que décadas de mal mantenimiento lo redujeron a paso de tortuga y dejó de circular por completo en los años 2000. Etiopía perdió el acceso a los puertos de Eritrea tras una guerra fronteriza en 1998-2000, lo que hizo aún más esencial el puerto de Yibuti, y en 2018 una nueva línea de ancho estándar, electrificada y construida por China, reabrió la misma ruta a velocidades que la antigua jamás alcanzó; hoy transporta más del 90% del comercio de la Etiopía sin salida al mar.|Le chemin de fer Djibouti-Addis-Abeba, construit par la France à l'écartement métrique, ouvrit en 1917 comme unique liaison ferroviaire de l'Éthiopie vers la mer et resta la principale connexion extérieure du pays pendant presque tout le XXe siècle, avant que des décennies de mauvais entretien ne le ralentissent à une allure d'escargot et qu'il ne cesse totalement de circuler dans les années 2000. L'Éthiopie perdit l'accès aux ports érythréens après une guerre frontalière en 1998-2000, rendant le port de Djibouti encore plus essentiel, et en 2018 une nouvelle ligne à écartement standard, électrifiée et construite par la Chine, rouvrit le même trajet à des vitesses que l'ancienne n'avait jamais approchées ; elle transporte aujourd'hui plus de 90 % du commerce de l'Éthiopie enclavée.|フランスが建設した軌間1000mmのジブチ―アディスアベバ鉄道は1917年に開通し、エチオピアが海へ出る唯一の鉄路として20世紀のほとんどを通じてこの国の主要な対外路であり続けた。しかし整備不足が数十年続いた末に速度は這うように遅くなり、2000年代にはついに運行を止めた。1998〜2000年の国境戦争でエチオピアがエリトリアの港を使えなくなったことでジブチの港はいっそう不可欠になり、2018年には中国建設の電化標準軌(1435mm)の新線が同じ経路を、旧線とは比べ物にならない速度で結び直した。いまや内陸国エチオピアの貿易の9割以上がこの路線を通っている。",
    [prop("Nagad Electrified Rail Terminal|Terminal ferroviaria electrificada de Nagad|Terminal ferroviaire électrifié de Nagad|ナガド電化鉄道ターミナル", 1100, 227),
     prop("Old French Station Quarter|Barrio de la vieja estación francesa|Quartier de l'ancienne gare française|旧フランス駅前地区", 500, 103)],
  ),
  addisababa: city(
    "Addis Ababa|Adís Abeba|Addis-Abeba|アディスアベバ",
    38.7469, 9.0250, "hoa", "electric", "capitalcity", "r",
    "A capital that got urban rail before it fully had rail to the sea|Una capital que tuvo tren urbano antes de tener bien resuelto el tren al mar|Une capitale qui a eu un tramway urbain avant d'avoir vraiment un train vers la mer|海への鉄路より先に都市鉄道を得た首都",
    "Addis Ababa opened sub-Saharan Africa's first light rail system in 2015, a Chinese-built and Chinese-financed electric network completed before the newer Chinese-built freight line to Djibouti was even fully open for commercial service — a landlocked capital got urban rail before it fully had reliable rail to the sea. Menelik II founded the city in 1886, and within a decade a firewood shortage nearly forced the whole capital to relocate; the eucalyptus trees planted from the 1890s to solve that problem still shade much of the city today.|Adís Abeba abrió el primer sistema de tren ligero del África subsahariana en 2015, una red eléctrica construida y financiada por China terminada antes de que la nueva línea de carga a Yibuti, también china, estuviera siquiera plenamente operativa — una capital sin salida al mar tuvo tren urbano antes de tener un tren fiable hasta el mar. Menelik II fundó la ciudad en 1886, y en menos de una década la escasez de leña estuvo a punto de obligar a trasladar toda la capital; los eucaliptos plantados desde la década de 1890 para resolver ese problema todavía dan sombra a buena parte de la ciudad.|Addis-Abeba a ouvert le premier tramway d'Afrique subsaharienne en 2015, un réseau électrique construit et financé par la Chine, achevé avant même que la nouvelle ligne de fret chinoise vers Djibouti ne soit pleinement opérationnelle — une capitale enclavée a eu un tramway urbain avant d'avoir un train fiable jusqu'à la mer. Ménélik II fonda la ville en 1886, et en moins d'une décennie une pénurie de bois de chauffe faillit forcer le déplacement de toute la capitale ; les eucalyptus plantés à partir des années 1890 pour résoudre ce problème ombragent encore une grande partie de la ville aujourd'hui.|アディスアベバは2015年、サハラ以南アフリカで最初のライトレールを開通させた。中国が建設・資金提供したこの電化路線は、同じく中国建設のジブチ行き貨物新線が商業運行を本格的に始めるより先に完成していた——内陸国の首都が、海への確かな鉄路を持つより先に都市鉄道を手にしたことになる。1886年にメネリク2世がこの街を建設したが、10年も経たないうちに薪の不足で首都全体の移転すら検討される事態になった。その問題を解決するために1890年代から植えられたユーカリの木は、いまも街の広い範囲に木陰を落としている。",
    [prop("Meskel Square LRT Interchange|Intercambiador de tren ligero de la plaza Meskel|Correspondance du tramway de la place Meskel|メスケル広場LRT乗換駅", 1300, 268),
     prop("Eucalyptus Grove Overlook|Mirador del bosque de eucaliptos|Belvédère de la forêt d'eucalyptus|ユーカリ林の展望地", 550, 113)],
  ),
  direbawa: city(
    "Dire Dawa|Dire Dawa|Dire Dawa|ディレダワ",
    41.8500, 9.6008, "hoa", "gauge", "desertport", "l",
    "The railway town that outgrew the capital, until the line broke down|El pueblo ferroviario que superó a la capital, hasta que la línea se averió|La ville-cheminot qui a surpassé la capitale, jusqu'à la panne de la ligne|線路が壊れるまで首都を凌いだ鉄道の町",
    "French engineers routed the 1917 Djibouti–Addis Ababa railway through open ground rather than through the existing hill town of Harar, so a brand-new railway town, Dire Dawa, grew up around the station instead and for decades rivalled Addis Ababa as Ethiopia's most modern city, laid out with its own French-style grid of avenues. When the old metre-gauge line fell into disrepair and stopped running altogether in the 2000s, the town's original reason for existing went with it, even though the newer 2018 standard-gauge line still calls at a station nearby.|Los ingenieros franceses trazaron el ferrocarril Yibuti-Adís Abeba de 1917 por terreno abierto en vez de por la ciudad de Harar, ya existente en la colina, así que en su lugar creció alrededor de la estación un pueblo ferroviario totalmente nuevo, Dire Dawa, que durante décadas rivalizó con Adís Abeba como la ciudad más moderna de Etiopía, trazada con su propia cuadrícula de avenidas al estilo francés. Cuando la vieja línea de ancho métrico se deterioró y dejó de circular del todo en la década de 2000, la razón de ser original del pueblo desapareció con ella, aunque la nueva línea de ancho estándar de 2018 todavía para en una estación cercana.|Les ingénieurs français firent passer le chemin de fer Djibouti-Addis-Abeba de 1917 par un terrain dégagé plutôt que par la ville collinaire déjà existante de Harar, si bien qu'une toute nouvelle ville-cheminot, Dire Dawa, grandit autour de la gare et rivalisa pendant des décennies avec Addis-Abeba comme ville la plus moderne d'Éthiopie, tracée selon sa propre grille d'avenues à la française. Quand l'ancienne ligne à voie métrique se dégrada et cessa totalement de circuler dans les années 2000, la raison d'être originelle de la ville disparut avec elle, même si la nouvelle ligne à écartement standard de 2018 dessert encore une gare non loin.|フランス人技師たちは1917年開通のジブチ―アディスアベバ鉄道を、既存の丘の町ハラールではなく開けた土地に通したため、駅の周りにまったく新しい鉄道の町ディレダワが生まれた。この町は数十年にわたり、フランス風の街路格子を持つエチオピア随一の近代都市としてアディスアベバと張り合った。旧メーターゲージ線が荒廃し2000年代に完全に止まると、町がそもそも存在した理由も失われた。2018年開通の新標準軌線は近くに駅を構えているものの、かつての勢いは戻っていない。",
    [prop("French Quarter Station Grid|Cuadrícula de la estación del barrio francés|Grille de la gare du quartier français|仏人街の駅前街路", 480, 99),
     prop("Old Metre-Gauge Platform|Andén del viejo ancho métrico|Quai de l'ancienne voie métrique|旧メーターゲージのホーム", 260, 54)],
  ),
  asmara: city(
    "Asmara|Asmara|Asmara|アスマラ",
    38.9327, 15.3229, "hoa", "viaduct", "highlandpass", "r",
    "A mountain railway rebuilt by hand, now stopped at a closed border|Un ferrocarril de montaña reconstruido a mano, hoy detenido en una frontera cerrada|Un chemin de fer de montagne reconstruit à la main, aujourd'hui arrêté à une frontière fermée|人の手で復元された山岳鉄道が、閉じた国境で止まっている",
    "Italian engineers completed the Eritrean Railway from the Red Sea port of Massawa up to highland Asmara in 1911, climbing more than 2,300 metres through switchbacks and tunnels; war damage shut the line for decades until volunteers and retired railwaymen rebuilt much of it by hand in the 1990s using salvaged parts, since the original Italian steam locomotives were still the only ones that fit the narrow track. The border with Ethiopia, closed for most of the time since a war ended in 2000, has kept the railway from ever again reaching Addis Ababa, so it now runs only heritage trips within Eritrea itself.|Los ingenieros italianos terminaron el Ferrocarril Eritreo desde el puerto de Massawa, en el mar Rojo, hasta la altiplánica Asmara en 1911, subiendo más de 2.300 metros por zigzags y túneles; los daños de guerra cerraron la línea durante décadas hasta que voluntarios y ferroviarios jubilados reconstruyeron gran parte a mano en los años noventa usando piezas rescatadas, ya que las locomotoras de vapor italianas originales seguían siendo las únicas que encajaban en la vía estrecha. La frontera con Etiopía, cerrada la mayor parte del tiempo desde que terminó una guerra en 2000, ha impedido que el ferrocarril vuelva a llegar a Adís Abeba, así que hoy solo hace recorridos patrimoniales dentro de Eritrea.|Les ingénieurs italiens achevèrent le chemin de fer érythréen depuis le port de Massaoua, sur la mer Rouge, jusqu'à Asmara en altitude en 1911, grimpant plus de 2 300 mètres par lacets et tunnels ; les dégâts de guerre fermèrent la ligne pendant des décennies jusqu'à ce que des bénévoles et des cheminots retraités en reconstruisent une grande partie à la main dans les années 1990 avec des pièces récupérées, les locomotives à vapeur italiennes d'origine restant les seules à s'adapter à la voie étroite. La frontière avec l'Éthiopie, fermée la majeure partie du temps depuis la fin d'une guerre en 2000, a empêché le chemin de fer d'atteindre à nouveau Addis-Abeba, si bien qu'il ne fait plus aujourd'hui que des trajets patrimoniaux à l'intérieur de l'Érythrée.|イタリア人技師たちは1911年、紅海の港マッサワから高地のアスマラまでエリトリア鉄道を完成させた。標高差2,300メートル余りをスイッチバックとトンネルで登る路線だった。戦禍で数十年閉ざされていたが、1990年代にボランティアと退役した鉄道員たちが、狭軌に合う唯一の車両であるイタリア製の旧式蒸気機関車の部品を寄せ集めて、大半を手作業で復元した。2000年に終結した戦争以来ほとんどの期間閉じられたままのエチオピア国境が、この鉄道が再びアディスアベバへ届くことを妨げており、いまはエリトリア国内だけを走る観光復元運行にとどまっている。",
    [prop("Massawa–Asmara Switchback Overlook|Mirador de los zigzags Massawa-Asmara|Belvédère des lacets Massaoua-Asmara|マッサワ―アスマラ・スイッチバック展望台", 520, 107),
     prop("Heritage Locomotive Shed|Cochera de locomotoras patrimoniales|Remise des locomotives patrimoniales|保存蒸気機関車の車庫", 380, 78)],
  ),

  // ---------------------------------------------------------------------
  // caf — 中部アフリカ・コンゴ盆地
  // ---------------------------------------------------------------------
  lubumbashi: city(
    "Lubumbashi|Lubumbashi|Lubumbashi|ルブンバシ",
    27.4794, -11.6609, "caf", "smelter", "copperbelt", "r",
    "A copper town with three ways out and none of them local|Una ciudad del cobre con tres salidas, ninguna local|Une ville du cuivre à trois sorties, aucune locale|三つの出口を持ちながら、どれも隣国へは向かわない銅の町",
    "Belgian colonists founded Lubumbashi in 1910 as Élisabethville to work the copper of Katanga, and getting that copper to a coast meant choosing between three competing colonial railways: north and west along the Congo River system to the Belgian-run port of Matadi, south through British-administered Rhodesia to South African ports, or west across Portuguese Angola on the Benguela Railway, completed in 1931, to the Atlantic port of Lobito. None of the three was built to connect neighbouring countries to each other; each moved Katanga's copper the shortest way to whichever empire's coastline was available, and Angola's civil war shut the Benguela route for decades until it fully reopened only in 2015.|Los colonos belgas fundaron Lubumbashi en 1910 como Élisabethville para explotar el cobre de Katanga, y llevar ese cobre hasta una costa suponía elegir entre tres ferrocarriles coloniales rivales: al norte y al oeste por el sistema del río Congo hasta el puerto belga de Matadi, al sur a través de la Rodesia administrada por los británicos hasta puertos sudafricanos, o al oeste cruzando la Angola portuguesa por el Ferrocarril de Benguela, terminado en 1931, hasta el puerto atlántico de Lobito. Ninguna de las tres se construyó para conectar países vecinos entre sí; cada una llevaba el cobre de Katanga por el camino más corto hasta la costa del imperio que estuviera disponible, y la guerra civil angoleña cerró la ruta de Benguela durante décadas, hasta que reabrió por completo solo en 2015.|Les colons belges fondèrent Lubumbashi en 1910 sous le nom d'Élisabethville pour exploiter le cuivre du Katanga, et acheminer ce cuivre jusqu'à une côte imposait de choisir entre trois chemins de fer coloniaux rivaux : au nord et à l'ouest par le réseau du fleuve Congo jusqu'au port belge de Matadi, au sud à travers la Rhodésie administrée par les Britanniques jusqu'aux ports sud-africains, ou à l'ouest à travers l'Angola portugais par le chemin de fer de Benguela, achevé en 1931, jusqu'au port atlantique de Lobito. Aucun des trois n'avait été construit pour relier des pays voisins entre eux ; chacun acheminait le cuivre du Katanga par la route la plus courte vers la côte de l'empire disponible, et la guerre civile angolaise ferma la ligne de Benguela pendant des décennies, jusqu'à sa pleine réouverture en 2015 seulement.|ベルギー人入植者は1910年、カタンガの銅を採掘するためにエリザベートヴィルとしてルブンバシを建設した。その銅を海岸まで運ぶには、互いに競い合う三つの植民地鉄道のどれかを選ぶ必要があった。北西へコンゴ川水系をたどりベルギー統治下の港マタディへ向かう路線、南へイギリス統治下のローデシアを抜けて南アフリカの港へ向かう路線、そして西へポルトガル領アンゴラを横断し、1931年に完成したベンゲラ鉄道で大西洋岸のロビト港へ向かう路線である。この三つはいずれも隣国どうしを結ぶために敷かれたのではなく、それぞれがカタンガの銅をそのとき使える帝国の海岸まで最短で運ぶためだけに存在した。ベンゲラ線はアンゴラ内戦のために数十年閉ざされ、全面再開したのは2015年になってからだった。",
    [prop("Copper Smelter Rail Siding|Vía muerta de la fundición de cobre|Voie de garage de la fonderie de cuivre|銅精錬所の側線", 700, 144),
     prop("Union Minière Rail Yard|Patio ferroviario de la Union Minière|Cour ferroviaire de l'Union Minière|ユニオン・ミニエール鉄道操車場", 450, 93)],
  ),
  kinshasa: city(
    "Kinshasa|Kinshasa|Kinshasa|キンシャサ",
    15.2663, -4.4419, "caf", "riverport", "rivercrossing", "r",
    "The closest two capitals in the world, with no bridge between them|Las dos capitales más cercanas del mundo, sin puente entre ellas|Les deux capitales les plus proches au monde, sans pont entre elles|世界で最も近い二つの首都、その間に橋は無い",
    "Kinshasa and Brazzaville face each other across barely a few kilometres of the Congo River, among the closest pairs of national capitals anywhere in the world, yet no bridge or tunnel has ever linked them; a proposed rail-and-road bridge has been discussed on and off since the 1980s without construction ever starting, so people, cars and freight still cross by ferry. Kinshasa's own railway, the Matadi–Kinshasa line completed by Belgian colonists in 1898 to bypass the Congo River's unnavigable rapids downstream, remains the only rail Congo's capital has ever had — it still doesn't connect to anything on the river's other bank.|Kinshasa y Brazzaville se miran a través de apenas unos kilómetros del río Congo, uno de los pares de capitales nacionales más cercanos del mundo, y sin embargo nunca se ha construido un puente o túnel que las una; un proyectado puente ferroviario y vial lleva discutiéndose de forma intermitente desde los años ochenta sin que la obra haya empezado nunca, así que la gente, los coches y la carga siguen cruzando en ferry. El propio ferrocarril de Kinshasa, la línea Matadi-Kinshasa terminada por los colonos belgas en 1898 para sortear los rápidos innavegables del río Congo aguas abajo, sigue siendo el único ferrocarril que ha tenido jamás la capital congoleña, y todavía no conecta con nada en la otra orilla.|Kinshasa et Brazzaville se font face à travers à peine quelques kilomètres du fleuve Congo, l'une des paires de capitales nationales les plus proches au monde, et pourtant aucun pont ni tunnel ne les a jamais reliées ; un projet de pont ferroviaire et routier est discuté par intermittence depuis les années 1980 sans que la construction n'ait jamais commencé, si bien que les gens, les voitures et le fret traversent encore en ferry. Le propre chemin de fer de Kinshasa, la ligne Matadi-Kinshasa achevée par les colons belges en 1898 pour contourner les rapides infranchissables du fleuve Congo en aval, reste le seul chemin de fer qu'ait jamais eu la capitale congolaise — il ne se connecte toujours à rien sur l'autre rive.|キンシャサとブラザヴィルは、コンゴ川をわずか数キロ隔てて向き合っており、世界でも指折りに近接した二つの首都どうしである。それでも橋もトンネルも一度も架けられたことがない。鉄道と道路を兼ねた橋の構想は1980年代から断続的に議論されてきたが、着工したことは一度も無く、人も車も貨物もいまなおフェリーで渡っている。キンシャサ自身の鉄道、1898年にベルギー植民地当局が完成させたマタディ―キンシャサ線は、下流にあるコンゴ川の航行不能な急流を迂回するために敷かれたもので、コンゴの首都が持ったことのある唯一の鉄道であり、対岸の何とも今なおつながっていない。",
    [prop("Congo River Ferry Terminal|Terminal del ferry del río Congo|Terminal du ferry du fleuve Congo|コンゴ川フェリーターミナル", 900, 185),
     prop("Matadi–Kinshasa Line Terminus|Terminal de la línea Matadi-Kinshasa|Terminus de la ligne Matadi-Kinshasa|マタディ―キンシャサ線の終着駅", 700, 144)],
  ),
  kolwezi: city(
    "Kolwezi|Kolwezi|Kolwezi|コルウェジ",
    25.4700, -10.7167, "caf", "smelter", "copperbelt", "l",
    "A new mining boom riding a century-old copper corridor|Un nuevo auge minero sobre un corredor de cobre centenario|Un nouveau boom minier sur un corridor du cuivre centenaire|百年前の銅の回廊に乗った新しい鉱山ブーム",
    "Kolwezi sits atop some of the richest cobalt deposits on Earth, and as electric-vehicle battery demand surged in the 2010s and 2020s the town became the centre of a mining boom that made Congo the source of well over half the world's mined cobalt; almost all of it still leaves by the same colonial-era rail and road corridors built a century earlier to move copper, not batteries. Artisanal miners digging by hand alongside industrial open pits have made Kolwezi a symbol of how a very old extraction economy adapted, almost unchanged in its transport routes, to a very new global technology.|Kolwezi se asienta sobre algunos de los yacimientos de cobalto más ricos del planeta, y cuando la demanda de baterías para vehículos eléctricos se disparó en las décadas de 2010 y 2020, la ciudad se convirtió en el centro de un auge minero que hizo del Congo la fuente de bastante más de la mitad del cobalto extraído en el mundo; casi todo sigue saliendo por los mismos corredores ferroviarios y viales de la época colonial construidos un siglo antes para mover cobre, no baterías. Los mineros artesanales que excavan a mano junto a las grandes minas a cielo abierto han hecho de Kolwezi un símbolo de cómo una economía extractiva muy antigua se adaptó, casi sin cambiar sus rutas de transporte, a una tecnología global muy nueva.|Kolwezi repose sur certains des gisements de cobalt les plus riches de la planète, et quand la demande de batteries pour véhicules électriques explosa dans les années 2010 et 2020, la ville devint le centre d'un boom minier qui fit du Congo la source de bien plus de la moitié du cobalt extrait dans le monde ; presque tout continue de sortir par les mêmes corridors ferroviaires et routiers de l'époque coloniale, construits un siècle plus tôt pour transporter du cuivre, pas des batteries. Les mineurs artisanaux creusant à la main à côté des mines industrielles à ciel ouvert ont fait de Kolwezi un symbole de la façon dont une économie extractive très ancienne s'est adaptée, presque sans changer ses voies de transport, à une technologie mondiale très récente.|コルウェジは地球でも屈指の豊かなコバルト鉱床の上にある。2010年代から2020年代にかけて電気自動車用電池の需要が急増すると、この町はコンゴを世界のコバルト産出量の半分をゆうに超える供給源にした鉱山ブームの中心地になった。それでもほぼすべてが、電池ではなく銅を運ぶために一世紀前に敷かれた植民地時代の鉄道・道路の回廊を通っていまも運び出されている。産業用の露天掘りのすぐ脇で手掘りする零細採掘者たちの姿は、きわめて古い資源採掘経済が、輸送路をほとんど変えないまま、まったく新しい世界的な技術に適応した象徴となっている。",
    [prop("Cobalt Open Pit Overlook|Mirador de la mina de cobalto a cielo abierto|Belvédère de la mine de cobalt à ciel ouvert|コバルト露天掘りの展望台", 780, 161),
     prop("Artisanal Miners' Rail Depot|Depósito ferroviario de los mineros artesanales|Dépôt ferroviaire des mineurs artisanaux|零細採掘者の鉄道集積場", 380, 78)],
  ),
  brazzaville: city(
    "Brazzaville|Brazzaville|Brazzaville|ブラザヴィル",
    15.2429, -4.2634, "caf", "riverport", "rivercrossing", "l",
    "A capital that watches its twin across a river with no bridge|Una capital que observa a su gemela al otro lado de un río sin puente|Une capitale qui observe sa jumelle de l'autre côté d'un fleuve sans pont|橋の無い川越しに双子を見つめる首都",
    "Brazzaville and Kinshasa are separated by the Congo River but connected to almost nothing else: no rail line inside the Republic of Congo has ever crossed the river to reach the network on the other side, so Brazzaville's own railway, the Congo–Ocean line to Pointe-Noire, exists purely to move goods that arrived by river barge from as far away as the Central African Republic and Chad out to the Atlantic, never toward its closest foreign capital just across the water. A river ferry, not a bridge, still carries the passengers and cargo that do cross between the two.|Brazzaville y Kinshasa están separadas por el río Congo, pero conectadas a casi nada más: ninguna línea ferroviaria dentro de la República del Congo ha cruzado nunca el río para llegar a la red del otro lado, así que el propio ferrocarril de Brazzaville, la línea Congo-Océano hasta Pointe-Noire, existe solo para llevar hacia el Atlántico mercancías que llegaron en barcaza fluvial desde lugares tan lejanos como la República Centroafricana y el Chad, nunca hacia la capital extranjera más cercana, justo al otro lado del agua. Un ferry fluvial, no un puente, sigue transportando a los pasajeros y la carga que sí cruzan entre las dos.|Brazzaville et Kinshasa sont séparées par le fleuve Congo mais reliées à presque rien d'autre : aucune ligne ferroviaire à l'intérieur de la République du Congo n'a jamais traversé le fleuve pour rejoindre le réseau de l'autre côté, si bien que le propre chemin de fer de Brazzaville, la ligne Congo-Océan vers Pointe-Noire, existe uniquement pour acheminer vers l'Atlantique des marchandises arrivées par chaland fluvial depuis d'aussi loin que la République centrafricaine et le Tchad, jamais vers la capitale étrangère la plus proche, juste de l'autre côté de l'eau. Un ferry fluvial, et non un pont, transporte encore les passagers et le fret qui traversent bel et bien entre les deux.|ブラザヴィルとキンシャサはコンゴ川で隔てられているが、それ以外ではほとんど何ともつながっていない。コンゴ共和国内のどの鉄道も川を越えて対岸の鉄道網に達したことは一度も無く、ブラザヴィル自身の鉄道であるコンゴ―オセアン線(ポワントノワールへ向かう)は、中央アフリカ共和国やチャドほど遠くから川船で届いた荷物を大西洋へ送り出すためだけに存在し、水を挟んですぐ隣にある外国の首都へ向かうことは一度も無い。二つの都市の間を実際に行き来する旅客と貨物を運ぶのは、いまも橋ではなく川のフェリーである。",
    [prop("Congo River Barge Quay|Muelle de barcazas del río Congo|Quai des chalands du fleuve Congo|コンゴ川はしけの船着き場", 620, 128),
     prop("Congo–Ocean Line Terminus|Terminal de la línea Congo-Océano|Terminus de la ligne Congo-Océan|コンゴ―オセアン線の終着駅", 500, 103)],
  ),
  pointenoire: city(
    "Pointe-Noire|Pointe-Noire|Pointe-Noire|ポワントノワール",
    11.8635, -4.7761, "caf", "port", "atlanticport", "l",
    "A railway whose Atlantic terminus cost more lives than kilometres|Un ferrocarril cuyo terminal atlántico costó más vidas que kilómetros|Un chemin de fer dont le terminus atlantique a coûté plus de vies que de kilomètres|路線の距離より多くの命を費やした大西洋の終着駅",
    "French colonial authorities built the Congo–Ocean railway from Pointe-Noire inland to Brazzaville between 1921 and 1934 almost entirely with forced labour conscripted from across French Equatorial Africa, and an estimated 14,000 to 20,000 workers died from disease, exhaustion and accidents blasting the line's many tunnels through the Mayombe hills — a death toll historians have called one of the deadliest single construction projects of the colonial era anywhere in Africa. The railway still runs today, carrying the country's oil, timber and potash out through Pointe-Noire's Atlantic harbour.|Las autoridades coloniales francesas construyeron el ferrocarril Congo-Océano desde Pointe-Noire hasta Brazzaville entre 1921 y 1934 casi enteramente con trabajo forzado reclutado en toda el África Ecuatorial Francesa, y se calcula que entre 14.000 y 20.000 trabajadores murieron de enfermedad, agotamiento y accidentes al abrir a dinamita los numerosos túneles de la línea a través de las colinas de Mayombe, una cifra de muertes que los historiadores han calificado como uno de los proyectos de construcción más mortíferos de toda la época colonial en África. El ferrocarril sigue funcionando hoy, sacando el petróleo, la madera y la potasa del país por el puerto atlántico de Pointe-Noire.|Les autorités coloniales françaises construisirent le chemin de fer Congo-Océan de Pointe-Noire jusqu'à Brazzaville entre 1921 et 1934, presque entièrement avec du travail forcé enrôlé dans toute l'Afrique équatoriale française, et l'on estime que 14 000 à 20 000 travailleurs moururent de maladie, d'épuisement et d'accidents en perçant à l'explosif les nombreux tunnels de la ligne à travers les collines du Mayombe — un bilan que les historiens ont qualifié de l'un des chantiers les plus meurtriers de toute l'époque coloniale en Afrique. Le chemin de fer fonctionne encore aujourd'hui, acheminant le pétrole, le bois et la potasse du pays par le port atlantique de Pointe-Noire.|フランス植民地当局は1921年から1934年にかけて、フランス領赤道アフリカ各地から徴用した強制労働者をほぼ全面的に使ってポワントノワールからブラザヴィルへ至るコンゴ―オセアン鉄道を建設した。マヨンベの丘陵に多数のトンネルを爆破で切り開く中で、推定1万4000人から2万人の労働者が病気・疲労・事故で命を落とし、歴史家たちはこれを植民地時代のアフリカで最も死者を出した単一の建設事業の一つと呼んでいる。この鉄道はいまも走り続けており、国の石油・木材・カリ塩をポワントノワールの大西洋岸の港へ運び出している。",
    [prop("Mayombe Tunnel Memorial Cutting|Trinchera conmemorativa del túnel de Mayombe|Tranchée commémorative du tunnel du Mayombe|マヨンベ・トンネルの記念切通し", 500, 103),
     prop("Atlantic Oil & Timber Quay|Muelle atlántico de petróleo y madera|Quai atlantique du pétrole et du bois|大西洋岸の石油・木材埠頭", 750, 155)],
  ),
  douala: city(
    "Douala|Duala|Douala|ドゥアラ",
    9.7043, 4.0511, "caf", "port", "atlanticport", "r",
    "A single line north, and nowhere else it can go|Una única línea al norte, y ningún otro sitio al que pueda ir|Une seule ligne vers le nord, et nulle part ailleurs où aller|北へ一本きり、それ以上どこへも行けない線",
    "The Cameroon Railway runs a single trunk line north from the port of Douala to Ngaoundéré, more than 900km inland, and stops there — no track has ever continued further north to Chad or the Central African Republic, both of which still rely on Cameroonian roads and this one railhead to reach any port at all. The line was built by the French in stages through the 20th century mainly to move cotton, livestock and, later, oil-related freight south to the Atlantic, not to connect Cameroon's neighbours to each other.|El Ferrocarril de Camerún tiene una única línea troncal que va al norte desde el puerto de Duala hasta Ngaundere, más de 900 km tierra adentro, y ahí se detiene: ninguna vía ha continuado nunca más al norte hacia el Chad o la República Centroafricana, que siguen dependiendo de las carreteras camerunesas y de esta única cabecera ferroviaria para llegar a cualquier puerto. La línea fue construida por los franceses por etapas a lo largo del siglo XX, sobre todo para llevar algodón, ganado y, después, carga relacionada con el petróleo hacia el sur, al Atlántico, no para conectar entre sí a los vecinos de Camerún.|Le chemin de fer camerounais fait courir une seule ligne principale vers le nord depuis le port de Douala jusqu'à Ngaoundéré, à plus de 900 km à l'intérieur des terres, et s'arrête là — aucune voie n'a jamais continué plus au nord vers le Tchad ou la République centrafricaine, qui dépendent tous deux encore des routes camerounaises et de cette unique tête de ligne pour atteindre un port quelconque. La ligne fut construite par les Français par étapes tout au long du XXe siècle, surtout pour acheminer coton, bétail puis, plus tard, du fret lié au pétrole vers le sud, vers l'Atlantique, et non pour relier entre eux les voisins du Cameroun.|カメルーン鉄道は港町ドゥアラから北へ、内陸900km余りのンガウンデレまで一本の幹線を走らせ、そこで終わる。その先、チャドや中央アフリカ共和国へ線路が続いたことは一度も無く、両国はいまもカメルーンの道路とこの一つの鉄道終端に頼ってどこかの港へたどり着いている。この路線は20世紀を通じて段階的にフランスによって建設され、おもに綿花・家畜、のちには石油関連の貨物を南の大西洋へ運ぶためのものであり、カメルーンの隣国どうしを結ぶためのものではなかった。",
    [prop("Ngaoundéré Railhead Depot|Depósito de la cabecera de Ngaundere|Dépôt de la tête de ligne de Ngaoundéré|ンガウンデレ鉄道終端の集積場", 620, 128),
     prop("Douala Port Container Yard|Patio de contenedores del puerto de Duala|Cour à conteneurs du port de Douala|ドゥアラ港のコンテナヤード", 950, 196)],
  ),
  yaounde: city(
    "Yaoundé|Yaundé|Yaoundé|ヤウンデ",
    11.5021, 3.8480, "caf", "capital", "capitalcity", "l",
    "A capital that is a railway crossroads but not a port|Una capital que es cruce ferroviario pero no puerto|Une capitale qui est un carrefour ferroviaire mais pas un port|鉄道の要衝でありながら港ではない首都",
    "Yaoundé has been linked to Douala's port by rail since 1927, decades before the line was extended north to Ngaoundéré's cattle and cotton country between 1964 and 1974, even though the capital itself sits on inland hills with no navigable river to the sea. Long-distance trains still connect the two roles the French colonial administration split between the cities a century ago: Douala for commerce, Yaoundé for government.|Yaundé ha estado unida al puerto de Duala por ferrocarril desde 1927, décadas antes de que la línea se extendiera al norte hacia la región ganadera y algodonera de Ngaundere entre 1964 y 1974, aunque la propia capital se asienta en colinas interiores sin ningún río navegable hasta el mar. Los trenes de largo recorrido siguen conectando los dos papeles que la administración colonial francesa repartió entre las dos ciudades hace un siglo: Duala para el comercio, Yaundé para el gobierno.|Yaoundé est reliée au port de Douala par le rail depuis 1927, des décennies avant que la ligne ne soit prolongée vers le nord jusqu'au pays du bétail et du coton de Ngaoundéré entre 1964 et 1974, alors même que la capitale se dresse sur des collines intérieures sans aucun cours d'eau navigable vers la mer. Les trains longue distance relient encore les deux rôles que l'administration coloniale française répartit entre les villes il y a un siècle : Douala pour le commerce, Yaoundé pour le gouvernement.|ヤウンデは1927年からドゥアラの港と鉄道で結ばれており、この路線が1964年から1974年にかけて北のンガウンデレの牧畜・綿花地帯へ延伸されるよりずっと前のことだった。首都そのものは内陸の丘陵地にあり、海へ通じる航行可能な川は無い。長距離列車はいまも、一世紀前にフランス植民地当局が両都市に割り振った役割——商業のドゥアラ、統治のヤウンデ——を結び続けている。",
    [prop("1927 Yaoundé Rail Terminus|Terminal ferroviaria de Yaundé de 1927|Terminus ferroviaire de Yaoundé de 1927|1927年開通ヤウンデ駅", 680, 140),
     prop("Nsam Freight Interchange|Intercambiador de carga de Nsam|Échangeur de fret de Nsam|ンサム貨物連絡駅", 420, 87)],
  ),
  owendo: city(
    "Owendo|Owendo|Owendo|オウェンド",
    9.5000, 0.2833, "caf", "port", "atlanticport", "r",
    "A national railway that has never once crossed a border|Un ferrocarril nacional que nunca ha cruzado una frontera|Un chemin de fer national qui n'a jamais franchi une frontière|一度も国境を越えたことのない国産鉄道",
    "The Transgabonais railway, built between 1974 and 1986 to move manganese and timber from the interior, runs entirely within Gabon from the port at Owendo near Libreville to the mining town of Franceville, 650km inland — one of the very few railways in Africa that has never been extended toward, or even planned to reach, a neighbouring country's border. Gabon's oil wealth paid for a line built purely to move Gabonese resources to a Gabonese port, without the colonial-era compromises that shaped almost every other railway on the continent.|El ferrocarril Transgabonés, construido entre 1974 y 1986 para llevar manganeso y madera desde el interior, transcurre enteramente dentro de Gabón, desde el puerto de Owendo, cerca de Libreville, hasta la localidad minera de Franceville, 650 km tierra adentro, uno de los pocos ferrocarriles de África que nunca se ha extendido hacia la frontera de un país vecino, ni siquiera se ha planeado hacerlo. La riqueza petrolera de Gabón pagó una línea construida únicamente para llevar recursos gaboneses a un puerto gabonés, sin los compromisos de la época colonial que dieron forma a casi todos los demás ferrocarriles del continente.|Le chemin de fer Transgabonais, construit entre 1974 et 1986 pour acheminer manganèse et bois depuis l'intérieur, se déroule entièrement à l'intérieur du Gabon, du port d'Owendo près de Libreville jusqu'à la ville minière de Franceville, à 650 km à l'intérieur des terres — l'un des très rares chemins de fer d'Afrique qui n'a jamais été prolongé vers, ni même envisagé pour atteindre, la frontière d'un pays voisin. La richesse pétrolière du Gabon a financé une ligne construite uniquement pour acheminer des ressources gabonaises vers un port gabonais, sans les compromis de l'époque coloniale qui ont façonné presque tous les autres chemins de fer du continent.|1974年から1986年にかけて内陸のマンガンと木材を運ぶために建設されたトランスガボネ鉄道は、リーブルヴィル近郊オウェンドの港から内陸650kmの鉱山町フランスヴィルまで、すべてガボン国内だけを走る。隣国の国境へ向けて延伸されたことも、そもそも計画されたことすら無い、アフリカでは数少ない鉄道の一つである。ガボンの石油の富がまかなったこの路線は、大陸のほとんどすべての鉄道を形づくった植民地時代の妥協を経ずに、ガボンの資源をガボンの港へ運ぶためだけに造られた。",
    [prop("Owendo Manganese Export Terminal|Terminal de exportación de manganeso de Owendo|Terminal d'exportation du manganèse d'Owendo|オウェンド・マンガン輸出ターミナル", 700, 144),
     prop("Transgabonais Timber Yard|Patio de madera del Transgabonés|Cour à bois du Transgabonais|トランスガボネ木材ヤード", 460, 95)],
  ),

  // ---------------------------------------------------------------------
  // gof — ギニア湾岸
  // ---------------------------------------------------------------------
  dakar: city(
    "Dakar|Dakar|Dakar|ダカール",
    -17.4467, 14.6928, "gof", "peanut", "atlanticport", "r",
    "A railway built to keep the interior's trade out of a rival's ports|Un ferrocarril construido para que el comercio del interior no fuera a puertos rivales|Un chemin de fer bâti pour que le commerce de l'intérieur évite les ports rivaux|内陸の交易を競合国の港へ逃がさないために敷かれた鉄道",
    "French colonial administrators built the Dakar–Niger railway in stages from 1907 to 1923, mainly to carry groundnuts and other exports from what is now Mali down to Dakar's harbour rather than let that trade drift toward British-run ports in nearby Gambia or Sierra Leone. Passenger trains covered the 1,300km run to Bamako for most of the 20th century, but international service collapsed for good in the 2000s as the track fell into disrepair. Dakar's next passenger railway, the electric TER commuter line opened in 2021 and extended to the international airport in 2024, had nothing to do with the old colonial route and has never crossed a border.|Los administradores coloniales franceses construyeron el ferrocarril Dakar-Níger por etapas entre 1907 y 1923, sobre todo para llevar cacahuetes y otras exportaciones desde lo que hoy es Malí hasta el puerto de Dakar, en vez de dejar que ese comercio se desviara hacia los puertos británicos de la vecina Gambia o Sierra Leona. Los trenes de pasajeros cubrieron el trayecto de 1.300 km hasta Bamako durante casi todo el siglo XX, pero el servicio internacional se derrumbó definitivamente en los años 2000 al deteriorarse la vía. El siguiente ferrocarril de pasajeros de Dakar, la línea eléctrica de cercanías TER, inaugurada en 2021 y extendida hasta el aeropuerto internacional en 2024, no tuvo nada que ver con la antigua ruta colonial y nunca ha cruzado una frontera.|Les administrateurs coloniaux français construisirent le chemin de fer Dakar-Niger par étapes de 1907 à 1923, surtout pour acheminer l'arachide et d'autres exportations depuis ce qui est aujourd'hui le Mali jusqu'au port de Dakar, plutôt que de laisser ce commerce dériver vers les ports britanniques de la Gambie ou de la Sierra Leone voisines. Des trains de voyageurs parcoururent les 1 300 km jusqu'à Bamako pendant presque tout le XXe siècle, mais le service international s'effondra définitivement dans les années 2000 à mesure que la voie se dégradait. Le chemin de fer de voyageurs suivant de Dakar, la ligne électrique de banlieue TER ouverte en 2021 et prolongée jusqu'à l'aéroport international en 2024, n'avait aucun lien avec l'ancienne route coloniale et n'a jamais franchi de frontière.|フランスの植民地当局は1907年から1923年にかけて段階的にダカール―ニジェール鉄道を建設した。おもな目的は、今日のマリにあたる内陸部の落花生などの輸出品を、近隣のガンビアやシエラレオネにあるイギリス統治下の港へ流れさせず、ダカールの港へ運び下ろすことだった。旅客列車は20世紀のほとんどを通じてバマコまでの1300kmを走り続けたが、線路の荒廃とともに国際旅客サービスは2000年代についに途絶えた。ダカールが次に得た旅客鉄道、2021年に開通し2024年には国際空港まで延伸された電化通勤鉄道TERは、この旧植民地路線とは無関係で、いまだ一度も国境を越えたことがない。",
    [prop("Dakar-Niger Rail Terminus|Terminal del ferrocarril Dakar-Níger|Terminus du chemin de fer Dakar-Niger|ダカール―ニジェール鉄道の終着駅", 800, 165),
     prop("TER Regional Rail Platform|Andén regional del TER|Quai régional du TER|TER地域鉄道のホーム", 950, 196)],
  ),

  // ---------------------------------------------------------------------
  // mag — マグレブ・ナイル・モーリタニア
  // ---------------------------------------------------------------------
  cairo: city(
    "Cairo|El Cairo|Le Caire|カイロ",
    31.2357, 30.0444, "mag", "pyramid", "nilebank", "l",
    "Africa's first railway, then Africa's first metro|El primer ferrocarril de África, luego su primer metro|Le premier chemin de fer d'Afrique, puis son premier métro|アフリカ最初の鉄道、そして最初の地下鉄",
    "The Cairo–Alexandria railway, opened in 1854 under British engineer Robert Stephenson's firm, was the first railway built anywhere in Africa or the Middle East. Cairo returned to that first-on-the-continent role in 1987, opening Africa's first metro system, which today moves well over a billion passengers a year through a city whose surface traffic ranks among the world's most congested.|El ferrocarril Cairo-Alejandría, inaugurado en 1854 por la empresa del ingeniero británico Robert Stephenson, fue el primer ferrocarril construido en cualquier parte de África o Oriente Medio. El Cairo repitió ese papel pionero en 1987 al abrir el primer sistema de metro de África, que hoy mueve muchísimo más de mil millones de pasajeros al año en una ciudad cuyo tráfico en superficie está entre los más congestionados del mundo.|Le chemin de fer Le Caire-Alexandrie, ouvert en 1854 par l'entreprise de l'ingénieur britannique Robert Stephenson, fut le premier chemin de fer construit en Afrique ou au Moyen-Orient. Le Caire rejoua ce rôle de pionnier du continent en 1987 en ouvrant le premier métro d'Afrique, qui transporte aujourd'hui bien plus d'un milliard de passagers par an dans une ville dont la circulation de surface compte parmi les plus congestionnées au monde.|1854年、イギリス人技師ロバート・スティーヴンソンの会社が開通させたカイロ―アレクサンドリア鉄道は、アフリカでも中東でも最初の鉄道だった。カイロは1987年、アフリカ初の地下鉄を開通させて再び大陸の先頭に立った。この地下鉄はいまや年間10億人をゆうに超える乗客を運んでおり、地上の交通は世界有数の渋滞で知られる街を支えている。",
    [prop("1854 Cairo Terminus Platform|Andén de la terminal de El Cairo de 1854|Quai du terminus du Caire de 1854|1854年開通カイロ駅のホーム", 1400, 288),
     prop("Cairo Metro Line 1 Concourse|Vestíbulo de la Línea 1 del metro de El Cairo|Hall de la ligne 1 du métro du Caire|カイロ地下鉄1号線のコンコース", 900, 185)],
  ),
  alexandria: city(
    "Alexandria|Alejandría|Alexandrie|アレクサンドリア",
    29.9187, 31.2001, "mag", "port", "nilebank", "l",
    "The Mediterranean end of Africa's oldest railway|El extremo mediterráneo del ferrocarril más antiguo de África|L'extrémité méditerranéenne du plus vieux chemin de fer d'Afrique|アフリカ最古の鉄道が地中海に着く終点",
    "Alexandria was the western terminus of the 1854 Cairo–Alexandria line, Africa's first railway, built to move Egyptian cotton to Mediterranean steamships faster than the Nile's barges ever could; the crop's exports boomed further after the American Civil War cut off competing US cotton supplies in the 1860s. The colonial-era Misr Station, rebuilt in the 1920s with a domed clock tower, still anchors the city's rail network more than 170 years later.|Alejandría fue la terminal occidental de la línea Cairo-Alejandría de 1854, el primer ferrocarril de África, construido para llevar el algodón egipcio a los vapores del Mediterráneo más rápido de lo que jamás pudieron las barcazas del Nilo; las exportaciones del cultivo se dispararon aún más después de que la Guerra Civil estadounidense cortara el algodón rival de EE. UU. en la década de 1860. La estación Misr de la época colonial, reconstruida en los años veinte con una torre del reloj abovedada, sigue siendo el eje de la red ferroviaria de la ciudad más de 170 años después.|Alexandrie fut le terminus occidental de la ligne Le Caire-Alexandrie de 1854, premier chemin de fer d'Afrique, construite pour acheminer le coton égyptien vers les vapeurs méditerranéens plus vite que ne l'avaient jamais fait les péniches du Nil ; les exportations du coton s'envolèrent encore après que la guerre de Sécession américaine eut coupé le coton concurrent des États-Unis dans les années 1860. La gare Misr de l'époque coloniale, reconstruite dans les années 1920 avec une tour d'horloge à coupole, reste le pivot du réseau ferroviaire de la ville plus de 170 ans plus tard.|アレクサンドリアは1854年開通のカイロ―アレクサンドリア鉄道(アフリカ最初の鉄道)の西の終点であり、エジプト産綿花をナイル川のはしけよりずっと速く地中海の汽船へ運ぶために敷かれた。1860年代にアメリカ南北戦争でアメリカ産綿花の輸出が途絶えると、この輸出はさらに膨らんだ。植民地時代のミスル駅は1920年代にドーム型の時計塔を備えて建て直され、170年以上を経たいまも市の鉄道網の要であり続けている。",
    [prop("Misr Station Clock Tower|Torre del reloj de la estación Misr|Tour d'horloge de la gare Misr|ミスル駅の時計塔", 1000, 206),
     prop("Cotton Exchange Quay|Muelle de la bolsa del algodón|Quai de la bourse du coton|綿花取引所の埠頭", 650, 134)],
  ),
  aswan: city(
    "Aswan|Asuán|Assouan|アスワン",
    32.8998, 24.0889, "mag", "dam", "nilebank", "r",
    "The railhead where the Cape-to-Cairo dream ran out of continent|La cabecera donde el sueño de El Cabo a El Cairo se quedó sin continente|Le terminus où le rêve du Cap au Caire a manqué de continent|ケープ〜カイロ構想が大陸を使い果たした終着駅",
    "Aswan became Egypt's southernmost rail terminus in 1898, built partly to move labour and stone for the first Aswan Dam and partly as the northern anchor of Cecil Rhodes's dream of a British 'Cape to Cairo' railway spanning the continent — a dream never realised, undone by gaps through Sudan and Central Africa that were never closed. The much larger Aswan High Dam, completed in 1970, now floods the old cataract the earlier line was built to bypass.|Asuán se convirtió en la terminal ferroviaria más meridional de Egipto en 1898, construida en parte para transportar mano de obra y piedra para la primera presa de Asuán, y en parte como el ancla septentrional del sueño de Cecil Rhodes de un ferrocarril británico 'de El Cabo a El Cairo' que recorriera todo el continente, un sueño nunca cumplido, deshecho por los tramos sin construir en Sudán y África Central que jamás se cerraron. La presa Alta de Asuán, mucho mayor y terminada en 1970, hoy inunda la antigua catarata que la primera línea fue construida para sortear.|Assouan devint le terminus ferroviaire le plus méridional d'Égypte en 1898, construit en partie pour acheminer main-d'œuvre et pierre vers le premier barrage d'Assouan, et en partie comme ancrage septentrional du rêve de Cecil Rhodes d'un chemin de fer britannique « du Cap au Caire » traversant tout le continent — un rêve jamais réalisé, défait par des tronçons manquants au Soudan et en Afrique centrale qui ne furent jamais comblés. Le barrage d'Assouan, bien plus vaste et achevé en 1970, inonde aujourd'hui l'ancienne cataracte que la première ligne fut bâtie pour contourner.|アスワンは1898年、エジプトで最も南にある鉄道の終着駅になった。最初のアスワンダム建設のための労働力と石材を運ぶためであると同時に、大陸を縦断するセシル・ローズの「ケープ〜カイロ鉄道」構想の北の起点でもあった。この構想はついに実現せず、スーダンや中部アフリカに残った空白区間は最後まで埋まらなかった。はるかに大規模なアスワン・ハイダムは1970年に完成し、最初の路線が迂回するために敷かれた古い急流をいまは水底に沈めている。",
    [prop("1898 Aswan Terminus Platform|Andén de la terminal de Asuán de 1898|Quai du terminus d'Assouan de 1898|1898年開通アスワン駅のホーム", 700, 144),
     prop("First Cataract Quay|Muelle de la Primera Catarata|Quai de la première cataracte|第一急流の船着き場", 500, 103)],
  ),
  tunis: city(
    "Tunis|Túnez|Tunis|チュニス",
    10.1815, 36.8065, "mag", "medina", "oldtown", "l",
    "Africa's oldest electric line, next to a border line that no longer runs|La línea eléctrica más antigua de África, junto a una frontera sin trenes|La plus vieille ligne électrique d'Afrique, à côté d'une frontière sans trains|アフリカ最古の電化路線と、いまは走らない国境路線",
    "The TGM line linking Tunis to its northern suburbs opened in 1872 and was electrified in 1908, making it one of the oldest electric railways still running anywhere in Africa. A separate international line once carried passengers all the way from Tunis to Algiers, but regular cross-border passenger service between Tunisia and Algeria has not run in years, and today the track sees only occasional freight.|La línea TGM que une Túnez con sus suburbios del norte se inauguró en 1872 y se electrificó en 1908, lo que la convierte en uno de los ferrocarriles eléctricos más antiguos que siguen funcionando en toda África. Una línea internacional aparte llevaba antes a los pasajeros desde Túnez hasta Argel, pero el servicio regular de pasajeros entre Túnez y Argelia lleva años sin circular, y hoy la vía solo ve algún tren de mercancías ocasional.|La ligne TGM reliant Tunis à ses banlieues nord ouvrit en 1872 et fut électrifiée en 1908, ce qui en fait l'un des plus anciens chemins de fer électriques encore en service en Afrique. Une ligne internationale distincte menait autrefois les voyageurs de Tunis jusqu'à Alger, mais le service régulier de voyageurs entre la Tunisie et l'Algérie ne circule plus depuis des années, et la voie ne voit plus aujourd'hui que du fret occasionnel.|チュニスと北の郊外を結ぶTGM線は1872年に開通し、1908年に電化された。アフリカでいまも走る電化鉄道としては最も古い部類に入る。かつては別の国際路線がチュニスからアルジェまで旅客を運んでいたが、チュニジアとアルジェリアを結ぶ定期旅客サービスはここ数年途絶えており、いまその線路を通るのはときおりの貨物列車だけである。",
    [prop("TGM La Marsa Terminus|Terminal de La Marsa del TGM|Terminus du TGM à La Marsa|TGM線ラ・マルサ終着駅", 600, 124),
     prop("Tunis–Algiers Border Halt|Apeadero fronterizo Túnez-Argel|Halte frontalière Tunis-Alger|チュニス―アルジェ国境の停車場", 320, 66)],
  ),
  sfax: city(
    "Sfax|Sfax|Sfax|スファックス",
    10.7603, 34.7406, "mag", "port", "harborcity", "r",
    "A phosphate line that made a small port surprisingly rich|Una línea de fosfatos que hizo rico a un pequeño puerto|Une ligne de phosphate qui a rendu un petit port étonnamment riche|小さな港を思いがけず豊かにしたリン鉱石の鉄道",
    "Sfax grew wealthy on phosphate mined at Gafsa and Metlaoui and hauled to its harbour by a French-built mining railway completed in 1899, decades before oil was found anywhere nearby; by the early 20th century Tunisia ranked among the world's largest phosphate exporters almost entirely because of this one line. The trade still runs today, though repeated strikes and blockades along the Gafsa–Sfax line in recent years have shown how easily a single-corridor economy can be brought to a halt.|Sfax se enriqueció con el fosfato extraído en Gafsa y Metlaoui y transportado a su puerto por un ferrocarril minero construido por Francia y terminado en 1899, décadas antes de que se encontrara petróleo en cualquier lugar cercano; a principios del siglo XX Túnez figuraba entre los mayores exportadores mundiales de fosfato casi enteramente gracias a esta única línea. El comercio sigue hoy en marcha, aunque las repetidas huelgas y bloqueos en la línea Gafsa-Sfax en años recientes han mostrado lo fácil que es paralizar una economía que depende de un solo corredor.|Sfax s'enrichit grâce au phosphate extrait à Gafsa et Métlaoui et acheminé jusqu'à son port par un chemin de fer minier construit par la France et achevé en 1899, des décennies avant qu'on ne trouve du pétrole à proximité ; au début du XXe siècle, la Tunisie comptait parmi les plus grands exportateurs mondiaux de phosphate presque uniquement grâce à cette seule ligne. Le commerce se poursuit aujourd'hui, mais les grèves et blocages répétés sur la ligne Gafsa-Sfax ces dernières années ont montré combien il est facile de paralyser une économie à corridor unique.|スファックスは、ガフサやメトラウィで採れるリン鉱石をフランス建設の鉱山鉄道(1899年完成)で港まで運ぶことで富を得た。近くで石油が見つかるよりずっと前のことである。20世紀初頭、チュニジアはほぼこの一本の鉄道のおかげで世界有数のリン鉱石輸出国になった。この交易はいまも続いているが、近年ガフサ―スファックス線で繰り返されるストライキや封鎖は、一本の輸送路に頼る経済がいかに簡単に止まってしまうかを示している。",
    [prop("Gafsa Phosphate Loading Quay|Muelle de carga de fosfato de Gafsa|Quai de chargement du phosphate de Gafsa|ガフサ産リン鉱石の積出埠頭", 550, 113),
     prop("1899 Mining Rail Terminus|Terminal ferroviaria minera de 1899|Terminus ferroviaire minier de 1899|1899年開通の鉱山鉄道終着駅", 400, 82)],
  ),
  algiers: city(
    "Algiers|Argel|Alger|アルジェ",
    3.0588, 36.7538, "mag", "gauge", "oldtown", "l",
    "A gauge that matches its neighbours, a border that doesn't|Un ancho de vía que coincide con los vecinos, una frontera que no|Un écartement conforme à ses voisins, une frontière qui ne l'est pas|隣国と揃う軌間、揃わない国境",
    "French engineers built Algeria's railways, starting with the Algiers–Blida line in 1862, to the 1,435mm standard gauge used in mainland France — the same choice made across Morocco and Tunisia, but a very different one from almost every French, British, German, Belgian or Portuguese railway built anywhere south of the Sahara, which nearly all used a narrower gauge to save money. Gauge alone would let a train run from Tangier to Tunis; the Algeria–Morocco land border, closed since 1994, is what actually stops it, not the tracks.|Los ingenieros franceses construyeron los ferrocarriles de Argelia, empezando por la línea Argel-Blida en 1862, con el ancho estándar de 1.435 mm usado en la Francia metropolitana, la misma elección hecha en Marruecos y Túnez, pero muy distinta de casi todos los ferrocarriles franceses, británicos, alemanes, belgas o portugueses construidos al sur del Sahara, que casi siempre usaron un ancho más estrecho para ahorrar dinero. El ancho de vía por sí solo permitiría que un tren fuera de Tánger a Túnez; es la frontera terrestre entre Argelia y Marruecos, cerrada desde 1994, la que en realidad lo impide, no las vías.|Les ingénieurs français construisirent les chemins de fer algériens, à commencer par la ligne Alger-Blida en 1862, à l'écartement standard de 1 435 mm utilisé en France métropolitaine — le même choix fait au Maroc et en Tunisie, mais très différent de presque tous les chemins de fer français, britanniques, allemands, belges ou portugais construits au sud du Sahara, qui utilisèrent presque tous un écartement plus étroit pour économiser. L'écartement seul permettrait à un train de rouler de Tanger à Tunis ; c'est la frontière terrestre algéro-marocaine, fermée depuis 1994, qui l'en empêche réellement, pas les rails.|フランス人技師たちは1862年のアルジェ―ブリダ線を皮切りに、本国フランスと同じ軌間1435mm(標準軌)でアルジェリアの鉄道を敷いた。これはモロッコやチュニジアでも同じ選択だったが、サハラ以南でフランス・イギリス・ドイツ・ベルギー・ポルトガルが敷いたほぼすべての鉄道(たいてい費用を抑えるためより狭い軌間を選んだ)とはまったく異なる。軌間だけを見ればタンジェからチュニスまで一本の列車が走れるはずだが、実際にそれを阻んでいるのは線路ではなく、1994年から閉じられたままのアルジェリア―モロッコ国境である。",
    [prop("Algiers–Blida Line Terminus|Terminal de la línea Argel-Blida|Terminus de la ligne Alger-Blida|アルジェ―ブリダ線の終着駅", 850, 175),
     prop("Agha Station Concourse|Vestíbulo de la estación Agha|Hall de la gare d'Agha|アガ駅のコンコース", 700, 144)],
  ),
  oran: city(
    "Oran|Orán|Oran|オラン",
    -0.6418, 35.6971, "mag", "border", "borderline", "r",
    "A border station that has waited three decades for a train|Una estación fronteriza que espera un tren desde hace tres décadas|Une gare frontière qui attend un train depuis trois décennies|三十年、列車を待ち続ける国境の駅",
    "Oran once had a direct rail connection to Morocco through Tlemcen and Oujda, part of the same standard-gauge Maghreb network that also reaches Tunis, but Algeria closed its land border with Morocco in 1994 after a militant attack in Marrakesh was blamed on Algerian involvement, and the frontier has stayed shut ever since. The rails at the border post are still there, rusting from three decades without a single train.|Orán tuvo antes una conexión ferroviaria directa con Marruecos a través de Tremecén y Uxda, parte de la misma red magrebí de ancho estándar que también llega a Túnez, pero Argelia cerró su frontera terrestre con Marruecos en 1994 tras un atentado en Marrakech que se atribuyó a la implicación argelina, y la frontera ha permanecido cerrada desde entonces. Los raíles del puesto fronterizo siguen ahí, oxidándose tras tres décadas sin un solo tren.|Oran avait autrefois une liaison ferroviaire directe avec le Maroc via Tlemcen et Oujda, faisant partie du même réseau maghrébin à écartement standard qui atteint aussi Tunis, mais l'Algérie ferma sa frontière terrestre avec le Maroc en 1994 après qu'un attentat à Marrakech eut été imputé à une implication algérienne, et la frontière est restée close depuis. Les rails du poste-frontière sont toujours là, rouillant après trois décennies sans un seul train.|オランはかつて、チュニスにも達する同じ標準軌のマグレブ鉄道網を通じて、トレムセンとウジダ経由でモロッコと直接結ばれていた。しかし1994年、マラケシュでの襲撃事件にアルジェリアの関与が疑われたことをきっかけにアルジェリアがモロッコとの陸上国境を閉鎖し、それ以来国境は閉じられたままである。国境の駅の線路はいまも残っているが、三十年間一本の列車も通らないまま錆びついている。",
    [prop("Oran Ville Station Hall|Sala de la estación de Orán Ciudad|Salle de la gare d'Oran-Ville|オラン・ヴィル駅の駅舎", 500, 103),
     prop("Closed Frontier Rail Spur|Ramal ferroviario de la frontera cerrada|Embranchement de la frontière fermée|閉ざされた国境の側線", 260, 54)],
  ),
  constantine: city(
    "Constantine|Constantina|Constantine|コンスタンティーヌ",
    6.6147, 36.3650, "mag", "viaduct", "highlandpass", "l",
    "A city whose railway had to cross a gorge before it could go anywhere|Una ciudad cuyo ferrocarril tuvo que cruzar un desfiladero antes de ir a ningún sitio|Une ville dont le chemin de fer a dû franchir un gouffre avant d'aller ailleurs|どこへ向かうより先に、自らの峡谷を越えねばならなかった鉄道の町",
    "Constantine sits on a rock plateau ringed by a gorge roughly 200 metres deep, and before the railway could connect the city to Algiers or the Tunisian border it first had to solve the gorge itself; engineers threaded the line along ledges and short tunnels cut into the cliff face to reach the station, part of the eastern Algerian network completed in the 1870s and 1880s. The city's several suspension and arch bridges spanning the same gorge, built across the following decades, are now as much a symbol of Constantine as the railway that first forced the crossing.|Constantina se asienta en una meseta rocosa rodeada por un desfiladero de unos 200 metros de profundidad, y antes de que el ferrocarril pudiera conectar la ciudad con Argel o la frontera tunecina, primero tuvo que resolver el propio desfiladero; los ingenieros trazaron la línea por repisas y túneles cortos excavados en el acantilado para llegar a la estación, parte de la red del este argelino completada en las décadas de 1870 y 1880. Los varios puentes colgantes y de arco de la ciudad que cruzan el mismo desfiladero, construidos en las décadas siguientes, son hoy tan símbolo de Constantina como el ferrocarril que primero forzó el cruce.|Constantine se dresse sur un plateau rocheux ceint d'un gouffre profond d'environ 200 mètres, et avant que le chemin de fer ne puisse relier la ville à Alger ou à la frontière tunisienne, il dut d'abord résoudre le gouffre lui-même ; les ingénieurs firent passer la ligne par des corniches et de courts tunnels taillés dans la falaise pour atteindre la gare, dans le cadre du réseau de l'Est algérien achevé dans les années 1870 et 1880. Les nombreux ponts suspendus et en arc de la ville enjambant le même gouffre, construits au cours des décennies suivantes, sont aujourd'hui tout autant un symbole de Constantine que le chemin de fer qui força le premier passage.|コンスタンティーヌは深さ約200メートルの峡谷に囲まれた岩の台地の上にある。鉄道がこの街をアルジェやチュニジア国境と結ぶ前に、まず峡谷そのものを克服しなければならなかった。技師たちは崖に刻んだ棚状の道と短いトンネルで線路を通し、1870〜80年代に完成した東部アルジェリアの鉄道網の一部として駅へたどり着かせた。その後数十年で架けられた市内のいくつもの吊り橋・アーチ橋は、いまではこの峡谷を最初に越えた鉄道と同じくらい、コンスタンティーヌを象徴する存在になっている。",
    [prop("Rhumel Gorge Rail Ledge|Repisa ferroviaria del desfiladero del Rhumel|Corniche ferroviaire du gouffre du Rhumel|ルメル峡谷の鉄道棚道", 480, 99),
     prop("Sidi M'Cid Bridge Overlook|Mirador del puente Sidi M'Cid|Belvédère du pont Sidi M'Cid|シディ・ムシッド橋の展望台", 380, 78)],
  ),
  nouadhibou: city(
    "Nouadhibou|Nuadibú|Nouadhibou|ヌアディブ",
    -17.0347, 20.9310, "mag", "caravan", "sahara", "r",
    "The line built for one train, 2.5 kilometres of it at a time|La línea construida para un solo tren, de 2,5 kilómetros|La ligne bâtie pour un seul train, 2,5 kilomètres à la fois|たった一本の、しかし2.5kmの列車のために敷かれた線",
    "The SNIM railway hauls iron ore about 700km from the mines at Zouérat to the port at Nouadhibou on trains regularly over 2.5km long with 200 or more wagons, among the longest trains running anywhere in the world; the line has no passenger timetable, no connection to any other railway, and crosses no border despite running the length of the country. Local travellers ride anyway, climbing onto the empty ore wagons for the only overland route across this stretch of the Sahara, an unofficial practice railway staff have long tolerated rather than approved.|El ferrocarril de la SNIM transporta mineral de hierro unos 700 km desde las minas de Zuérate hasta el puerto de Nuadibú en trenes que suelen superar los 2,5 km de longitud con 200 vagones o más, entre los trenes más largos que circulan en el mundo; la línea no tiene horario de pasajeros, no se conecta con ningún otro ferrocarril y no cruza ninguna frontera pese a recorrer todo el país. Aun así, los viajeros locales suben a los vagones vacíos de mineral para tener la única ruta terrestre a través de este tramo del Sahara, una práctica no oficial que el personal ferroviario lleva tiempo tolerando sin aprobarla.|Le chemin de fer de la SNIM achemine le minerai de fer sur environ 700 km depuis les mines de Zouérate jusqu'au port de Nouadhibou, sur des trains dépassant régulièrement 2,5 km de long avec 200 wagons ou plus, parmi les plus longs trains circulant au monde ; la ligne n'a aucun horaire voyageurs, aucune connexion avec un autre chemin de fer, et ne franchit aucune frontière bien qu'elle traverse tout le pays. Les voyageurs locaux y montent quand même, grimpant sur les wagons de minerai vides pour emprunter l'unique route terrestre à travers ce tronçon du Sahara, une pratique officieuse que le personnel ferroviaire tolère depuis longtemps sans l'approuver.|SNIM鉄道は、ズエラットの鉱山からヌアディブの港まで約700kmにわたって鉄鉱石を運ぶ。列車はしばしば2.5kmを超える長さで貨車200両以上にもなり、世界でも屈指の長さの列車として知られる。この路線には旅客時刻表が無く、他のどの鉄道ともつながっておらず、国を縦断していながら国境を一つも越えない。それでも地元の人々は、このサハラの一角を陸路で渡る唯一の手段として、空の鉱石貨車によじ登って乗る。鉄道側が長らく黙認してきた非公式の慣行である。",
    [prop("Zouérat Ore Loading Terminal|Terminal de carga de mineral de Zuérate|Terminal de chargement du minerai de Zouérate|ズエラット鉱石積出ターミナル", 620, 128),
     prop("Nouadhibou Ore Wharf|Muelle de mineral de Nuadibú|Quai à minerai de Nouadhibou|ヌアディブ鉱石埠頭", 400, 82)],
  ),
};

/**
 * 路線。5都市は地理的に大きく離れており(東アフリカ・南部アフリカ・
 * アフリカの角・中部アフリカ・西アフリカ)、この時点で意味のある直接の
 * 隣接路線は無い。都市が出そろってから、地方内の近い都市どうしを
 * つなぐ形で設計する。
 */
export const AFRICA_EDGES = [];
