/**
 * アフリカ大陸盤面の都市と路線(いまは5都市の見本のみ)。
 *
 * 大陸盤面の主題は「国をまたぐ話」。すでにモロッコとガーナの盤面があるので、
 * 同じ都市を選ぶ場合でも中身は変える(このファイルでは同じ都市はまだ選んでいない)。
 * この盤面固有の主題は「大陸を貫く鉄路がついに一本につながらなかったこと」——
 * 軌間が国ごとにバラバラ(1067mm/1000mm/1435mm)で、路線の大半は内陸の資源を
 * 港へ運ぶためだけに敷かれ、隣国とはもともと繋がる設計になっていない。
 * ケープ〜カイロ構想は完成せず、いま新しく敷かれている線(電化標準軌)は
 * その古い構図をようやく書き換え始めている、という筋。
 *
 * 地方区分(暫定、7つ。このファイルではまだ eaf/saf/hoa/caf/gof の5つしか
 * 使っていない): `mag` マグレブ・ナイル / `sah` サヘル・西アフリカ内陸 /
 * `gof` ギニア湾岸 / `caf` 中部アフリカ・コンゴ盆地 / `hoa` アフリカの角 /
 * `eaf` 東アフリカ・大湖地方 / `saf` 南部アフリカ。
 *
 * 経度・緯度は実際の値。投影の範囲は今後 geography.mjs で定義する
 * (団体側の見積りでは経度-17〜51度・緯度37〜-35度、都市1つあたり約90k px²
 * 目標なら BW≈2258×BH≈2391 前後になる見込み。都市総数が決まってから確定する)。
 *
 * ## この5都市で選んだ角度
 *
 * - ダルエスサラーム(`eaf`): タンザニア自前の鉄道(ドイツ・イギリスが敷いた
 *   メーターゲージ1000mm)と、中国が建設したタンザン鉄道TAZARA(ケープゲージ
 *   1067mm)が同じ市内の別々のターミナルに着き、いまも物理的につながっていない。
 *   「軌間の断絶」を都市の中の断絶として書く。
 * - カピリンポシ(`saf`): TAZARAのザンビア側終点。あえてザンビア既存網と
 *   同じ軌間で敷かれた点(ダルエスサラームとは対照的に軌間は揃っている)と、
 *   「白人少数支配のローデシア/南アフリカを通らずに銅を運ぶ」という
 *   建設そのものの政治的動機を書く。理想が薄れたあとの赤字も隠さない。
 * - ジブチ(`hoa`): 1917年開通のフランス製メーターゲージ線が朽ちて止まり、
 *   2018年の中国製電化標準軌線がそれに置き換わった。エリトリア戦争で
 *   陸封国エチオピアがこの港にいっそう依存するようになった経緯も書く。
 *   「いま新しく敷かれている線」の代表例。
 * - ルブンバシ(`caf`): カタンガの銅を運ぶために競合した3本の植民地鉄道
 *   (ベルギー領コンゴ川水系・イギリス領ローデシア経由・ポルトガル領
 *   アンゴラのベンゲラ鉄道)。どれも隣国を結ぶためではなく、資源を
 *   最短で港へ運ぶためだけに敷かれたという主題そのもの。
 * - ダカール(`gof`): ダカール〜ニジェール鉄道(1907〜1923年)は、内陸の
 *   交易をイギリス領ガンビア/シエラレオネの港へ逃がさないための線。
 *   国際旅客が途絶えたあと、2021年開通のTERは国境を越えない都市内路線
 *   になった——「植民地時代の線」と「いまの新線」を1都市で対比させる。
 *
 * モロッコとガーナの盤面にある都市は、この5都市では選んでいない。
 */
import { city, prop } from "../../content-overrides/city-helpers.mjs";

export const AFRICA_CITIES = {
  // ---------------------------------------------------------------------
  // eaf — 東アフリカ・大湖地方
  // ---------------------------------------------------------------------
  daressalaam: city(
    "Dar es Salaam|Dar es Salam|Dar es-Salaam|ダルエスサラーム",
    39.2083, -6.7924, "eaf", "gauge", "portrail", "l",
    "A port where two railways still don't touch tracks|Un puerto donde dos anchos de vía todavía no se tocan|Un port où deux écartements ne se touchent toujours pas|二つの軌間がいまも触れ合わない港",
    "Tanzania's own railway, built to metre gauge (1,000mm) by German and British colonizers from 1905, reaches the harbour at Dar es Salaam from one side of downtown; the Tanzania–Zambia Railway (TAZARA), opened in 1975 on the wider Cape gauge (1,067mm) with Chinese financing and around 50,000 Chinese engineers and labourers over the course of construction, reaches it from a separate terminal on the other side. The two networks have never been physically linked, so freight switching between them is trucked across the city instead of simply rolled from one gauge onto the other.|La red ferroviaria propia de Tanzania, tendida con ancho métrico (1.000 mm) por los colonizadores alemanes y británicos desde 1905, llega al puerto de Dar es Salaam desde un lado del centro; el Ferrocarril Tanzania-Zambia (TAZARA), inaugurado en 1975 con el ancho Cabo más amplio (1.067 mm), financiado por China y construido por unos 50.000 ingenieros y obreros chinos a lo largo de la obra, llega a él desde una terminal aparte al otro lado. Las dos redes nunca se han conectado físicamente, así que la carga que cambia de una a otra se transporta en camión a través de la ciudad en vez de simplemente rodar de un ancho al otro.|Le réseau ferroviaire propre à la Tanzanie, posé à l'écartement métrique (1 000 mm) par les colonisateurs allemands puis britanniques à partir de 1905, atteint le port de Dar es Salaam d'un côté du centre-ville ; le chemin de fer Tanzanie-Zambie (TAZARA), ouvert en 1975 à l'écartement Cap plus large (1 067 mm), financé par la Chine et construit par environ 50 000 ingénieurs et ouvriers chinois au fil du chantier, l'atteint depuis un terminus séparé de l'autre côté. Les deux réseaux n'ont jamais été physiquement reliés, si bien que le fret changeant de l'un à l'autre est transporté en camion à travers la ville plutôt que simplement roulé d'un écartement à l'autre.|ドイツとイギリスの植民地当局が1905年から敷いたタンザニア自前の鉄道網は、軌間1000mm(メーターゲージ)で市街の一方からダルエスサラームの港に達する。中国の資金援助と、のべ約5万人の中国人技術者・労働者によって1975年に開通したタンザン鉄道(TAZARA)は、より広い軌間1067mm(ケープゲージ)で市の反対側の別のターミナルから港に達する。二つの鉄道網はいまも物理的につながっておらず、貨物の積み替えは軌間を履き替えるのではなく、トラックで市内を横切って運ばれる。",
    [prop("TAZARA Terminus Platform|Andén de la terminal de TAZARA|Quai du terminus du TAZARA|タンザン鉄道ターミナルのホーム", 900, 185),
     prop("Central Line Break-of-Gauge Yard|Patio de cambio de ancho de la Línea Central|Cour de changement d'écartement de la ligne centrale|セントラル線の軌間境界操車場", 500, 103)],
  ),

  // ---------------------------------------------------------------------
  // saf — 南部アフリカ
  // ---------------------------------------------------------------------
  kapirimposhi: city(
    "New Kapiri Mposhi|Nueva Kapiri Mposhi|New Kapiri Mposhi|ニューカピリンポシ",
    28.6833, -13.9667, "saf", "junction", "railjunction", "r",
    "A junction chosen so Zambia's copper could avoid two countries|Un empalme elegido para que el cobre de Zambia evitara dos países|Une jonction choisie pour que le cuivre zambien évite deux pays|ザンビアの銅が二つの国を避けるために選ばれた分岐点",
    "When Zambia's government looked for a copper export route that touched neither white-minority-ruled Rhodesia nor apartheid South Africa, China agreed to build TAZARA, laying it deliberately to the same 1,067mm gauge as Zambia's own network so wagons could roll straight from one system onto the other. New Kapiri Mposhi, a stop 200km north of Lusaka with little else to distinguish it, became the line's Zambian terminus when it opened in 1975; once white-minority rule ended in both neighbouring countries during the 1980s and 1990s, cheaper southern routes drew most of the copper traffic back, and TAZARA has run at a loss for decades since.|Cuando el gobierno de Zambia buscó una ruta de exportación de cobre que no tocara ni la Rodesia gobernada por la minoría blanca ni la Sudáfrica del apartheid, China aceptó construir el TAZARA, tendido deliberadamente con el mismo ancho de 1.067 mm que la propia red zambiana para que los vagones pudieran pasar directamente de un sistema a otro. Nueva Kapiri Mposhi, una parada 200 km al norte de Lusaka sin nada más que la distinguiera, se convirtió en la terminal zambiana de la línea cuando esta abrió en 1975; una vez que el gobierno de la minoría blanca terminó en los dos países vecinos durante los años ochenta y noventa, las rutas del sur, más baratas, recuperaron la mayor parte del tráfico de cobre, y el TAZARA lleva décadas operando con pérdidas.|Quand le gouvernement zambien a cherché une route d'exportation du cuivre qui ne touche ni la Rhodésie dirigée par la minorité blanche ni l'Afrique du Sud de l'apartheid, la Chine a accepté de construire le TAZARA, posé délibérément au même écartement de 1 067 mm que le réseau zambien lui-même afin que les wagons puissent rouler directement d'un système à l'autre. New Kapiri Mposhi, un arrêt à 200 km au nord de Lusaka sans rien d'autre pour le distinguer, devint le terminus zambien de la ligne à son ouverture en 1975 ; une fois le pouvoir de la minorité blanche tombé dans les deux pays voisins durant les années 1980 et 1990, des routes méridionales moins chères ont récupéré l'essentiel du trafic de cuivre, et le TAZARA fonctionne à perte depuis des décennies.|ザンビア政府が、白人少数支配下のローデシアにもアパルトヘイト下の南アフリカにも触れない銅の輸出路を探していたとき、中国はザンビア自前の鉄道網と同じ軌間1067mmであえて敷いたタンザン鉄道の建設を引き受けた。これにより貨車は一方の路線からもう一方へそのまま乗り入れられる。ルサカの北200kmにある、それ以外は特に目立たない駅だったニューカピリンポシは、1975年の開通時にこの路線のザンビア側終点となった。しかし1980〜90年代に両隣国の白人少数支配が終わると、より安価な南回りの経路が銅の輸送の大半を取り戻し、タンザン鉄道はそれ以来数十年にわたって赤字を続けている。",
    [prop("New Kapiri Mposhi Terminus Hall|Sala de la terminal de Nueva Kapiri Mposhi|Salle du terminus de New Kapiri Mposhi|ニューカピリンポシ駅の待合ホール", 400, 82),
     prop("Zambia Railways Interchange Sidings|Vías de enlace de Zambia Railways|Voies de raccordement de Zambia Railways|ザンビア鉄道の連絡側線", 260, 54)],
  ),

  // ---------------------------------------------------------------------
  // hoa — アフリカの角
  // ---------------------------------------------------------------------
  djibouti: city(
    "Djibouti|Yibuti|Djibouti|ジブチ",
    43.1456, 11.5885, "hoa", "electric", "desertport", "l",
    "The port that outlived its railway, then got a faster one|El puerto que sobrevivió a su ferrocarril, y luego tuvo uno más rápido|Le port qui a survécu à son chemin de fer, puis en a eu un plus rapide|自らの鉄道より長生きし、やがてより速い鉄道を得た港",
    "The French-built, metre-gauge Djibouti–Addis Ababa railway opened in 1917 as Ethiopia's only rail link to the sea and stayed the country's main outside connection for most of the 20th century, before decades of poor maintenance slowed it to a crawl and it stopped running altogether in the 2000s. Ethiopia lost access to Eritrea's ports after a 1998–2000 border war, making Djibouti's harbour even more essential, and in 2018 a new Chinese-built, electrified standard-gauge line reopened the same route at speeds the old one never came close to; it now carries over 90% of landlocked Ethiopia's trade.|El ferrocarril Djibouti-Adís Abeba, construido por Francia con ancho métrico, se inauguró en 1917 como el único enlace ferroviario de Etiopía con el mar y siguió siendo la principal conexión exterior del país durante casi todo el siglo XX, hasta que décadas de mal mantenimiento lo redujeron a paso de tortuga y dejó de circular por completo en los años 2000. Etiopía perdió el acceso a los puertos de Eritrea tras una guerra fronteriza en 1998-2000, lo que hizo aún más esencial el puerto de Yibuti, y en 2018 una nueva línea de ancho estándar, electrificada y construida por China, reabrió la misma ruta a velocidades que la antigua jamás alcanzó; hoy transporta más del 90% del comercio de la Etiopía sin salida al mar.|Le chemin de fer Djibouti-Addis-Abeba, construit par la France à l'écartement métrique, ouvrit en 1917 comme unique liaison ferroviaire de l'Éthiopie vers la mer et resta la principale connexion extérieure du pays pendant presque tout le XXe siècle, avant que des décennies de mauvais entretien ne le ralentissent à une allure d'escargot et qu'il ne cesse totalement de circuler dans les années 2000. L'Éthiopie perdit l'accès aux ports érythréens après une guerre frontalière en 1998-2000, rendant le port de Djibouti encore plus essentiel, et en 2018 une nouvelle ligne à écartement standard, électrifiée et construite par la Chine, rouvrit le même trajet à des vitesses que l'ancienne n'avait jamais approchées ; elle transporte aujourd'hui plus de 90 % du commerce de l'Éthiopie enclavée.|フランスが建設した軌間1000mmのジブチ―アディスアベバ鉄道は1917年に開通し、エチオピアが海へ出る唯一の鉄路として20世紀のほとんどを通じてこの国の主要な対外路であり続けた。しかし整備不足が数十年続いた末に速度は這うように遅くなり、2000年代にはついに運行を止めた。1998〜2000年の国境戦争でエチオピアがエリトリアの港を使えなくなったことでジブチの港はいっそう不可欠になり、2018年には中国建設の電化標準軌(1435mm)の新線が同じ経路を、旧線とは比べ物にならない速度で結び直した。いまや内陸国エチオピアの貿易の9割以上がこの路線を通っている。",
    [prop("Nagad Electrified Rail Terminal|Terminal ferroviaria electrificada de Nagad|Terminal ferroviaire électrifié de Nagad|ナガド電化鉄道ターミナル", 1100, 227),
     prop("Old French Station Quarter|Barrio de la vieja estación francesa|Quartier de l'ancienne gare française|旧フランス駅前地区", 500, 103)],
  ),

  // ---------------------------------------------------------------------
  // caf — 中部アフリカ・コンゴ盆地
  // ---------------------------------------------------------------------
  lubumbashi: city(
    "Lubumbashi|Lubumbashi|Lubumbashi|ルブンバシ",
    27.4794, -11.6609, "caf", "smelter", "copperbelt", "r",
    "A copper town with three ways out and none of them local|Una ciudad del cobre con tres salidas, ninguna local|Une ville du cuivre à trois sorties, aucune locale|三つの出口を持ちながら、どれも隣国へは向かわない銅の町",
    "Belgian colonists founded Lubumbashi in 1910 as Élisabethville to work the copper of Katanga, and getting that copper to a coast meant choosing between three competing colonial railways: north and west along the Congo River system to the Belgian-run port of Matadi, south through British-administered Rhodesia to South African ports, or west across Portuguese Angola on the Benguela Railway, completed in 1931, to the Atlantic port of Lobito. None of the three was built to connect neighbouring countries to each other; each moved Katanga's copper the shortest way to whichever empire's coastline was available, and Angola's civil war shut the Benguela route for decades until it fully reopened only in 2015.|Los colonos belgas fundaron Lubumbashi en 1910 como Élisabethville para explotar el cobre de Katanga, y llevar ese cobre hasta una costa suponía elegir entre tres ferrocarriles coloniales rivales: al norte y al oeste por el sistema del río Congo hasta el puerto belga de Matadi, al sur a través de la Rodesia administrada por los británicos hasta puertos sudafricanos, o al oeste cruzando la Angola portuguesa por el Ferrocarril de Benguela, terminado en 1931, hasta el puerto atlántico de Lobito. Ninguna de las tres se construyó para conectar países vecinos entre sí; cada una llevaba el cobre de Katanga por el camino más corto hasta la costa del imperio que estuviera disponible, y la guerra civil angoleña cerró la ruta de Benguela durante décadas, hasta que reabrió por completo solo en 2015.|Les colons belges fondèrent Lubumbashi en 1910 sous le nom d'Élisabethville pour exploiter le cuivre du Katanga, et acheminer ce cuivre jusqu'à une côte imposait de choisir entre trois chemins de fer coloniaux rivaux : au nord et à l'ouest par le réseau du fleuve Congo jusqu'au port belge de Matadi, au sud à travers la Rhodésie administrée par les Britanniques jusqu'aux ports sud-africains, ou à l'ouest à travers l'Angola portugais par le chemin de fer de Benguela, achevé en 1931, jusqu'au port atlantique de Lobito. Aucun des trois n'avait été construit pour relier des pays voisins entre eux ; chacun acheminait le cuivre du Katanga par la route la plus courte vers la côte de l'empire disponible, et la guerre civile angolaise ferma la ligne de Benguela pendant des décennies, jusqu'à sa pleine réouverture en 2015 seulement.|ベルギー人入植者は1910年、カタンガの銅を採掘するためにエリザベートヴィルとしてルブンバシを建設した。その銅を海岸まで運ぶには、互いに競い合う三つの植民地鉄道のどれかを選ぶ必要があった。北西へコンゴ川水系をたどりベルギー統治下の港マタディへ向かう路線、南へイギリス統治下のローデシアを抜けて南アフリカの港へ向かう路線、そして西へポルトガル領アンゴラを横断し、1931年に完成したベンゲラ鉄道で大西洋岸のロビト港へ向かう路線である。この三つはいずれも隣国どうしを結ぶために敷かれたのではなく、それぞれがカタンガの銅をそのとき使える帝国の海岸まで最短で運ぶためだけに存在した。ベンゲラ線はアンゴラ内戦のために数十年閉ざされ、全面再開したのは2015年になってからだった。",
    [prop("Copper Smelter Rail Siding|Vía muerta de la fundición de cobre|Voie de garage de la fonderie de cuivre|銅精錬所の側線", 700, 144),
     prop("Union Minière Rail Yard|Patio ferroviario de la Union Minière|Cour ferroviaire de l'Union Minière|ユニオン・ミニエール鉄道操車場", 450, 93)],
  ),

  // ---------------------------------------------------------------------
  // gof — ギニア湾岸
  // ---------------------------------------------------------------------
  dakar: city(
    "Dakar|Dakar|Dakar|ダカール",
    -17.4467, 14.6928, "gof", "peanut", "atlanticport", "r",
    "A railway built to keep the interior's trade out of a rival's ports|Un ferrocarril construido para que el comercio del interior no fuera a puertos rivales|Un chemin de fer bâti pour que le commerce de l'intérieur évite les ports rivaux|内陸の交易を競合国の港へ逃がさないために敷かれた鉄道",
    "French colonial administrators built the Dakar–Niger railway in stages from 1907 to 1923, mainly to carry groundnuts and other exports from what is now Mali down to Dakar's harbour rather than let that trade drift toward British-run ports in nearby Gambia or Sierra Leone. Passenger trains covered the 1,300km run to Bamako for most of the 20th century, but international service collapsed for good in the 2000s as the track fell into disrepair. Dakar's next passenger railway, the electric TER commuter line opened in 2021 and extended to the international airport in 2024, had nothing to do with the old colonial route and has never crossed a border.|Los administradores coloniales franceses construyeron el ferrocarril Dakar-Níger por etapas entre 1907 y 1923, sobre todo para llevar cacahuetes y otras exportaciones desde lo que hoy es Malí hasta el puerto de Dakar, en vez de dejar que ese comercio se desviara hacia los puertos británicos de la vecina Gambia o Sierra Leona. Los trenes de pasajeros cubrieron el trayecto de 1.300 km hasta Bamako durante casi todo el siglo XX, pero el servicio internacional se derrumbó definitivamente en los años 2000 al deteriorarse la vía. El siguiente ferrocarril de pasajeros de Dakar, la línea eléctrica de cercanías TER, inaugurada en 2021 y extendida hasta el aeropuerto internacional en 2024, no tuvo nada que ver con la antigua ruta colonial y nunca ha cruzado una frontera.|Les administrateurs coloniaux français construisirent le chemin de fer Dakar-Niger par étapes de 1907 à 1923, surtout pour acheminer l'arachide et d'autres exportations depuis ce qui est aujourd'hui le Mali jusqu'au port de Dakar, plutôt que de laisser ce commerce dériver vers les ports britanniques de la Gambie ou de la Sierra Leone voisines. Des trains de voyageurs parcoururent les 1 300 km jusqu'à Bamako pendant presque tout le XXe siècle, mais le service international s'effondra définitivement dans les années 2000 à mesure que la voie se dégradait. Le chemin de fer de voyageurs suivant de Dakar, la ligne électrique de banlieue TER ouverte en 2021 et prolongée jusqu'à l'aéroport international en 2024, n'avait aucun lien avec l'ancienne route coloniale et n'a jamais franchi de frontière.|フランスの植民地当局は1907年から1923年にかけて段階的にダカール―ニジェール鉄道を建設した。おもな目的は、今日のマリにあたる内陸部の落花生などの輸出品を、近隣のガンビアやシエラレオネにあるイギリス統治下の港へ流れさせず、ダカールの港へ運び下ろすことだった。旅客列車は20世紀のほとんどを通じてバマコまでの1300kmを走り続けたが、線路の荒廃とともに国際旅客サービスは2000年代についに途絶えた。ダカールが次に得た旅客鉄道、2021年に開通し2024年には国際空港まで延伸された電化通勤鉄道TERは、この旧植民地路線とは無関係で、いまだ一度も国境を越えたことがない。",
    [prop("Dakar-Niger Rail Terminus|Terminal del ferrocarril Dakar-Níger|Terminus du chemin de fer Dakar-Niger|ダカール―ニジェール鉄道の終着駅", 800, 165),
     prop("TER Regional Rail Platform|Andén regional del TER|Quai régional du TER|TER地域鉄道のホーム", 950, 196)],
  ),

  // ---------------------------------------------------------------------
  // mag — マグレブ・ナイル・モーリタニア
  // ---------------------------------------------------------------------
  cairo: city(
    "Cairo|El Cairo|Le Caire|カイロ",
    31.2357, 30.0444, "mag", "pyramid", "nilebank", "l",
    "Africa's first railway, then Africa's first metro|El primer ferrocarril de África, luego su primer metro|Le premier chemin de fer d'Afrique, puis son premier métro|アフリカ最初の鉄道、そして最初の地下鉄",
    "The Cairo–Alexandria railway, opened in 1854 under British engineer Robert Stephenson's firm, was the first railway built anywhere in Africa or the Middle East. Cairo returned to that first-on-the-continent role in 1987, opening Africa's first metro system, which today moves well over a billion passengers a year through a city whose surface traffic ranks among the world's most congested.|El ferrocarril Cairo-Alejandría, inaugurado en 1854 por la empresa del ingeniero británico Robert Stephenson, fue el primer ferrocarril construido en cualquier parte de África o Oriente Medio. El Cairo repitió ese papel pionero en 1987 al abrir el primer sistema de metro de África, que hoy mueve muchísimo más de mil millones de pasajeros al año en una ciudad cuyo tráfico en superficie está entre los más congestionados del mundo.|Le chemin de fer Le Caire-Alexandrie, ouvert en 1854 par l'entreprise de l'ingénieur britannique Robert Stephenson, fut le premier chemin de fer construit en Afrique ou au Moyen-Orient. Le Caire rejoua ce rôle de pionnier du continent en 1987 en ouvrant le premier métro d'Afrique, qui transporte aujourd'hui bien plus d'un milliard de passagers par an dans une ville dont la circulation de surface compte parmi les plus congestionnées au monde.|1854年、イギリス人技師ロバート・スティーヴンソンの会社が開通させたカイロ―アレクサンドリア鉄道は、アフリカでも中東でも最初の鉄道だった。カイロは1987年、アフリカ初の地下鉄を開通させて再び大陸の先頭に立った。この地下鉄はいまや年間10億人をゆうに超える乗客を運んでおり、地上の交通は世界有数の渋滞で知られる街を支えている。",
    [prop("1854 Cairo Terminus Platform|Andén de la terminal de El Cairo de 1854|Quai du terminus du Caire de 1854|1854年開通カイロ駅のホーム", 1400, 288),
     prop("Cairo Metro Line 1 Concourse|Vestíbulo de la Línea 1 del metro de El Cairo|Hall de la ligne 1 du métro du Caire|カイロ地下鉄1号線のコンコース", 900, 185)],
  ),
  alexandria: city(
    "Alexandria|Alejandría|Alexandrie|アレクサンドリア",
    29.9187, 31.2001, "mag", "port", "nilebank", "l",
    "The Mediterranean end of Africa's oldest railway|El extremo mediterráneo del ferrocarril más antiguo de África|L'extrémité méditerranéenne du plus vieux chemin de fer d'Afrique|アフリカ最古の鉄道が地中海に着く終点",
    "Alexandria was the western terminus of the 1854 Cairo–Alexandria line, Africa's first railway, built to move Egyptian cotton to Mediterranean steamships faster than the Nile's barges ever could; the crop's exports boomed further after the American Civil War cut off competing US cotton supplies in the 1860s. The colonial-era Misr Station, rebuilt in the 1920s with a domed clock tower, still anchors the city's rail network more than 170 years later.|Alejandría fue la terminal occidental de la línea Cairo-Alejandría de 1854, el primer ferrocarril de África, construido para llevar el algodón egipcio a los vapores del Mediterráneo más rápido de lo que jamás pudieron las barcazas del Nilo; las exportaciones del cultivo se dispararon aún más después de que la Guerra Civil estadounidense cortara el algodón rival de EE. UU. en la década de 1860. La estación Misr de la época colonial, reconstruida en los años veinte con una torre del reloj abovedada, sigue siendo el eje de la red ferroviaria de la ciudad más de 170 años después.|Alexandrie fut le terminus occidental de la ligne Le Caire-Alexandrie de 1854, premier chemin de fer d'Afrique, construite pour acheminer le coton égyptien vers les vapeurs méditerranéens plus vite que ne l'avaient jamais fait les péniches du Nil ; les exportations du coton s'envolèrent encore après que la guerre de Sécession américaine eut coupé le coton concurrent des États-Unis dans les années 1860. La gare Misr de l'époque coloniale, reconstruite dans les années 1920 avec une tour d'horloge à coupole, reste le pivot du réseau ferroviaire de la ville plus de 170 ans plus tard.|アレクサンドリアは1854年開通のカイロ―アレクサンドリア鉄道(アフリカ最初の鉄道)の西の終点であり、エジプト産綿花をナイル川のはしけよりずっと速く地中海の汽船へ運ぶために敷かれた。1860年代にアメリカ南北戦争でアメリカ産綿花の輸出が途絶えると、この輸出はさらに膨らんだ。植民地時代のミスル駅は1920年代にドーム型の時計塔を備えて建て直され、170年以上を経たいまも市の鉄道網の要であり続けている。",
    [prop("Misr Station Clock Tower|Torre del reloj de la estación Misr|Tour d'horloge de la gare Misr|ミスル駅の時計塔", 1000, 206),
     prop("Cotton Exchange Quay|Muelle de la bolsa del algodón|Quai de la bourse du coton|綿花取引所の埠頭", 650, 134)],
  ),
  aswan: city(
    "Aswan|Asuán|Assouan|アスワン",
    32.8998, 24.0889, "mag", "dam", "nilebank", "r",
    "The railhead where the Cape-to-Cairo dream ran out of continent|La cabecera donde el sueño de El Cabo a El Cairo se quedó sin continente|Le terminus où le rêve du Cap au Caire a manqué de continent|ケープ〜カイロ構想が大陸を使い果たした終着駅",
    "Aswan became Egypt's southernmost rail terminus in 1898, built partly to move labour and stone for the first Aswan Dam and partly as the northern anchor of Cecil Rhodes's dream of a British 'Cape to Cairo' railway spanning the continent — a dream never realised, undone by gaps through Sudan and Central Africa that were never closed. The much larger Aswan High Dam, completed in 1970, now floods the old cataract the earlier line was built to bypass.|Asuán se convirtió en la terminal ferroviaria más meridional de Egipto en 1898, construida en parte para transportar mano de obra y piedra para la primera presa de Asuán, y en parte como el ancla septentrional del sueño de Cecil Rhodes de un ferrocarril británico 'de El Cabo a El Cairo' que recorriera todo el continente, un sueño nunca cumplido, deshecho por los tramos sin construir en Sudán y África Central que jamás se cerraron. La presa Alta de Asuán, mucho mayor y terminada en 1970, hoy inunda la antigua catarata que la primera línea fue construida para sortear.|Assouan devint le terminus ferroviaire le plus méridional d'Égypte en 1898, construit en partie pour acheminer main-d'œuvre et pierre vers le premier barrage d'Assouan, et en partie comme ancrage septentrional du rêve de Cecil Rhodes d'un chemin de fer britannique « du Cap au Caire » traversant tout le continent — un rêve jamais réalisé, défait par des tronçons manquants au Soudan et en Afrique centrale qui ne furent jamais comblés. Le barrage d'Assouan, bien plus vaste et achevé en 1970, inonde aujourd'hui l'ancienne cataracte que la première ligne fut bâtie pour contourner.|アスワンは1898年、エジプトで最も南にある鉄道の終着駅になった。最初のアスワンダム建設のための労働力と石材を運ぶためであると同時に、大陸を縦断するセシル・ローズの「ケープ〜カイロ鉄道」構想の北の起点でもあった。この構想はついに実現せず、スーダンや中部アフリカに残った空白区間は最後まで埋まらなかった。はるかに大規模なアスワン・ハイダムは1970年に完成し、最初の路線が迂回するために敷かれた古い急流をいまは水底に沈めている。",
    [prop("1898 Aswan Terminus Platform|Andén de la terminal de Asuán de 1898|Quai du terminus d'Assouan de 1898|1898年開通アスワン駅のホーム", 700, 144),
     prop("First Cataract Quay|Muelle de la Primera Catarata|Quai de la première cataracte|第一急流の船着き場", 500, 103)],
  ),
  tunis: city(
    "Tunis|Túnez|Tunis|チュニス",
    10.1815, 36.8065, "mag", "medina", "oldtown", "l",
    "Africa's oldest electric line, next to a border line that no longer runs|La línea eléctrica más antigua de África, junto a una frontera sin trenes|La plus vieille ligne électrique d'Afrique, à côté d'une frontière sans trains|アフリカ最古の電化路線と、いまは走らない国境路線",
    "The TGM line linking Tunis to its northern suburbs opened in 1872 and was electrified in 1908, making it one of the oldest electric railways still running anywhere in Africa. A separate international line once carried passengers all the way from Tunis to Algiers, but regular cross-border passenger service between Tunisia and Algeria has not run in years, and today the track sees only occasional freight.|La línea TGM que une Túnez con sus suburbios del norte se inauguró en 1872 y se electrificó en 1908, lo que la convierte en uno de los ferrocarriles eléctricos más antiguos que siguen funcionando en toda África. Una línea internacional aparte llevaba antes a los pasajeros desde Túnez hasta Argel, pero el servicio regular de pasajeros entre Túnez y Argelia lleva años sin circular, y hoy la vía solo ve algún tren de mercancías ocasional.|La ligne TGM reliant Tunis à ses banlieues nord ouvrit en 1872 et fut électrifiée en 1908, ce qui en fait l'un des plus anciens chemins de fer électriques encore en service en Afrique. Une ligne internationale distincte menait autrefois les voyageurs de Tunis jusqu'à Alger, mais le service régulier de voyageurs entre la Tunisie et l'Algérie ne circule plus depuis des années, et la voie ne voit plus aujourd'hui que du fret occasionnel.|チュニスと北の郊外を結ぶTGM線は1872年に開通し、1908年に電化された。アフリカでいまも走る電化鉄道としては最も古い部類に入る。かつては別の国際路線がチュニスからアルジェまで旅客を運んでいたが、チュニジアとアルジェリアを結ぶ定期旅客サービスはここ数年途絶えており、いまその線路を通るのはときおりの貨物列車だけである。",
    [prop("TGM La Marsa Terminus|Terminal de La Marsa del TGM|Terminus du TGM à La Marsa|TGM線ラ・マルサ終着駅", 600, 124),
     prop("Tunis–Algiers Border Halt|Apeadero fronterizo Túnez-Argel|Halte frontalière Tunis-Alger|チュニス―アルジェ国境の停車場", 320, 66)],
  ),
  sfax: city(
    "Sfax|Sfax|Sfax|スファックス",
    10.7603, 34.7406, "mag", "port", "harborcity", "r",
    "A phosphate line that made a small port surprisingly rich|Una línea de fosfatos que hizo rico a un pequeño puerto|Une ligne de phosphate qui a rendu un petit port étonnamment riche|小さな港を思いがけず豊かにしたリン鉱石の鉄道",
    "Sfax grew wealthy on phosphate mined at Gafsa and Metlaoui and hauled to its harbour by a French-built mining railway completed in 1899, decades before oil was found anywhere nearby; by the early 20th century Tunisia ranked among the world's largest phosphate exporters almost entirely because of this one line. The trade still runs today, though repeated strikes and blockades along the Gafsa–Sfax line in recent years have shown how easily a single-corridor economy can be brought to a halt.|Sfax se enriqueció con el fosfato extraído en Gafsa y Metlaoui y transportado a su puerto por un ferrocarril minero construido por Francia y terminado en 1899, décadas antes de que se encontrara petróleo en cualquier lugar cercano; a principios del siglo XX Túnez figuraba entre los mayores exportadores mundiales de fosfato casi enteramente gracias a esta única línea. El comercio sigue hoy en marcha, aunque las repetidas huelgas y bloqueos en la línea Gafsa-Sfax en años recientes han mostrado lo fácil que es paralizar una economía que depende de un solo corredor.|Sfax s'enrichit grâce au phosphate extrait à Gafsa et Métlaoui et acheminé jusqu'à son port par un chemin de fer minier construit par la France et achevé en 1899, des décennies avant qu'on ne trouve du pétrole à proximité ; au début du XXe siècle, la Tunisie comptait parmi les plus grands exportateurs mondiaux de phosphate presque uniquement grâce à cette seule ligne. Le commerce se poursuit aujourd'hui, mais les grèves et blocages répétés sur la ligne Gafsa-Sfax ces dernières années ont montré combien il est facile de paralyser une économie à corridor unique.|スファックスは、ガフサやメトラウィで採れるリン鉱石をフランス建設の鉱山鉄道(1899年完成)で港まで運ぶことで富を得た。近くで石油が見つかるよりずっと前のことである。20世紀初頭、チュニジアはほぼこの一本の鉄道のおかげで世界有数のリン鉱石輸出国になった。この交易はいまも続いているが、近年ガフサ―スファックス線で繰り返されるストライキや封鎖は、一本の輸送路に頼る経済がいかに簡単に止まってしまうかを示している。",
    [prop("Gafsa Phosphate Loading Quay|Muelle de carga de fosfato de Gafsa|Quai de chargement du phosphate de Gafsa|ガフサ産リン鉱石の積出埠頭", 550, 113),
     prop("1899 Mining Rail Terminus|Terminal ferroviaria minera de 1899|Terminus ferroviaire minier de 1899|1899年開通の鉱山鉄道終着駅", 400, 82)],
  ),
  algiers: city(
    "Algiers|Argel|Alger|アルジェ",
    3.0588, 36.7538, "mag", "gauge", "oldtown", "l",
    "A gauge that matches its neighbours, a border that doesn't|Un ancho de vía que coincide con los vecinos, una frontera que no|Un écartement conforme à ses voisins, une frontière qui ne l'est pas|隣国と揃う軌間、揃わない国境",
    "French engineers built Algeria's railways, starting with the Algiers–Blida line in 1862, to the 1,435mm standard gauge used in mainland France — the same choice made across Morocco and Tunisia, but a very different one from almost every French, British, German, Belgian or Portuguese railway built anywhere south of the Sahara, which nearly all used a narrower gauge to save money. Gauge alone would let a train run from Tangier to Tunis; the Algeria–Morocco land border, closed since 1994, is what actually stops it, not the tracks.|Los ingenieros franceses construyeron los ferrocarriles de Argelia, empezando por la línea Argel-Blida en 1862, con el ancho estándar de 1.435 mm usado en la Francia metropolitana, la misma elección hecha en Marruecos y Túnez, pero muy distinta de casi todos los ferrocarriles franceses, británicos, alemanes, belgas o portugueses construidos al sur del Sahara, que casi siempre usaron un ancho más estrecho para ahorrar dinero. El ancho de vía por sí solo permitiría que un tren fuera de Tánger a Túnez; es la frontera terrestre entre Argelia y Marruecos, cerrada desde 1994, la que en realidad lo impide, no las vías.|Les ingénieurs français construisirent les chemins de fer algériens, à commencer par la ligne Alger-Blida en 1862, à l'écartement standard de 1 435 mm utilisé en France métropolitaine — le même choix fait au Maroc et en Tunisie, mais très différent de presque tous les chemins de fer français, britanniques, allemands, belges ou portugais construits au sud du Sahara, qui utilisèrent presque tous un écartement plus étroit pour économiser. L'écartement seul permettrait à un train de rouler de Tanger à Tunis ; c'est la frontière terrestre algéro-marocaine, fermée depuis 1994, qui l'en empêche réellement, pas les rails.|フランス人技師たちは1862年のアルジェ―ブリダ線を皮切りに、本国フランスと同じ軌間1435mm(標準軌)でアルジェリアの鉄道を敷いた。これはモロッコやチュニジアでも同じ選択だったが、サハラ以南でフランス・イギリス・ドイツ・ベルギー・ポルトガルが敷いたほぼすべての鉄道(たいてい費用を抑えるためより狭い軌間を選んだ)とはまったく異なる。軌間だけを見ればタンジェからチュニスまで一本の列車が走れるはずだが、実際にそれを阻んでいるのは線路ではなく、1994年から閉じられたままのアルジェリア―モロッコ国境である。",
    [prop("Algiers–Blida Line Terminus|Terminal de la línea Argel-Blida|Terminus de la ligne Alger-Blida|アルジェ―ブリダ線の終着駅", 850, 175),
     prop("Agha Station Concourse|Vestíbulo de la estación Agha|Hall de la gare d'Agha|アガ駅のコンコース", 700, 144)],
  ),
  oran: city(
    "Oran|Orán|Oran|オラン",
    -0.6418, 35.6971, "mag", "border", "borderline", "r",
    "A border station that has waited three decades for a train|Una estación fronteriza que espera un tren desde hace tres décadas|Une gare frontière qui attend un train depuis trois décennies|三十年、列車を待ち続ける国境の駅",
    "Oran once had a direct rail connection to Morocco through Tlemcen and Oujda, part of the same standard-gauge Maghreb network that also reaches Tunis, but Algeria closed its land border with Morocco in 1994 after a militant attack in Marrakesh was blamed on Algerian involvement, and the frontier has stayed shut ever since. The rails at the border post are still there, rusting from three decades without a single train.|Orán tuvo antes una conexión ferroviaria directa con Marruecos a través de Tremecén y Uxda, parte de la misma red magrebí de ancho estándar que también llega a Túnez, pero Argelia cerró su frontera terrestre con Marruecos en 1994 tras un atentado en Marrakech que se atribuyó a la implicación argelina, y la frontera ha permanecido cerrada desde entonces. Los raíles del puesto fronterizo siguen ahí, oxidándose tras tres décadas sin un solo tren.|Oran avait autrefois une liaison ferroviaire directe avec le Maroc via Tlemcen et Oujda, faisant partie du même réseau maghrébin à écartement standard qui atteint aussi Tunis, mais l'Algérie ferma sa frontière terrestre avec le Maroc en 1994 après qu'un attentat à Marrakech eut été imputé à une implication algérienne, et la frontière est restée close depuis. Les rails du poste-frontière sont toujours là, rouillant après trois décennies sans un seul train.|オランはかつて、チュニスにも達する同じ標準軌のマグレブ鉄道網を通じて、トレムセンとウジダ経由でモロッコと直接結ばれていた。しかし1994年、マラケシュでの襲撃事件にアルジェリアの関与が疑われたことをきっかけにアルジェリアがモロッコとの陸上国境を閉鎖し、それ以来国境は閉じられたままである。国境の駅の線路はいまも残っているが、三十年間一本の列車も通らないまま錆びついている。",
    [prop("Oran Ville Station Hall|Sala de la estación de Orán Ciudad|Salle de la gare d'Oran-Ville|オラン・ヴィル駅の駅舎", 500, 103),
     prop("Closed Frontier Rail Spur|Ramal ferroviario de la frontera cerrada|Embranchement de la frontière fermée|閉ざされた国境の側線", 260, 54)],
  ),
  constantine: city(
    "Constantine|Constantina|Constantine|コンスタンティーヌ",
    6.6147, 36.3650, "mag", "viaduct", "highlandpass", "l",
    "A city whose railway had to cross a gorge before it could go anywhere|Una ciudad cuyo ferrocarril tuvo que cruzar un desfiladero antes de ir a ningún sitio|Une ville dont le chemin de fer a dû franchir un gouffre avant d'aller ailleurs|どこへ向かうより先に、自らの峡谷を越えねばならなかった鉄道の町",
    "Constantine sits on a rock plateau ringed by a gorge roughly 200 metres deep, and before the railway could connect the city to Algiers or the Tunisian border it first had to solve the gorge itself; engineers threaded the line along ledges and short tunnels cut into the cliff face to reach the station, part of the eastern Algerian network completed in the 1870s and 1880s. The city's several suspension and arch bridges spanning the same gorge, built across the following decades, are now as much a symbol of Constantine as the railway that first forced the crossing.|Constantina se asienta en una meseta rocosa rodeada por un desfiladero de unos 200 metros de profundidad, y antes de que el ferrocarril pudiera conectar la ciudad con Argel o la frontera tunecina, primero tuvo que resolver el propio desfiladero; los ingenieros trazaron la línea por repisas y túneles cortos excavados en el acantilado para llegar a la estación, parte de la red del este argelino completada en las décadas de 1870 y 1880. Los varios puentes colgantes y de arco de la ciudad que cruzan el mismo desfiladero, construidos en las décadas siguientes, son hoy tan símbolo de Constantina como el ferrocarril que primero forzó el cruce.|Constantine se dresse sur un plateau rocheux ceint d'un gouffre profond d'environ 200 mètres, et avant que le chemin de fer ne puisse relier la ville à Alger ou à la frontière tunisienne, il dut d'abord résoudre le gouffre lui-même ; les ingénieurs firent passer la ligne par des corniches et de courts tunnels taillés dans la falaise pour atteindre la gare, dans le cadre du réseau de l'Est algérien achevé dans les années 1870 et 1880. Les nombreux ponts suspendus et en arc de la ville enjambant le même gouffre, construits au cours des décennies suivantes, sont aujourd'hui tout autant un symbole de Constantine que le chemin de fer qui força le premier passage.|コンスタンティーヌは深さ約200メートルの峡谷に囲まれた岩の台地の上にある。鉄道がこの街をアルジェやチュニジア国境と結ぶ前に、まず峡谷そのものを克服しなければならなかった。技師たちは崖に刻んだ棚状の道と短いトンネルで線路を通し、1870〜80年代に完成した東部アルジェリアの鉄道網の一部として駅へたどり着かせた。その後数十年で架けられた市内のいくつもの吊り橋・アーチ橋は、いまではこの峡谷を最初に越えた鉄道と同じくらい、コンスタンティーヌを象徴する存在になっている。",
    [prop("Rhumel Gorge Rail Ledge|Repisa ferroviaria del desfiladero del Rhumel|Corniche ferroviaire du gouffre du Rhumel|ルメル峡谷の鉄道棚道", 480, 99),
     prop("Sidi M'Cid Bridge Overlook|Mirador del puente Sidi M'Cid|Belvédère du pont Sidi M'Cid|シディ・ムシッド橋の展望台", 380, 78)],
  ),
  nouadhibou: city(
    "Nouadhibou|Nuadibú|Nouadhibou|ヌアディブ",
    -17.0347, 20.9310, "mag", "caravan", "sahara", "r",
    "The line built for one train, 2.5 kilometres of it at a time|La línea construida para un solo tren, de 2,5 kilómetros|La ligne bâtie pour un seul train, 2,5 kilomètres à la fois|たった一本の、しかし2.5kmの列車のために敷かれた線",
    "The SNIM railway hauls iron ore about 700km from the mines at Zouérat to the port at Nouadhibou on trains regularly over 2.5km long with 200 or more wagons, among the longest trains running anywhere in the world; the line has no passenger timetable, no connection to any other railway, and crosses no border despite running the length of the country. Local travellers ride anyway, climbing onto the empty ore wagons for the only overland route across this stretch of the Sahara, an unofficial practice railway staff have long tolerated rather than approved.|El ferrocarril de la SNIM transporta mineral de hierro unos 700 km desde las minas de Zuérate hasta el puerto de Nuadibú en trenes que suelen superar los 2,5 km de longitud con 200 vagones o más, entre los trenes más largos que circulan en el mundo; la línea no tiene horario de pasajeros, no se conecta con ningún otro ferrocarril y no cruza ninguna frontera pese a recorrer todo el país. Aun así, los viajeros locales suben a los vagones vacíos de mineral para tener la única ruta terrestre a través de este tramo del Sahara, una práctica no oficial que el personal ferroviario lleva tiempo tolerando sin aprobarla.|Le chemin de fer de la SNIM achemine le minerai de fer sur environ 700 km depuis les mines de Zouérate jusqu'au port de Nouadhibou, sur des trains dépassant régulièrement 2,5 km de long avec 200 wagons ou plus, parmi les plus longs trains circulant au monde ; la ligne n'a aucun horaire voyageurs, aucune connexion avec un autre chemin de fer, et ne franchit aucune frontière bien qu'elle traverse tout le pays. Les voyageurs locaux y montent quand même, grimpant sur les wagons de minerai vides pour emprunter l'unique route terrestre à travers ce tronçon du Sahara, une pratique officieuse que le personnel ferroviaire tolère depuis longtemps sans l'approuver.|SNIM鉄道は、ズエラットの鉱山からヌアディブの港まで約700kmにわたって鉄鉱石を運ぶ。列車はしばしば2.5kmを超える長さで貨車200両以上にもなり、世界でも屈指の長さの列車として知られる。この路線には旅客時刻表が無く、他のどの鉄道ともつながっておらず、国を縦断していながら国境を一つも越えない。それでも地元の人々は、このサハラの一角を陸路で渡る唯一の手段として、空の鉱石貨車によじ登って乗る。鉄道側が長らく黙認してきた非公式の慣行である。",
    [prop("Zouérat Ore Loading Terminal|Terminal de carga de mineral de Zuérate|Terminal de chargement du minerai de Zouérate|ズエラット鉱石積出ターミナル", 620, 128),
     prop("Nouadhibou Ore Wharf|Muelle de mineral de Nuadibú|Quai à minerai de Nouadhibou|ヌアディブ鉱石埠頭", 400, 82)],
  ),
};

/**
 * 路線。5都市は地理的に大きく離れており(東アフリカ・南部アフリカ・
 * アフリカの角・中部アフリカ・西アフリカ)、この時点で意味のある直接の
 * 隣接路線は無い。都市が出そろってから、地方内の近い都市どうしを
 * つなぐ形で設計する。
 */
export const AFRICA_EDGES = [];
