/**
 * キューバの都市と路線。
 *
 * ## この盤面の芯(フェーズ1・5都市のみ)
 *
 * 「スペイン本国より11年早く鉄道を持った島」。1837年11月19日、ハバナ―ベフカル
 * 間で蒸気機関車が走り、イベロアメリカ(ラテンアメリカ)最初の鉄道が開業した。
 * スペイン本国最初の鉄道(バルセロナ―マタロ)は1848年で、11年遅れている。
 *
 * **なぜそうなったか。**この鉄道はスペイン王室の金ではなく、ハバナの砂糖・
 * タバコ商人たちが牛耳るフォメント公社(Junta de Fomento)が出資して敷いた。
 * 狙いは人ではなく砂糖で、雨季にぬかるむ道を牛車で運ぶ非効率と時間の目減りを
 * 断つためだった。**ハバナ―ベフカル―グイネスという経路そのものが、最初から
 * 目的地として計画されていた。**1830年設立の鉄の道委員会がこの経路をすでに
 * 検討しており、1832年にはグイネス周辺の砂糖農園主たち(ペドロ・ディアゴ、
 * ラファエル・オファリルら)が、自分たちの畑からハバナへの道を作ってほしいと
 * 自ら請願している。フォメント公社総裁ビリャヌエバ伯クラウディオ・マルティネス・
 * デ・ピニリョスが計画を再開し、1834年10月12日に女王の認可を得た。南岸
 * バタバノーへの支線は曲げて捨てられた案ではなく、1841年になって初めて認可
 * された**あとから足された枝**にすぎない(開業は1843年12月)——鉄道は
 * 最初から、乗客ではなく、請願した農園主たちの砂糖のために敷かれている。
 *
 * 早い時期の建設に誰の手が使われたかも(惨状としてではなく構造として)
 * 書いた。ベフカルの豆知識を参照。
 *
 * この5都市は、開業(ハバナ)→実際の終点(ベフカル)→本来の狙い(グイネス)→
 * 2番目の鉄道と砂糖港の拡張(カルデナス)→砂糖景気が去ったあとに残ったもの
 * (トリニダー、遺産としての鉄道)という流れで選んだ。
 *
 * ## 地方(3区分・確定ではない。全都市確定時に見直す)
 *
 * `oc` オクシデンテ(西部・ハバナ周辺、鉄道発祥の地) / `ce` セントロ(中部、
 * 砂糖農園主の私有鉄道が伸びた地帯) / `or` オリエンテ(東部)。
 * 音楽3地方の指定に合わせている(oc=ダンソン系、ce=グアヒーラ/田舎の吟遊、
 * or=ソン/チャンギー発祥)。
 *
 * ## mark / bg
 *
 * まだ仮のキー。絵の担当が付く前提で、全都市が揃ってから見直す
 * (`docs/50-authoring` の「絵の鍵は規則で決める」を参照)。
 */
import { city, prop } from "../../content-overrides/city-helpers.mjs";

export const CUBA_CITIES = {
  // ---------------------------------------------------------------------
  // oc — オクシデンテ(西部。鉄道発祥の地)
  // ---------------------------------------------------------------------
  habana: city(
    "Havana|La Habana|La Havane|ハバナ",
    -82.3666, 23.1136, "oc", "steamdepot", "capitalport", "l",
    "The city Spain's own railway would not catch for eleven years|La ciudad que España tardó once años en igualar con su propio ferrocarril|La ville que l'Espagne mettra onze ans à rattraper avec son propre chemin de fer|スペイン本国の鉄道が11年追いつけなかった町",
    "On 19 November 1837 a steam locomotive pulled out of Havana bound for Bejucal, opening the first railway anywhere in Latin America — eleven years before Spain built one of its own, between Barcelona and Mataró in 1848. It was paid for not by the Spanish crown but by the Junta de Fomento, a board dominated by Havana's sugar and tobacco merchants, who wanted cane sugar off the mud roads and onto rails before the cost of hauling it by ox-cart ate into a harvest that could not wait.|El 19 de noviembre de 1837 una locomotora de vapor salió de La Habana rumbo a Bejucal, abriendo el primer ferrocarril de toda Latinoamérica, once años antes de que España construyera el suyo propio, entre Barcelona y Mataró, en 1848. Lo pagó no la corona española, sino la Junta de Fomento, dominada por los comerciantes de azúcar y tabaco de La Habana, que querían sacar el azúcar del barro de los caminos y subirlo a los rieles antes de que el costo de acarrearlo en carretas se comiera las ganancias de una zafra que no podía esperar.|Le 19 novembre 1837, une locomotive à vapeur quitta La Havane pour Bejucal, ouvrant le premier chemin de fer de toute l'Amérique latine — onze ans avant que l'Espagne ne construise le sien, entre Barcelone et Mataró, en 1848. Il fut financé non par la couronne espagnole mais par la Junta de Fomento, un conseil dominé par les marchands de sucre et de tabac de La Havane, qui voulaient sortir la canne des routes boueuses et la mettre sur des rails avant que le coût du transport par char à bœufs n'entame une récolte qui ne pouvait attendre.|1837年11月19日、ハバナからベフカルへ向けて蒸気機関車が走り出し、ラテンアメリカで最初の鉄道が開業した。スペイン本国がバルセロナ―マタロ間に自国初の鉄道を開業させる1848年より、実に11年早い。費用を出したのはスペイン王室ではなく、ハバナの砂糖・タバコ商人が牛耳るフォメント公社だった。狙いは、待ったなしの収穫期に、牛車でぬかるんだ道を運ぶ費用と時間の目減りから砂糖を救い出し、線路の上に乗せることだった。",
    [prop("Railway Terminus Warehouse|Almacén de la terminal ferroviaria|Entrepôt de la gare terminus|鉄道終着駅の倉庫", 420, 86),
     prop("Sugar Merchants' Counting House|Casa de cambio de los hacendados azucareros|Comptoir des marchands de sucre|砂糖商人の勘定部屋", 2600, 533)],
  ),
  bejucal: city(
    "Bejucal|Bejucal|Bejucal|ベフカル",
    -82.3833, 22.9333, "oc", "firstterminus", "smalltownplaza", "r",
    "The actual end of the line, not Havana|El verdadero final de la línea, no La Habana|Le véritable terminus de la ligne, pas La Havane|路線の本当の終点は、ハバナではなかった",
    "Bejucal, not Havana itself, marked the end of the railway's first completed stretch: 27.5 kilometres of track opened here on 19 November 1837, part of a Havana–Bejucal–Güines route a colonial roads board had already been studying since 1830. The rails themselves were laid mostly by gangs of enslaved workers rented from nearby estates, working alongside free immigrant labourers — including Irish and Canary Island contract workers, hired because planters were unwilling to risk their more valuable slaves on such dangerous construction work — and from the 1850s, as the network kept growing, indentured Chinese labourers joined that same mix.|Bejucal, y no La Habana misma, marcó el final del primer tramo terminado del ferrocarril: los 27,5 kilómetros de vía se inauguraron aquí el 19 de noviembre de 1837, como parte de una ruta Habana–Bejucal–Güines que una junta colonial de caminos ya venía estudiando desde 1830. Los propios rieles los tendieron sobre todo cuadrillas de esclavizados alquilados de las fincas cercanas, junto con jornaleros inmigrantes libres —entre ellos irlandeses y canarios contratados, porque los hacendados no querían arriesgar a sus esclavos más valiosos en un trabajo tan peligroso—, y desde la década de 1850, a medida que la red seguía creciendo, se sumaron también trabajadores chinos bajo contrato de servidumbre.|Bejucal, et non La Havane elle-même, marqua la fin du premier tronçon achevé du chemin de fer : les 27,5 kilomètres de voie y furent inaugurés le 19 novembre 1837, dans le cadre d'un tracé Havane–Bejucal–Güines qu'une commission coloniale des routes étudiait déjà depuis 1830. Les rails eux-mêmes furent posés surtout par des équipes d'esclaves loués aux propriétés voisines, aux côtés d'ouvriers immigrés libres — dont des Irlandais et des Canariens engagés sous contrat, les planteurs répugnant à risquer leurs esclaves les plus précieux dans un chantier aussi dangereux — et, à partir des années 1850, des travailleurs chinois sous contrat d'engagisme vinrent s'ajouter à ce même mélange à mesure que le réseau s'étendait.|路線の本当の終点はハバナではなく、ベフカルだった。27.5キロメートルの線路が1837年11月19日にここで開業し、これは1830年設立の鉄の道委員会がすでに検討していたハバナ―ベフカル―グイネス経路の最初の区間だった。線路そのものは主に、近隣の農園から借り出された奴隷の作業班によって敷かれ、そこにアイルランドやカナリア諸島から契約で来た自由身分の移民労働者も加わっていた。より高価な奴隷を危険な工事で失いたくない農園主たちが、こうした労働者を雇ったためである。1850年代以降、鉄道網がさらに伸びるにつれて、年季奉公の中国人労働者も同じ現場に加わっていった。",
    [prop("Track-Gang Work Camp|Campamento de la cuadrilla de vía|Camp de la brigade de pose de voie|線路工事班の飯場", 220, 46),
     prop("1837 Terminus Platform|Andén de la terminal de 1837|Quai du terminus de 1837|1837年開業ホームの跡", 260, 54)],
  ),
  guines: city(
    "Güines|Güines|Güines|グイネス",
    -82.0167, 22.8333, "oc", "canefield", "sugarplain", "b",
    "The plain whose planters asked for the railway themselves|La llanura cuyos hacendados pidieron el ferrocarril ellos mismos|La plaine dont les planteurs réclamèrent eux-mêmes le chemin de fer|農園主たちが自ら鉄道を求めた平野",
    "Güines sits amid the flattest, richest cane country near Havana — Cubans nicknamed the plain 'the garden of Cuba' — and this sugar country was the destination from the very start: a Havana–Bejucal–Güines route was already being studied by a colonial roads board in 1830, and the line reached Güines, 44.5 kilometres out, at the very end of 1839. It was sugar planters who pushed the project forward, not planners looking for a shortcut: in 1832 a group that included Pedro Diago and Rafael O'Farril petitioned the colonial government directly for a railway from their own cane fields at Güines to the port of Havana, years before a branch line to the south-coast port of Batabanó was even authorised, in 1841.|Güines se asienta en la llanura cañera más rica y plana cerca de La Habana —los cubanos apodaron a esta llanura 'el jardín de Cuba'— y esta zona azucarera fue el destino desde el principio: una junta colonial de caminos ya estudiaba en 1830 una ruta Habana–Bejucal–Güines, y la línea llegó a Güines, a 44,5 kilómetros de distancia, a finales de 1839. Fueron los propios hacendados quienes impulsaron el proyecto, no ingenieros en busca de un atajo: en 1832 un grupo que incluía a Pedro Diago y Rafael O'Farril pidió directamente al gobierno colonial un ferrocarril desde sus propios cañaverales de Güines hasta el puerto de La Habana, años antes de que se autorizara siquiera, en 1841, un ramal al puerto sureño de Batabanó.|Güines se trouve au cœur de la plaine à canne la plus riche et la plus plate près de La Havane — les Cubains surnommaient cette plaine « le jardin de Cuba » — et cette région sucrière fut la destination dès le départ : une commission coloniale des routes étudiait déjà en 1830 un tracé Havane–Bejucal–Güines, et la ligne atteignit Güines, à 44,5 kilomètres, à la toute fin de 1839. Ce sont les planteurs de sucre eux-mêmes qui firent avancer le projet, et non des ingénieurs en quête d'un raccourci : en 1832, un groupe comprenant Pedro Diago et Rafael O'Farril demanda directement au gouvernement colonial un chemin de fer reliant leurs propres champs de canne de Güines au port de La Havane, des années avant qu'un embranchement vers le port méridional de Batabanó ne soit seulement autorisé, en 1841.|グイネスは、ハバナ近郊でもっとも平らで肥沃なサトウキビ地帯にある。この平野はキューバの人々に「キューバの庭」と呼ばれた。この砂糖地帯こそが最初からの目的地であり、1830年にはすでに鉄の道委員会がハバナ―ベフカル―グイネスという経路を検討していた。路線は1839年の年末、44.5キロメートル先のグイネスに到達した。この計画を進めたのは近道を探す技師たちではなく、砂糖農園主たち自身だった。1832年、ペドロ・ディアゴやラファエル・オファリルらを含む一団が、自分たちの畑があるグイネスからハバナ港への鉄道を、植民地政府へ直接請願している。南岸の港バタバノーへの支線がようやく認可されたのは、それより何年もあとの1841年のことである。",
    [prop("Cane Plain Warehouse|Almacén de la llanura cañera|Entrepôt de la plaine à canne|サトウキビ平野の倉庫", 240, 50),
     prop("Planters' Petition House|Casa de la petición de los hacendados|Maison de la pétition des planteurs|農園主たちの請願の家", 210, 44)],
  ),
  pinardelrio: city(
    "Pinar del Río|Pinar del Río|Pinar del Río|ピナル・デル・リオ",
    -83.6981, 22.4175, "oc", "tobaccoleaf", "tobaccovalley", "l",
    "The tobacco capital the railway reached last|La capital del tabaco a la que el ferrocarril llegó al final|La capitale du tabac que le chemin de fer atteignit en dernier|鉄道が最後にたどり着いたタバコの都",
    "Pinar del Río sits at the western edge of Vuelta Abajo, the small growing region whose shade-grown leaf is generally rated the finest cigar tobacco in the world, and rollers elsewhere still pay a premium for it. Because tobacco here was grown on small family plots rather than the vast estates sugar needed, the province was one of the last parts of the island reached by rail, its line arriving only in the 1890s, decades after cane country further east was already crossed with track.|Pinar del Río se asienta en el extremo occidental de Vuelta Abajo, la pequeña región cuya hoja cultivada a la sombra suele considerarse el mejor tabaco de puro del mundo, y torcedores de otros lugares aún pagan un sobreprecio por ella. Como aquí el tabaco se cultivaba en pequeñas parcelas familiares y no en las grandes fincas que exigía el azúcar, la provincia fue de las últimas partes de la isla a las que llegó el ferrocarril, cuya línea no llegó hasta la década de 1890, décadas después de que la zona cañera más al este ya estuviera cruzada por vías.|Pinar del Río se trouve à l'extrémité occidentale de Vuelta Abajo, la petite région dont la feuille cultivée à l'ombre est généralement considérée comme le meilleur tabac à cigare au monde, et les rouleurs d'ailleurs paient encore un supplément pour l'obtenir. Comme le tabac y était cultivé sur de petites parcelles familiales plutôt que sur les vastes domaines qu'exigeait le sucre, la province fut l'une des dernières parties de l'île atteintes par le rail, sa ligne n'arrivant que dans les années 1890, des décennies après que le pays de la canne plus à l'est fut déjà traversé de voies.|ピナル・デル・リオは、ビエルタ・アバホ地方の西端に位置する。日陰で育てられるこの狭い産地の葉は、世界でも最高級の葉巻タバコとされ、他国の巻き手たちはいまも割高な値段を払ってこれを求める。ここのタバコは砂糖が必要とした広大な農園ではなく小さな家族経営の畑で育てられていたため、この州は島の中でも鉄道がもっとも遅く届いた地域のひとつだった。線路が届いたのは1890年代になってからで、東側の砂糖地帯にはすでに何十年も前から線路が通っていた。",
    [prop("Vuelta Abajo Leaf Warehouse|Almacén de hoja de Vuelta Abajo|Entrepôt de feuille de Vuelta Abajo|ビエルタ・アバホ葉たばこ倉庫", 300, 62),
     prop("Late-Arriving Rail Depot|Depósito del ferrocarril tardío|Dépôt du chemin de fer tardif|遅れて着いた鉄道の車庫", 220, 46)],
  ),
  vinales: city(
    "Viñales|Viñales|Viñales|ビニャーレス",
    -83.7134, 22.6167, "oc", "mogote", "karstvalley", "r",
    "A valley farmed the way it always was, without rails|Un valle cultivado como siempre, sin rieles|Une vallée cultivée comme toujours, sans rails|鉄道が来ないまま、昔ながらの耕し方を続ける谷",
    "The limestone mogotes that ring the Viñales valley are riddled with caves, and the deep red soil between them is still worked largely by ox and plough rather than machinery, because a landscape this steep and broken never attracted the branch lines built for flatter cane country. UNESCO listed the valley in 1999 for exactly that unbroken traditional farming, not for any ruin — it's one of the few places in Cuba where the old way of moving a harvest never needed replacing.|Los mogotes de piedra caliza que rodean el valle de Viñales están llenos de cuevas, y la tierra roja y profunda entre ellos todavía se trabaja sobre todo con bueyes y arado en vez de maquinaria, porque un paisaje tan escarpado y quebrado nunca atrajo los ramales construidos para la zona cañera más llana. La UNESCO declaró el valle en 1999 precisamente por esa agricultura tradicional ininterrumpida, no por ninguna ruina: es uno de los pocos lugares de Cuba donde la vieja forma de mover una cosecha nunca tuvo que sustituirse.|Les mogotes calcaires qui entourent la vallée de Viñales sont criblés de grottes, et la terre rouge et profonde qui les sépare est encore travaillée surtout au bœuf et à la charrue plutôt qu'à la machine, car un relief aussi escarpé et découpé n'a jamais attiré les embranchements construits pour le pays de la canne, plus plat. L'UNESCO a classé la vallée en 1999 précisément pour cette agriculture traditionnelle ininterrompue, et non pour une ruine quelconque : c'est l'un des rares endroits de Cuba où l'ancienne façon d'acheminer une récolte n'a jamais eu besoin d'être remplacée.|ビニャーレス渓谷を取り囲む石灰岩の岩山モゴテには洞窟が無数にあり、その間に広がる深い赤土はいまも機械ではなく牛と鋤で耕されることが多い。これほど急峻で入り組んだ地形には、より平らな砂糖地帯向けに敷かれた支線が引かれることがなかったからである。ユネスコが1999年にこの谷を登録したのは、廃墟としてではなく、まさにこの途切れない伝統的な農法そのものに対してだった。ここはキューバでも数少ない、収穫を運ぶ昔ながらのやり方を置き換える必要が一度もなかった土地である。",
    [prop("Mogote-Ringed Tobacco Vega|Vega de tabaco entre mogotes|Vega de tabac entre mogotes|モゴテに囲まれたタバコ農園", 260, 54),
     prop("Ox-Plough Farmstead|Finca de arado con bueyes|Ferme au labour à bœufs|牛耕の農家", 200, 42)],
  ),
  matanzas: city(
    "Matanzas|Matanzas|Matanzas|マタンサス",
    -81.5775, 23.0511, "oc", "danzonhall", "sugarport", "l",
    "Where a ballroom dance was born in the city sugar built|Donde nació un baile de salón en la ciudad que hizo el azúcar|Où naquit une danse de salon dans la ville bâtie par le sucre|砂糖が築いた町で生まれた舞踏場のダンス",
    "Matanzas grew rich enough on sugar exports through its bay that Cubans nicknamed it the 'Athens of Cuba' for its theatres and poets, and its own rail line to Havana, opened in the 1840s, was among Cuba's earliest extensions beyond the original Güines route. In 1879 a local bandleader named Miguel Failde premiered a slower, closer-partnered dance called danzón at a Matanzas ballroom, and it became Cuba's first officially recognised national dance.|Matanzas se enriqueció tanto con las exportaciones de azúcar por su bahía que los cubanos la apodaron 'la Atenas de Cuba' por sus teatros y poetas, y su propia línea de ferrocarril hasta La Habana, inaugurada en la década de 1840, fue una de las primeras extensiones de Cuba más allá de la ruta original de Güines. En 1879, un director de orquesta local llamado Miguel Failde estrenó en un salón de Matanzas un baile más lento y de pareja más cercana llamado danzón, que se convirtió en el primer baile nacional oficialmente reconocido de Cuba.|Matanzas s'enrichit tant grâce aux exportations de sucre par sa baie que les Cubains la surnommèrent « l'Athènes de Cuba » pour ses théâtres et ses poètes, et sa propre ligne ferroviaire vers La Havane, ouverte dans les années 1840, fut l'une des premières extensions de Cuba au-delà du tracé initial de Güines. En 1879, un chef d'orchestre local nommé Miguel Failde créa dans une salle de bal de Matanzas une danse plus lente et à couple plus rapproché appelée danzón, qui devint la première danse nationale officiellement reconnue de Cuba.|マタンサスは入り江を通じた砂糖輸出でたいへん豊かになり、劇場と詩人の多さから「キューバのアテネ」と呼ばれた。ハバナへ向かう独自の鉄道は1840年代に開業し、もとのグイネス路線を超えてキューバで最初期に延伸された路線のひとつだった。1879年、地元の楽団指揮者ミゲル・ファイジェは、より遅いテンポで男女が近く組んで踊るダンソンという踊りをマタンサスの舞踏場で初披露し、これはキューバで最初に公式に国民的な踊りと認められた。",
    [prop("Danzón Ballroom|Salón de baile del danzón|Salle de bal du danzón|ダンソン発祥の舞踏場", 650, 133),
     prop("Bayfront Sugar Pier|Muelle azucarero de la bahía|Quai à sucre de la baie|入り江の砂糖桟橋", 300, 62)],
  ),
  batabano: city(
    "Batabanó|Batabanó|Batabanó|バタバノー",
    -82.2939, 22.7061, "oc", "spongeboat", "fishingport", "b",
    "The branch that came six years after Güines|El ramal que llegó seis años después que Güines|L'embranchement arrivé six ans après Güines|グイネスから6年遅れて届いた支線",
    "The line to Batabanó, on Cuba's south coast, wasn't authorised until 1841 and opened in December 1843 — six years after the original railway reached Bejucal — built to shorten the route for trade heading toward the Caribbean and South America rather than for sugar. The town's economy turned instead to the sea itself: Batabanó became one of Cuba's main sponge-fishing ports, and boats still go out from here for the sponge beds of the Gulf of Batabanó.|La línea a Batabanó, en la costa sur de Cuba, no se autorizó hasta 1841 y se inauguró en diciembre de 1843 —seis años después de que el ferrocarril original llegara a Bejucal—, construida para acortar la ruta del comercio hacia el Caribe y Sudamérica y no por el azúcar. La economía del pueblo se volcó en cambio hacia el propio mar: Batabanó se convirtió en uno de los principales puertos esponjeros de Cuba, y de aquí todavía salen barcos hacia los criaderos de esponjas del golfo de Batabanó.|La ligne vers Batabanó, sur la côte sud de Cuba, ne fut autorisée qu'en 1841 et ouverte en décembre 1843 — six ans après que le chemin de fer d'origine eut atteint Bejucal —, construite pour raccourcir la route du commerce vers les Caraïbes et l'Amérique du Sud plutôt que pour le sucre. L'économie de la ville se tourna plutôt vers la mer elle-même : Batabanó devint l'un des principaux ports d'éponges de Cuba, et des bateaux en repartent encore aujourd'hui vers les bancs d'éponges du golfe de Batabanó.|キューバ南岸のバタバノーへの路線が認可されたのは1841年になってからで、開業は1843年12月——最初の鉄道がベフカルに届いてから実に6年後だった。これは砂糖のためではなく、カリブ海・南米交易の航路を短くするために敷かれたものだった。この町の経済はむしろ海そのものに向かった。バタバノーはキューバ有数の海綿漁の港となり、いまもバタバノー湾の海綿床へ向けて船が出ている。",
    [prop("Sponge-Diving Wharf|Muelle de los esponjeros|Quai des pêcheurs d'éponges|海綿漁の桟橋", 240, 50),
     prop("1843 Branch Terminus|Terminal del ramal de 1843|Terminus de l'embranchement de 1843|1843年開業の支線終着駅", 200, 42)],
  ),
  artemisa: city(
    "Artemisa|Artemisa|Artemisa|アルテミサ",
    -82.7642, 22.8133, "oc", "mixedcrop", "sugarplain", "r",
    "A sugar and tobacco town split down the middle|Un pueblo dividido entre el azúcar y el tabaco|Une ville partagée entre le sucre et le tabac|砂糖とタバコに引き裂かれた町",
    "Artemisa grew up around the Ferrocarril del Oeste's push west from Havana in the mid-19th century, and the district's soil made it suited to both sugar and tobacco, a mixed economy unusual for a Cuban rail town built mostly to move a single crop. Its warehouses once served both a sugar mill and a cigar-leaf trade, and the town remains one of the few in western Cuba where neither crop ever fully overtook the other.|Artemisa creció en torno al avance hacia el oeste del Ferrocarril del Oeste desde La Habana a mediados del siglo XIX, y el suelo de la zona la hacía apta tanto para el azúcar como para el tabaco, una economía mixta poco común en un pueblo ferroviario cubano construido casi siempre para mover un solo cultivo. Sus almacenes sirvieron a la vez a un ingenio azucarero y al comercio de hoja de tabaco, y el pueblo sigue siendo uno de los pocos del occidente cubano donde ningún cultivo llegó a imponerse del todo sobre el otro.|Artemisa se développa autour de la poussée vers l'ouest du Ferrocarril del Oeste depuis La Havane au milieu du XIXe siècle, et le sol du district la rendait propice à la fois au sucre et au tabac, une économie mixte inhabituelle pour une ville ferroviaire cubaine bâtie presque toujours pour transporter une seule culture. Ses entrepôts servaient à la fois une sucrerie et le commerce de la feuille à cigares, et la ville reste l'une des rares de l'ouest cubain où aucune des deux cultures n'a jamais vraiment supplanté l'autre.|アルテミサは、19世紀半ばにハバナから西へ延びていった西部鉄道(フェロカリル・デル・オエステ)の周りに育った町である。この一帯の土壌は砂糖にもタバコにも向いており、単一の作物を運ぶために敷かれることが多いキューバの鉄道の町としては珍しい、二つの作物が併存する経済を持っていた。かつての倉庫は製糖工場と葉巻用タバコの取引の両方に使われ、この町はいまもキューバ西部で数少ない、どちらの作物も完全にはもう一方を圧倒しなかった土地のひとつである。",
    [prop("Mixed-Crop Warehouse|Almacén de cultivos mixtos|Entrepôt à cultures mixtes|混作の倉庫", 230, 48),
     prop("Ferrocarril del Oeste Yard|Patio del Ferrocarril del Oeste|Cour du Ferrocarril del Oeste|西部鉄道の操車場", 210, 44)],
  ),
  sanantoniodelosbanos: city(
    "San Antonio de los Baños|San Antonio de los Baños|San Antonio de los Baños|サン・アントニオ・デ・ロス・バニョス",
    -82.5014, 22.8908, "oc", "sulphurspring", "smalltownplaza", "l",
    "Thermal springs, then a rail stop, then a film school|Aguas termales, luego una parada de tren, luego una escuela de cine|Des sources thermales, puis un arrêt de train, puis une école de cinéma|温泉、それから鉄道の駅、それから映画学校",
    "The town grew up around sulphur springs that Havana's colonial elite visited for their health, and once the Ferrocarril del Oeste reached it in the 19th century the springs became easier to get to than ever, turning San Antonio into a resort town as much as a farming one. It's now known nationally for something the railway never carried: the Escuela Internacional de Cine y Televisión, a filmmaking school that has trained students from across Latin America since 1986, is based here rather than in Havana.|El pueblo creció en torno a unos manantiales sulfurosos que la élite colonial de La Habana visitaba por su salud, y en cuanto el Ferrocarril del Oeste llegó aquí en el siglo XIX, los baños se volvieron más accesibles que nunca, convirtiendo a San Antonio tanto en un pueblo balneario como agrícola. Hoy es conocido en todo el país por algo que el ferrocarril nunca transportó: la Escuela Internacional de Cine y Televisión, que forma a estudiantes de toda Latinoamérica desde 1986, tiene su sede aquí y no en La Habana.|La ville se développa autour de sources sulfureuses que l'élite coloniale de La Havane fréquentait pour sa santé, et dès que le Ferrocarril del Oeste l'atteignit au XIXe siècle, les bains devinrent plus accessibles que jamais, faisant de San Antonio une ville thermale autant qu'agricole. Elle est aujourd'hui connue dans tout le pays pour quelque chose que le chemin de fer n'a jamais transporté : l'Escuela Internacional de Cine y Televisión, une école de cinéma qui forme des étudiants venus de toute l'Amérique latine depuis 1986, a son siège ici plutôt qu'à La Havane.|この町は、ハバナの植民地時代の上流階級が療養に訪れた硫黄泉の周りに発展した。19世紀に西部鉄道が届くと、温泉はそれまでになく行きやすくなり、サン・アントニオは農業の町であると同時に保養地にもなった。いまこの町が全国的に知られているのは、鉄道が一度も運んだことのないものによってである。1986年からラテンアメリカ各地の学生を育ててきた映画学校、国際映画テレビ学校(EICTV)は、ハバナではなくここに本拠を置いている。",
    [prop("Sulphur Spring Bathhouse|Balneario de aguas sulfurosas|Établissement thermal sulfureux|硫黄温泉の浴場", 260, 54),
     prop("Film School Backlot|Terreno de la escuela de cine|Terrain de l'école de cinéma|映画学校の撮影地", 280, 58)],
  ),
  nuevagerona: city(
    "Nueva Gerona|Nueva Gerona|Nueva Gerona|ヌエバ・ヘロナ",
    -82.8033, 21.8811, "oc", "grapefruitcrate", "islandtown", "r",
    "An island whose railway carried grapefruit, not sugar|Una isla cuyo ferrocarril llevaba toronjas, no azúcar|Une île dont le chemin de fer transportait des pamplemousses, pas du sucre|砂糖ではなくグレープフルーツを運んだ島の鉄道",
    "Isla de la Juventud, then called Isla de Pinos, grew citrus rather than cane, and a narrow-gauge railway built in the early 20th century by settlers who had bought up land there hauled grapefruit and oranges to the coast for export rather than sugar. The island is separated from the mainland by open water, so unlike almost everywhere else in this story, no bridge or causeway ever let a mainland line reach it — everything here still has to go by boat.|La Isla de la Juventud, entonces llamada Isla de Pinos, cultivaba cítricos en vez de caña, y un ferrocarril de vía estrecha construido a principios del siglo XX por colonos que habían comprado tierras allí llevaba toronjas y naranjas hasta la costa para exportarlas, no azúcar. La isla está separada del resto del país por mar abierto, así que, a diferencia de casi todos los demás lugares de esta historia, ningún puente ni terraplén permitió jamás que llegara una línea desde tierra firme: aquí todo todavía tiene que ir en barco.|L'Isla de la Juventud, alors appelée Isla de Pinos, cultivait des agrumes plutôt que de la canne, et un chemin de fer à voie étroite construit au début du XXe siècle par des colons ayant acheté des terres là-bas transportait pamplemousses et oranges vers la côte pour l'exportation, et non du sucre. L'île est séparée du continent par la pleine mer, donc, contrairement à presque tous les autres lieux de cette histoire, aucun pont ni digue n'a jamais permis à une ligne continentale de l'atteindre — ici, tout doit encore passer par bateau.|現在の青年の島(イスラ・デ・ラ・フベントゥ)は、かつてはイスラ・デ・ピノスと呼ばれ、サトウキビではなく柑橘類を育てていた。20世紀初頭、この地に土地を買い集めた入植者たちが敷いた狭軌鉄道は、砂糖ではなくグレープフルーツやオレンジを海岸まで運んで輸出するためのものだった。この島は本土と外洋で隔てられているため、この物語に出てくるほかのほとんどの場所と違い、本土の路線を橋や築堤でつなぐことは一度もなかった。ここではいまも何もかも船で運ぶしかない。",
    [prop("Citrus Export Wharf|Muelle de exportación de cítricos|Quai d'exportation d'agrumes|柑橘輸出の桟橋", 240, 50),
     prop("Narrow-Gauge Grapefruit Line|Vía angosta de la toronja|Voie étroite du pamplemousse|グレープフルーツ運搬の狭軌線", 220, 46)],
  ),
  consolaciondelsur: city(
    "Consolación del Sur|Consolación del Sur|Consolación del Sur|コンソラシオン・デル・スル",
    -83.5169, 22.5069, "oc", "tobaccobundle", "tobaccovalley", "b",
    "Between the tobacco fields and the railhead|Entre los campos de tabaco y la cabecera del ferrocarril|Entre les champs de tabac et la tête de ligne|タバコ畑と鉄道の終端のあいだで",
    "Consolación del Sur sits in Vuelta Abajo's second, slightly less prized tobacco belt, and its warehouses long served as a staging point where leaf grown on outlying vegas (tobacco farms) was bundled before the final haul to Pinar del Río. The town's own rail link only reached this deep into the tobacco zone toward the very end of the 19th century, decades after the sugar lines further east had already crossed the island.|Consolación del Sur se encuentra en la segunda franja tabacalera de Vuelta Abajo, algo menos prestigiosa, y sus almacenes sirvieron durante mucho tiempo como punto de acopio donde se empacaba la hoja cultivada en las vegas cercanas antes del traslado final a Pinar del Río. El propio enlace ferroviario del pueblo no llegó tan adentro de la zona tabacalera hasta finales del siglo XIX, décadas después de que las líneas azucareras más al este ya hubieran cruzado la isla.|Consolación del Sur se trouve dans la seconde zone tabacole de Vuelta Abajo, un peu moins prisée, et ses entrepôts servirent longtemps de point de rassemblement où la feuille cultivée dans les vegas (fermes de tabac) voisines était mise en balles avant le trajet final vers Pinar del Río. La propre liaison ferroviaire de la ville n'a atteint aussi profondément la zone tabacole qu'à la toute fin du XIXe siècle, des décennies après que les lignes sucrières plus à l'est eurent déjà traversé l'île.|コンソラシオン・デル・スルは、ビエルタ・アバホの中でもやや格の落ちる二番目のタバコ地帯にある。その倉庫は長らく、周辺のベガ(タバコ農園)で育てられた葉を、ピナル・デル・リオへの最終輸送の前に束ねる集積地として使われてきた。この町自体に鉄道が届き、タバコ地帯の奥深くまで路線が延びたのは19世紀もほぼ終わりになってからで、東側の砂糖路線がすでに島を横断してから何十年も経っていた。",
    [prop("Leaf-Bundling Warehouse|Almacén de empaque de hoja|Entrepôt de conditionnement de feuille|葉たばこ結束の倉庫", 220, 46),
     prop("Vega Farmstead|Finca de vega tabacalera|Ferme de vega tabacole|タバコ農園(ベガ)の農家", 190, 40)],
  ),

  // ---------------------------------------------------------------------
  // ce — セントロ(中部。砂糖農園主の私有鉄道が伸びた地帯)
  // ---------------------------------------------------------------------
  cardenas: city(
    "Cárdenas|Cárdenas|Cárdenas|カルデナス",
    -81.2039, 23.0447, "ce", "sugarwarehouse", "sugarport", "r",
    "A decade-old town, then Cuba's second railway|Un pueblo de apenas una década, luego el segundo ferrocarril de Cuba|Une ville née dix ans plus tôt, puis le deuxième chemin de fer de Cuba|できて10年の町に、キューバ2番目の鉄道",
    "Cárdenas was barely a decade old — founded in 1828 on an empty stretch of coast — when the Cárdenas–Bemba line reached it in 1840, only Cuba's second railway, built like the first to move sugar rather than people to a port. The rail-fed sugar trade turned it within a generation into one of Cuba's busiest ports, and its old warehouse district along the bay still carries the shape of a town built to load ships fast, not to entertain them.|Cárdenas apenas tenía una década —fundada en 1828 sobre un tramo de costa vacío— cuando en 1840 llegó la línea Cárdenas–Bemba, apenas el segundo ferrocarril de Cuba, construido, como el primero, para mover azúcar y no personas hacia un puerto. El comercio azucarero alimentado por el riel la convirtió en una generación en uno de los puertos más activos de Cuba, y su viejo barrio de almacenes junto a la bahía todavía conserva la forma de un pueblo hecho para cargar barcos rápido, no para entretenerlos.|Cárdenas n'avait guère plus de dix ans — fondée en 1828 sur un tronçon de côte vide — quand la ligne Cárdenas–Bemba l'atteignit en 1840, à peine le deuxième chemin de fer de Cuba, construit comme le premier pour déplacer du sucre plutôt que des gens vers un port. Le commerce du sucre nourri par le rail en fit en une génération l'un des ports les plus actifs de Cuba, et son vieux quartier d'entrepôts en bord de baie garde encore la forme d'une ville bâtie pour charger les navires vite, pas pour les distraire.|カルデナスは、1828年に何もない海岸線に開かれてからまだ10年ほどしか経っていない町だった。そこへ1840年、カルデナス―ベンバ線が届いた。キューバでまだ2番目の鉄道であり、最初の鉄道と同じく、人ではなく砂糖を港へ運ぶために敷かれたものだった。鉄道に支えられた砂糖交易は、一世代のうちにこの町をキューバ有数の忙しい港へと変えた。入り江沿いに残る古い倉庫街は、船をもてなすためではなく速く積み込むために作られた町の形を、いまも留めている。",
    [prop("Bayfront Sugar Warehouse|Almacén azucarero de la bahía|Entrepôt à sucre du front de mer|入り江沿いの砂糖倉庫", 320, 66),
     prop("Cárdenas–Bemba Freight Shed|Galpón de carga Cárdenas–Bemba|Hangar de fret Cárdenas–Bemba|カルデナス―ベンバ線の貨物小屋", 260, 54)],
  ),
  trinidad: city(
    "Trinidad|Trinidad|Trinidad|トリニダード(キューバ)",
    -79.9843, 21.8046, "ce", "watchtower", "cobbletown", "l",
    "Frozen in time because the sugar boom moved on|Congelada en el tiempo porque el auge azucarero siguió su camino|Figée dans le temps parce que le boom sucrier est parti ailleurs|砂糖景気が去ったせいで時が止まった町",
    "More than fifty sugar mills once packed the valley behind Trinidad, worked by tens of thousands of enslaved laborers and watched over from towers such as the roughly 45-metre one on the Manaca Iznaga estate, built so an overseer could see across the cane and ring a bell at the first sign of trouble. Trinidad's harbor was too shallow for the larger ships later sugar ports needed, and the town was slow to gain a proper rail link to the rest of the island, so as the sugar economy moved elsewhere the old town was largely left alone rather than rebuilt — which is why so much of its colonial core still stands, now UNESCO-listed, with a preserved steam train still running part of the old mill railway into the valley.|Más de cincuenta ingenios llegaron a apretarse en el valle detrás de Trinidad, trabajados por decenas de miles de personas esclavizadas y vigilados desde torres como la de unos 45 metros de la finca Manaca Iznaga, construida para que un capataz pudiera ver todo el cañaveral y tocar una campana ante el primer indicio de problema. El puerto de Trinidad resultó demasiado somero para los barcos más grandes que necesitaron después otros puertos azucareros, y el pueblo tardó en obtener una buena conexión ferroviaria con el resto de la isla, así que cuando la economía del azúcar se trasladó a otra parte, el casco antiguo quedó en gran medida sin tocar en vez de reconstruirse, razón por la cual buena parte de él sigue en pie, hoy declarado Patrimonio de la Humanidad, con un tren de vapor conservado que aún recorre parte del viejo ferrocarril de los ingenios hacia el valle.|Plus de cinquante sucreries s'entassaient autrefois dans la vallée derrière Trinidad, où travaillaient des dizaines de milliers de personnes réduites en esclavage, surveillées depuis des tours telles que celle d'environ 45 mètres du domaine Manaca Iznaga, construite pour qu'un contremaître puisse voir toute la canne et sonner une cloche au premier signe de trouble. Le port de Trinidad se révéla trop peu profond pour les plus grands navires dont eurent besoin par la suite d'autres ports sucriers, et la ville tarda à obtenir une vraie liaison ferroviaire avec le reste de l'île, si bien que lorsque l'économie du sucre se déplaça ailleurs, le vieux centre fut largement laissé tel quel plutôt que reconstruit — d'où le fait qu'une si grande partie de son cœur colonial tient encore debout, aujourd'hui classée à l'UNESCO, avec un train à vapeur préservé qui parcourt encore une partie de l'ancien chemin de fer des sucreries jusque dans la vallée.|トリニダードの背後に広がる谷には、かつて50を超える製糖工場がひしめき、何万人もの奴隷労働者が働かされていた。マナカ・イスナガ農園に立つ高さおよそ45メートルの塔のような見張り塔からは、監督者がサトウキビ畑全体を見渡し、異変があればすぐに鐘を鳴らせるようになっていた。トリニダードの港は、のちの砂糖港が必要とした大型船には浅すぎ、この町は島の他地域とを結ぶ本格的な鉄道網の接続にも恵まれなかった。そのため砂糖経済がよそへ移ると、旧市街は建て替えられることなくほぼそのまま取り残された。だからこそ植民地時代の中心部の多くがいまも残り、世界遺産に登録され、製糖工場時代の鉄道の一部を保存された蒸気機関車がいまも谷へ向けて走っている。",
    [prop("Manaca Iznaga Watchtower Grounds|Terrenos de la torre de Manaca Iznaga|Terrain de la tour de Manaca Iznaga|マナカ・イスナガの見張り塔の敷地", 2200, 451),
     prop("Steam Train Workshop|Taller del tren de vapor|Atelier du train à vapeur|蒸気機関車の整備小屋", 300, 62)],
  ),
  cienfuegos: city(
    "Cienfuegos|Cienfuegos|Cienfuegos|シエンフエゴス",
    -80.4444, 22.1481, "ce", "frenchgrid", "sugarport", "l",
    "A French colonial port, and the road it took south|Un puerto colonial francés, y el camino que tomó hacia el sur|Un port colonial français, et la voie qu'il prit vers le sud|フランス植民地の港と、南へ延びた道",
    "Cienfuegos was founded in 1819 by French settlers from Louisiana and Bordeaux rather than Spaniards, and its neat colonial grid — laid out from the start rather than grown organically — earned its historic centre UNESCO listing in 2005 as an unusually planned example of 19th-century Latin American urbanism. A rail line reached it from Havana's network via Santa Clara within a few decades, turning what had begun as a farming and shipping colony into one of the south coast's busiest sugar-export ports.|Cienfuegos fue fundada en 1819 por colonos franceses de Luisiana y Burdeos, no por españoles, y su ordenada cuadrícula colonial —trazada desde el principio y no crecida de forma orgánica— hizo que su centro histórico fuera declarado Patrimonio de la Humanidad por la UNESCO en 2005, como un ejemplo inusualmente planificado de urbanismo latinoamericano del siglo XIX. Una línea férrea la conectó con la red de La Habana vía Santa Clara al cabo de pocas décadas, convirtiendo lo que había empezado como una colonia agrícola y portuaria en uno de los puertos azucareros más activos de la costa sur.|Cienfuegos fut fondée en 1819 par des colons français de Louisiane et de Bordeaux plutôt que par des Espagnols, et sa nette grille coloniale — tracée dès le départ plutôt que née de façon organique — valut à son centre historique un classement UNESCO en 2005, comme exemple inhabituellement planifié d'urbanisme latino-américain du XIXe siècle. Une ligne de chemin de fer la relia au réseau de La Havane via Santa Clara en quelques décennies, transformant ce qui avait commencé comme une colonie agricole et portuaire en l'un des ports d'exportation de sucre les plus actifs de la côte sud.|シエンフエゴスは、スペイン人ではなくルイジアナとボルドーから来たフランス人入植者によって1819年に築かれた町である。自然に広がるのではなく最初から計画された整然とした植民地時代の碁盤目状の街並みは、19世紀ラテンアメリカ都市計画の異例なほど整った例として、2005年にその歴史地区がユネスコ世界遺産に登録される理由となった。ハバナの鉄道網からサンタクララ経由で数十年のうちに線路が届き、農業と海運の植民地として始まったこの町は、南岸でも有数の砂糖輸出港へと変わっていった。",
    [prop("French Colonial Grid Plaza|Plaza del trazado colonial francés|Place du plan colonial français|フランス植民地の碁盤目広場", 750, 154),
     prop("South-Coast Sugar Pier|Muelle azucarero de la costa sur|Quai à sucre de la côte sud|南岸の砂糖桟橋", 300, 62)],
  ),
  santaclara: city(
    "Santa Clara|Santa Clara|Santa Clara|サンタクララ",
    -79.9647, 22.4069, "ce", "armoredtrain", "railjunctiontown", "r",
    "Where an armoured train was pulled off its own tracks|Donde un tren blindado fue arrancado de sus propios rieles|Où un train blindé fut arraché de ses propres rails|装甲列車が自ら敷いた線路から引きはがされた町",
    "Santa Clara sits at the crossroads of Cuba's central railway network, which is exactly why Fulgencio Batista's government sent an armoured train loaded with troops and ammunition there in December 1958 — and why rebel fighters led by Ernesto 'Che' Guevara used a bulldozer to tear up the track ahead of it, derailing the train and forcing its surrender within hours. The derailed carriages are preserved on the spot as a monument, a rare case of a Cuban railway becoming famous for the one time it stopped moving sugar or anyone else.|Santa Clara se halla en el cruce de la red ferroviaria central de Cuba, y por eso exactamente el gobierno de Fulgencio Batista envió allí un tren blindado cargado de tropas y municiones en diciembre de 1958, y por eso los rebeldes liderados por Ernesto 'Che' Guevara usaron un bulldozer para levantar la vía por delante, descarrilando el tren y forzando su rendición en pocas horas. Los vagones descarrilados se conservan en el mismo sitio como monumento, un raro caso de un ferrocarril cubano hecho famoso por la única vez que dejó de mover azúcar o a cualquier otra cosa.|Santa Clara se trouve au carrefour du réseau ferroviaire central de Cuba, et c'est exactement pour cela que le gouvernement de Fulgencio Batista y envoya en décembre 1958 un train blindé chargé de troupes et de munitions — et pour cela que des combattants rebelles menés par Ernesto « Che » Guevara utilisèrent un bulldozer pour arracher la voie devant lui, le déraillant et forçant sa reddition en quelques heures. Les wagons déraillés sont conservés sur place comme monument, un cas rare d'un chemin de fer cubain devenu célèbre pour la seule fois où il a cessé de transporter du sucre ou quoi que ce soit d'autre.|サンタクララはキューバ中央鉄道網の交差点にあり、まさにそれゆえに、1958年12月フルヘンシオ・バティスタ政権は兵士と弾薬を積んだ装甲列車をここへ送り込んだ。そしてまさにそれゆえに、エルネスト・「チェ」・ゲバラ率いる反乱軍はブルドーザーで前方の線路を剥がし、列車を脱線させて数時間のうちに降伏させた。脱線した車両はそのままの場所に記念碑として保存されており、キューバの鉄道が砂糖でも他の何かでもなく、動くのを止めたたった一度のことで有名になった珍しい例である。",
    [prop("Armoured Train Memorial|Monumento del tren blindado|Monument du train blindé|装甲列車の記念碑", 320, 66),
     prop("Central Junction Freight Yard|Patio de carga del empalme central|Cour de fret de la jonction centrale|中央分岐点の貨物操車場", 280, 58)],
  ),
  remedios: city(
    "Remedios|Remedios|Remedios|レメディオス",
    -79.5450, 22.4939, "ce", "parrandatower", "cobbletown", "l",
    "Fireworks over the town that never got its own railway boom|Fuegos artificiales sobre el pueblo que nunca tuvo su propio auge ferroviario|Des feux d'artifice sur la ville qui n'a jamais connu son propre essor ferroviaire|独自の鉄道景気を持たなかった町に上がる花火",
    "Remedios holds Las Parrandas, a rival-team festival of fireworks, floats and all-night noise held every 24 December that is generally considered the oldest of Cuba's parranda traditions, tracing back to at least the early 19th century. Unlike the sugar towns further inland, Remedios never grew into a major rail hub, and its well-preserved colonial square — two churches facing each other across one plaza — survived largely because the town simply stayed the size it always was.|Remedios celebra Las Parrandas, una fiesta de bandos rivales con fuegos artificiales, carrozas y bullicio toda la noche que se celebra cada 24 de diciembre y que suele considerarse la más antigua de las tradiciones de parranda cubanas, con raíces que se remontan al menos a principios del siglo XIX. A diferencia de los pueblos azucareros más hacia el interior, Remedios nunca llegó a ser un gran nudo ferroviario, y su bien conservada plaza colonial —dos iglesias que se miran de frente sobre una misma plaza— sobrevivió en gran parte porque el pueblo simplemente se quedó del tamaño que siempre tuvo.|Remedios célèbre Las Parrandas, une fête à équipes rivales faite de feux d'artifice, de chars et de vacarme toute la nuit organisée chaque 24 décembre, généralement considérée comme la plus ancienne des traditions de parranda cubaines, remontant au moins au début du XIXe siècle. Contrairement aux villes sucrières plus à l'intérieur des terres, Remedios ne devint jamais un grand nœud ferroviaire, et sa place coloniale bien conservée — deux églises se faisant face sur une même place — survécut en grande partie parce que la ville resta simplement de la taille qu'elle avait toujours eue.|レメディオスには「ラス・パランダス」という祭りがある。毎年12月24日に開かれる対抗形式の花火・山車・夜通しの騒ぎで、キューバのパランダ系祭りの中でももっとも古いとされ、少なくとも19世紀初頭にまでさかのぼる。内陸の砂糖の町々と違い、レメディオスは大きな鉄道の拠点に育つことはなかった。よく保存された植民地時代の広場——一つの広場を挟んで向かい合う二つの教会——が残ったのは、この町がずっと同じ大きさのままだったことが大きい。",
    [prop("Parrandas Fireworks Tower|Torre de fuegos de las Parrandas|Tour de feux d'artifice des Parrandas|パランダスの花火やぐら", 300, 62),
     prop("Twin-Church Plaza House|Casa de la plaza de las dos iglesias|Maison de la place aux deux églises|双子教会広場の家", 280, 58)],
  ),
  sanctispiritus: city(
    "Sancti Spíritus|Sancti Spíritus|Sancti Spíritus|サンクティ・スピリトゥス",
    -79.4422, 21.9328, "ce", "stonebridge", "cobbletown", "r",
    "One of Cuba's first seven towns, still crossed by its old bridge|Uno de los siete primeros pueblos de Cuba, todavía cruzado por su viejo puente|L'une des sept premières villes de Cuba, toujours traversée par son vieux pont|キューバ最初の7つの町のひとつ、いまも古い橋を渡す",
    "Sancti Spíritus was one of the seven original villas Diego Velázquez founded across Cuba between 1513 and 1515, making it one of the oldest continuously inhabited towns in the Americas. Its stone Yayabo bridge, built in the 1800s over the river of the same name, is the only bridge of its kind left standing in Cuba and still carries traffic through the old town rather than sitting as a museum piece.|Sancti Spíritus fue una de las siete villas originales que Diego Velázquez fundó en Cuba entre 1513 y 1515, lo que la convierte en uno de los pueblos habitados sin interrupción más antiguos de América. Su puente de piedra sobre el río Yayabo, construido en el siglo XIX, es el único de su tipo que queda en pie en Cuba y todavía da paso al tráfico por el casco antiguo en vez de quedar como pieza de museo.|Sancti Spíritus fut l'une des sept villas originelles que Diego Velázquez fonda à Cuba entre 1513 et 1515, ce qui en fait l'une des plus anciennes villes continuellement habitées des Amériques. Son pont de pierre sur le Yayabo, bâti au XIXe siècle, est le seul de son genre encore debout à Cuba et porte toujours la circulation à travers la vieille ville plutôt que de rester une pièce de musée.|サンクティ・スピリトゥスは、1513年から1515年にかけてディエゴ・べラスケスがキューバ各地に築いた最初の7つのビリャの一つであり、アメリカ大陸でも途切れず人が住み続けてきたもっとも古い町のひとつである。同じ名を持つヤヤボ川に架かる石橋は19世紀に建てられ、キューバに残る同種の橋としては唯一のもので、博物館の展示品としてではなく、いまも旧市街の交通をそのまま支えている。",
    [prop("Yayabo Stone Bridge Toll|Peaje del puente de piedra del Yayabo|Péage du pont de pierre du Yayabo|ヤヤボ石橋の通行料", 550, 113),
     prop("Original Villa Plaza|Plaza de la villa original|Place de la villa originelle|創建当初の広場", 300, 62)],
  ),
  camaguey: city(
    "Camagüey|Camagüey|Camagüey|カマグエイ",
    -77.9161, 21.3808, "ce", "tinajon", "provincialcapital", "l",
    "Streets built crooked on purpose|Calles construidas torcidas a propósito|Des rues bâties tordues à dessein|わざと曲げて作られた通り",
    "Camagüey's historic centre still follows a maze of narrow, winding streets rather than the grid pattern of most other colonial Cuban towns, a layout local tradition credits to residents trying to confuse pirate raiders, and the historic centre was UNESCO-listed in 2008 for that very irregularity. The city also gave its name to the large earthenware jars called tinajones once used across the region to catch and store rainwater, now mostly decorative but still standing outside courtyards by the thousand.|El centro histórico de Camagüey todavía sigue un laberinto de calles estrechas y sinuosas en vez del trazado en cuadrícula de la mayoría de los demás pueblos coloniales cubanos, un diseño que la tradición local atribuye a los vecinos que intentaban confundir a los piratas, y el centro histórico fue declarado Patrimonio de la Humanidad por la UNESCO en 2008 precisamente por esa irregularidad. La ciudad también dio nombre a las grandes tinajas de barro llamadas tinajones, usadas antaño en toda la región para recoger y guardar agua de lluvia, hoy en su mayoría decorativas pero todavía de pie por miles a las puertas de los patios.|Le centre historique de Camagüey suit toujours un labyrinthe de rues étroites et sinueuses plutôt que le tracé en damier de la plupart des autres villes coloniales cubaines, un plan que la tradition locale attribue aux habitants cherchant à égarer les pirates, et le centre historique fut classé UNESCO en 2008 précisément pour cette irrégularité. La ville a aussi donné son nom aux grandes jarres de terre cuite appelées tinajones, autrefois utilisées dans toute la région pour recueillir et conserver l'eau de pluie, aujourd'hui surtout décoratives mais encore debout par milliers devant les cours.|カマグエイの歴史地区は、キューバのほかの植民地時代の町の多くにみられる碁盤目状ではなく、いまも狭く曲がりくねった道の迷路のままである。この配置は、住民が海賊の襲撃を混乱させようとしたためだという地元の言い伝えがあり、まさにこの不規則さゆえに歴史地区は2008年にユネスコ世界遺産に登録された。この町はまた、かつてこの地方一帯で雨水を集めて蓄えるのに使われた「ティナホン」と呼ばれる大きな素焼きの壺にもその名を与えており、いまでは大半が装飾用になったとはいえ、中庭の外に何千と立ち並んでいる。",
    [prop("Tinajón Courtyard House|Casa con patio de tinajones|Maison à cour aux tinajones|ティナホンの中庭付きの家", 850, 174),
     prop("Maze-Street Corner Shop|Tienda de la esquina del laberinto|Boutique du coin du labyrinthe|迷路の街角の店", 280, 58)],
  ),
  ciegodeavila: city(
    "Ciego de Ávila|Ciego de Ávila|Ciego de Ávila|シエゴ・デ・アビラ",
    -78.7614, 21.8489, "ce", "trochafort", "railjunctiontown", "r",
    "A fortified line built to stop a war, not carry sugar|Una línea fortificada construida para frenar una guerra, no para llevar azúcar|Une ligne fortifiée bâtie pour arrêter une guerre, pas pour transporter du sucre|戦争を止めるために敷かれた、砂糖のためではない要塞線",
    "La Trocha de Júcaro a Morón, a fortified military line with its own narrow-gauge railway, forts and barbed wire, was built across the narrowest part of the island through here starting in 1871 to try to keep independence fighters from crossing between eastern and western Cuba during the Ten Years' War — one of the very few Cuban rail lines built for war rather than sugar. Almost nothing of the line's forts survives today, and the province is now known instead for pineapples grown on the same flat land the Trocha once cut across.|La Trocha de Júcaro a Morón, una línea militar fortificada con su propio ferrocarril de vía estrecha, fuertes y alambre de púas, se construyó a partir de 1871 a través de la parte más estrecha de la isla, aquí mismo, para tratar de impedir que los independentistas cruzaran entre el este y el oeste de Cuba durante la Guerra de los Diez Años: una de las poquísimas líneas ferroviarias cubanas construidas para la guerra y no para el azúcar. Hoy casi nada queda de los fuertes de la línea, y la provincia es conocida ahora más bien por las piñas que crecen en la misma tierra llana que la Trocha atravesaba.|La Trocha de Júcaro a Morón, une ligne militaire fortifiée avec son propre chemin de fer à voie étroite, ses forts et ses barbelés, fut construite à partir de 1871 à travers la partie la plus étroite de l'île, ici même, pour tenter d'empêcher les indépendantistes de passer entre l'est et l'ouest de Cuba pendant la guerre de Dix Ans — l'une des très rares lignes ferroviaires cubaines bâties pour la guerre plutôt que pour le sucre. Presque rien des forts de la ligne ne subsiste aujourd'hui, et la province est désormais plutôt connue pour les ananas cultivés sur les mêmes terres plates que la Trocha traversait autrefois.|フカロ―モロン間の要塞線「ラ・トロチャ」は、独自の狭軌鉄道と砦、有刺鉄線を備えた軍事施設で、1871年からこの島の一番狭い部分を横断するように敷かれた。目的は、十年戦争のあいだ独立派の戦闘員が東西キューバを行き来するのを食い止めることであり、砂糖ではなく戦争のために敷かれたごく数少ないキューバの鉄道のひとつである。この線の砦はいまではほとんど残っていない。この州はいまではむしろ、かつてトロチャが横切っていたのと同じ平らな土地で育つパイナップルで知られている。",
    [prop("Trocha Fort Ruins|Ruinas del fuerte de la Trocha|Ruines du fort de la Trocha|トロチャの砦跡", 260, 54),
     prop("Pineapple Packing Shed|Galpón de empaque de piña|Hangar d'emballage d'ananas|パイナップル梱包小屋", 240, 50)],
  ),
  moron: city(
    "Morón|Morón|Morón|モロン",
    -78.6289, 22.1017, "ce", "roosterclock", "railjunctiontown", "b",
    "The rooster city at the trocha's northern end|La ciudad del gallo en el extremo norte de la trocha|La ville du coq à l'extrémité nord de la trocha|要塞線の北端にある雄鶏の町",
    "Morón was the northern anchor of La Trocha de Júcaro a Morón, the fortified wartime line that ran to Júcaro on the south coast, and it grew as a rail town on the strength of that military engineering long before it became a farming centre. A giant bronze rooster statue and clock now stand at the town's entrance, a nod to a local legend about a corrupt colonial official nicknamed 'the rooster of Morón' — a story told about the man, not verified as literal history.|Morón fue el ancla norte de la Trocha de Júcaro a Morón, la línea fortificada de guerra que llegaba hasta Júcaro en la costa sur, y creció como pueblo ferroviario gracias a esa ingeniería militar mucho antes de convertirse en un centro agrícola. Una gigantesca estatua de bronce de un gallo con reloj se alza hoy a la entrada del pueblo, en referencia a una leyenda local sobre un funcionario colonial corrupto apodado 'el gallo de Morón', una historia que se cuenta sobre el hombre, no verificada como historia literal.|Morón fut l'ancrage nord de la Trocha de Júcaro a Morón, la ligne fortifiée de guerre menant à Júcaro sur la côte sud, et se développa comme ville ferroviaire grâce à cette ingénierie militaire bien avant de devenir un centre agricole. Une gigantesque statue de coq en bronze surmontée d'une horloge se dresse aujourd'hui à l'entrée de la ville, clin d'œil à une légende locale sur un fonctionnaire colonial corrompu surnommé « le coq de Morón » — une histoire racontée sur cet homme, non vérifiée comme fait historique.|モロンは、南岸のフカロまで通じていた戦時の要塞線ラ・トロチャの北端の拠点であり、農業の中心地になるよりずっと前に、この軍事技術の力で鉄道の町として育った。いまこの町の入口には巨大なブロンズ製の雄鶏の時計像が立っている。これは「モロンの雄鶏」とあだ名された植民地時代の汚職役人にまつわる地元の言い伝えにちなむもので、その人物について語られる話であって、史実として確かめられたものではない。",
    [prop("Trocha Northern Terminus|Terminal norte de la Trocha|Terminus nord de la Trocha|トロチャ北端の終着駅", 240, 50),
     prop("Rooster Clock Plaza|Plaza del reloj del gallo|Place de l'horloge au coq|雄鶏時計広場", 260, 54)],
  ),
  chaparra: city(
    "Chaparra|Chaparra|Chaparra|チャパラ",
    -76.5397, 21.1547, "ce", "companymill", "companymilltown", "l",
    "The company town built entirely around one mill|El pueblo de compañía construido enteramente en torno a un ingenio|La ville-usine bâtie entièrement autour d'une sucrerie|一つの製糖工場のためだけに作られた企業城下町",
    "The Chaparra sugar mill, built by an American-owned company in the early 1900s, grew so large that at its peak it was among the biggest sugar mills anywhere in the world, and the settlement around it — company housing, company stores, a company hospital — existed almost entirely to serve it, its own private rail network hauling cane in and refined sugar out. The mill and town were later renamed Jesús Menéndez, after a sugar-workers' union leader, and though the mill has slowed and changed hands over the decades since, the streets still follow the plan a sugar company, not a town council, once drew up.|El ingenio azucarero de Chaparra, construido por una compañía de capital estadounidense a principios del siglo XX, llegó a ser tan grande que en su apogeo estuvo entre los mayores del mundo, y el poblado a su alrededor —viviendas, tiendas y hasta un hospital de la compañía— existía casi por completo para servirlo, con su propia red ferroviaria privada que llevaba caña y sacaba azúcar refinada. El ingenio y el pueblo fueron rebautizados después como Jesús Menéndez, en honor a un líder sindical azucarero, y aunque el ingenio se ha ralentizado y cambiado de manos a lo largo de las décadas siguientes, las calles todavía siguen el trazado que una vez diseñó una compañía azucarera y no un ayuntamiento.|La sucrerie de Chaparra, construite par une compagnie américaine au début du XXe siècle, devint si grande qu'à son apogée elle comptait parmi les plus grandes sucreries au monde, et l'agglomération qui l'entourait — logements, magasins et même hôpital de la compagnie — existait presque entièrement pour la servir, son propre réseau ferroviaire privé acheminant la canne et évacuant le sucre raffiné. L'usine et la ville furent plus tard rebaptisées Jesús Menéndez, du nom d'un dirigeant syndical des ouvriers du sucre, et bien que l'usine ait ralenti et changé de mains au fil des décennies suivantes, les rues suivent encore le plan qu'une compagnie sucrière, et non un conseil municipal, avait un jour tracé.|チャパラの製糖工場は、20世紀初頭にアメリカ資本の会社によって建てられ、最盛期には世界でも屈指の規模の製糖工場のひとつにまで成長した。その周りに広がった集落——社宅、会社の売店、会社病院——は、ほぼすべてこの工場に仕えるために存在し、独自の私有鉄道網がサトウキビを運び入れ、精製した砂糖を運び出していた。この工場と町は、のちに砂糖労働者の組合指導者にちなんでヘスス・メネンデスと改名された。工場はそれから数十年のあいだに速度を落とし持ち主を変えてきたが、街路はいまも町議会ではなく製糖会社がかつて引いた計画のとおりである。",
    [prop("Company Mill Housing Row|Hilera de viviendas del ingenio|Rangée de logements de l'usine|製糖会社の社宅通り", 260, 54),
     prop("Private Cane Rail Yard|Patio del ferrocarril privado del ingenio|Cour du chemin de fer privé du moulin|製糖会社専用線の操車場", 300, 62)],
  ),
  jatibonico: city(
    "Jatibonico|Jatibonico|Jatibonico|ハティボニコ",
    -79.1667, 21.9167, "ce", "stillrunningmill", "companymilltown", "r",
    "The mill that never stopped|El ingenio que nunca se detuvo|L'usine qui ne s'est jamais arrêtée|止まらなかった製糖工場",
    "The Uruguay sugar mill at Jatibonico, opened in the early 20th century and still grinding cane today, is one of the relatively few of Cuba's dozens of historic mills to survive the sharp contraction of the sugar industry after 2002, when the government closed roughly half the country's mills at once. Its own network of narrow rail spurs, built to bring cane in from the surrounding fields, is one of the last still doing the everyday work the whole island's railways were originally built for.|El ingenio Uruguay de Jatibonico, inaugurado a principios del siglo XX y todavía moliendo caña hoy, es uno de los relativamente pocos entre las decenas de ingenios históricos de Cuba que sobrevivieron a la fuerte contracción de la industria azucarera tras 2002, cuando el gobierno cerró de golpe cerca de la mitad de los ingenios del país. Su propia red de ramales de vía estrecha, construida para traer caña de los campos vecinos, es una de las últimas que todavía hace el trabajo cotidiano para el que se construyeron originalmente los ferrocarriles de toda la isla.|Le central sucrier Uruguay de Jatibonico, ouvert au début du XXe siècle et broyant encore de la canne aujourd'hui, fait partie des relativement rares parmi les dizaines de sucreries historiques de Cuba à avoir survécu à la forte contraction de l'industrie sucrière après 2002, lorsque le gouvernement ferma d'un coup près de la moitié des sucreries du pays. Son propre réseau d'embranchements à voie étroite, construit pour amener la canne des champs environnants, est l'un des derniers à accomplir encore le travail quotidien pour lequel les chemins de fer de toute l'île furent conçus à l'origine.|ハティボニコにあるウルグアイ製糖工場は20世紀初頭に開業し、いまもサトウキビを挽き続けている。政府が国内のおよそ半数の製糖工場を一度に閉鎖した2002年以降、キューバの何十とある歴史ある製糖工場のうち生き残った比較的数少ない例のひとつである。周囲の畑からサトウキビを運び込むために敷かれた独自の狭軌の専用線網は、島じゅうの鉄道がもともと敷かれた目的である日々の仕事を、いまもなお続けている数少ない例のひとつである。",
    [prop("Uruguay Mill Cane Spur|Ramal cañero del central Uruguay|Embranchement cannier du central Uruguay|ウルグアイ製糖工場の専用線", 280, 58),
     prop("Still-Running Mill Yard|Patio del ingenio en actividad|Cour de l'usine encore active|いまも稼働する製糖工場の構内", 320, 66)],
  ),
  sagualagrande: city(
    "Sagua la Grande|Sagua la Grande|Sagua la Grande|サグア・ラ・グランデ",
    -80.0761, 22.8092, "ce", "ironmarket", "sugarport", "l",
    "A river port that iron replaced with a bridge|Un puerto fluvial que el hierro sustituyó con un puente|Un port fluvial que le fer remplaça par un pont|鉄の橋に置き換わった川港",
    "Sagua la Grande grew rich enough on sugar shipped down its namesake river that by the late 19th century it could afford an ornate cast-iron market hall, and its historic centre still has more surviving 19th-century ironwork architecture than most Cuban towns of its size. A steel bridge over the river, prefabricated and shipped in from abroad, replaced the old crossing and became one of the town's own landmarks.|Sagua la Grande se enriqueció tanto con el azúcar embarcado río abajo que a finales del siglo XIX pudo permitirse un ornamentado mercado de hierro fundido, y su centro histórico todavía conserva más arquitectura de hierro decimonónica que la mayoría de los pueblos cubanos de su tamaño. Un puente de acero sobre el río, prefabricado y traído del extranjero, sustituyó al viejo cruce y se convirtió en uno de los símbolos propios del pueblo.|Sagua la Grande s'enrichit tant grâce au sucre expédié en aval de son fleuve éponyme qu'à la fin du XIXe siècle elle put s'offrir un marché ornementé en fonte, et son centre historique conserve encore plus d'architecture en fer du XIXe siècle que la plupart des villes cubaines de sa taille. Un pont d'acier sur le fleuve, préfabriqué et expédié de l'étranger, remplaça l'ancien passage et devint l'un des repères propres à la ville.|サグア・ラ・グランデは、その名を持つ川を下って運ばれる砂糖でたいへん豊かになり、19世紀末には装飾を凝らした鋳鉄製の市場会館を建てるほどだった。歴史地区にはいまも、同規模のキューバの町の多くより多く19世紀の鉄工芸建築が残っている。海外から取り寄せて組み立てられた鋼鉄の橋が川の古い渡し場に取って代わり、この町自体の名物のひとつになった。",
    [prop("Cast-Iron Market Hall|Mercado de hierro fundido|Halle de marché en fonte|鋳鉄の市場会館", 300, 62),
     prop("River Steel Bridge Toll|Peaje del puente de acero del río|Péage du pont d'acier sur la rivière|川の鉄橋の通行料", 260, 54)],
  ),
  caibarien: city(
    "Caibarién|Caibarién|Caibarién|カイバリエン",
    -79.4664, 22.5233, "ce", "causewaygate", "fishingport", "r",
    "The port at the end of the causeway to the cays|El puerto al final del terraplén hacia los cayos|Le port au bout de la chaussée vers les cayos|コーズウェイの先にある港",
    "Caibarién grew as a fishing and sugar-export port off the Cárdenas–Santa Clara rail network, and it's still where the causeway (the pedraplén) connecting the mainland to the resort cays of Cayo Santa María and Cayo Las Brujas begins. Fishing crews still work out of the same harbor that once loaded sugar, even as tourism from the cays has become the bigger business nearby.|Caibarién creció como puerto pesquero y de exportación de azúcar vinculado a la red ferroviaria de Cárdenas a Santa Clara, y todavía es donde empieza el terraplén (el pedraplén) que conecta tierra firme con los cayos turísticos de Cayo Santa María y Cayo Las Brujas. Las tripulaciones de pesca siguen trabajando en el mismo puerto que antes cargaba azúcar, aunque el turismo de los cayos se haya convertido en el negocio más grande de la zona.|Caibarién se développa comme port de pêche et d'exportation de sucre relié au réseau ferroviaire de Cárdenas à Santa Clara, et c'est encore là que commence la chaussée (le pedraplén) reliant le continent aux cayos touristiques de Cayo Santa María et Cayo Las Brujas. Les équipages de pêche travaillent toujours depuis le même port qui chargeait autrefois le sucre, même si le tourisme des cayos est devenu la plus grande activité des environs.|カイバリエンは、カルデナス―サンタクララの鉄道網につながる漁業と砂糖輸出の港として育った。いまもここは、本土とカヨ・サンタマリア、カヨ・ラス・ブルハスといった観光用の島々を結ぶ築堤(ペドラプレン)の起点になっている。周辺ではカヨの観光業がより大きな商売になった今も、漁船団はかつて砂糖を積み込んだのと同じ港からいまも出漁している。",
    [prop("Causeway Gatehouse|Caseta de entrada al pedraplén|Poste d'entrée du pedraplén|コーズウェイ入口の詰所", 260, 54),
     prop("Fishing Harbor Ice House|Nevera del puerto pesquero|Chambre froide du port de pêche|漁港の製氷倉庫", 220, 46)],
  ),
  florida: city(
    "Florida|Florida|Florida|フロリダ(カマグエイ)",
    -78.2261, 21.5372, "ce", "wildflowerplain", "railjunctiontown", "b",
    "A town named for the crop's next stop, not the peninsula|Un pueblo con el nombre de la parada siguiente del cultivo, no de la península|Une ville nommée d'après l'étape suivante de la récolte, pas la péninsule|作物の次の停車場にちなむ名で、あの半島とは無関係",
    "The town of Florida grew up as a sugar-mill stop on the Ferrocarril Central, the trunk line finished in 1902 that finally linked Havana to Santiago de Cuba end to end, and its name has nothing to do with the American state — it comes from the wildflowers once common on the surrounding plain. Long-distance trains on the Central line still stop here on the run across the island's midsection.|El pueblo de Florida creció como una parada de ingenio en el Ferrocarril Central, la línea troncal terminada en 1902 que por fin unió La Habana con Santiago de Cuba de punta a punta, y su nombre no tiene nada que ver con el estado estadounidense: viene de las flores silvestres antes comunes en la llanura circundante. Los trenes de largo recorrido de la línea Central todavía paran aquí en su cruce por el centro de la isla.|La ville de Florida se développa comme halte d'une sucrerie sur le Ferrocarril Central, la ligne principale achevée en 1902 qui relia enfin La Havane à Santiago de Cuba de bout en bout, et son nom n'a rien à voir avec l'État américain : il vient des fleurs sauvages autrefois courantes dans la plaine environnante. Les trains longue distance de la ligne Central s'y arrêtent encore lors de la traversée du centre de l'île.|フロリダの町は、1902年に完成しハバナとサンティアゴ・デ・クーバをついに端から端までつないだ幹線、中央鉄道の製糖工場の停車場として発展した。この名はアメリカの州とは何の関係もなく、かつてこの平野に多く咲いていた野の花に由来する。中央鉄道の長距離列車は、島の中央部を横断する道すがら、いまもここに停まる。",
    [prop("Ferrocarril Central Whistle Stop|Apeadero del Ferrocarril Central|Halte du Ferrocarril Central|中央鉄道の停車場", 240, 50),
     prop("Wildflower Plain Warehouse|Almacén de la llanura florida|Entrepôt de la plaine fleurie|花咲く平野の倉庫", 210, 44)],
  ),
  colon: city(
    "Colón|Colón|Colón|コロン",
    -80.9014, 22.7217, "ce", "signalhouse", "railjunctiontown", "l",
    "The junction named for an admiral, built for cane|El empalme con nombre de almirante, construido para la caña|La jonction au nom d'amiral, bâtie pour la canne|提督の名を持つ、サトウキビのための分岐点",
    "Colón grew up around its position as a junction where several of Matanzas province's private sugar-mill railways met the main trunk line, more crossing point than destination in its own right for much of the 19th century. Dozens of mills once fed cane through its yards; far fewer still operate today, and the junction now handles a fraction of the traffic that once passed through it.|Colón creció en torno a su posición como empalme donde varios de los ferrocarriles privados de los ingenios azucareros de la provincia de Matanzas se unían a la línea troncal principal, más punto de cruce que destino propio durante buena parte del siglo XIX. Docenas de ingenios alimentaban antaño de caña sus patios; hoy funcionan muchos menos, y el empalme maneja hoy solo una fracción del tráfico que pasaba antes por él.|Colón se développa autour de sa position de jonction où plusieurs des chemins de fer privés des sucreries de la province de Matanzas rejoignaient la ligne principale, davantage point de passage que destination en soi pendant une bonne partie du XIXe siècle. Des dizaines d'usines alimentaient autrefois ses cours en canne ; bien moins fonctionnent encore aujourd'hui, et la jonction traite désormais une fraction du trafic qui y transitait jadis.|コロンは、マタンサス州の複数の製糖工場の私有鉄道が幹線と合流する分岐点としての位置づけを中心に発展した町で、19世紀の大半のあいだ、それ自体の目的地というよりむしろ交差点だった。かつては何十もの製糖工場からサトウキビがこの操車場に流れ込んでいた。いま稼働している工場ははるかに少なく、この分岐点を通る貨物量もかつてのごく一部にすぎない。",
    [prop("Multi-Mill Junction Yard|Patio del empalme de varios ingenios|Cour de la jonction à plusieurs usines|複数製糖工場が集まる操車場", 260, 54),
     prop("Trunk Line Signal House|Casa de señales de la línea troncal|Poste d'aiguillage de la ligne principale|幹線の信号所", 220, 46)],
  ),
  uniondereyes: city(
    "Unión de Reyes|Unión de Reyes|Unión de Reyes|ウニオン・デ・レイエス",
    -81.5372, 22.7825, "ce", "watertower", "railjunctiontown", "r",
    "Two lines that met and gave the town its name|Dos líneas que se unieron y dieron nombre al pueblo|Deux lignes réunies qui donnèrent son nom à la ville|二つの路線が出会い、その名を与えた町",
    "Unión de Reyes takes its name from the point where two of Matanzas province's early sugar railways were joined into one system in the 19th century, and the town grew up around that junction rather than around any older settlement. It remains a rail crossing more than a destination, much like several of the towns this network created almost by accident along its private mill branches.|Unión de Reyes toma su nombre del punto donde dos de los primeros ferrocarriles azucareros de la provincia de Matanzas se unieron en un solo sistema en el siglo XIX, y el pueblo creció en torno a ese empalme y no en torno a ningún asentamiento anterior. Sigue siendo más un cruce ferroviario que un destino en sí, como varios de los pueblos que esta red creó casi por accidente a lo largo de sus ramales privados de ingenio.|Unión de Reyes tire son nom du point où deux des premiers chemins de fer sucriers de la province de Matanzas furent réunis en un seul système au XIXe siècle, et la ville se développa autour de cette jonction plutôt qu'autour d'un peuplement plus ancien. Elle reste davantage un croisement ferroviaire qu'une destination en soi, comme plusieurs des villes que ce réseau créa presque par accident le long de ses embranchements privés d'usine.|ウニオン・デ・レイエスの名は、19世紀にマタンサス州の初期の砂糖鉄道二本が一つの系統に結ばれた地点に由来する。この町は、以前からあった集落の周りではなく、その分岐点そのものを中心に育った。私有の製糖工場の支線に沿ってこの鉄道網がほとんど偶然のように生み出した他の町々と同じく、この町もいまなお目的地というより鉄道の交差点であり続けている。",
    [prop("Joined-Lines Junction House|Casa del empalme de las dos vías|Maison de la jonction des deux voies|二線合流の分岐小屋", 220, 46),
     prop("Branch-Line Water Tower|Torre de agua del ramal|Château d'eau de l'embranchement|支線の給水塔", 200, 42)],
  ),
  placetas: city(
    "Placetas|Placetas|Placetas|プラセタス",
    -79.6489, 22.3181, "ce", "cattlepen", "cattletown", "b",
    "A tobacco and cattle crossroads between two rail lines|Un cruce de tabaco y ganado entre dos líneas ferroviarias|Un carrefour de tabac et de bétail entre deux lignes ferroviaires|二本の鉄道にはさまれたタバコと家畜の交差点",
    "Placetas sits between the Cárdenas–Santa Clara sugar network and the tobacco and cattle country further into central Cuba, and its own economy historically leaned more on livestock markets and leaf tobacco than on cane. The town's rail link let both kinds of cargo — tobacco bales and cattle on the hoof — reach Santa Clara's larger junction faster than the roads through the surrounding hills ever could.|Placetas se encuentra entre la red azucarera de Cárdenas a Santa Clara y la zona ganadera y tabacalera más hacia el centro de Cuba, y su propia economía se apoyó históricamente más en los mercados de ganado y la hoja de tabaco que en la caña. El enlace ferroviario del pueblo permitía que ambos tipos de carga —pacas de tabaco y ganado en pie— llegaran al gran empalme de Santa Clara más rápido de lo que jamás pudieron los caminos por las colinas circundantes.|Placetas se trouve entre le réseau sucrier de Cárdenas à Santa Clara et le pays du tabac et du bétail plus avant dans le centre de Cuba, et son économie s'appuya historiquement davantage sur les marchés de bétail et la feuille de tabac que sur la canne. La liaison ferroviaire de la ville permettait aux deux types de fret — balles de tabac et bétail sur pied — d'atteindre le grand embranchement de Santa Clara plus vite que ne l'ont jamais pu les routes à travers les collines environnantes.|プラセタスは、カルデナス―サンタクララの砂糖鉄道網と、キューバ中部の奥に広がるタバコと牧畜の土地のあいだにあり、その経済は歴史的にサトウキビよりも家畜市場と葉タバコに寄りかかってきた。この町の鉄道は、タバコの俵と牛の両方の貨物を、周囲の丘を抜ける道よりずっと速くサンタクララの大きな分岐点まで届けることを可能にした。",
    [prop("Cattle Market Pen|Corral del mercado de ganado|Enclos du marché aux bestiaux|家畜市場の囲い", 230, 48),
     prop("Leaf Tobacco Depot|Depósito de hoja de tabaco|Dépôt de feuille de tabac|葉たばこの集積所", 210, 44)],
  ),

  // ---------------------------------------------------------------------
  // or — オリエンテ(東部)
  // ---------------------------------------------------------------------
  santiagodecuba: city(
    "Santiago de Cuba|Santiago de Cuba|Santiago de Cuba|サンティアゴ・デ・クーバ",
    -75.8219, 20.0247, "or", "soncorner", "provincialcapital", "l",
    "Where son cubano came down from the hills|Donde el son cubano bajó de las lomas|Où le son cubain descendit des collines|ソン・クバーノが山から下りてきた町",
    "Santiago de Cuba, the island's second city and for a time its colonial capital, sits at the foot of the Sierra Maestra, and son cubano — the guitar-and-percussion style that later fed into salsa worldwide — is generally traced to rural groups from these eastern hills who began playing in the city's streets and bars around the turn of the 20th century. The Ferrocarril Central reached the city only in 1902, the last major stretch to close the line all the way from Havana.|Santiago de Cuba, la segunda ciudad de la isla y durante un tiempo su capital colonial, se asienta al pie de la Sierra Maestra, y el son cubano —el estilo de guitarra y percusión que más tarde alimentó la salsa en todo el mundo— suele rastrearse hasta grupos rurales de estas lomas orientales que empezaron a tocar en las calles y bares de la ciudad hacia principios del siglo XX. El Ferrocarril Central llegó a la ciudad solo en 1902, el último gran tramo en cerrar la línea desde La Habana.|Santiago de Cuba, deuxième ville de l'île et un temps sa capitale coloniale, se trouve au pied de la Sierra Maestra, et le son cubain — le style guitare et percussions qui allait plus tard nourrir la salsa dans le monde entier — est généralement rattaché à des groupes ruraux de ces collines orientales qui commencèrent à jouer dans les rues et les bars de la ville vers le tournant du XXe siècle. Le Ferrocarril Central n'atteignit la ville qu'en 1902, le dernier grand tronçon à fermer la ligne depuis La Havane.|島で二番目に大きく、一時は植民地時代の首都でもあったサンティアゴ・デ・クーバは、シエラ・マエストラ山脈の麓にある。のちに世界中のサルサへと流れ込むギターと打楽器の様式ソン・クバーノは、20世紀の変わり目ごろにこの東部の山あいの田舎から出てきた楽団が町の通りやバーで演奏を始めたことに、おおむね起源をたどることができる。中央鉄道がこの町に届いたのは1902年になってからで、ハバナからの路線をようやくつなぎ終えた最後の大きな区間だった。",
    [prop("Son Cubano Street Corner|Esquina del son cubano|Coin de rue du son cubain|ソン・クバーノの街角", 360, 74),
     prop("Ferrocarril Central Terminus|Terminal del Ferrocarril Central|Terminus du Ferrocarril Central|中央鉄道の終着駅", 900, 185)],
  ),
  baracoa: city(
    "Baracoa|Baracoa|Baracoa|バラコア",
    -74.4958, 20.3486, "or", "cacaostall", "isolatedcove", "r",
    "The first Spanish town in the Americas, and the last to get a road|El primer pueblo español de América, y el último en tener carretera|La première ville espagnole des Amériques, et la dernière à avoir une route|アメリカ大陸最初のスペイン人の町、そして道が最後に届いた町",
    "Founded in 1511, Baracoa was the first Spanish settlement in Cuba and briefly its colonial capital, but the mountains ringing it on three sides kept it cut off from the rest of the island by road until 1965, when a highway called La Farola finally crossed the Sierra del Purial — no railway ever reached it at all. That isolation shaped a local cuisine built around coconut and cacao that tastes noticeably different from the rest of Cuba, in a place the sugar-railway story of this island simply never touched.|Fundada en 1511, Baracoa fue el primer asentamiento español de Cuba y brevemente su capital colonial, pero las montañas que la rodean por tres lados la mantuvieron aislada del resto de la isla por carretera hasta 1965, cuando una vía llamada La Farola cruzó por fin la Sierra del Purial: nunca llegó ningún ferrocarril. Ese aislamiento moldeó una cocina local basada en el coco y el cacao que sabe notablemente distinta al resto de Cuba, en un lugar al que la historia azucarera y ferroviaria de esta isla sencillamente nunca llegó.|Fondée en 1511, Baracoa fut le premier établissement espagnol de Cuba et brièvement sa capitale coloniale, mais les montagnes qui l'entourent sur trois côtés la maintinrent coupée du reste de l'île par la route jusqu'en 1965, quand une route appelée La Farola franchit enfin la Sierra del Purial — aucun chemin de fer n'y parvint jamais. Cet isolement façonna une cuisine locale bâtie autour de la noix de coco et du cacao, au goût nettement différent du reste de Cuba, en un lieu que l'histoire sucrière et ferroviaire de cette île n'a tout simplement jamais touché.|1511年に築かれたバラコアはキューバ最初のスペイン人集落であり、一時はその植民地首都でもあった。しかし三方を山に囲まれたこの町は、1965年に「ラ・ファロラ」という道がシエラ・デル・プリアルをようやく越えるまで、島の他地域から道で隔てられていた——鉄道は一度もここに届かなかった。この孤立が、キューバの他地域とは目立って違う味の、ココナッツとカカオを中心にした独自の料理を育んだ。ここは、この島の砂糖と鉄道の物語が一度も触れなかった場所である。",
    [prop("Cacao and Coconut Stall|Puesto de cacao y coco|Étal de cacao et de noix de coco|カカオとココナッツの屋台", 260, 54),
     prop("La Farola Overlook|Mirador de La Farola|Belvédère de La Farola|ラ・ファロラの展望所", 300, 62)],
  ),
  guantanamo: city(
    "Guantánamo|Guantánamo|Guantánamo|グアンタナモ",
    -75.2075, 20.1408, "or", "marimbula", "mountaintown", "b",
    "Where changüí kept its own beat before son took over|Donde el changüí llevó su propio compás antes de que el son se impusiera|Où le changüí gardait son propre rythme avant que le son ne domine|ソンに先立ちチャンギーが独自の拍を刻んだ土地",
    "Changüí, a rural style built around a small hand-cranked scraper called a güiro and a marímbula (a large wooden box with metal keys played like a bass), developed in the countryside around Guantánamo in the 19th century and is generally regarded as one of son cubano's direct ancestors. The city's rail link came late and never carried the volume of cargo the sugar lines further west did, and changüí itself stayed a mostly local, rural sound even as son spread across the rest of the country and the world.|El changüí, un estilo rural construido en torno a un pequeño raspador llamado güiro y a la marímbula (una gran caja de madera con lengüetas metálicas tocada como bajo), se desarrolló en el campo alrededor de Guantánamo en el siglo XIX y suele considerarse uno de los antecesores directos del son cubano. El enlace ferroviario de la ciudad llegó tarde y nunca movió el volumen de carga que sí movieron las líneas azucareras más al oeste, y el changüí se mantuvo como un sonido en gran parte local y rural incluso cuando el son se extendió por el resto del país y del mundo.|Le changüí, style rural construit autour d'un petit racloir appelé güiro et d'une marímbula (grande caisse en bois à languettes métalliques jouée comme une basse), se développa dans la campagne autour de Guantánamo au XIXe siècle et est généralement considéré comme l'un des ancêtres directs du son cubain. La liaison ferroviaire de la ville arriva tard et ne transporta jamais le volume de fret des lignes sucrières plus à l'ouest, et le changüí resta un son surtout local et rural même quand le son se répandit dans le reste du pays et du monde.|チャンギーは、ギロと呼ばれる小さな手回しの擦り楽器と、金属片を弾いて低音を出す大きな木箱「マリンブラ」を中心にした田舎の音楽様式で、19世紀にグアンタナモ周辺の農村部で育まれ、ソン・クバーノの直接の祖先の一つと一般に考えられている。この町への鉄道の接続は遅く、西側の砂糖路線ほどの貨物量を運ぶことは一度もなかった。ソンが国内外に広がっていく間も、チャンギー自体はおおむね地元だけの田舎の音として残り続けた。",
    [prop("Marímbula Workshop|Taller de marímbulas|Atelier de marímbulas|マリンブラ制作工房", 260, 54),
     prop("Late-Arriving Rail Halt|Apeadero de llegada tardía|Halte d'arrivée tardive|遅れて敷かれた鉄道の停車場", 220, 46)],
  ),
  holguin: city(
    "Holguín|Holguín|Holguín|オルギン",
    -76.2642, 20.8872, "or", "parkbench", "provincialcapital", "l",
    "The city of parks, one climb short of the top|La ciudad de los parques, a un tramo de la cima|La ville des parcs, à un pas du sommet|頂上まであと一登りの、公園の町",
    "Holguín is nicknamed the city of parks for the string of small plazas running through its centre, and climbing several hundred steps up the Loma de la Cruz hill just outside town for a view over the whole city is a local tradition dating to a cross planted at the summit in the 19th century during a drought. The Ferrocarril Central's branch to the nearby sugar ports of Chaparra and Antilla made Holguín more of a crossroads than a terminus in its own right.|Holguín es apodada la ciudad de los parques por la sucesión de pequeñas plazas que recorren su centro, y subir varios cientos de escalones por la loma de la Cruz, justo a las afueras, para ver toda la ciudad, es una tradición local que se remonta a una cruz plantada en la cima en el siglo XIX durante una sequía. El ramal del Ferrocarril Central hacia los cercanos puertos azucareros de Chaparra y Antilla hizo de Holguín más un cruce de caminos que un destino propio.|Holguín est surnommée la ville des parcs pour la suite de petites places qui traverse son centre, et gravir plusieurs centaines de marches sur la colline de la Loma de la Cruz juste à l'extérieur de la ville pour une vue sur toute la ville est une tradition locale remontant à une croix plantée au sommet au XIXe siècle pendant une sécheresse. L'embranchement du Ferrocarril Central vers les ports sucriers voisins de Chaparra et Antilla fit d'Holguín davantage un carrefour qu'une destination en soi.|オルギンは、中心部を貫く小さな広場の連なりから「パルケス(公園)の町」と呼ばれる。町のすぐ外にあるロマ・デ・ラ・クルスの丘を何百段も登って町全体を見渡すのは地元の伝統で、19世紀の干ばつの際に頂上に十字架が立てられたことに由来する。近くの砂糖港チャパラとアンティージャへ向かう中央鉄道の支線は、オルギンをそれ自体の終着地というよりむしろ交差点にした。",
    [prop("City-of-Parks Bench Row|Hilera de bancos de la ciudad de los parques|Rangée de bancs de la ville des parcs|パルケスの街のベンチ通り", 280, 58),
     prop("Branch-Line Crossroads Depot|Depósito del cruce de ramales|Dépôt du carrefour d'embranchements|支線が交わる操車場", 260, 54)],
  ),
  lastunas: city(
    "Las Tunas|Las Tunas|Las Tunas|ラス・トゥナス",
    -76.9511, 20.9614, "or", "roundaboutsculpture", "cattletown", "r",
    "A cattle and farming crossroads that grew statues instead of a mill|Un cruce ganadero y agrícola que hizo crecer estatuas en vez de un ingenio|Un carrefour d'élevage et d'agriculture qui vit pousser des statues plutôt qu'une sucrerie|製糖工場の代わりに彫刻を育てた牧畜と農業の交差点",
    "Las Tunas never grew a sugar mill on the scale of its neighbours, leaning instead on cattle ranching and general farming, and today the city fills its parks and roundabouts with public sculpture to the point that it's nicknamed the city of sculptures. Its rail link tied it into the same Ferrocarril Central network as the bigger sugar towns on either side, moving cattle and produce rather than cane.|Las Tunas nunca desarrolló un ingenio a la escala de sus vecinos, apoyándose en cambio en la ganadería y la agricultura general, y hoy la ciudad llena sus parques y rotondas de escultura pública hasta el punto de ser apodada la ciudad de las esculturas. Su enlace ferroviario la unió a la misma red del Ferrocarril Central que los pueblos azucareros más grandes a ambos lados, moviendo ganado y productos en vez de caña.|Las Tunas ne développa jamais de sucrerie à l'échelle de ses voisines, s'appuyant plutôt sur l'élevage bovin et l'agriculture générale, et la ville remplit aujourd'hui ses parcs et ronds-points de sculptures publiques au point d'être surnommée la ville des sculptures. Sa liaison ferroviaire la relia au même réseau du Ferrocarril Central que les plus grandes villes sucrières de part et d'autre, transportant bétail et produits plutôt que canne.|ラス・トゥナスは隣接する町々のような規模の製糖工場を一度も持たず、むしろ牧畜と一般的な農業に頼ってきた。いまこの町は公園やロータリーを公共彫刻で埋め尽くしており、「彫刻の町」とあだ名されるほどである。この町の鉄道は、両隣のより大きな砂糖の町々と同じ中央鉄道網に結ばれていたが、運んでいたのはサトウキビではなく牛と農産物だった。",
    [prop("Roundabout Sculpture Garden|Jardín de esculturas de la rotonda|Jardin de sculptures du rond-point|ロータリーの彫刻庭園", 240, 50),
     prop("Cattle Loading Ramp|Rampa de carga de ganado|Rampe de chargement du bétail|家畜の積み込み台", 220, 46)],
  ),
  bayamo: city(
    "Bayamo|Bayamo|Bayamo|バヤモ",
    -76.6417, 20.3797, "or", "rebuiltplaza", "cattletown", "b",
    "The city its own people burned down|La ciudad que su propia gente incendió|La ville que son propre peuple incendia|自らの手で焼いた町",
    "Bayamo, one of the seven original villas founded by Diego Velázquez in the 1510s, was set alight by its own residents in January 1869 rather than let a besieging Spanish force retake it during the Ten Years' War, and the rebuilt town that stands today dates almost entirely from after that fire. The railway reached it only much later than the sugar towns further west, since Bayamo's economy leaned on cattle ranching rather than cane.|Bayamo, una de las siete villas originales fundadas por Diego Velázquez en la década de 1510, fue incendiada por sus propios habitantes en enero de 1869 antes de dejar que una fuerza española sitiadora la recuperara durante la Guerra de los Diez Años, y el pueblo reconstruido que hoy se ve data casi por completo de después de ese incendio. El ferrocarril llegó mucho más tarde que a los pueblos azucareros más al oeste, ya que la economía de Bayamo se apoyaba en la ganadería y no en la caña.|Bayamo, l'une des sept villas originelles fondées par Diego Velázquez dans les années 1510, fut incendiée par ses propres habitants en janvier 1869 plutôt que de laisser une force espagnole assiégeante la reprendre pendant la guerre de Dix Ans, et la ville reconstruite que l'on voit aujourd'hui date presque entièrement d'après cet incendie. Le chemin de fer n'y parvint que bien plus tard que dans les villes sucrières plus à l'ouest, l'économie de Bayamo reposant sur l'élevage plutôt que sur la canne.|1510年代にディエゴ・べラスケスが築いた最初の7つのビリャの一つバヤモは、十年戦争のさなか、包囲するスペイン軍に奪還されるくらいなら、と1869年1月に住民自身の手で火を放たれた。いま目にする再建された町並みは、ほぼすべてその大火のあとに建てられたものである。バヤモの経済はサトウキビではなく牧畜に頼っていたため、鉄道が届いたのは西側の砂糖の町々よりもずっと遅かった。",
    [prop("Rebuilt-After-the-Fire Plaza House|Casa de la plaza reconstruida tras el incendio|Maison de la place reconstruite après l'incendie|大火後に再建された広場の家", 280, 58),
     prop("Cattle Ranch Loading Yard|Patio de carga del rancho ganadero|Cour de chargement du ranch d'élevage|牧場の積み出し場", 240, 50)],
  ),
  manzanillo: city(
    "Manzanillo|Manzanillo|Manzanillo|マンサニージョ",
    -77.1064, 20.3406, "or", "glorieta", "coastalpalms", "l",
    "A port that shipped sugar past a swamp with no line through it|Un puerto que embarcaba azúcar bordeando un pantano sin vía alguna|Un port qui expédiait du sucre en longeant un marais sans aucune voie|線路の通らない沼を避けて砂糖を積み出した港",
    "Manzanillo grew as the main export port for the sugar and cattle country of Granma province, its harbor doing the job a railway couldn't, since the marshy ground of the nearby Cauto river delta made track-laying far harder here than on the flat cane plains further north. The city's waterfront malecón and its brightly painted, Moorish-influenced glorieta bandstand are local landmarks that owe more to that port trade than to any rail line.|Manzanillo creció como el principal puerto exportador de la zona azucarera y ganadera de la provincia de Granma, con su puerto haciendo el trabajo que un ferrocarril no podía, ya que el terreno pantanoso del cercano delta del río Cauto hacía aquí el tendido de vías mucho más difícil que en las llanuras cañeras más al norte. El malecón de la ciudad y su vistosa glorieta de influencia morisca son símbolos locales que deben más a ese comercio portuario que a ninguna línea férrea.|Manzanillo se développa comme principal port d'exportation du pays du sucre et du bétail de la province de Granma, son port faisant le travail qu'un chemin de fer ne pouvait pas, car le terrain marécageux du delta voisin du fleuve Cauto rendait la pose de voies bien plus difficile ici que sur les plaines à canne plus plates du nord. Le malecón du front de mer et sa glorieta aux couleurs vives, d'influence mauresque, sont des repères locaux qui doivent davantage à ce commerce portuaire qu'à une quelconque ligne de chemin de fer.|マンサニージョはグランマ州の砂糖・牧畜地帯の主要な輸出港として発展した。近くのカウト川河口のぬかるんだ地面では、北側の平らな砂糖平野よりもはるかに線路を敷きにくく、その分の仕事を鉄道の代わりに港が担った。この町の海岸通りマレコンと、色鮮やかでムーア風の意匠を持つ楽団台グロリエタは、鉄道よりもむしろこの港の交易のおかげで生まれた地元の名物である。",
    [prop("Cauto Delta Sugar Pier|Muelle azucarero del delta del Cauto|Quai à sucre du delta du Cauto|カウト川河口の砂糖桟橋", 280, 58),
     prop("Glorieta Bandstand Square|Plaza de la glorieta|Place de la glorieta|グロリエタ楽団台の広場", 260, 54)],
  ),
  antilla: city(
    "Antilla|Antilla|Antilla|アンティージャ",
    -75.7358, 20.8375, "or", "deepwaterport", "sugarport", "r",
    "A harbour built for sugar, now mostly empty|Un puerto construido para el azúcar, hoy casi vacío|Un port bâti pour le sucre, aujourd'hui presque vide|砂糖のために作られ、いまはほとんど空の港",
    "Antilla was purpose-built in the early 20th century around one of the best natural deep-water harbors on Cuba's north coast, largely to export sugar from the Chaparra and Delicias mills further inland via its own rail spur, and for a time it was one of the busiest sugar ports on the island. As the mills it served slowed after the sugar industry's contraction, the port's traffic shrank with them, and much of Antilla today is quieter than the harbor it was built around was ever meant to be.|Antilla se construyó a propósito a principios del siglo XX en torno a uno de los mejores puertos naturales de aguas profundas de la costa norte de Cuba, sobre todo para exportar el azúcar de los ingenios de Chaparra y Delicias, más adentro, mediante su propio ramal ferroviario, y por un tiempo fue uno de los puertos azucareros más activos de la isla. A medida que los ingenios a los que servía se fueron ralentizando tras la contracción de la industria azucarera, el tráfico del puerto se redujo con ellos, y buena parte de Antilla es hoy más tranquila de lo que el puerto en torno al cual se construyó estaba pensado para ser.|Antilla fut spécialement bâtie au début du XXe siècle autour de l'un des meilleurs ports naturels en eaux profondes de la côte nord de Cuba, surtout pour exporter le sucre des sucreries de Chaparra et Delicias plus à l'intérieur des terres via son propre embranchement, et fut un temps l'un des ports sucriers les plus actifs de l'île. À mesure que les usines qu'elle desservait ralentissaient après la contraction de l'industrie sucrière, le trafic du port a diminué avec elles, et une grande partie d'Antilla est aujourd'hui plus calme que le port autour duquel elle fut bâtie n'était censé l'être.|アンティージャは20世紀初頭、キューバ北岸でも屈指の天然の深水港を中心に、内陸のチャパラとデリシアスの製糖工場から独自の専用線で運ばれる砂糖を輸出するために計画的に建設され、一時は島でも有数の忙しい砂糖港だった。その港が仕えていた製糖工場が砂糖産業の縮小とともに勢いを落とすと、港の取扱量もそれに連れて減っていった。いまのアンティージャの多くは、かつてこの港が作られた目的からすればずっと静かな町である。",
    [prop("Deep-Water Sugar Terminal|Terminal azucarera de aguas profundas|Terminal sucrier en eaux profondes|深水港の砂糖ターミナル", 300, 62),
     prop("Quiet Harbor Warehouse Row|Hilera de almacenes del puerto tranquilo|Rangée d'entrepôts du port tranquille|静かになった港の倉庫街", 240, 50)],
  ),
  nuevitas: city(
    "Nuevitas|Nuevitas|Nuevitas|ヌエビタス",
    -77.2606, 21.5486, "or", "cargopier", "sugarport", "b",
    "Camagüey's outlet to the sea, still working|La salida al mar de Camagüey, todavía en activo|La sortie maritime de Camagüey, toujours active|いまも働き続けるカマグエイの海への出口",
    "Nuevitas has served as Camagüey province's main port since Spanish colonial times, and unlike Antilla or Trinidad it never really slowed down: cargo, including sugar and cement, still moves through its harbor and rail yards today. Christopher Columbus is traditionally said to have landed near here in 1492, on his first voyage — a claim tourism brochures repeat more confidently than historians do.|Nuevitas ha servido como principal puerto de la provincia de Camagüey desde tiempos coloniales españoles, y a diferencia de Antilla o Trinidad, nunca llegó a ralentizarse del todo: carga como azúcar y cemento sigue moviéndose hoy por su puerto y sus patios ferroviarios. La tradición dice que Cristóbal Colón desembarcó cerca de aquí en 1492, en su primer viaje, una afirmación que los folletos turísticos repiten con más seguridad que los historiadores.|Nuevitas sert de port principal à la province de Camagüey depuis l'époque coloniale espagnole, et contrairement à Antilla ou Trinidad, elle ne ralentit jamais vraiment : des marchandises, dont du sucre et du ciment, transitent encore aujourd'hui par son port et ses cours ferroviaires. La tradition veut que Christophe Colomb ait débarqué non loin d'ici en 1492, lors de son premier voyage — une affirmation que les brochures touristiques répètent avec plus d'assurance que les historiens.|ヌエビタスはスペイン植民地時代からずっとカマグエイ州の主要港として機能してきた。アンティージャやトリニダードと違い、この港が本当に勢いを落としたことは一度もなく、砂糖やセメントを含む貨物がいまも港と操車場を行き交っている。クリストファー・コロンブスが1492年の最初の航海でこの近くに上陸したという言い伝えがあるが、これは歴史家よりも観光パンフレットのほうが自信たっぷりに繰り返す話である。",
    [prop("Working Cargo Pier|Muelle de carga en actividad|Quai de fret en activité|稼働中の貨物埠頭", 280, 58),
     prop("Nickel Concentrate Siding|Apartadero de concentrado de níquel|Voie de garage du concentré de nickel|ニッケル精鉱の側線", 260, 54)],
  ),
  gibara: city(
    "Gibara|Gibara|Gibara|ヒバラ",
    -76.1339, 21.1108, "or", "poormanshavana", "cobbletown", "l",
    "Havana's poor relation, preserved by being passed over|La pariente pobre de La Habana, conservada por haber sido pasada por alto|La cousine pauvre de La Havane, préservée en étant délaissée|素通りされたおかげで残った、ハバナの貧しい親戚",
    "Gibara was one of the north coast's busiest ports in the 19th century, prosperous enough that its grand seafront buildings earned it the nickname 'the poor man's Havana,' but larger, deeper ports such as Nuevitas and Antilla drew shipping away in the 20th century and the town's rail connection never grew much past a modest spur. That being-passed-over left much of Gibara's 19th-century waterfront intact, and the town now hosts an annual international film festival that trades on exactly that well-preserved backdrop.|Gibara fue uno de los puertos más activos de la costa norte en el siglo XIX, lo bastante próspero como para que sus grandiosos edificios frente al mar le ganaran el apodo de 'la Habana del pobre', pero puertos más grandes y profundos como Nuevitas y Antilla se llevaron el tráfico en el siglo XX, y la conexión ferroviaria del pueblo nunca pasó de un modesto ramal. Ese haber quedado atrás dejó intacta buena parte del malecón decimonónico de Gibara, y el pueblo alberga hoy un festival internacional de cine anual que se apoya justamente en ese escenario tan bien conservado.|Gibara fut l'un des ports les plus actifs de la côte nord au XIXe siècle, assez prospère pour que ses grands édifices en front de mer lui valent le surnom de « La Havane du pauvre », mais des ports plus grands et plus profonds comme Nuevitas et Antilla détournèrent le trafic au XXe siècle, et la liaison ferroviaire de la ville ne dépassa jamais guère un modeste embranchement. Cet oubli laissa intact une grande partie du front de mer du XIXe siècle de Gibara, et la ville accueille aujourd'hui un festival international de cinéma annuel qui tire précisément parti de ce décor bien préservé.|ヒバラは19世紀、北岸でも屈指の忙しい港のひとつだった。海岸沿いの壮麗な建物群のおかげで「貧者のハバナ」とあだ名されるほど繁栄していたが、20世紀に入るとヌエビタスやアンティージャといったより大きく水深のある港に船が流れ、この町の鉄道の接続はささやかな支線どまりのままだった。この置き去りにされた経緯こそが、19世紀の海岸通りの多くをそのまま残す結果になった。いまこの町は、まさにその保存状態のよい町並みを土台にした国際映画祭を毎年開いている。",
    [prop("Poor Man's Havana Seafront|Malecón del pobre habanero|Front de mer du pauvre havanais|「貧者のハバナ」の海岸通り", 300, 62),
     prop("Modest Rail Spur Shed|Cobertizo del ramal modesto|Hangar de l'embranchement modeste|控えめな支線の車庫", 220, 46)],
  ),
  elcobre: city(
    "El Cobre|El Cobre|El Cobre|エル・コブレ",
    -75.9333, 20.0625, "or", "coppershaft", "miningtown", "r",
    "A copper mine that gave Cuba its patron saint|Una mina de cobre que le dio a Cuba su santa patrona|Une mine de cuivre qui donna à Cuba sa sainte patronne|キューバに守護聖人を与えた銅山",
    "El Cobre's copper mine, worked from the 16th century using enslaved and later free Black labor, is where a small wooden statue of the Virgin Mary is said to have been found floating in the bay in the early 1600s, carried inland, and enshrined in the basilica that still stands here; she is now venerated across Cuba as Nuestra Señora de la Caridad del Cobre, the country's patron saint. The mine itself, one of the oldest continuously worked in the Americas, never needed the sugar railways — its copper and later its miners moved by road to Santiago instead.|La mina de cobre de El Cobre, trabajada desde el siglo XVI con mano de obra esclavizada y después negra libre, es el lugar donde se dice que una pequeña talla de madera de la Virgen se halló flotando en la bahía a principios del siglo XVII, se llevó tierra adentro y se veneró en la basílica que aún se alza aquí; hoy se venera en toda Cuba como Nuestra Señora de la Caridad del Cobre, patrona del país. La mina misma, una de las más antiguas en explotación continua de América, nunca necesitó los ferrocarriles azucareros: su cobre, y después sus mineros, se movieron por carretera hacia Santiago.|La mine de cuivre d'El Cobre, exploitée dès le XVIe siècle par une main-d'œuvre d'abord esclave puis noire libre, est l'endroit où une petite statue en bois de la Vierge aurait été retrouvée flottant dans la baie au début du XVIIe siècle, portée à l'intérieur des terres et vénérée dans la basilique qui se dresse encore ici ; elle est aujourd'hui vénérée dans tout Cuba comme Nuestra Señora de la Caridad del Cobre, patronne du pays. La mine elle-même, l'une des plus anciennes en exploitation continue des Amériques, n'eut jamais besoin des chemins de fer sucriers — son cuivre, puis ses mineurs, empruntèrent plutôt la route vers Santiago.|16世紀から奴隷労働、のちに自由黒人の労働によって採掘されてきたエル・コブレの銅山は、1600年代初め、木彫りの小さな聖母像が入り江に浮かんでいるのが見つかり、内陸へ運ばれて、いまも建つバジリカに祀られたと伝えられる場所である。この聖母はいま、キューバ全土でこの国の守護聖人「エル・コブレの慈愛の聖母」として崇敬されている。この鉱山自体は、アメリカ大陸でも途切れず採掘が続く最古のもののひとつだが、砂糖鉄道を必要としたことは一度もない。銅も、のちには鉱山労働者も、道でサンティアゴへ運ばれた。",
    [prop("Copper Mine Shaft Head|Boca del pozo de la mina de cobre|Chevalement de la mine de cuivre|銅鉱山の坑口", 280, 58),
     prop("Basilica Pilgrimage Stall|Puesto de peregrinos de la basílica|Étal des pèlerins de la basilique|バジリカ巡礼者の屋台", 300, 62)],
  ),
  moa: city(
    "Moa|Moa|Moa|モア",
    -74.9394, 20.6528, "or", "oreconveyor", "miningtown", "b",
    "Where nickel replaced sugar as the export that mattered|Donde el níquel sustituyó al azúcar como la exportación que importaba|Où le nickel remplaça le sucre comme exportation qui compte|砂糖に代わって輸出の主役になったニッケル",
    "Moa's laterite soil, poor for growing cane, turned out to sit on some of the world's largest nickel and cobalt reserves, and since large-scale processing plants opened here in the mid-20th century the town has run on mining rather than sugar — one of the few parts of eastern Cuba where that's true. Ore concentrate now moves out through Moa's own port rather than any of the old sugar railways, on a route this island's 1837 railway was never built to imagine.|El suelo laterítico de Moa, pobre para la caña, resultó asentarse sobre algunas de las mayores reservas de níquel y cobalto del mundo, y desde que aquí se abrieron plantas de procesamiento a gran escala a mediados del siglo XX, el pueblo vive de la minería y no del azúcar, una de las pocas zonas del oriente cubano donde eso es cierto. El concentrado de mineral sale ahora por el propio puerto de Moa y no por ninguno de los viejos ferrocarriles azucareros, por una ruta que el ferrocarril de 1837 de esta isla nunca se construyó para imaginar.|Le sol latéritique de Moa, pauvre pour la canne, se trouva reposer sur certaines des plus grandes réserves de nickel et de cobalt au monde, et depuis que de grandes usines de traitement y ont ouvert au milieu du XXe siècle, la ville vit de l'exploitation minière plutôt que du sucre — l'une des rares régions de l'est de Cuba où cela est vrai. Le concentré de minerai sort désormais par le propre port de Moa plutôt que par l'un des vieux chemins de fer sucriers, sur un trajet que le chemin de fer de 1837 de cette île n'a jamais été conçu pour imaginer.|サトウキビには向かなかったモアのラテライト土壌は、実は世界でも有数のニッケル・コバルト鉱床の上にあることが分かった。20世紀半ばにここへ大規模な精錬プラントが建てられて以来、この町は砂糖ではなく鉱業で成り立っている——キューバ東部では数少ない例である。精鉱はいま、古い砂糖鉄道のどれでもなく、モア自身の港を通じて運び出される。1837年のこの島の鉄道が思い描くことすらなかった経路である。",
    [prop("Laterite Ore Conveyor|Cinta transportadora de mineral laterítico|Convoyeur de minerai latéritique|ラテライト鉱石のコンベア", 300, 62),
     prop("Nickel Port Loading Dock|Muelle de carga de níquel|Quai de chargement du nickel|ニッケル積み出し埠頭", 320, 66)],
  ),
};

/**
 * 路線(40都市・43本)。
 *
 * 西部は「ハバナ―ベフカル―グイネス」という1837年の最初の路線と、
 * 「ハバナ―サン・アントニオ・デ・ロス・バニョス―アルテミサ―コンソラシオン・
 * デル・スル―ピナル・デル・リオ」という別系統の西部鉄道(フェロカリル・
 * デル・オエステ)を分けて描いている。バタバノーへの支線はベフカル寄りの
 * 分岐点から南へ、イスラ・デ・ラ・フベントゥへは海路(バタバノーが本土側の
 * 渡し場)。中部はサンタクララを結節点に、東部はサンティアゴ・デ・クーバへの
 * 中央鉄道の縦貫を軸に組んだ。海路は陸路が地理的に成立しない1本のみ
 * (バタバノー―ヌエバ・ヘロナ)。他の沿岸路線(モア―バラコアなど)は
 * 現実には20世紀以降の道路(ラ・ファロラなど)にあたるが、盤面上は
 * 陸路として扱う。
 */
export const CUBA_EDGES = [
  // --- oc(西部) ---
  ["habana", "bejucal"],
  ["bejucal", "guines"],
  ["bejucal", "batabano"],
  ["batabano", "nuevagerona", "sea"],
  ["habana", "sanantoniodelosbanos"],
  ["sanantoniodelosbanos", "artemisa"],
  ["artemisa", "consolaciondelsur"],
  ["consolaciondelsur", "pinardelrio"],
  ["pinardelrio", "vinales"],
  ["habana", "matanzas"],
  // --- ce(中部) ---
  ["matanzas", "cardenas"],
  ["cardenas", "uniondereyes"],
  ["uniondereyes", "colon"],
  ["colon", "sagualagrande"],
  ["sagualagrande", "cienfuegos"],
  ["colon", "santaclara"],
  ["santaclara", "cienfuegos"],
  ["cienfuegos", "trinidad"],
  ["santaclara", "remedios"],
  ["remedios", "caibarien"],
  ["santaclara", "placetas"],
  ["placetas", "sanctispiritus"],
  ["sanctispiritus", "jatibonico"],
  ["jatibonico", "ciegodeavila"],
  ["ciegodeavila", "moron"],
  ["ciegodeavila", "florida"],
  ["florida", "camaguey"],
  // --- or(東部) ---
  ["camaguey", "nuevitas"],
  ["camaguey", "lastunas"],
  ["lastunas", "holguin"],
  ["lastunas", "bayamo"],
  ["holguin", "chaparra"],
  ["chaparra", "antilla"],
  ["holguin", "gibara"],
  ["bayamo", "manzanillo"],
  ["bayamo", "santiagodecuba"],
  ["santiagodecuba", "elcobre"],
  ["santiagodecuba", "guantanamo"],
  ["guantanamo", "baracoa"],
  ["antilla", "moa"],
  ["baracoa", "moa"], // 端の順を入れ替え。海に出ていた95px→0px(check-sea-routes.mjs)
  ["nuevitas", "antilla"],
  ["gibara", "antilla"],
];
