/**
 * 中国の青マス・赤マスで起きる出来事(21件。増12・減9)。
 *
 * 地方コード: hb=華北 / db=東北 / hd=華東 / hn=華南 / xn=西南 / xb=西北
 *
 * 地方も月も指定しない出来事を4件(増2・減2)置いてあるので、
 * どの地方・どの月でも必ず1件は引ける(他の盤面と同じ約束)。
 * そのうえで、6地方それぞれに2〜4件、土地の実在の習わしや市場に結びつけて置いている。
 */
function t(source) {
  const parts = source.split("|");
  if (parts.length !== 4) {
    throw new Error(`4言語(en|es|fr|ja)で書いてください: ${source.slice(0, 60)}…`);
  }
  const [en, es, fr, ja] = parts;
  return { en, es, fr, ja };
}

/**
 * 出来事1件。`months` を指定すると、その月にしか起こらない
 * (0=4月。9月=5、10月=6、11月=7、12月=8、1月=9、2月=10、3月=11)。
 * 省略すれば通年。
 */
function ev(id, kind, regs, emoji, amount, title, narrative, months = []) {
  return { id, kind, regs, e: emoji, amount, n: t(title), t: t(narrative), months };
}

export const CHINA_MONEY_EVENTS = [
  // ---- 全国どこでも・通年(どの地方・どの月でも必ず引けるようにするための4件) ----
  ev(
    "waimai-gaofeng", "gain", [], "🛵", 210,
    "Covering a lunchtime food-delivery surge|Cubriendo un pico de reparto de comida al mediodía|Assurer un coup de feu de livraison de repas à midi|昼どきの出前ラッシュを手伝う",
    "A food-delivery app needed extra riders during a lunchtime surge and paid a bonus per completed order, no experience required beyond a scooter and a phone. Delivery apps route orders by the minute nationwide, so a rider willing to work exactly the busiest hour rarely goes unpaid.|Una aplicación de reparto de comida necesitaba repartidores extra durante el pico del mediodía y pagó una prima por cada pedido completado, sin más requisito que un ciclomotor y un teléfono. Las aplicaciones de reparto asignan pedidos minuto a minuto en todo el país, así que un repartidor dispuesto a trabajar justo la hora más ajetreada casi nunca se queda sin paga.|Une appli de livraison de repas avait besoin de livreurs en renfort pendant le coup de feu de midi et payait une prime par commande menée à bien, sans autre condition qu'un scooter et un téléphone. Les applis de livraison répartissent les commandes à la minute près dans tout le pays, si bien qu'un livreur prêt à travailler pile l'heure la plus chargée reste rarement sans paie.|フードデリバリーのアプリが昼どきのピークで配達員を急募しており、注文一件ごとに割増しが付いた。必要なのはスクーターと電話だけだった。配達アプリは全国で分刻みに注文を振り分けているので、いちばん忙しい時間帯にちょうど働ける配達員が無給で終わることはまずない。",
  ),
  ev(
    "danche-tiaoxi", "gain", [], "🚲", 190,
    "Rounding up stray shared bikes overnight|Recogiendo de noche bicicletas compartidas descarriadas|Rassembler de nuit des vélos partagés égarés|夜のうちに乱れたシェア自転車を集める",
    "A bike-share operator paid by the piece to haul dozens of misparked rental bikes back to a marked zone before the morning commute, a night's work best done with a flatbed tricycle and a strong back. Cities of this size can have hundreds of thousands of shared bikes in circulation, and someone has to keep them from drifting into an unrideable pile.|Una empresa de bicicletas compartidas pagó por unidad para llevar decenas de bicicletas mal aparcadas de vuelta a una zona señalizada antes de la hora punta matutina, un trabajo nocturno mejor hecho con un triciclo de plataforma y buena espalda. Ciudades de este tamaño pueden tener cientos de miles de bicicletas compartidas en circulación, y alguien tiene que evitar que acaben amontonadas e inservibles.|Un opérateur de vélos en libre-service payait à la pièce pour ramener des dizaines de vélos mal garés vers une zone balisée avant l'heure de pointe matinale, un travail de nuit mieux fait avec un tricycle à plateau et de bons reins. Des villes de cette taille peuvent compter des centaines de milliers de vélos en circulation, et quelqu'un doit les empêcher de finir en tas inutilisables.|シェア自転車の運営会社が、通勤ラッシュ前に乱雑に置かれた自転車を指定の置き場へ何十台も運ぶ仕事を歩合で募集していた。荷台付き三輪車と丈夫な腰があれば向く夜の仕事だった。この規模の都市ではシェア自転車が何十万台と出回っており、誰かが乗れない山になる前に整えなければならない。",
  ),
  ev(
    "majiang-shuqian", "loss", [], "🀄", 200,
    "Losing badly at mahjong|Perdiendo feo al mahjong|Une lourde défaite au mahjong|麻将の勝負に負ける",
    "The tiles kept running the wrong way, and by the fourth round the little stack of chips on the table had shrunk to almost nothing. Mahjong tables fill teahouses, courtyard corners and long train-car aisles alike, and the scoring rules shift enough from region to region that a visitor rarely reads the hand as fast as the locals do.|Las fichas no dejaban de salir mal, y para la cuarta ronda la pequeña pila de fichas sobre la mesa casi había desaparecido. Las mesas de mahjong llenan casas de té, rincones de patio y pasillos de vagones de tren por igual, y las reglas de puntuación cambian tanto de una región a otra que un visitante rara vez lee la mano tan rápido como los lugareños.|Les tuiles tombaient sans cesse du mauvais côté, et à la quatrième manche, la petite pile de jetons sur la table avait presque disparu. Les tables de mahjong envahissent maisons de thé, coins de cour et couloirs de wagons de train, et les règles de comptage changent assez d'une région à l'autre pour qu'un visiteur ne lise que rarement la main aussi vite que les habitués.|牌がどうにも噛み合わず、四局目には卓の上のわずかな点棒の山もほとんど尽きていた。麻将卓は茶館の隅から中庭、長距離列車の通路にまで至る所にあり、点の数え方は地方ごとにかなり違うので、旅行者が地元の打ち手と同じ速さで手を読めることはまずない。",
  ),
  ev(
    "gaotie-cuoguo", "loss", [], "🎫", 220,
    "Missing a high-speed train over a one-character typo|Perdiendo un tren de alta velocidad por un carácter mal tecleado|Rater un train à grande vitesse pour une faute de frappe|一文字の誤字で高鉄に乗り遅れる",
    "The ticket gate scans an ID against the seat reservation, and a name typed one character wrong at booking meant standing in a separate queue while the train pulled out without its buyer. A same-day replacement ticket on a different route was the only way to still make the day's plans.|La puerta de embarque escanea el documento de identidad contra la reserva del asiento, y un nombre tecleado con un carácter erróneo al comprar significó hacer cola aparte mientras el tren salía sin su comprador. Un billete de repuesto para el mismo día por otra ruta fue la única forma de salvar los planes.|Le portique de contrôle scanne une pièce d'identité en regard de la réservation, et un nom saisi avec un caractère erroné à l'achat a valu une file à part pendant que le train partait sans son acheteur. Un billet de remplacement le jour même sur un autre trajet fut le seul moyen de sauver les projets du jour.|改札は身分証と座席予約を照合する仕組みで、予約時に名前を一文字打ち間違えていたせいで別の列に回され、列車は買った本人を乗せずに出発してしまった。その日の予定を守るには、別路線の当日券を買い直すしかなかった。",
  ),

  // ---- hb 華北 ----
  ev(
    "panjiayuan-jiagu", "loss", ["hb"], "🏺", 230,
    "Talked into a fake antique at Panjiayuan|Convencido de comprar una falsa antigüedad en Panjiayuan|Convaincu d'acheter une fausse antiquité à Panjiayuan|潘家園で偽の骨董をつかまされる",
    "A dealer at the weekend market swore the bronze coin was Han dynasty and priced it accordingly, and only a friend who collects for real pointed out the mould seam still visible along the edge. Panjiayuan is famous precisely for this mix of genuine finds and confident fakes sitting side by side on the same blanket, and telling them apart is half the sport of shopping there.|Un vendedor del mercado de fin de semana juró que la moneda de bronce era de la dinastía Han y la tasó en consecuencia, y solo un amigo coleccionista de verdad señaló la costra de molde aún visible en el borde. Panjiayuan es famoso precisamente por esta mezcla de hallazgos genuinos y falsificaciones convincentes puestos lado a lado sobre la misma manta.|Un marchand du marché du week-end jurait que la pièce de bronze datait des Han et l'a tarifée en conséquence, et seul un ami collectionneur sérieux a repéré la bavure de moulage encore visible sur le bord. Panjiayuan est justement réputé pour ce mélange de trouvailles authentiques et de faux bien faits posés côte à côte sur la même couverture.|週末市の露天商は、この青銅銭は漢代のものだと言い張り、値もそれなりに付けていたが、本物の蒐集家である友人だけが縁に残る鋳型の継ぎ目を見抜いた。潘家園はまさに、本物と自信満々の贋作が同じ敷布の上に並ぶことで知られる場所で、見分けることこそがそこで買い物をする醍醐味の半分を占める。",
  ),
  ev(
    "goubuli-baozi", "gain", ["hb"], "🥟", 210,
    "Folding steamed buns before the lunch rush|Plegando bollos al vapor antes de la hora punta del mediodía|Plier des brioches vapeur avant le coup de feu de midi|昼どき前に包子のひだを寄せる",
    "A century-old steamed-bun shop needed an extra pair of hands folding pleats and loading bamboo steamers before the lunchtime line stretched around the corner, paid in cash and a bag of the seconds that came out slightly misshapen. Locals will tell you the eighteen pleats per bun are counted, not estimated, and a shop that shorts the count hears about it fast.|Una tienda centenaria de bollos al vapor necesitaba manos extra para plegar los pliegues y cargar las vaporeras de bambú antes de que la cola del mediodía diera la vuelta a la esquina, pagado en efectivo y con una bolsa de piezas de segunda algo deformes. Los lugareños dirán que los dieciocho pliegues por bollo se cuentan, no se calculan a ojo.|Une boutique de brioches vapeur centenaire avait besoin de bras pour plisser la pâte et charger les paniers en bambou avant que la file de midi ne contourne le pâté de maisons, payée en espèces et avec un sac de pièces ratées légèrement difformes. Les habitants vous diront que les dix-huit plis par brioche se comptent, ils ne s'estiment pas.|百年続く包子の店が、昼どきの行列が角を曲がるほど伸びる前に、ひだを寄せて竹の蒸籠を積む手を求めていた。給金は現金と、形が少しいびつになった不良品の袋だった。地元の人によれば、一つの包子のひだは十八本と数えられているのであって目分量ではなく、数が足りない店はすぐに噂になるという。",
  ),

  // ---- db 東北 ----
  ev(
    "zhongyang-dalieba", "gain", ["db"], "🍞", 220,
    "A night shift at a Russian-style bakery|Un turno de noche en una panadería de estilo ruso|Un service de nuit dans une boulangerie de style russe|露西亜風パン屋の夜勤",
    "A bakery on the old cobblestone street needed a night-shift hand to pull loaves of dense Russian-style bread from the oven before the morning tourist crowd arrived, the ovens themselves older than most of the buildings still standing nearby. The recipe came with the Chinese Eastern Railway builders a century ago and never really left.|Una panadería en la vieja calle empedrada necesitaba una mano en el turno de noche para sacar del horno hogazas de pan denso al estilo ruso antes de que llegara la multitud turística de la mañana, hornos más antiguos que la mayoría de los edificios que aún quedan cerca. La receta llegó con los constructores del ferrocarril del Este Chino hace un siglo y nunca se fue del todo.|Une boulangerie de la vieille rue pavée avait besoin d'un renfort de nuit pour sortir du four des miches de pain dense de style russe avant l'arrivée de la foule de touristes du matin, des fours plus vieux que la plupart des bâtiments encore debout à proximité. La recette est arrivée avec les bâtisseurs du chemin de fer de l'Est chinois il y a un siècle et n'est jamais vraiment repartie.|石畳の旧市街の通りにあるパン屋が、朝の観光客が来る前にロシア風の重いパンをオーブンから取り出す夜勤の手を求めていた。オーブン自体、近くに残る建物の大半より古かった。このレシピは一世紀前、中東鉄道の建設者たちとともに伝わり、その後もずっと根付いたままである。",
    [8, 9, 10],
  ),
  ev(
    "gugong-xiangqi", "loss", ["db"], "♟️", 180,
    "A side bet on a park chess match goes wrong|Una apuesta paralela en una partida de ajedrez en el parque sale mal|Un pari annexe sur une partie d'échecs de parc tourne mal|公園の象棋の賭けで損をする",
    "A crowd had gathered around two elderly men hunched over a folding board outside the old Qing palace walls, and a small side bet on the underdog's next move seemed safe until three moves later proved it wasn't. Retirees fill these corner matches every clear morning, and years of practice make the outcome far less obvious to a stranger than the board suggests.|Se había reunido una multitud alrededor de dos ancianos encorvados sobre un tablero plegable junto a los muros del antiguo palacio Qing, y una pequeña apuesta al perdedor aparente pareció segura hasta que, tres jugadas después, quedó claro que no lo era. Los jubilados llenan estas partidas de esquina cada mañana despejada.|Une foule s'était rassemblée autour de deux vieux messieurs penchés sur un échiquier pliant près des murs de l'ancien palais Qing, et un petit pari annexe sur l'outsider a semblé sûr jusqu'à ce que, trois coups plus tard, il s'avère qu'il ne l'était pas. Les retraités remplissent ces parties de coin de rue chaque matin dégagé.|旧清朝の宮殿の壁のそばで、折り畳み盤に屈み込む二人の老人の周りに人だかりができていた。劣勢に見えるほうに軽く賭けたのは安全に思えたが、三手後にはそうではないと分かった。晴れた朝にはいつも隠居した年配者たちがこうした街角の対局で埋まっており、長年の経験のぶん、傍目に見えるより勝敗はずっと読みにくい。",
    [0, 1, 2, 3, 4, 5, 6, 7],
  ),
  ev(
    "changying-qunyan", "gain", ["db"], "🎬", 240,
    "A day as a film-set extra|Un día como extra en un rodaje|Une journée comme figurant sur un tournage|撮影所のエキストラを一日務める",
    "The old film studio still shoots period dramas on its back lots, and a call for background extras willing to stand in a crowd scene for a full day paid a flat fee plus a boxed lunch between takes. The studio has been turning out films since before the country's other big production centres existed, and locals treat a day of extra work as a minor family tradition.|El viejo estudio cinematográfico aún rueda dramas de época en sus platós exteriores, y una convocatoria de extras dispuestos a hacer bulto en una escena de multitud durante un día entero pagó una tarifa fija más un almuerzo entre tomas. El estudio lleva rodando películas desde antes de que existieran los otros grandes centros de producción del país.|Le vieux studio de cinéma tourne encore des drames d'époque sur ses terrains extérieurs, et un appel à figurants prêts à faire nombre dans une scène de foule toute une journée a payé un forfait plus un panier-repas entre les prises. Le studio produit des films depuis avant même que les autres grands centres de production du pays n'existent.|古い撮影所ではいまも時代劇の外ロケが行われており、丸一日群衆シーンに立つエキストラの募集は、定額の給金と撮影の合間の弁当付きだった。この撮影所は、国内の他の大きな製作拠点ができるよりも前から映画を作り続けており、地元では一日エキストラをすることがちょっとした家族の恒例行事になっている。",
  ),

  // ---- hd 華東 ----
  ev(
    "sushui-shuangmian", "gain", ["hd"], "🧵", 230,
    "Threading needles for a double-sided embroidery|Enhebrando agujas para un bordado a doble cara|Enfiler des aiguilles pour une broderie double face|双面刺繍の針に絹糸を通す",
    "A double-sided embroidery workshop was behind on a commission and paid by the hour for someone patient enough to thread needles with silk split into strands finer than human hair. The finished piece would show a different image on each face of the same sheer silk, a technique the city's embroiderers have specialised in for centuries.|Un taller de bordado a doble cara iba retrasado en un encargo y pagó por hora a alguien lo bastante paciente para enhebrar agujas con seda dividida en hebras más finas que un cabello humano. La pieza terminada mostraría una imagen distinta en cada cara de la misma seda transparente, una técnica en la que los bordadores de la ciudad se han especializado durante siglos.|Un atelier de broderie double face avait pris du retard sur une commande et payait à l'heure quiconque assez patient pour enfiler des aiguilles avec de la soie fendue en brins plus fins qu'un cheveu humain. La pièce finie montrerait une image différente sur chaque face du même voile de soie, une technique dans laquelle les brodeuses de la ville se spécialisent depuis des siècles.|双面刺繍の工房が納期に追われており、人の髪よりも細く裂いた絹糸を針に通せる根気のある人を時給で募集していた。仕上がった品は、同じ薄絹の両面にそれぞれ違う絵柄が浮かぶという、この街の刺繍職人が何世紀も磨いてきた技法によるものだった。",
  ),
  ev(
    "xihu-jiacha", "loss", ["hd"], "🍵", 210,
    "Overpaying for tea sold as lakeside-picked|Pagando de más por un té vendido como recién recogido junto al lago|Payer trop cher un thé vendu comme cueilli au bord du lac|湖畔摘みと称する茶に払いすぎる",
    "A vendor by the lake swore the tin of green tea was picked from the terraces just up the hill, and only back at the hotel did the price per gram work out to roughly ten times what the same terraces charge at their own gate. West Lake's lakeside stalls see enough of this that guidebooks now warn visitors to buy tea only from a shop with a fixed, posted price.|Un vendedor junto al lago juró que la lata de té verde se había recogido en las terrazas justo cuesta arriba, y solo de vuelta en el hotel el precio por gramo resultó ser unas diez veces lo que cobran esas mismas terrazas en su propia puerta. Los puestos junto al Lago del Oeste ven tanto de esto que las guías ahora avisan de comprar té solo en tiendas con precio fijo y visible.|Un vendeur au bord du lac jurait que la boîte de thé vert venait des terrasses juste en amont, et ce n'est qu'à l'hôtel que le prix au gramme s'est révélé environ dix fois supérieur à celui pratiqué par ces mêmes terrasses à leur propre porte. Les étals du bord du lac de l'Ouest en voient tant que les guides recommandent désormais de n'acheter du thé qu'à prix fixe affiché.|湖畔の売り子は、この緑茶の缶はすぐ裏山の段々畑で摘んだものだと言い張ったが、宿に戻ってグラム単価を計算してみると、その同じ段々畑が自分の店先で付ける値段のおよそ十倍だった。西湖の湖畔の露店ではこうした話があまりに多く、ガイドブックはいまや、値札が固定された店でしか茶を買わないようにと注意を促している。",
  ),
  ev(
    "pijiujie-banyun", "gain", ["hd"], "🍺", 240,
    "Rolling kegs for the beer festival|Rodando barriles para el festival de la cerveza|Rouler des fûts pour le festival de la bière|ビール祭りで樽を転がす",
    "The beer festival's tent city needed extra hands rolling kegs off delivery trucks before the gates opened for the evening crowd, heavy work rewarded with a flat rate and a mug that never quite ran dry that shift. The brewery tracing back to the city's period as a German concession still supplies a fair share of what gets poured under those tents.|La ciudad de carpas del festival de la cerveza necesitaba manos extra para bajar barriles de los camiones de reparto antes de que abrieran las puertas al público de la tarde, trabajo pesado recompensado con una tarifa fija y una jarra que esa jornada nunca se quedaba del todo vacía. La cervecera que se remonta a la época en que la ciudad fue concesión alemana sigue sirviendo buena parte de lo que se sirve bajo esas carpas.|La ville de tentes du festival de la bière avait besoin de bras pour décharger des fûts des camions de livraison avant l'ouverture des portes à la foule du soir, un travail lourd récompensé par un forfait et une chope qui, ce jour-là, ne restait jamais bien longtemps vide. La brasserie remontant à l'époque où la ville fut concession allemande fournit encore une bonne part de ce qui se verse sous ces tentes.|ビール祭りのテント村では、夕方の客を迎える開場前にトラックから樽を転がして下ろす人手を求めていた。重労働だったが定額の報酬に加え、その日はジョッキが空になりきることがなかった。テントの下で注がれるビールの少なからぬ分は、この街がドイツの租借地だった時代にさかのぼる醸造所からいまも供給されている。",
    [4, 5],
  ),
  ev(
    "kongmiao-xianggun", "loss", ["hd"], "🕯️", 190,
    "Overpaying a tout for temple incense|Pagando de más a un vendedor insistente por incienso del templo|Payer trop cher de l'encens à un rabatteur devant le temple|廟の門前で線香に払いすぎる",
    "A tout at the temple gate insisted the ordinary incense sold inside wouldn't carry a wish as far as the bundle wrapped in red paper he happened to be holding, and it was only past the gate that a posted price list showed the plain bundles cost a fraction of what he'd charged. The temple complex has drawn pilgrims to honour the philosopher for roughly two and a half thousand years, more than enough time for a side trade in overpriced incense to take root.|Un vendedor insistente en la puerta del templo aseguró que el incienso corriente vendido dentro no llevaría un deseo tan lejos como el manojo envuelto en papel rojo que él tenía a mano, y solo pasada la puerta una lista de precios reveló que los manojos comunes costaban una fracción de lo cobrado. El complejo del templo lleva atrayendo peregrinos que honran al filósofo desde hace unos dos mil quinientos años.|Un rabatteur devant le portail du temple assurait que l'encens ordinaire vendu à l'intérieur ne porterait pas un vœu aussi loin que le paquet enveloppé de papier rouge qu'il tenait justement à la main, et ce n'est qu'après le portail qu'une liste de prix affichée a révélé que les paquets ordinaires coûtaient une fraction de ce qu'il avait facturé. Le complexe attire des pèlerins venus honorer le philosophe depuis environ deux mille cinq cents ans.|廟の門前の客引きは、中で売っている普通の線香では願いはそこまで届かない、自分が手にしている赤紙包みのものでなければと言い張ったが、門をくぐった先に貼られた価格表を見ると、普通の束はその言い値のごくわずかな金額でしかなかった。この廟は、この哲学者を敬う参拝客をおよそ二千五百年にわたって集め続けており、割高な線香を売る商いが根付くには十分すぎる時間である。",
    [5],
  ),

  // ---- hn 華南 ----
  ev(
    "huashi-banyun", "gain", ["hn"], "🌺", 230,
    "Hauling blossoms for the pre-New Year flower market|Cargando flores para el mercado previo al año nuevo|Décharger des fleurs pour le marché d'avant nouvel an|迎春花市の花を運び込む",
    "Stallholders setting up for the pre-New Year flower market paid by the hour for someone to help haul kumquat trees and gladiolus bundles off delivery trucks before dawn, the whole street turning into a corridor of blossoms that would sell out completely by the last night. Every district holds its own version of this market, and buying nothing at all on the final evening is considered bad luck going into the new year.|Los feriantes que montaban el mercado de flores previo al año nuevo pagaron por hora a alguien que ayudara a bajar de los camiones kumquats en maceta y ramos de gladiolo antes del alba, mientras la calle entera se convertía en un pasillo de flores que se agotaría por completo la última noche. Cada distrito celebra su propia versión de este mercado, y no comprar nada la última noche se considera mala suerte para el año que empieza.|Les forains montant le marché aux fleurs d'avant nouvel an payaient à l'heure quiconque aidait à décharger des kumquats en pot et des bottes de glaïeuls avant l'aube, la rue entière se transformant en un couloir de fleurs qui serait entièrement vendu le dernier soir. Chaque quartier tient sa propre version de ce marché, et n'y rien acheter le dernier soir passe pour un mauvais présage pour l'année qui vient.|旧正月前の迎春花市を設営する露店主たちが、夜明け前にトラックから金柑の鉢植えやグラジオラスの束を運び下ろす手伝いを時給で募集していた。通り全体が花の回廊と化し、最後の夜には売り切れてしまう。どの区にもそれぞれの花市があり、大晦日の夜に何も買わずに終えるのは新年に向けて縁起が悪いとされている。",
    [9, 10],
  ),
  ev(
    "huaqiangbei-shouji", "loss", ["hn"], "📱", 200,
    "Overpaying at the electronics wholesale market|Pagando de más en el mercado mayorista de electrónica|Payer trop cher au marché de gros de l'électronique|電子部品市場で携帯ケースに払いすぎる",
    "A stall in the electronics market quoted a price for a phone case that seemed reasonable until a friend pointed out the same case one floor up for less than half as much, in a building where entire wholesale floors specialise in nothing but accessories. The market grew up to supply the factories nearby and still prices everything for buyers ordering by the thousand, not the one.|Un puesto del mercado de electrónica cotizó un precio por una funda de móvil que pareció razonable hasta que un amigo señaló la misma funda un piso más arriba por menos de la mitad, en un edificio donde pisos enteros al por mayor se especializan solo en accesorios. El mercado creció para abastecer a las fábricas cercanas y sigue fijando precios para compradores que piden por miles, no de uno en uno.|Un stand du marché de l'électronique a annoncé un prix pour une coque de téléphone qui semblait raisonnable jusqu'à ce qu'un ami la repère un étage plus haut à moins de la moitié, dans un immeuble où des étages entiers en gros ne vendent que des accessoires. Le marché s'est développé pour approvisionner les usines voisines et fixe encore ses prix pour des acheteurs commandant par milliers, pas à l'unité.|電子部品市場のある露店が提示した携帯ケースの値段は妥当に思えたが、一階上に半額以下で同じケースがあると友人に指摘された。その建物では、フロアまるごとアクセサリーの卸専門になっている。この市場は近隣の工場に部品を供給するために育った場所で、いまも値付けは一個単位ではなく千個単位の買い手を基準にしている。",
  ),

  // ---- xn 西南 ----
  ev(
    "xiongmao-jidi", "gain", ["xn"], "🐼", 250,
    "Chopping bamboo at the panda breeding centre|Cortando bambú en el centro de cría de pandas|Couper du bambou au centre d'élevage de pandas|パンダ繁殖センターで竹を刻む",
    "The breeding centre needed extra hands chopping bamboo into short lengths and hosing down enclosures before the morning gates opened to visitors, work that came with a strict rule against approaching any panda without a keeper present. Cubs born at the centre are weighed daily for their first weeks, a routine detailed enough that keepers can spot a problem from a few grams' difference.|El centro de cría necesitaba manos extra para cortar bambú en trozos cortos y lavar con manguera los recintos antes de que abrieran las puertas a los visitantes por la mañana, un trabajo con la regla estricta de no acercarse a ningún panda sin un cuidador presente. Las crías nacidas en el centro se pesan a diario durante sus primeras semanas.|Le centre d'élevage avait besoin de bras pour couper du bambou en tronçons et nettoyer les enclos au jet avant l'ouverture des portes aux visiteurs le matin, un travail assorti d'une règle stricte interdisant d'approcher un panda sans la présence d'un soigneur. Les petits nés au centre sont pesés chaque jour durant leurs premières semaines.|繁殖センターが、朝の開場前に竹を短く切って囲いをホースで洗い流す人手を求めていた。ただし飼育員が同席しない限りパンダに近づいてはならないという厳格な決まりがあった。ここで生まれた子パンダは最初の数週間、毎日体重を量られる。数グラムの差から異変を見抜けるほど徹底した習わしである。",
  ),
  ev(
    "qingguidao-cuoche", "loss", ["xn"], "🚇", 190,
    "A wrong transfer in the stacked mountain city|Un transbordo equivocado en la ciudad de montaña apilada|Une mauvaise correspondance dans la ville-montagne empilée|山城の軽軌で乗り換えを間違える",
    "The map showed the monorail line running straight through, but this city stacks its streets on top of each other across a dozen levels, and the platform that looked like the right one led to a transfer requiring a fresh ticket back the way already come from. Even residents joke that giving directions here means specifying which floor of the mountain you mean.|El mapa mostraba la línea del monorriel corriendo en línea recta, pero esta ciudad apila sus calles unas sobre otras en una docena de niveles, y el andén que parecía el correcto llevaba a un transbordo que exigía un billete nuevo de vuelta por donde ya se había venido. Hasta los vecinos bromean con que dar direcciones aquí significa precisar a qué piso de la montaña te refieres.|Le plan montrait la ligne du monorail filant tout droit, mais cette ville empile ses rues les unes sur les autres sur une douzaine de niveaux, et le quai qui semblait le bon menait à une correspondance exigeant un nouveau billet pour refaire le chemin déjà parcouru. Même les habitants plaisantent qu'indiquer un chemin ici oblige à préciser quel étage de la montagne on veut dire.|地図では軽軌の路線はまっすぐ通っているはずだったが、この街は通りを十数層にも重ねて積み上げており、正しく見えたホームは結局、来た道をまた新しい切符で戻る乗り換えにしかつながっていなかった。住民でさえ、この街で道を教えるには山の何階を指すか言わねばならないと冗談を言う。",
  ),
  ev(
    "bakuo-jiedian", "gain", ["xn"], "📿", 260,
    "Restringing beads for a shop on the pilgrim circuit|Reensartando cuentas para una tienda del circuito de peregrinos|Renfiler des perles pour une boutique du circuit de pèlerinage|巡礼路の店で数珠を通し直す",
    "A shopkeeper along the pilgrim circuit around the old temple needed a hand restringing turquoise beads and refolding prayer flags before the morning's first circuit of walkers came past, paid at the day's end in cash counted twice. The circuit has been walked clockwise by pilgrims for over a thousand years, and the shops lining it have adjusted their hours to that rhythm rather than the other way around.|Un tendero a lo largo del circuito de peregrinos que rodea el antiguo templo necesitaba una mano para reensartar cuentas de turquesa y replegar banderas de oración antes de que pasara la primera ronda de caminantes de la mañana, pagado al final del día en efectivo contado dos veces. El circuito lleva más de mil años recorriéndose en sentido horario por los peregrinos.|Un commerçant le long du circuit de pèlerinage entourant l'ancien temple avait besoin d'un coup de main pour renfiler des perles de turquoise et replier des drapeaux de prière avant le passage de la première ronde de marcheurs du matin, payé en fin de journée en espèces comptées deux fois. Le circuit est parcouru dans le sens horaire par les pèlerins depuis plus de mille ans.|古い寺院を囲む巡礼路沿いの店主が、朝いちばんの巡礼者の列が通り過ぎる前に、トルコ石の数珠を通し直し、タルチョーを畳み直す手を求めていた。支払いは一日の終わりに、二度数え直した現金で渡された。この巡礼路は千年以上にわたり時計回りに歩かれ続けており、沿道の店々はその歩みのほうに合わせて開く時間を決めてきた。",
  ),

  // ---- xb 西北 ----
  ev(
    "huiminjie-mianshi", "gain", ["xb"], "🍜", 220,
    "Stretching noodles before the dinner rush|Estirando fideos antes de la hora punta de la cena|Étirer des nouilles avant le coup de feu du dîner|夕食どき前に麺を延ばす",
    "A noodle stall in the old quarter needed a hand pounding dough flat and slapping it against the counter to stretch it into the wide, belt-like noodles the shop is known for, timed to be ready exactly as the dinner crowd started arriving. The quarter has fed travellers passing through on the trade routes east and west for over a thousand years, long before this particular noodle style had a name.|Un puesto de fideos del barrio antiguo necesitaba una mano para aplanar la masa y golpearla contra el mostrador hasta estirarla en los fideos anchos, como cinturones, por los que es conocido el local, listo justo cuando empezaba a llegar la clientela de la cena. El barrio lleva más de mil años dando de comer a viajeros de las rutas comerciales de oriente y occidente.|Un stand de nouilles du vieux quartier avait besoin d'un coup de main pour aplatir la pâte et la claquer sur le comptoir afin de l'étirer en ces larges nouilles façon ceinture pour lesquelles l'échoppe est connue, prêtes pile à l'arrivée de la clientèle du dîner. Le quartier nourrit les voyageurs des routes commerciales d'orient et d'occident depuis plus de mille ans.|旧市街の麺屋が、生地を平たく延ばし、台に叩きつけてはあの店名物の帯のように幅広い麺に伸ばす手を求めていた。ちょうど夕食どきの客が来始める頃に仕上がるよう間に合わせる仕事だった。この一角は、この麺の型に名前が付くよりずっと前から、千年以上にわたり東西の交易路を行く旅人に食事を出し続けてきた。",
  ),
  ev(
    "lanzhou-lamian-wuche", "loss", ["xb"], "🍜", 170,
    "A noodle-broth debate that runs past the last bus|Una discusión sobre el caldo de fideos que dura hasta perder el último autobús|Un débat sur le bouillon des nouilles qui fait rater le dernier car|麺のスープ談義で終バスを逃す",
    "The debate over whether the broth needed another few minutes of simmering ran long enough at a favourite noodle stand near the river that the last long-distance bus of the night pulled out from the station a few streets over, unreachable in time. A replacement ticket for the morning bus, plus a room for the night, cost far more than the bowl of noodles that started the argument.|La discusión sobre si el caldo necesitaba unos minutos más de cocción se alargó tanto en un puesto de fideos favorito cerca del río que el último autobús de largo recorrido de la noche salió de la estación, a pocas calles, sin que hubiera tiempo de alcanzarlo. Un billete de repuesto para el autobús de la mañana, más una habitación para pasar la noche, costaron mucho más que el tazón de fideos que inició la discusión.|Le débat sur la nécessité de laisser mijoter le bouillon quelques minutes de plus s'est éternisé dans une échoppe de nouilles réputée près du fleuve, si bien que le dernier car longue distance de la nuit a quitté la gare, à quelques rues de là, sans qu'il soit possible de le rattraper à temps. Un billet de remplacement pour le car du matin, plus une chambre pour la nuit, ont coûté bien plus cher que le bol de nouilles à l'origine de la dispute.|川の近くの評判の麺屋で、スープをあと数分煮込むべきかどうかの言い合いが長引き、数本先の通りにある発着所からその夜最後の長距離バスが、間に合わないまま出てしまった。言い争いのきっかけになった一杯の麺よりも、翌朝便の乗り継ぎ切符と一晩の宿代のほうがずっと高くついた。",
  ),
  ev(
    "mingshashan-luotuo", "gain", ["xb"], "🐫", 240,
    "Leading camels back down after the sunset dune tour|Guiando camellos de vuelta tras el paseo por las dunas al atardecer|Ramener les chameaux après la balade au coucher du soleil sur les dunes|夕暮れの砂丘見学の後、駱駝を連れ帰る",
    "The camel caravans that carry visitors up the dunes at sunset need an extra hand leading the animals back down single file once the light fades and the tourists have gone, work best suited to someone unbothered by sand in every boot seam by the end of the walk. The dunes here are said to sing under the right wind, a sound old enough that travellers on the trade routes wrote about it centuries before any camel wore a saddle for sightseers.|Las caravanas de camellos que llevan a los visitantes a las dunas al atardecer necesitan una mano extra para guiar a los animales de vuelta en fila india una vez que la luz se apaga y los turistas se han ido, trabajo apto para quien no le importe llevar arena en cada costura de la bota al final del paseo. Se dice que estas dunas cantan con el viento adecuado, un sonido tan antiguo que los viajeros de las rutas comerciales ya escribían sobre él siglos antes de que un camello llevara silla para turistas.|Les caravanes de chameaux qui mènent les visiteurs sur les dunes au coucher du soleil ont besoin d'un renfort pour ramener les bêtes en file indienne une fois la lumière tombée et les touristes partis, un travail qui convient surtout à qui ne craint pas d'avoir du sable dans chaque couture de botte à la fin de la marche. Ces dunes sont réputées chanter sous le bon vent, un son assez ancien pour que des voyageurs des routes commerciales en aient déjà parlé des siècles avant qu'un chameau ne porte une selle pour touristes.|夕暮れに観光客を丘の上まで運ぶラクダの隊商には、日が沈んで客がいなくなったあと、動物たちを一列に並べて下まで連れ帰る助っ人が要る。歩き終える頃にはブーツの縫い目という縫い目に砂が入り込んでも気にならない人向きの仕事だった。この砂丘は風向きが合えば鳴るといわれ、旅人の乗せる鞍がラクダの背に載るよりずっと前から、交易路を行く者たちがその音について書き残しているほど古い言い伝えである。",
    [0, 1, 6, 7],
  ),
];
