/**
 * ガーナの青マス・赤マスで起きる出来事(22件。増14・減8)。
 *
 * 地方コード: gar=大アクラ / cen=中部・海岸 / asa=アシャンティ / vol=ヴォルタ /
 * nor=北部 / wes=西部
 *
 * 地方も月も指定しない出来事を4件(増2・減2)置いてあるので、
 * どの地方でも必ず1件は引ける(他の盤面と同じ約束)。
 * そのうえで6地方それぞれに3件(増2・減1)を、その土地らしい仕事や
 * 出費に結びつけて置いている。**地方ごとの `gains`/`losses` は、
 * その地方の出来事だけで増・減の両方が引けることを個別に確認済み**
 * (全国共通の4件に頼らなくても成り立つ)。
 */
function t(source) {
  const parts = source.split("|");
  if (parts.length !== 4) {
    throw new Error(`4言語(en|es|fr|ja)で書いてください: ${source.slice(0, 60)}…`);
  }
  const [en, es, fr, ja] = parts;
  return { en, es, fr, ja };
}

/**
 * 出来事1件。`months` を指定すると、その月にしか起こらない
 * (0=4月。9月=5、10月=6、11月=7、12月=8、1月=9、2月=10、3月=11)。
 * 省略すれば通年。
 */
function ev(id, kind, regs, emoji, amount, title, narrative, months = []) {
  return { id, kind, regs, e: emoji, amount, n: t(title), t: t(narrative), months };
}

export const GHANA_MONEY_EVENTS = [
  // ---- 全国どこでも・通年(どの地方でも必ず引けるようにするための4件) ----
  ev(
    "street-vendor-help", "gain", [], "💧", 220,
    "Helping a hawker sell through traffic|Ayudando a un vendedor a vender entre el tráfico|Aider un vendeur ambulant dans les embouteillages|渋滞の中で行商を手伝う",
    "A hawker balancing a tray of sachet water and ice cream through stalled traffic needed an extra pair of hands during the afternoon rush, and splitting the takings at the next junction paid better than the wait itself cost. Traffic hawkers work window to window at literally every red light in Ghana's biggest cities.|Un vendedor que llevaba una bandeja de agua en bolsitas y helado entre el tráfico detenido necesitaba una mano extra en la hora punta de la tarde, y repartir lo recaudado en el siguiente cruce pagó mejor de lo que costó la espera. Los vendedores ambulantes de tráfico trabajan de ventanilla en ventanilla en todos los semáforos de las grandes ciudades de Ghana.|Un vendeur ambulant portant un plateau de sachets d'eau et de glaces entre les voitures à l'arrêt avait besoin d'un coup de main pendant l'heure de pointe de l'après-midi, et partager la recette au carrefour suivant a rapporté plus que l'attente n'a coûté. Les vendeurs de rue travaillent vitre après vitre à absolument chaque feu rouge des grandes villes du Ghana.|渋滞の中を小袋入りの飲み水とアイスクリームの盆を抱えて歩く行商人が、夕方のラッシュで手を求めていた。次の交差点で稼ぎを分けてもらうと、待ち時間そのものより実入りが良かった。渋滞行商人はガーナの大都市の文字どおりあらゆる赤信号で、車の窓から窓へと働いている。",
  ),
  ev(
    "funeral-band-gig", "gain", [], "🎺", 240,
    "Filling in for a funeral brass band|Sustituyendo en una banda de metales de un funeral|Remplacer dans une fanfare pour un enterrement|葬儀のブラスバンドで代役を務める",
    "A funeral brass band short a trumpet player for a Saturday service paid session rates for the afternoon, on the condition of learning the specific hymn the family had requested by ear before the procession began. Ghanaian funerals are major social and financial events, often planned for months and drawing crowds that rival weddings.|Una banda de metales de un funeral, con falta de un trompetista para el servicio del sábado, pagó tarifas de sesión por la tarde, con la condición de aprender de oído el himno concreto que había pedido la familia antes de que empezara la procesión. Los funerales ghaneses son grandes eventos sociales y económicos, a menudo planeados durante meses y con multitudes que rivalizan con las de una boda.|Une fanfare d'enterrement à qui il manquait un trompettiste pour la cérémonie du samedi a payé des cachets de session pour l'après-midi, à condition d'apprendre à l'oreille l'hymne précis demandé par la famille avant le début du cortège. Les funérailles ghanéennes sont de grands événements sociaux et financiers, souvent préparés pendant des mois et rassemblant des foules qui rivalisent avec celles d'un mariage.|土曜の葬儀でトランペット奏者が足りなかったブラスバンドは、行列が始まる前に遺族が望んだ賛美歌を耳で覚えることを条件に、その午後のセッション料を払った。ガーナの葬儀は大きな社会的・経済的行事で、何か月も前から計画され、結婚式に匹敵する人出を集めることも多い。",
  ),
  ev(
    "checkpoint-fine", "loss", [], "🚔", 180,
    "A roadworthiness sticker a month out of date|Una pegatina de inspección técnica caducada hace un mes|Un macaron de contrôle technique périmé d'un mois|1か月切れていた車検ステッカー",
    "A routine police checkpoint found the vehicle's roadworthiness sticker a month out of date, and the on-the-spot fine was cheaper than the afternoon it would have cost to sort out at the licensing office. Checkpoints like this one are common on Ghana's main highways, checking documents as much as speed.|Un control policial rutinario descubrió que la pegatina de inspección técnica del vehículo llevaba un mes caducada, y la multa en el acto salió más barata que la tarde que habría costado arreglarlo en la oficina de licencias. Controles como este son comunes en las principales carreteras de Ghana, y revisan tanto documentos como velocidad.|Un contrôle de police de routine a révélé que le macaron de contrôle technique du véhicule était périmé d'un mois, et l'amende sur place est revenue moins cher que l'après-midi qu'aurait coûté une régularisation au bureau des permis. Ce genre de contrôle est courant sur les grands axes du Ghana, vérifiant autant les papiers que la vitesse.|検問での日常的な取り締まりで車検ステッカーが1か月切れているのが見つかったが、その場での罰金は、免許事務所で手続きし直すのにかかる午後半日よりは安く済んだ。こうした検問はガーナの主要幹線道路でよくあり、速度だけでなく書類も調べられる。",
  ),
  ev(
    "market-overcharge", "loss", [], "🛍️", 160,
    "Paying the visitor's price at the market|Pagando el precio de forastero en el mercado|Payer le prix du visiteur au marché|市場でよそ者料金を払わされる",
    "Not knowing the going rate, and not haggling hard enough once it became obvious, ended in paying well above the price every stallholder nearby was quietly getting from everyone else. Bargaining is expected at almost every market stall in the country, and a fixed sticker price is the exception rather than the rule.|No conocer el precio habitual, y no regatear lo suficiente cuando se hizo evidente, acabó en pagar bastante más de lo que cada tendero cercano cobraba discretamente a todos los demás. En casi todos los puestos de mercado del país se espera que se regatee, y un precio fijo es la excepción y no la norma.|Ne pas connaître le tarif habituel, et ne pas marchander assez fort une fois la chose devenue évidente, a fini par payer bien plus que ce que chaque commerçant du coin faisait discrètement payer à tout le monde. Le marchandage est attendu à presque tous les étals du pays, un prix fixe affiché étant l'exception plutôt que la règle.|相場を知らず、それが明らかになってからも強く値切らなかったせいで、近くのどの店も他の客からは静かに取っていた額よりずっと高く払う羽目になった。この国のほとんどの市場の露店では値切ることが当たり前で、値札どおりの固定価格のほうがむしろ例外である。",
  ),

  // ---- gar 大アクラ ----
  ev(
    "dock-casual-labour", "gain", ["gar"], "🚢", 260,
    "A day of casual work at Tema's docks|Un día de trabajo eventual en los muelles de Tema|Une journée de travail occasionnel sur les quais de Tema|テマの波止場で日雇い仕事",
    "Tema's port needed extra hands for a single afternoon unloading a delayed container ship, and casual dock work like this pays by the shift rather than by contract, cash at the gate when the whistle blows. The port handles the large majority of everything the country imports and exports by sea.|El puerto de Tema necesitaba manos extra durante una sola tarde para descargar un buque portacontenedores retrasado, y este tipo de trabajo portuario eventual se paga por turno, en efectivo en la puerta cuando suena el silbato. El puerto gestiona la gran mayoría de todo lo que el país importa y exporta por mar.|Le port de Tema avait besoin de bras en plus pour une seule après-midi afin de décharger un porte-conteneurs en retard, et ce genre de travail portuaire occasionnel se paie à la vacation, en liquide au portail au coup de sifflet. Le port gère la grande majorité de tout ce que le pays importe et exporte par mer.|テマ港が、遅れて到着したコンテナ船の荷下ろしにたった一日だけ余分な人手を求めていた。こうした波止場の日雇い仕事は契約ではなく一勤務ごとに払われ、汽笛が鳴ると門で現金を受け取る。この港は、この国が海路で輸出入するもののほとんどを扱っている。",
  ),
  ev(
    "beach-bar-shift", "gain", ["gar"], "🍹", 230,
    "Covering a Sunday shift at a beach bar|Cubriendo un turno de domingo en un bar de playa|Assurer un service du dimanche dans un bar de plage|日曜のビーチバーで店番を代わる",
    "A beach bar along Labadi's stretch of sand was short-staffed for a busy Sunday afternoon, and carrying trays of grilled tilapia and cold drinks between sunbathers all day paid out in tips as much as in wages. Accra's beaches fill up fastest on Sundays, once church lets out.|Un bar de playa en el tramo de arena de Labadi tenía poco personal para una tarde de domingo muy concurrida, y llevar bandejas de tilapia asada y bebidas frías entre los bañistas todo el día pagó tanto en propinas como en salario. Las playas de Acra se llenan más rápido los domingos, cuando termina la misa.|Un bar de plage sur la bande de sable de Labadi manquait de personnel pour un dimanche après-midi très fréquenté, et porter toute la journée des plateaux de tilapia grillé et de boissons fraîches entre les baigneurs a rapporté autant en pourboires qu'en salaire. Les plages d'Accra se remplissent le plus vite le dimanche, une fois la messe terminée.|ラバディの浜辺のビーチバーは日曜の忙しい午後に人手が足りず、一日中、日光浴客のあいだを焼きティラピアと冷たい飲み物の盆を運んで回ると、給金と同じくらいチップが入った。アクラのビーチは、教会が終わる日曜にいちばん早く人で埋まる。",
  ),
  ev(
    "ring-road-jam", "loss", ["gar"], "🚗", 210,
    "Stuck on the Ring Road at rush hour|Atascado en la Ring Road en hora punta|Coincé sur la Ring Road à l'heure de pointe|ラッシュ時のリングロードで立ち往生",
    "What should have been a twenty-minute drive across town turned into two hours stuck on the Ring Road at rush hour, and the meeting it made late cost more than the fuel burned idling in place. Accra's traffic is dense enough that many residents now simply build the jam into how early they leave.|Lo que debería haber sido un trayecto de veinte minutos por la ciudad se convirtió en dos horas atascado en la Ring Road en hora punta, y la reunión a la que se llegó tarde costó más que el combustible quemado parado. El tráfico de Acra es tan denso que muchos residentes ya calculan el atasco al decidir a qué hora salir.|Ce qui aurait dû être un trajet de vingt minutes à travers la ville s'est transformé en deux heures coincé sur la Ring Road à l'heure de pointe, et la réunion manquée a coûté plus cher que le carburant brûlé à l'arrêt. La circulation d'Accra est si dense que beaucoup d'habitants intègrent désormais l'embouteillage dans l'heure à laquelle ils partent.|町を横切るだけなら20分のはずだった移動が、ラッシュ時のリングロードで2時間の立ち往生に変わり、遅刻した打ち合わせの損失はアイドリングで焼いた燃料代を上回った。アクラの渋滞はあまりに濃く、多くの住民はいまや渋滞を織り込んで出発時刻を早めている。",
  ),

  // ---- cen 中部・海岸 ----
  ev(
    "big-catch-share", "gain", ["cen"], "🐟", 250,
    "A share of an unusually big catch|Una parte de una pesca inusualmente grande|Une part d'une prise inhabituellement grosse|思いがけない大漁の分け前",
    "A canoe crew short a hand for the day offered a share of the catch instead of a wage, and the net came back heavier than usual with a school of anchovies that filled every basket on the beach. Fresh fish sold straight off the sand, before it ever reaches a market stall, usually goes for the best price of the day.|Una tripulación de canoa, con falta de una mano para el día, ofreció una parte de la pesca en lugar de un salario, y la red volvió más cargada de lo habitual, con un banco de anchoas que llenó todas las cestas de la playa. El pescado fresco vendido directamente en la arena suele alcanzar el mejor precio del día.|Un équipage de pirogue à qui il manquait une paire de bras pour la journée a proposé une part de la prise plutôt qu'un salaire, et le filet est revenu plus lourd que d'habitude, avec un banc d'anchois remplissant tous les paniers de la plage. Le poisson frais vendu directement sur le sable, avant d'atteindre un étal de marché, obtient généralement le meilleur prix de la journée.|カヌーの乗組が一日分の人手を求めていて、賃金の代わりに漁の分け前を申し出た。網はいつもより重く戻り、カタクチイワシの群れが浜のすべての籠を満たした。市場に並ぶ前に砂浜で直接売られる新鮮な魚は、たいていその日いちばんの値がつく。",
  ),
  ev(
    "festival-guide-tip", "gain", ["cen"], "🦌", 240,
    "Explaining the Aboakyer hunt to visitors|Explicando la cacería del Aboakyer a los visitantes|Expliquer la chasse de l'Aboakyer à des visiteurs|訪れた人々にアボアキェル猟を説明する",
    "A group of visitors following the Aboakyer festival's crowds needed someone who could explain what the two rival asafo companies were actually racing to do, and a clear answer, given in plain English on the spot, earned a tip larger than the whole morning's other work. Winneba's festival draws visitors from well beyond the region every May.|Un grupo de visitantes que seguía a la multitud del festival Aboakyer necesitaba a alguien que explicara qué estaban compitiendo realmente por hacer las dos compañías asafo rivales, y una respuesta clara, dada en inglés sencillo al momento, ganó una propina mayor que todo el resto del trabajo de la mañana. El festival de Winneba atrae cada mayo a visitantes de mucho más allá de la región.|Un groupe de visiteurs suivant la foule du festival Aboakyer avait besoin de quelqu'un capable d'expliquer ce que les deux compagnies asafo rivales cherchaient réellement à accomplir, et une réponse claire, donnée sur-le-champ en anglais simple, a rapporté un pourboire plus gros que tout le reste du travail de la matinée. Le festival de Winneba attire chaque mai des visiteurs venus de bien au-delà de la région.|アボアキェル祭の人混みについて来ていた一団の観光客が、二つの敵対するアサフォ団が実際に何を競っているのか説明できる人を求めていた。その場で分かりやすい英語で答えると、その朝の他の仕事すべてより大きなチップになった。ウィネバの祭りは毎年5月、地方の外からも大勢の観光客を集める。",
  ),
  ev(
    "net-torn-rocks", "loss", ["cen"], "🕸️", 190,
    "A fishing net torn on the rocks|Una red de pesca desgarrada en las rocas|Un filet de pêche déchiré sur les rochers|岩で漁網が裂ける",
    "A fishing net dragged too close to a rocky patch of the coastline came back torn along one whole seam, and the local net-mender's fee for restringing it by hand ate into what the next few days' catch would have earned. Rocky stretches like this one are marked by long memory rather than any buoy or sign.|Una red de pesca arrastrada demasiado cerca de un tramo rocoso de la costa volvió rasgada a lo largo de toda una costura, y la tarifa del remendador local por rehacerla a mano se comió lo que habrían ganado las capturas de los días siguientes. Tramos rocosos como este se recuerdan de memoria, sin boya ni señal alguna.|Un filet de pêche traîné trop près d'un tronçon rocheux du littoral est revenu déchiré sur toute une couture, et le tarif du répareur de filets local pour le retisser à la main a rogné sur ce que les prises des jours suivants auraient rapporté. Des tronçons rocheux comme celui-ci se retiennent par la mémoire, sans bouée ni panneau.|海岸の岩場に近づきすぎて引いた漁網が、縫い目一本まるごと裂けて戻ってきた。地元の網繕い職人に手で編み直してもらう手間賃は、この先数日の漁の稼ぎを食いつぶした。こうした岩場は浮標や標識ではなく、長年の記憶だけで覚えられている。",
  ),

  // ---- asa アシャンティ ----
  ev(
    "kente-rush-order", "gain", ["asa"], "🧵", 260,
    "Extra shifts at the loom for a wedding order|Turnos extra en el telar para un pedido de boda|Vacations supplémentaires au métier à tisser pour une commande de mariage|婚礼の注文で織機の作業を増やす",
    "A wholesale order for a wedding needed more kente strips finished by Friday than the workshop's usual pace allowed, and pulling extra shifts at the loom to hit the deadline paid a bonus on top of the normal piece rate. Weaving families in Bonwire regularly take on outside hands during the wedding and festival season.|Un pedido al por mayor para una boda necesitaba más tiras de kente terminadas para el viernes de lo que permitía el ritmo habitual del taller, y hacer turnos extra en el telar para cumplir el plazo pagó un bono además de la tarifa normal por pieza. Las familias tejedoras de Bonwire suelen contratar manos externas en temporada de bodas y festivales.|Une commande en gros pour un mariage exigeait plus de bandes de kente finies pour vendredi que le rythme habituel de l'atelier ne le permettait, et enchaîner des vacations supplémentaires au métier pour tenir le délai a rapporté une prime en plus du tarif à la pièce habituel. Les familles tisserandes de Bonwire embauchent régulièrement de la main-d'œuvre extérieure en saison de mariages et de festivals.|結婚式向けの卸注文で、金曜までに仕上げるケンテの帯が工房の通常のペースより多く必要になり、締め切りに間に合わせるため織機で余分に作業すると、通常の出来高賃金に加えてボーナスが払われた。ボンウィレの織物一家は結婚式や祭りの季節、外から人手を雇うことがよくある。",
  ),
  ev(
    "kejetia-porter-day", "gain", ["asa"], "🧺", 230,
    "A good day carrying loads at Kejetia|Un buen día cargando bultos en Kejetia|Une bonne journée à porter des charges à Kejetia|ケジェティアで荷を運ぶ実入りの良い一日",
    "Kejetia Market's narrow lanes are too tight for carts, so porters, mostly women known as kayayei, carry loads balanced on the head between stalls and waiting vehicles for a fee agreed before the first step. A particularly heavy, particularly generous customer made for an especially good day.|Los callejones de Kejetia son demasiado estrechos para carretillas, así que las porteadoras, casi siempre mujeres conocidas como kayayei, llevan cargas en equilibrio sobre la cabeza entre puestos y vehículos por una tarifa pactada antes del primer paso. Un cliente especialmente pesado y generoso hizo de ese día uno particularmente bueno.|Les ruelles étroites de Kejetia sont trop exiguës pour les charrettes, aussi les porteuses, surtout des femmes appelées kayayei, transportent-elles les charges en équilibre sur la tête entre les étals et les véhicules qui attendent, pour un tarif convenu avant le premier pas. Un client particulièrement chargé et particulièrement généreux a fait de cette journée une journée à part.|ケジェティア市場の狭い路地は台車が通らないほど細いため、ほとんどが「カヤイェイ」と呼ばれる女性の運び手たちが、最初の一歩を踏み出す前に決めた運賃で、頭に荷を載せて店と待つ車のあいだを運ぶ。とりわけ重く、とりわけ気前のよい客に当たった日は、格別に良い実入りになった。",
  ),
  ev(
    "fake-kente-bought", "loss", ["asa"], "🪡", 170,
    "Machine-printed cloth sold as kente|Tela estampada a máquina vendida como kente|Du tissu imprimé à la machine vendu comme du kente|ケンテとして売られた機械印刷の布",
    "The 'kente' bought cheap from a roadside stand outside town turned out, on a closer look back home, to be machine-printed cotton rather than hand-woven strips, and the price paid was closer to what genuine cloth costs by the metre. Genuine kente is sold by weavers who can usually explain what each pattern in the piece is called.|El «kente» comprado barato en un puesto al borde de la carretera resultó ser, al examinarlo mejor en casa, algodón estampado a máquina y no tiras tejidas a mano, y el precio pagado se acercaba más al del tejido genuino por metro. El kente auténtico lo venden tejedores que suelen poder explicar cómo se llama cada patrón de la pieza.|Le « kente » acheté bon marché à un étal en bordure de ville s'est révélé, en y regardant de plus près à la maison, être du coton imprimé à la machine plutôt que des bandes tissées à la main, et le prix payé se rapprochait de celui du tissu authentique au mètre. Le vrai kente est vendu par des tisserands capables en général d'expliquer le nom de chaque motif de la pièce.|町の外の路傍の露店で安く買った「ケンテ」は、家に帰ってよく見ると手織りの帯ではなく機械印刷の綿布で、払った値段はむしろ本物の布を1メートル買うのに近かった。本物のケンテは、その柄の一つ一つに名前を説明できる織り手から買うのが普通である。",
  ),

  // ---- vol ヴォルタ ----
  ev(
    "waterfall-guide-tip", "gain", ["vol"], "💧", 240,
    "Guiding hikers to the upper falls at Wli|Guiando a excursionistas a la catarata alta de Wli|Guider des randonneurs vers la chute supérieure de Wli|ウリの上段の滝へハイカーを案内する",
    "A group hiking up to Wli Falls needed a guide who knew which fork in the trail led to the upper falls rather than the lower, easier one, and the extra hour spent pointing out fruit bats roosting on the cliff earned a tip on top of the entrance fee split. Wli draws hikers from across the region for exactly that upper-falls view.|Un grupo que subía a la catarata de Wli necesitaba un guía que supiera qué bifurcación del sendero llevaba a la catarata alta en vez de a la baja, más fácil, y la hora extra señalando los murciélagos frugívoros posados en el acantilado ganó una propina además de la parte de la entrada. Wli atrae a excursionistas de toda la región precisamente por esa vista de la catarata alta.|Un groupe montant vers la chute de Wli avait besoin d'un guide sachant quelle bifurcation du sentier menait à la chute supérieure plutôt qu'à la chute inférieure, plus facile, et l'heure supplémentaire passée à montrer les roussettes nichant sur la falaise a rapporté un pourboire en plus de la part du droit d'entrée. Wli attire des randonneurs de toute la région justement pour cette vue de la chute supérieure.|ウリの滝へ登る一行が、易しい下段ではなく上段の滝へ通じる分岐を知るガイドを求めていた。崖に棲むオオコウモリを指し示しながら余分に過ごした1時間は、入場料の取り分に加えてチップを稼いだ。ウリの滝はまさにその上段の眺めを目当てに、地方じゅうからハイカーを集めている。",
  ),
  ev(
    "lake-cargo-load", "gain", ["vol"], "🛶", 230,
    "Loading a cargo canoe bound for Yeji|Cargando una canoa de carga rumbo a Yeji|Charger une pirogue de fret en partance pour Yeji|イェジ行きの荷カヌーの積み込み",
    "A cargo canoe heading up Lake Volta toward Yeji needed extra hands to load sacks of maize before the crossing, paid by the sack rather than by the hour, and the boat left the jetty riding low in the water with everything aboard. Lake Volta's canoes still move much of the cargo that road transport cannot easily reach.|Una canoa de carga que subía por el lago Volta hacia Yeji necesitaba manos extra para cargar sacos de maíz antes de la travesía, pagados por saco y no por hora, y la embarcación salió del embarcadero calada baja en el agua con todo a bordo. Las canoas del lago Volta siguen moviendo buena parte de la carga a la que el transporte por carretera no llega con facilidad.|Une pirogue de fret remontant le lac Volta vers Yeji avait besoin de bras supplémentaires pour charger des sacs de maïs avant la traversée, payés au sac plutôt qu'à l'heure, et l'embarcation a quitté la jetée bien enfoncée dans l'eau, chargée à ras bord. Les pirogues du lac Volta acheminent encore une bonne part du fret que le transport routier n'atteint pas facilement.|ボルタ湖をイェジへ向かって遡る荷カヌーが、渡航前にトウモロコシの俵を積み込む手を求めていた。賃金は時間ではなく俵ごとに払われ、船は積み荷をすべて載せて喫水を深く沈めながら桟橋を離れた。ボルタ湖のカヌーはいまも、道路がたやすくは届かない荷の多くを運んでいる。",
  ),
  ev(
    "shoreline-flood-crop", "loss", ["vol"], "🌾", 180,
    "A vegetable plot lost to the rising lake|Un huerto perdido por la subida del lago|Un potager perdu à cause de la montée du lac|湖の水位上昇で失った野菜畑",
    "A vegetable plot planted a little too close to the lake's edge went under when the reservoir's level rose after heavy rains upstream, and replanting further back cost both the lost seedlings and the labour of clearing new ground. Farmers along Lake Volta's shore watch the water line as closely as the weather.|Un huerto plantado un poco demasiado cerca de la orilla del lago quedó anegado cuando el nivel del embalse subió tras fuertes lluvias río arriba, y replantar más atrás costó tanto las plántulas perdidas como el trabajo de despejar terreno nuevo. Los agricultores a orillas del lago Volta vigilan la línea del agua tan de cerca como el clima.|Un potager planté un peu trop près de la rive du lac s'est retrouvé submergé quand le niveau du réservoir a monté après de fortes pluies en amont, et replanter plus en retrait a coûté à la fois les jeunes plants perdus et le travail de défrichage d'un nouveau terrain. Les agriculteurs des rives du lac Volta surveillent la ligne d'eau d'aussi près que la météo.|湖畔に少し寄せすぎて植えた野菜畑が、上流の大雨で貯水池の水位が上がったせいで水没した。もっと奥へ植え直すには、失った苗の分と新しい土地を開く手間の両方の代償がかかった。ボルタ湖畔の農家は天候と同じくらい注意深く水位線を見張っている。",
  ),

  // ---- nor 北部 ----
  ev(
    "shea-nut-crack", "gain", ["nor"], "🌰", 220,
    "Cracking shea nuts for the cooperative|Cascando nueces de karité para la cooperativa|Casser des noix de karité pour la coopérative|協同組合のシアナッツ割り",
    "A shea butter cooperative short on hands during the nut-cracking season paid by the basin for anyone willing to sit and crack shells for an afternoon, work usually done by women in a group, trading stories as much as effort. A basin of cracked kernels is only the first of several days of work before the butter itself is pressed.|Una cooperativa de manteca de karité, escasa de manos en la temporada de cascado de nueces, pagaba por cuenco a quien estuviera dispuesto a sentarse a cascar cáscaras toda una tarde, trabajo que suelen hacer mujeres en grupo, compartiendo historias tanto como esfuerzo. Un cuenco de almendras descascaradas es solo el primero de varios días de trabajo antes de prensar la manteca.|Une coopérative de beurre de karité, à court de main-d'œuvre en pleine saison de cassage des noix, payait au bassin quiconque acceptait de s'asseoir et de casser des coques pendant un après-midi, un travail habituellement fait par des femmes en groupe, échangeant autant d'histoires que d'efforts. Un bassin d'amandes décortiquées n'est que le premier de plusieurs jours de travail avant que le beurre lui-même ne soit pressé.|シアバターの協同組合は実割りの季節に人手が足りず、午後座って殻を割ってくれる人に鉢一杯ごとに支払っていた。この作業は普段、女性たちが集まって、労力と同じくらい話も交わしながら行う。割った実を鉢いっぱいにするのは、バター自体を搾るまでに続く数日がかりの作業のほんの最初の一歩にすぎない。",
  ),
  ev(
    "basket-tour-sale", "gain", ["nor"], "🧺", 230,
    "A tour minibus stops for baskets|Un minibús turístico se detiene por cestas|Un minibus de touristes s'arrête pour des paniers|観光バスがバスケット目当てに立ち寄る",
    "A tour minibus stopped briefly at a roadside stand on its way through, and a quick explanation of how each Bolga basket's colour pattern was dyed turned a look into a sale of three baskets at once, well above the average for a slow market day. Elephant-grass baskets like these are woven by hand across the whole Upper East Region.|Un minibús turístico se detuvo brevemente en un puesto al borde de la carretera de paso, y una explicación rápida de cómo se teñía el patrón de color de cada cesta Bolga convirtió una mirada en la venta de tres cestas a la vez, muy por encima de la media de un día flojo de mercado. Cestas de hierba elefante como estas se tejen a mano en toda la Región Alto Oriental.|Un minibus de touristes s'est brièvement arrêté à un étal en bordure de route sur son passage, et une explication rapide de la façon dont le motif coloré de chaque panier Bolga était teint a transformé un simple coup d'œil en la vente de trois paniers d'un coup, bien au-dessus de la moyenne d'une journée de marché calme. Des paniers en herbe à éléphant comme ceux-ci se tissent à la main dans toute la région du Haut-Est.|通りすがりの観光バスが道端の露店にちょっと立ち寄り、ボルガ・バスケットの色柄がどう染められているかを手短に説明すると、ただの一瞥が一度に三つの籠の売買に変わった。市の立ちが鈍い日の平均をはるかに上回る稼ぎだった。こうしたエレファントグラスの籠はアッパー・イースト州全域で手編みされている。",
  ),
  ev(
    "cattle-bargain-lost", "loss", ["nor"], "🐄", 200,
    "Closing a cattle deal too quickly|Cerrando un trato de ganado demasiado rápido|Conclure un marché de bétail trop vite|牛の取引を急ぎすぎる",
    "A cattle trader who seemed to be in a hurry to sell turned out to be waiting for a better offer the whole time, and the price agreed to close the deal quickly was, it became clear at the next stall over, well above what the same animal changed hands for minutes later. Livestock markets in the north run almost entirely on this kind of slow, patient negotiation.|Un comerciante de ganado que parecía tener prisa por vender resultó estar esperando todo el tiempo una oferta mejor, y el precio pactado para cerrar el trato rápido fue, como quedó claro en el puesto de al lado, muy superior al que el mismo animal cambió de manos minutos después. Los mercados de ganado del norte funcionan casi enteramente con este tipo de negociación lenta y paciente.|Un marchand de bétail qui semblait pressé de vendre attendait en réalité une meilleure offre depuis le début, et le prix accepté pour conclure vite l'affaire s'est révélé, à l'étal voisin, bien supérieur à celui auquel le même animal a changé de mains quelques minutes plus tard. Les marchés de bétail du nord reposent presque entièrement sur ce genre de négociation lente et patiente.|急いで売りたそうに見えた牛の商人は、実はずっとより良い申し出を待っていただけだった。すぐに話をまとめようと合意した値段は、隣の露店で分かったとおり、その数分後に同じ牛が取引された額よりずっと高かった。北部の家畜市場はほとんどが、こうしたゆっくりとした辛抱強い駆け引きで成り立っている。",
  ),

  // ---- wes 西部 ----
  ev(
    "oilfield-supply-day", "gain", ["wes"], "🛳️", 250,
    "A day's contract loading an oil supply boat|Un día de contrato cargando un barco de suministro petrolero|Une journée de contrat à charger un navire ravitailleur pétrolier|石油補給船の積み込みで一日契約",
    "Takoradi's offshore oil supply base needed an extra body for a single day loading crates onto a service boat, paid at the day rate the industry sets rather than what dock work elsewhere in the country usually pays. The offshore Jubilee field, discovered in 2007, has turned the whole port area into a hub for this kind of contract work.|La base de suministro petrolero marino de Takoradi necesitaba una persona más para un solo día cargando cajas en un barco de servicio, pagada a la tarifa diaria que fija la industria y no a lo que suele pagar el trabajo portuario en otras partes del país. El yacimiento marino Jubilee, descubierto en 2007, ha convertido toda la zona portuaria en un centro de este tipo de trabajo por contrato.|La base de ravitaillement pétrolier offshore de Takoradi avait besoin d'une personne de plus pour une seule journée de chargement de caisses sur un navire de service, payée au tarif journalier fixé par le secteur plutôt qu'à ce que rapporte habituellement le travail portuaire ailleurs dans le pays. Le gisement offshore Jubilee, découvert en 2007, a fait de toute la zone portuaire un pôle pour ce genre de travail sous contrat.|タコラディの洋上石油補給基地が、荷物を作業船に積み込むためにたった一日だけ余分な人手を求めていた。国内のほかの波止場仕事の相場ではなく、業界が定める日当で支払われた。2007年に発見された洋上ジュビリー油田は、この港湾地域全体をこうした契約仕事の拠点に変えた。",
  ),
  ev(
    "gold-dust-find", "gain", ["wes"], "✨", 260,
    "A heavier-than-usual pan of gold dust|Una batea de polvo de oro más pesada de lo habitual|Une battée de poudre d'or plus lourde que d'habitude|いつもより重い一杯の砂金",
    "A morning spent panning reclaimed ground on the edge of a licensed small-scale mining concession turned up a few flecks of gold dust heavier than the usual haul, sold on the spot to a licensed buyer at the day's posted rate. Small-scale panning like this has gone on around Tarkwa and Prestea for longer than any of the larger companies working the same ground.|Una mañana bateando en terreno recuperado al borde de una concesión minera artesanal con licencia dio unas motas de polvo de oro más pesadas de lo habitual, vendidas al momento a un comprador autorizado al precio publicado del día. El bateo artesanal como este se practica en torno a Tarkwa y Prestea desde antes que cualquiera de las grandes compañías que trabajan el mismo terreno.|Une matinée passée à orpailler un terrain récupéré en bordure d'une concession minière artisanale agréée a livré quelques paillettes d'or plus lourdes que la récolte habituelle, vendues sur place à un acheteur agréé au tarif du jour affiché. L'orpaillage artisanal comme celui-ci se pratique autour de Tarkwa et Prestea depuis plus longtemps qu'aucune des grandes compagnies exploitant le même terrain.|認可を受けた小規模採掘権区域の縁で、掘り返された土地を朝のうちに洗ったところ、いつもより重い砂金の粒がいくつか出た。その場で認可業者にその日の公示相場で売った。こうした小規模な砂金採りは、同じ土地で働く大手のどの会社よりも古くからタルクワとプレステアの周辺で続いている。",
  ),
  ev(
    "blackpod-cocoa-loss", "loss", ["wes"], "🍫", 200,
    "Black pod disease in the cocoa trees|Podredumbre parda en los cacaoteros|La pourriture brune dans les cacaoyers|カカオの木に黒莢病が広がる",
    "Black pod disease, a fungus that thrives in the region's humid air, spread through a stretch of cocoa trees before it was caught, and the pods that had to be cut out and burned to stop it spreading further were pods that would have been sold at harvest. Farmers across Ghana's western cocoa belt lose a meaningful share of every crop to the same disease most years.|La podredumbre parda, un hongo que prospera en el aire húmedo de la región, se extendió por una franja de cacaoteros antes de detectarse, y las vainas que hubo que cortar y quemar para frenar su avance eran vainas que se habrían vendido en la cosecha. Los agricultores de todo el cinturón cacaotero occidental de Ghana pierden cada año una parte considerable de la cosecha por esta misma enfermedad.|La pourriture brune, un champignon qui prospère dans l'air humide de la région, s'est propagée dans une parcelle de cacaoyers avant d'être repérée, et les cabosses qu'il a fallu couper et brûler pour l'empêcher de se répandre davantage sont des cabosses qui auraient été vendues à la récolte. Les agriculteurs de toute la ceinture cacaoyère occidentale du Ghana perdent chaque année une part non négligeable de leur récolte à cause de cette même maladie.|この地域の湿った空気で育ちやすい黒莢病という菌が、気づかれる前に一帯のカカオの木に広がった。これ以上広がるのを止めるために切り取って燃やさねばならなかった実は、収穫期に売られるはずだった実だった。ガーナ西部のカカオベルト一帯の農家は、ほとんどの年、この同じ病気で収穫のかなりの部分を失う。",
  ),
];
