/**
 * エジプトの都市と路線(41都市)。
 *
 * この盤面の芯: 国土の95%が無人の砂漠で、人口(と鉄道網そのもの)は
 * ナイル川本流とデルタという国土の5%足らずに押し込まれている。
 * 盤面の形そのものがこの国の人口地理を描き出すようにする。
 *
 * アフリカ大陸盤(`scripts/countries/africa/`)に既にカイロ・アレクサンドリア・
 * アスワンがあるため、事実は重複させていない(1854年アフリカ初の鉄道、
 * セシル・ローズのケープ〜カイロ構想、ハイダムが古い急流を沈めた話は
 * 大陸盤の担当領域)。ピラミッド・ファラオは意図的に0件
 * (アレクサンドリアの旧王宮地区が水没した、という1文のみ現代の
 * 地盤沈下の傍証として触れている)。
 *
 * 紅海沿岸(フルガダ・シャルム・エル・シェイクなど)とシナイ半島の大半
 * (エル・アリーシュなど)は対象外にしてある。エジプト国鉄の定期旅客列車が
 * 現在通っていないため(スエズ運河沿いのスエズ・イスマイリア・ポートサイド・
 * カンタラは対象内)。
 *
 * 地方コード:
 *   `cairo` 大カイロ / `delta` ナイルデルタ / `canal` スエズ運河沿い /
 *   `medit` 地中海沿岸(西) / `valley` 中部エジプトのナイル渓谷 /
 *   `upper` 上エジプト南部
 *
 * 経度・緯度は実際の値。投影(`EGYPT_PROJ`)は geography.mjs に書く。
 */
import { city, prop } from "../../content-overrides/city-helpers.mjs";

export const EGYPT_CITIES = {
  // ---------------------------------------------------------------------
  // cairo — 大カイロ
  // ---------------------------------------------------------------------
  cairo: city(
    "Cairo|El Cairo|Le Caire|カイロ",
    31.24, 30.06, "cairo", "railhub", "metrohub", "r",
    "Where every line in the country converges|Donde convergen todas las líneas del país|Là où convergent toutes les lignes du pays|国じゅうの路線が集まる一点",
    "Ramses Station is the single choke point through which nearly every long-distance train in Egypt must pass, because the country's rail network narrows to one main trunk here before it fans out into the Nile Delta — a shape forced by the fact that most Egyptians live within sight of the river. More than half of Greater Cairo's residents live in informal neighbourhoods that grew faster than any city plan could keep up with, spreading onto former farmland and even into the historic City of the Dead cemetery, where families have long lived among the tombs.|La estación de Ramsés es el único punto de paso obligado para casi todos los trenes de larga distancia de Egipto, porque la red ferroviaria del país se estrecha aquí hasta un único tronco antes de abrirse en abanico hacia el delta del Nilo, una forma impuesta por el hecho de que la mayoría de los egipcios vive a la vista del río. Más de la mitad de los habitantes de El Cairo metropolitano vive en barrios informales que crecieron más rápido de lo que cualquier plan urbano pudo seguir, extendiéndose sobre antiguas tierras de cultivo e incluso hasta la histórica Ciudad de los Muertos, donde desde hace tiempo hay familias que viven entre las tumbas.|La gare de Ramsès est le point de passage obligé de presque tous les trains longue distance d'Égypte, car le réseau ferroviaire du pays s'y resserre en un tronc unique avant de s'ouvrir en éventail vers le delta du Nil — une forme imposée par le fait que la plupart des Égyptiens vivent à portée de vue du fleuve. Plus de la moitié des habitants du Grand Caire vivent dans des quartiers informels qui ont grandi plus vite qu'aucun plan urbain n'a pu le suivre, s'étendant sur d'anciennes terres agricoles et jusque dans la Cité des morts historique, où des familles vivent depuis longtemps parmi les tombeaux.|ラムセス駅は、エジプトの長距離列車のほぼすべてが通らざるを得ない一点である。国の鉄道網はここで一本の幹線に絞られたのち、ナイル・デルタへ扇状に広がっていく――エジプト人の大半がナイル川を望む距離に暮らしているために生まれた形である。大カイロの住民の半数以上は、都市計画が追いつかないほど急速に広がった無許可の住宅地で暮らしており、かつての農地はもとより、歴史あるカイロの死者の街(城塞墓地)にまで及ぶ。そこでは長らく家族が墓のあいだで暮らしてきた。",
    [prop("Ramses Station Concourse|Vestíbulo de la estación de Ramsés|Hall de la gare de Ramsès|ラムセス駅のコンコース", 2600, 536),
     prop("Nile Corniche Felucca Mooring|Amarre de faluchas en la Corniche del Nilo|Mouillage de felouques sur la corniche du Nil|ナイル・コルニッシュのファルーカ係留所", 1200, 247)],
  ),
  giza: city(
    "Giza|Guiza|Gizeh|ギザ",
    31.14, 29.96, "cairo", "campus", "citycampus", "l",
    "A secular university and Africa's oldest zoo, side by side|Una universidad laica y el zoológico más antiguo de África, lado a lado|Une université laïque et le plus vieux zoo d'Afrique, côte à côte|世俗大学とアフリカ最古の動物園が隣り合う街",
    "Giza is home to Cairo University, founded in 1908 as Egypt's first non-religious, secular university, built as an alternative to the centuries-older religious institution of Al-Azhar across the river. Right next to campus sits Giza Zoo, opened in 1891 from a khedive's private botanical garden and now one of the oldest zoos in Africa, its Victorian iron bridge still carrying visitors over an artificial lake.|Guiza alberga la Universidad de El Cairo, fundada en 1908 como la primera universidad laica de Egipto, pensada como alternativa a la institución religiosa de Al-Azhar, siglos más antigua, al otro lado del río. Justo al lado del campus está el zoológico de Guiza, inaugurado en 1891 a partir del jardín botánico privado de un jedive y hoy uno de los más antiguos de África, con un puente de hierro victoriano que aún cruza sus visitantes sobre un lago artificial.|Gizeh abrite l'Université du Caire, fondée en 1908 comme la première université laïque d'Égypte, conçue comme alternative à l'institution religieuse d'Al-Azhar, vieille de plusieurs siècles, de l'autre côté du fleuve. Juste à côté du campus se trouve le zoo de Gizeh, ouvert en 1891 à partir du jardin botanique privé d'un khédive et aujourd'hui l'un des plus anciens d'Afrique, où un pont de fer victorien fait toujours traverser les visiteurs au-dessus d'un lac artificiel.|ギザにはカイロ大学がある。1908年、対岸にある何世紀も古い宗教施設アズハルに代わる存在として設立された、エジプト初の非宗教・世俗の大学である。キャンパスのすぐ隣にはギザ動物園があり、1891年にある副王の私的な植物園から開かれた、アフリカでも指折り古い動物園として、いまもヴィクトリア朝様式の鉄橋が来園者を人工湖の上へ渡している。",
    [prop("Cairo University Lecture Hall|Aula de la Universidad de El Cairo|Amphithéâtre de l'Université du Caire|カイロ大学の講堂", 1900, 391),
     prop("Zoo Garden Iron Bridge|Puente de hierro del zoológico|Pont de fer du jardin zoologique|動物園の鉄橋", 1000, 206)],
  ),
  helwan: city(
    "Helwan|Helwan|Helouan|ヘルワン",
    31.33, 29.85, "cairo", "steelworks", "industrialtown", "r",
    "A spa town turned overnight into a steel town|Un pueblo balneario convertido de la noche a la mañana en pueblo del acero|Une ville d'eaux devenue du jour au lendemain une ville de l'acier|一夜にして温泉町から製鉄の町へ",
    "Helwan was built up in the late 19th century as a spa resort around natural sulphur springs, popular enough that a narrow-gauge railway once carried Cairenes out just to bathe in its waters. After the 1952 revolution, the new government built one of Egypt's first heavy-industry projects here, an integrated iron and steel works that turned the old spa town into a smoke-heavy industrial suburb almost overnight.|Helwan se desarrolló a finales del siglo XIX como balneario en torno a manantiales sulfurosos naturales, tan popular que un ferrocarril de vía estrecha llevaba a los cairotas hasta allí solo para tomar sus aguas. Tras la revolución de 1952, el nuevo gobierno construyó aquí uno de los primeros grandes proyectos industriales de Egipto, una siderurgia integrada que convirtió al viejo pueblo balneario en un suburbio industrial cargado de humo casi de la noche a la mañana.|Helouan se développa à la fin du XIXe siècle comme station thermale autour de sources sulfureuses naturelles, assez prisée pour qu'un chemin de fer à voie étroite y amène les Cairotes rien que pour prendre les eaux. Après la révolution de 1952, le nouveau gouvernement y bâtit l'un des premiers grands projets industriels lourds d'Égypte, une aciérie intégrée qui transforma l'ancienne ville d'eaux en banlieue industrielle enfumée presque du jour au lendemain.|ヘルワンは19世紀末、天然の硫黄泉を囲む温泉保養地として栄えた。人気は高く、軽便鉄道がカイロの人々を湯浴みのためだけに運んでいたほどである。1952年革命後、新政権はここにエジプト初期の重工業プロジェクトの一つを建てた。一貫製鉄所である。かつての温泉町は、ほとんど一夜にして煙にまみれた工業郊外へと姿を変えた。",
    [prop("Sulphur Spring Bathhouse|Balneario de aguas sulfurosas|Bains aux eaux sulfureuses|硫黄泉の浴場", 480, 99),
     prop("Steelworks Rolling Mill|Tren de laminación de la acería|Laminoir de l'aciérie|製鉄所の圧延工場", 260, 54)],
  ),
  shubraelkheima: city(
    "Shubra el-Kheima|Shubra el-Kheima|Choubra el-Kheima|シュブラ・エル=ヘイマ",
    31.30, 30.18, "cairo", "tenement", "denseindustrial", "l",
    "Some of the densest streets on Earth, built one workshop at a time|Algunas de las calles más densas del planeta, levantadas taller a taller|Certaines des rues les plus denses de la planète, bâties atelier après atelier|一軒ずつの工房が積み上がった、地球有数の過密地帯",
    "Studies have repeatedly ranked Shubra el-Kheima among the most densely populated urban districts on Earth, its narrow streets packed between textile mills and metal workshops that spread north from Cairo with little room ever set aside for them by any plan. Small lead-battery recycling workshops here became notorious in the 1990s and 2000s for some of the highest recorded blood-lead levels in children found anywhere, a problem later documented by public-health researchers and only partly addressed since.|Diversos estudios han situado repetidamente a Shubra el-Kheima entre los distritos urbanos más densamente poblados del planeta, con calles estrechas apretadas entre fábricas textiles y talleres metálicos que se extendieron al norte de El Cairo sin que ningún plan les dejara apenas espacio. Pequeños talleres de reciclaje de baterías de plomo se hicieron tristemente famosos en los años noventa y dos mil por algunos de los niveles de plomo en sangre infantil más altos jamás registrados, un problema documentado después por investigadores de salud pública y solo parcialmente resuelto.|Des études ont plusieurs fois classé Choubra el-Kheima parmi les quartiers urbains les plus densément peuplés de la planète, ses rues étroites serrées entre filatures et ateliers de métal qui se sont étendus au nord du Caire sans qu'aucun plan ne leur ait vraiment fait de place. De petits ateliers de recyclage de batteries au plomb y devinrent tristement célèbres dans les années 1990 et 2000 pour certains des taux de plomb sanguin infantile les plus élevés jamais enregistrés, un problème documenté ensuite par des chercheurs en santé publique et seulement partiellement réglé depuis.|複数の調査が繰り返し、シュブラ・エル=ヘイマを地球でも指折りの過密都市地区に挙げてきた。細い路地は、いかなる都市計画もほとんど余地を残さないままカイロの北へ広がった紡績工場と金属工房のあいだにひしめく。ここの小さな鉛蓄電池の再生工房は1990年代から2000年代にかけて、子どもの血中鉛濃度がどこよりも高い部類として知られるようになった。この問題はのちに公衆衛生の研究者たちによって記録されたが、いまも部分的にしか解決していない。",
    [prop("Textile Workshop Row|Hilera de talleres textiles|Rangée d'ateliers textiles|織物工房の並び", 380, 78),
     prop("Workshop Alley Tea Stall|Puesto de té del callejón de talleres|Échoppe à thé de la ruelle des ateliers|工房通りの茶店", 220, 45)],
  ),
  newcapital: city(
    "New Administrative Capital|Nueva Capital Administrativa|Nouvelle capitale administrative|新行政首都",
    31.80, 30.02, "cairo", "newcapital", "desertcapital", "r",
    "A brand-new city built to empty the old one out|Una ciudad flamante construida para vaciar la vieja|Une ville toute neuve bâtie pour vider l'ancienne|旧都を空けるために建てられた新しい都市",
    "Since 2015, the government has been building an entirely new capital in the desert roughly 45 kilometres east of Cairo, explicitly to draw ministries, businesses and residents away from the old city's overcrowded core. A driverless monorail, opened in stages from 2022, now links the new capital and another desert satellite city to central Cairo — a rare case of new rail reaching out into the desert instead of following the Nile.|Desde 2015, el gobierno ha estado construyendo una capital totalmente nueva en el desierto, a unos 45 kilómetros al este de El Cairo, con el fin declarado de sacar ministerios, empresas y residentes del núcleo saturado de la vieja ciudad. Un monorraíl sin conductor, inaugurado por etapas desde 2022, une ahora esta nueva capital y otra ciudad satélite del desierto con el centro de El Cairo, un caso poco común de nueva vía férrea que se adentra en el desierto en lugar de seguir al Nilo.|Depuis 2015, le gouvernement bâtit dans le désert, à environ 45 kilomètres à l'est du Caire, une toute nouvelle capitale, dans le but explicite d'attirer ministères, entreprises et habitants hors du centre surpeuplé de l'ancienne ville. Un monorail sans conducteur, ouvert par étapes depuis 2022, relie désormais cette nouvelle capitale et une autre ville satellite du désert au centre du Caire — un cas rare de nouvelle voie ferrée qui s'enfonce dans le désert au lieu de suivre le Nil.|2015年以降、政府はカイロの東およそ45キロメートルの砂漠に、まったく新しい首都を建設し続けている。省庁・企業・住民を過密な旧市街の中心部から引き出すことが、はっきりとした目的である。2022年から段階的に開通した無人運転のモノレールは、いまやこの新首都ともう一つの砂漠の衛星都市をカイロ中心部と結んでいる――ナイル川に沿うのではなく、砂漠へ向かって伸びる鉄道というめずらしい例である。",
    [prop("Monorail Terminus Platform|Andén terminal del monorraíl|Quai du terminus du monorail|モノレール終着駅のホーム", 1700, 350),
     prop("Glass Tower Show Suite|Piso piloto de la torre de cristal|Appartement témoin de la tour de verre|ガラス張りタワーのモデルルーム", 800, 165)],
  ),

  // ---------------------------------------------------------------------
  // delta — ナイルデルタ
  // ---------------------------------------------------------------------
  tanta: city(
    "Tanta|Tanta|Tanta|タンタ",
    31.00, 30.78, "delta", "festival", "deltafields", "l",
    "A saint's festival that outgrew the city hosting it|Una fiesta de un santo que superó a la ciudad que la acoge|Une fête de saint plus grande que la ville qui l'accueille|開く街の大きさを超えた聖者の祭り",
    "Every October, Tanta hosts one of the largest mawlid festivals in the Islamic world, when as many as a few million pilgrims converge on the shrine of the 13th-century Sufi saint Ahmad al-Badawi, filling the streets with tents, food stalls and all-night chanting. The rest of the year, the same rail junction that carries those pilgrims in also earned Tanta its older nickname as Egypt's cotton capital, where the local exchange once set benchmark prices for the country's long-staple cotton.|Cada octubre, Tanta acoge uno de los mawlid (fiestas de un santo) más grandes del mundo islámico, cuando hasta varios millones de peregrinos convergen en el santuario del santo sufí del siglo XIII Ahmad al-Badawi, llenando las calles de tiendas de campaña, puestos de comida y cánticos que duran toda la noche. El resto del año, el mismo nudo ferroviario que trae a esos peregrinos también le valió a Tanta su apodo más antiguo de capital del algodón de Egipto, donde la bolsa local llegó a fijar los precios de referencia del algodón egipcio de fibra larga.|Chaque octobre, Tanta accueille l'un des plus grands mawlid (fêtes de saint) du monde musulman, lorsque jusqu'à plusieurs millions de pèlerins convergent vers le sanctuaire du saint soufi du XIIIe siècle Ahmad al-Badawi, remplissant les rues de tentes, d'étals de nourriture et de chants qui durent toute la nuit. Le reste de l'année, le même nœud ferroviaire qui amène ces pèlerins a aussi valu à Tanta son plus vieux surnom de capitale égyptienne du coton, où la bourse locale a longtemps fixé les prix de référence du coton égyptien à fibre longue.|毎年10月、タンタでは最大で数百万人の巡礼者が13世紀のスーフィー聖者アフマド・バダウィーの廟に集まる、イスラム世界でも屈指の規模のマウリド(聖者祭)が開かれる。街路はテントと屋台、夜通しの詠唱で埋め尽くされる。一年のそれ以外の時期、この巡礼者を運び入れるのと同じ鉄道の要衝が、タンタにもう一つの古い呼び名――エジプトの「綿の都」――も与えた。かつて地元の綿花取引所は、エジプト産長繊維綿の基準価格を決める場でもあった。",
    [prop("Mawlid Tent Row|Hilera de tiendas del mawlid|Rangée de tentes du mawlid|マウリドのテント列", 500, 103),
     prop("Cotton Exchange Floor|Sala de la bolsa del algodón|Parquet de la bourse du coton|綿花取引所の立会場", 260, 54)],
  ),
  mansoura: city(
    "Mansoura|Mansura|Mansourah|マンスーラ",
    31.38, 31.04, "delta", "fortress", "rivertown", "r",
    "Where a French king's crusade came apart|Donde se deshizo la cruzada de un rey francés|Là où la croisade d'un roi français se défit|フランス王の十字軍が崩れた場所",
    "In 1250, an Ayyubid force defeated the Seventh Crusade at Mansoura, and King Louis IX of France, retreating sick and encircled a few weeks later, was captured trying to reach the coast — a defeat costly enough that France paid a huge ransom for his release. The battle's aftermath helped topple the Ayyubid dynasty and clear the way for the Mamluks, soldier-rulers who would govern Egypt for the next two and a half centuries.|En 1250, una fuerza ayubí derrotó a la Séptima Cruzada en Mansura, y el rey Luis IX de Francia, enfermo y cercado semanas después en su retirada, fue capturado al intentar alcanzar la costa, una derrota tan costosa que Francia pagó un enorme rescate por su liberación. Las secuelas de la batalla ayudaron a derribar la dinastía ayubí y abrieron el camino a los mamelucos, soldados gobernantes que regirían Egipto durante los dos siglos y medio siguientes.|En 1250, une armée ayyoubide défit la septième croisade à Mansourah, et le roi Louis IX de France, malade et encerclé quelques semaines plus tard en pleine retraite, fut capturé en tentant de rejoindre la côte — une défaite si coûteuse que la France paya une énorme rançon pour sa libération. Les suites de la bataille contribuèrent à renverser la dynastie ayyoubide et ouvrirent la voie aux Mamelouks, soldats devenus maîtres qui gouvernèrent l'Égypte durant les deux siècles et demi suivants.|1250年、アイユーブ朝軍はマンスーラで第七回十字軍を破り、数週間後、病に倒れ包囲されて退却していたフランス王ルイ9世は、海岸へたどり着こうとして捕らえられた。この敗北は高くつき、フランスは彼の解放のために莫大な身代金を支払った。この戦いの余波はアイユーブ朝を揺るがし、以後二百五十年にわたりエジプトを統治することになる、軍人出身の支配者マムルーク朝への道を開いた。",
    [prop("Nile Retreat Battlefield Marker|Hito del campo de batalla junto al Nilo|Borne du champ de bataille au bord du Nil|ナイル河畔の古戦場碑", 800, 165),
     prop("River Crossing Ferry Landing|Embarcadero del transbordador fluvial|Débarcadère du bac fluvial|渡し船の船着場", 420, 87)],
  ),
  zagazig: city(
    "Zagazig|Zagazig|Zagazig|ザガジグ",
    31.50, 30.59, "delta", "monument", "railjunction", "l",
    "The hometown of Egypt's first modern uprising|La ciudad natal del primer levantamiento moderno de Egipto|La ville natale du premier soulèvement moderne d'Égypte|エジプト最初の近代的蜂起の生地",
    "Zagazig is the hometown of Ahmed Orabi, the army colonel whose 1879–82 revolt against the Khedive's government and foreign financial control is often called Egypt's first modern nationalist uprising. The revolt's suppression by a British invasion in 1882 led directly to a military occupation that, in one form or another, lasted for the next seventy years.|Zagazig es la ciudad natal de Ahmed Orabi, el coronel del ejército cuya revuelta de 1879-82 contra el gobierno del jedive y el control financiero extranjero se suele llamar el primer levantamiento nacionalista moderno de Egipto. La represión de la revuelta mediante una invasión británica en 1882 condujo directamente a una ocupación militar que, de una forma u otra, duró los siguientes setenta años.|Zagazig est la ville natale d'Ahmed Orabi, le colonel de l'armée dont la révolte de 1879-1882 contre le gouvernement du khédive et le contrôle financier étranger est souvent qualifiée de premier soulèvement nationaliste moderne d'Égypte. La répression de cette révolte par une invasion britannique en 1882 déboucha directement sur une occupation militaire qui, sous une forme ou une autre, dura les soixante-dix années suivantes.|ザガジグは、1879〜82年、副王の政府と外国による財政支配に対して反乱を起こした陸軍大佐アフマド・オラービーの生まれた町である。この反乱はしばしばエジプト最初の近代的民族主義蜂起と呼ばれる。1882年、この反乱がイギリスの侵攻によって鎮圧されたことは、その後70年間にわたり形を変えながら続く軍事占領へと直結した。",
    [prop("Orabi Statue Square|Plaza de la estatua de Orabi|Place de la statue d'Orabi|オラービー像の広場", 620, 128),
     prop("Junction Signal Cabin|Cabina de señales del cruce|Poste d'aiguillage de la jonction|分岐点の信号所", 320, 66)],
  ),
  damanhur: city(
    "Damanhur|Damanhur|Damanhour|ダマンフール",
    30.47, 31.03, "delta", "factory", "agroindustry", "r",
    "A cooler-weather sugar crop, grown against the calendar|Un cultivo azucarero de clima frío, sembrado a contrarreloj|Une culture sucrière de climat frais, semée contre la montre|寒い季節に合わせて育てる砂糖の作物",
    "Damanhur is home to one of the largest sugar-beet refineries in the Middle East, part of a push begun in the 1980s to grow sugar beet in the Delta as a cooler-season supplement to the sugarcane grown far to the south. The local canal network carries both raw beets in during a short autumn harvest and processed sugar back out, its schedule tied tightly to a window of only a few weeks.|Damanhur alberga una de las mayores refinerías de remolacha azucarera de Oriente Medio, parte de un impulso iniciado en los años ochenta para cultivar remolacha en el delta como complemento de temporada fría a la caña de azúcar sembrada muy al sur. La red de canales local transporta tanto la remolacha en bruto durante una breve cosecha otoñal como el azúcar ya procesado, con un calendario ceñido a solo unas semanas.|Damanhour abrite l'une des plus grandes raffineries de betterave sucrière du Moyen-Orient, dans le cadre d'un effort lancé dans les années 1980 pour cultiver la betterave dans le delta comme complément de saison fraîche à la canne à sucre cultivée bien plus au sud. Le réseau de canaux local achemine à la fois les betteraves brutes lors d'une courte récolte automnale et le sucre transformé, selon un calendrier resserré sur seulement quelques semaines.|ダマンフールには中東でも指折り規模のテンサイ精製工場がある。1980年代に始まった、はるか南で栽培されるサトウキビを補う涼しい季節の作物としてデルタでテンサイを育てる取り組みの一環である。地元の運河網は、秋の短い収穫期に原料のテンサイを運び入れ、加工した砂糖を運び出す。その日程はわずか数週間の窓に厳しく縛られている。",
    [prop("Sugar Beet Weighbridge|Báscula de la remolacha azucarera|Bascule des betteraves sucrières|テンサイの計量所", 560, 115),
     prop("Refinery Canal Lock|Esclusa del canal de la refinería|Écluse du canal de la raffinerie|精製工場そばの水門", 300, 62)],
  ),
  mahalla: city(
    "El Mahalla El Kubra|El Mahalla El Kubra|El Mahalla El Kubra|エル・マハッラ・エル・クブラ",
    31.17, 30.97, "delta", "textilemill", "millcompound", "l",
    "A textile strike that rehearsed a revolution|Una huelga textil que ensayó una revolución|Une grève textile qui répéta une révolution|革命の予行演習になった繊維工場のストライキ",
    "El Mahalla El Kubra is home to Misr Spinning and Weaving, one of the largest textile factories in the Middle East, employing tens of thousands of workers since the 1920s. A wave of strikes here in 2006–2008 over wages and a threatened privatisation is widely seen by historians as a rehearsal for the mass protests that toppled the president in 2011.|El Mahalla El Kubra alberga Misr Spinning and Weaving, una de las mayores fábricas textiles de Oriente Medio, que emplea a decenas de miles de trabajadores desde los años veinte. Una ola de huelgas aquí entre 2006 y 2008 por salarios y una amenaza de privatización es vista por muchos historiadores como un ensayo de las protestas masivas que derrocaron al presidente en 2011.|El Mahalla El Kubra abrite Misr Spinning and Weaving, l'une des plus grandes usines textiles du Moyen-Orient, employant des dizaines de milliers de travailleurs depuis les années 1920. Une vague de grèves ici entre 2006 et 2008, portant sur les salaires et une privatisation menacée, est largement considérée par les historiens comme une répétition des manifestations de masse qui renversèrent le président en 2011.|エル・マハッラ・エル・クブラには、1920年代から数万人を雇用してきた中東でも屈指の規模の紡績工場、ミスル紡織がある。2006〜2008年の賃金と民営化への反対を巡るここでのストライキの波は、2011年に大統領を退陣させた大規模抗議運動の予行演習だったと、多くの歴史家に見なされている。",
    [prop("Spinning Mill Floor|Sala de hilado de la fábrica|Atelier de filature|紡績工場の作業場", 950, 196),
     prop("Strike Committee Hall|Sala del comité de huelga|Salle du comité de grève|争議団の集会所", 480, 99)],
  ),
  damietta: city(
    "Damietta|Damietta|Damiette|ダミエッタ",
    31.82, 31.42, "delta", "carpentry", "deltaport", "r",
    "A whole town's worth of furniture workshops|Un pueblo entero convertido en talleres de mueblería|Toute une ville de menuiseries|町ぐるみの家具工房",
    "Damietta's old town is famous across Egypt for handmade wooden furniture, an industry so concentrated that whole streets are lined with workshops turning out everything from ornate bedroom sets to inlaid boxes. The modern container port built at the Nile's mouth in the 1980s now ranks among Egypt's busiest, its approach channel dredged constantly against the same silt that built the Delta in the first place.|El casco antiguo de Damietta es famoso en todo Egipto por sus muebles de madera hechos a mano, una industria tan concentrada que calles enteras están llenas de talleres que producen desde juegos de dormitorio ornamentados hasta cajas con incrustaciones. El puerto moderno de contenedores construido en la desembocadura del Nilo en los años ochenta figura hoy entre los más activos de Egipto, con un canal de acceso dragado constantemente contra el mismo limo que formó el delta.|La vieille ville de Damiette est célèbre dans toute l'Égypte pour ses meubles en bois faits main, une industrie si concentrée que des rues entières s'alignent d'ateliers produisant tout, des chambres à coucher ornées aux boîtes marquetées. Le port à conteneurs moderne construit à l'embouchure du Nil dans les années 1980 compte aujourd'hui parmi les plus actifs d'Égypte, son chenal d'accès dragué en permanence contre le même limon qui a façonné le delta.|ダミエッタの旧市街は、エジプトじゅうに知られる手作りの木製家具の産地である。この産業はあまりに集中しており、街路のいくつもが装飾的な寝室セットから象嵌箱まで作る工房で埋まっている。1980年代にナイル川の河口に建設された近代的なコンテナ港はいまやエジプト有数の忙しさで、その航路は、そもそもデルタを作り上げたのと同じ堆積土に対して絶えず浚渫され続けている。",
    [prop("Inlaid Furniture Workshop|Taller de muebles con incrustaciones|Atelier de meubles marquetés|象嵌家具の工房", 700, 144),
     prop("Container Port Berth|Muelle del puerto de contenedores|Poste à quai du port à conteneurs|コンテナ埠頭", 380, 78)],
  ),
  kafrelsheikh: city(
    "Kafr el-Sheikh|Kafr el-Sheikh|Kafr el-Cheikh|カフル・エル=シェイフ",
    30.94, 31.11, "delta", "paddyfield", "deltafields", "l",
    "Rice grown against a chronic water shortage|Arroz cultivado a pesar de una escasez crónica de agua|Du riz cultivé malgré une pénurie d'eau chronique|慢性的な水不足の中で作られる米",
    "Kafr el-Sheikh governorate grows more rice than anywhere else in Egypt, flooding its fields each summer despite the country's chronic water shortages, because the crop is deeply embedded in both local diets and export earnings. The nearby brackish Lake Burullus has also made the area a centre of fish farming, now one of the largest sources of farmed fish anywhere in Africa.|La provincia de Kafr el-Sheikh cultiva más arroz que ninguna otra parte de Egipto, inundando sus campos cada verano a pesar de la escasez crónica de agua del país, porque el cultivo está profundamente arraigado tanto en la dieta local como en los ingresos por exportación. El cercano lago salobre de Burullus también ha convertido la zona en un centro de piscicultura, hoy una de las mayores fuentes de pescado de granja de toda África.|La province de Kafr el-Cheikh cultive plus de riz que partout ailleurs en Égypte, inondant ses champs chaque été malgré la pénurie d'eau chronique du pays, car cette culture est profondément ancrée à la fois dans l'alimentation locale et les recettes d'exportation. Le lac saumâtre voisin de Bourollos a aussi fait de la région un centre de pisciculture, aujourd'hui l'une des plus grandes sources de poisson d'élevage de toute l'Afrique.|カフル・エル=シェイフ県は、エジプトのどこよりも多く米を作る。国の慢性的な水不足にもかかわらず毎夏田に水を張るのは、この作物が地元の食生活と輸出収入の両方に深く根を下ろしているからである。近くの汽水湖ブルッルスは、この一帯をアフリカでも指折りの養殖魚の産地にもしている。",
    [prop("Rice Paddy Threshing Floor|Era de la arrocera|Aire de battage du riz|水田の脱穀場", 460, 95),
     prop("Fish Farm Pond|Estanque de piscicultura|Bassin de pisciculture|養殖池", 240, 49)],
  ),
  mitghamr: city(
    "Mit Ghamr|Mit Ghamr|Mit Ghamr|ミト・ガムル",
    31.27, 30.72, "delta", "bank", "rivertown", "r",
    "Where a five-year experiment became a global industry|Donde un experimento de cinco años se volvió una industria mundial|Là où une expérience de cinq ans devint une industrie mondiale|五年の実験が、やがて世界産業に育った場所",
    "In 1963, an economist named Ahmad El Najjar opened an experimental interest-free savings bank in Mit Ghamr, modelled loosely on German credit unions, that is now widely cited as the first modern Islamic bank. The experiment closed after only a few years amid political suspicion of its founder, but the model it tested was revived and scaled up elsewhere over the following decade, eventually growing into a global Islamic finance industry.|En 1963, un economista llamado Ahmad El Najjar abrió en Mit Ghamr un banco de ahorro experimental sin intereses, inspirado vagamente en las cajas de crédito alemanas, que hoy se cita ampliamente como el primer banco islámico moderno. El experimento cerró tras solo unos años en medio de la sospecha política hacia su fundador, pero el modelo que puso a prueba se retomó y se amplió en otros lugares durante la década siguiente, hasta convertirse en una industria financiera islámica global.|En 1963, un économiste nommé Ahmad El Najjar ouvrit à Mit Ghamr une caisse d'épargne expérimentale sans intérêt, vaguement inspirée des coopératives de crédit allemandes, aujourd'hui largement considérée comme la première banque islamique moderne. L'expérience ferma après seulement quelques années sous la suspicion politique pesant sur son fondateur, mais le modèle qu'elle avait testé fut repris et étendu ailleurs au cours de la décennie suivante, jusqu'à devenir une industrie financière islamique mondiale.|1963年、アフマド・エル=ナッジャールという経済学者がミト・ガムルに、ドイツの信用組合を緩くお手本にした無利子の実験的貯蓄銀行を開いた。これはいまや、近代的なイスラム銀行の第一号として広く引用されている。この実験はわずか数年で、創設者への政治的な疑念のなかで幕を閉じたが、そこで試された仕組みはその後10年のうちに各地で復活・拡大され、やがて世界規模のイスラム金融産業へと育っていった。",
    [prop("Savings Bank Ledger Room|Sala de libros del banco de ahorro|Salle des registres de la caisse d'épargne|貯蓄銀行の帳簿室", 320, 66),
     prop("Riverside Grain Silo|Silo de grano junto al río|Silo à grain au bord du fleuve|川辺の穀物サイロ", 180, 37)],
  ),
  rosetta: city(
    "Rosetta|Rashid|Rosette|ロゼッタ",
    30.42, 31.40, "delta", "stone", "rivermouth", "l",
    "A stone that has spent two centuries in another country's museum|Una piedra que lleva dos siglos en el museo de otro país|Une pierre qui passe deux siècles dans le musée d'un autre pays|二百年よその国の博物館で過ごしている石",
    "A French officer found the Rosetta Stone here in 1799 during Napoleon's occupation of Egypt, but British forces seized it as war spoils after France's defeat in 1801, and it has been displayed in the British Museum ever since. Egypt's government has repeatedly and publicly demanded the stone's return, most recently as part of a wider campaign for the repatriation of major Egyptian antiquities held abroad.|Un oficial francés encontró la piedra de Rosetta aquí en 1799, durante la ocupación napoleónica de Egipto, pero las fuerzas británicas la confiscaron como botín de guerra tras la derrota francesa de 1801, y desde entonces se exhibe en el Museo Británico. El gobierno egipcio ha exigido repetida y públicamente su devolución, más recientemente como parte de una campaña más amplia por la repatriación de grandes antigüedades egipcias que se hallan en el extranjero.|Un officier français trouva la pierre de Rosette ici en 1799, pendant l'occupation napoléonienne de l'Égypte, mais les forces britanniques la saisirent comme butin de guerre après la défaite française de 1801, et elle est exposée au British Museum depuis lors. Le gouvernement égyptien a réclamé à plusieurs reprises et publiquement son retour, plus récemment dans le cadre d'une campagne plus large pour le rapatriement de grandes antiquités égyptiennes conservées à l'étranger.|1799年、ナポレオンによるエジプト占領のさなか、フランス人士官がここでロゼッタ・ストーンを見つけた。しかし1801年のフランス軍敗北後、イギリス軍がこれを戦利品として押収し、以来ずっと大英博物館に展示されている。エジプト政府はこの石の返還を繰り返し公に求めてきており、近年では海外にある主要なエジプト古美術品の返還を求める、より広い運動の一環として位置づけられている。",
    [prop("Stone Inscription Replica Stand|Puesto de la réplica de la piedra|Stand de la réplique de la pierre|石碑レプリカの展示台", 340, 70),
     prop("River Mouth Fish Market|Mercado de pescado en la desembocadura|Marché aux poissons de l'embouchure|河口の魚市場", 190, 39)],
  ),
  banha: city(
    "Banha|Banha|Benha|バンハー",
    31.18, 30.46, "delta", "orchard", "deltafields", "r",
    "A crate-by-crate mango season along the highway|Una temporada de mangos, cajón a cajón, junto a la carretera|Une saison de mangues, cageot après cageot, le long de la route|幹線道路沿い、木箱ひとつずつのマンゴーの季節",
    "Banha and the orchards around it grow a large share of Egypt's mangoes, and the town holds an annual mango festival each summer when roadside stalls along the highway sell dozens of named local varieties by the crate. The mango only became a major Egyptian crop in the 20th century, planted on land that had grown mostly grain and cotton before irrigation and rail links made fast delivery to Cairo's markets possible.|Banha y los huertos que la rodean cultivan buena parte de los mangos de Egipto, y la ciudad celebra cada verano un festival del mango, cuando los puestos junto a la carretera venden por cajones decenas de variedades locales con nombre propio. El mango solo se convirtió en un cultivo egipcio importante en el siglo XX, sembrado en tierras que antes producían sobre todo cereal y algodón, hasta que el riego y el ferrocarril permitieron una entrega rápida a los mercados de El Cairo.|Benha et les vergers qui l'entourent produisent une grande part des mangues d'Égypte, et la ville tient chaque été un festival de la mangue, où des étals au bord de la route vendent par cageots des dizaines de variétés locales nommées. La mangue n'est devenue une culture égyptienne majeure qu'au XXe siècle, plantée sur des terres qui produisaient surtout du grain et du coton avant que l'irrigation et le rail ne permettent une livraison rapide aux marchés du Caire.|バンハーとその周りの果樹園は、エジプトのマンゴーの多くを産する。毎年夏に開かれるマンゴー祭りでは、幹線道路沿いの露店が名前の付いた地元品種を木箱単位で何十種類も売る。マンゴーがエジプトの主要な作物になったのは20世紀に入ってからで、灌漑と鉄道がカイロの市場への速い輸送を可能にする前は、この土地の多くは穀物と綿花を作っていた。",
    [prop("Mango Crate Stall|Puesto de cajas de mango|Étal de caisses de mangues|マンゴーの木箱売り場", 380, 78),
     prop("Highway Fruit Stand|Puesto de fruta en la carretera|Étal de fruits sur la route|幹線道路の果物屋台", 200, 41)],
  ),
  kafreldawwar: city(
    "Kafr el-Dawwar|Kafr el-Dawwar|Kafr el-Dawwar|カフル・エル=ダッワール",
    30.13, 31.13, "delta", "factory", "industrialtown", "l",
    "A strike put down within days of a revolution|Una huelga sofocada a los pocos días de una revolución|Une grève écrasée quelques jours après une révolution|革命からわずか数日で鎮圧されたストライキ",
    "Days after the 1952 revolution that overthrew the monarchy, textile workers in Kafr el-Dawwar went on strike over pay and conditions, and the new military government responded not with concessions but with a swift military trial. Two of the strike's leaders were executed within days, an early sign that the officers who had just seized power would not tolerate the kind of labour unrest that had helped destabilise the old order.|A los pocos días de la revolución de 1952 que derrocó a la monarquía, los trabajadores textiles de Kafr el-Dawwar se declararon en huelga por salarios y condiciones, y el nuevo gobierno militar respondió no con concesiones, sino con un rápido consejo de guerra. Dos de los líderes de la huelga fueron ejecutados en cuestión de días, una señal temprana de que los oficiales que acababan de tomar el poder no tolerarían el tipo de agitación laboral que había ayudado a desestabilizar el viejo orden.|Quelques jours après la révolution de 1952 qui renversa la monarchie, des ouvriers textiles de Kafr el-Dawwar se mirent en grève pour les salaires et les conditions de travail, et le nouveau gouvernement militaire répondit non par des concessions mais par un procès militaire expéditif. Deux meneurs de la grève furent exécutés en quelques jours, signe précoce que les officiers qui venaient de prendre le pouvoir ne toléreraient pas le genre d'agitation ouvrière qui avait contribué à déstabiliser l'ancien ordre.|1952年、王政を打倒した革命からわずか数日後、カフル・エル=ダッワールの繊維労働者たちが賃金と待遇を巡ってストライキを起こした。新しい軍事政権はこれに譲歩ではなく、迅速な軍事裁判で応じた。ストライキの指導者2人は数日のうちに処刑された。権力を握ったばかりの将校たちが、旧体制を揺るがす一因となったような労働争議を許さないという、早い段階での兆しだった。",
    [prop("Mill Gate Memorial|Monumento en la puerta de la fábrica|Mémorial devant l'usine|工場正門の記念碑", 300, 62),
     prop("Weaving Hall Floor|Sala de tejeduría|Atelier de tissage|織布工場の作業場", 190, 39)],
  ),
  qanater: city(
    "Al Qanater el-Khayreya|Al Qanater el-Khayreya|Al Qanater el-Khayreya|アル・カナーティル・エル=ハイリーヤ",
    31.13, 30.19, "delta", "barrage", "nileforkbarrage", "r",
    "The exact point where one river becomes two|El punto exacto donde un río se convierte en dos|Le point exact où un fleuve en devient deux|一つの川が二つに分かれる、まさにその場所",
    "This is the exact point where the Nile splits into its Rosetta and Damietta branches, and the barrage built across both channels here in 1861, expanded in 1939, was Egypt's first large-scale attempt to control the river's flow, decades before the barrages at Asyut or the dams at Aswan existed. The gardens planted around the barrage to stabilise its foundations became one of the country's most popular weekend escapes for Cairenes, reachable in the age before cars by a railway built specifically to carry day-trippers.|Este es el punto exacto donde el Nilo se divide en sus ramales de Rosetta y Damietta, y la presa construida sobre ambos canales aquí en 1861, ampliada en 1939, fue el primer intento egipcio a gran escala de controlar el caudal del río, décadas antes de que existieran las presas de Asiut o las de Asuán. Los jardines plantados alrededor de la presa para estabilizar sus cimientos se convirtieron en una de las escapadas de fin de semana más populares para los cairotas, a las que se llegaba, en la era anterior al automóvil, por un ferrocarril construido específicamente para excursionistas de un día.|C'est le point exact où le Nil se divise en ses bras de Rosette et de Damiette, et le barrage construit sur les deux canaux ici en 1861, agrandi en 1939, fut la première tentative égyptienne à grande échelle de maîtriser le débit du fleuve, des décennies avant les barrages d'Assiout ou les barrages d'Assouan. Les jardins plantés autour du barrage pour en stabiliser les fondations devinrent l'une des escapades de fin de semaine les plus prisées des Cairotes, accessibles à l'époque précédant l'automobile par un chemin de fer bâti spécialement pour les excursionnistes d'un jour.|ここはナイル川がロゼッタ支流とダミエッタ支流に分かれる、まさにその一点である。1861年に両水路にまたがって築かれ、1939年に拡張されたこの堰は、アシュートの堰やアスワンのダムができるよりも何十年も前の、エジプトによる川の流れの制御としては最初の大規模な試みだった。堰の基礎を安定させるために周囲に植えられた庭園は、カイロの人々にとって週末の行楽地として指折りの人気を得た。自動車の時代より前は、日帰り客を運ぶために作られた専用の鉄道でここへ来ることができた。",
    [prop("Barrage Garden Pavilion|Pabellón del jardín de la presa|Pavillon du jardin du barrage|バラージュ庭園のあずまや", 420, 87),
     prop("Day-Tripper Rail Platform|Andén del tren de excursionistas|Quai du train d'excursion|行楽列車のホーム", 220, 45)],
  ),
  kafrelzayat: city(
    "Kafr el-Zayat|Kafr el-Zayat|Kafr el-Zayat|カフル・エル=ザヤート",
    30.82, 30.83, "delta", "bridge", "rivercrossing", "l",
    "A bridge that has to open without stopping the trains for long|Un puente que debe abrirse sin detener los trenes demasiado tiempo|Un pont qui doit s'ouvrir sans arrêter les trains trop longtemps|列車を長く止めずに開かねばならない橋",
    "Kafr el-Zayat grew up around some of the Delta's earliest cotton-ginning factories, processing raw cotton picked nearby before it moved on by rail to the spinning mills of Mahalla or the docks of Alexandria. A swing bridge carries the rail line and the road together across the Rosetta branch here, one of a handful of crossings engineered to open for river traffic without ever halting trains for long.|Kafr el-Zayat creció en torno a algunas de las primeras desmotadoras de algodón del delta, que procesaban el algodón en bruto recolectado cerca antes de que siguiera por tren hacia las hilanderías de Mahalla o los muelles de Alejandría. Un puente giratorio lleva aquí la vía férrea y la carretera juntas sobre el ramal de Rosetta, uno de los pocos cruces diseñados para abrirse al tráfico fluvial sin detener nunca los trenes por mucho tiempo.|Kafr el-Zayat se développa autour de certaines des premières usines d'égrenage du coton du delta, traitant le coton brut cueilli à proximité avant qu'il ne parte par le rail vers les filatures de Mahalla ou les quais d'Alexandrie. Un pont tournant y porte ensemble la voie ferrée et la route au-dessus du bras de Rosette, l'un des rares passages conçus pour s'ouvrir au trafic fluvial sans jamais arrêter les trains bien longtemps.|カフル・エル=ザヤートは、デルタでも最も早い時期の綿繰り工場のいくつかを核に育った町で、近隣で摘まれた原綿を加工したのち、マハッラの紡績工場やアレクサンドリアの波止場へ鉄道で送り出していた。ここでは可動橋が鉄道と道路を一体でロゼッタ支流の上に渡している。川の交通のために開きながらも、列車を長く止めずに済むよう設計された数少ない渡河点の一つである。",
    [prop("Cotton Gin Floor|Sala de la desmotadora de algodón|Salle de l'égreneuse à coton|綿繰り工場の作業場", 280, 58),
     prop("Swing Bridge Control Room|Sala de control del puente giratorio|Salle de contrôle du pont tournant|可動橋の操作室", 190, 39)],
  ),
  zefta: city(
    "Zefta|Zefta|Zefta|ゼフタ",
    31.16, 30.65, "delta", "flag", "rivertown", "r",
    "A republic that lasted about two weeks|Una república que duró unas dos semanas|Une république qui dura environ deux semaines|およそ二週間続いた共和国",
    "During the 1919 revolution against British rule, residents of Zefta cut the town off from British control for about two weeks and declared it an independent republic, complete with its own flag, stamped currency and checkpoints. British troops eventually retook the town, but the episode is still remembered locally as one of the most defiant local acts of the wider uprising that spread across the country that spring.|Durante la revolución de 1919 contra el dominio británico, los habitantes de Zefta aislaron la ciudad del control británico durante unas dos semanas y la declararon república independiente, con bandera propia, moneda sellada y puestos de control. Las tropas británicas acabaron retomando la ciudad, pero el episodio sigue recordándose localmente como uno de los actos de desafío más notables del levantamiento más amplio que se extendió por el país aquella primavera.|Pendant la révolution de 1919 contre la domination britannique, les habitants de Zefta coupèrent la ville du contrôle britannique pendant environ deux semaines et la déclarèrent république indépendante, avec son propre drapeau, sa monnaie tamponnée et ses postes de contrôle. Les troupes britanniques finirent par reprendre la ville, mais l'épisode reste localement rappelé comme l'un des actes de défi les plus marquants du soulèvement plus large qui se répandit dans le pays ce printemps-là.|1919年、イギリスの支配に対する革命のさなか、ゼフタの住民は町をおよそ2週間にわたりイギリスの統制から切り離し、独自の旗・押印した通貨・検問所まで備えた独立共和国を宣言した。イギリス軍はやがて町を奪還したが、この出来事はいまも地元で、その春に国じゅうへ広がったより大きな蜂起の中でも指折り反抗的な地域行動として記憶されている。",
    [prop("Republic Flag Post|Asta de la bandera de la república|Mât du drapeau de la république|「共和国」の旗竿", 260, 54),
     prop("Checkpoint Gatehouse|Garita del puesto de control|Poste de contrôle|検問所の詰所", 190, 39)],
  ),

  // ---------------------------------------------------------------------
  // canal — スエズ運河沿い
  // ---------------------------------------------------------------------
  suez: city(
    "Suez|Suez|Suez|スエズ",
    32.55, 29.97, "canal", "canal", "canalcity", "l",
    "The city that named a crisis|La ciudad que dio nombre a una crisis|La ville qui donna son nom à une crise|危機に名を与えた街",
    "In July 1956, President Gamal Abdel Nasser announced the nationalisation of the Suez Canal Company from a speech tied to this waterway, a move that triggered a brief war with Britain, France and Israel later that year. The crisis ended with the invading forces withdrawing under international pressure, an outcome widely seen as marking the effective end of Britain and France's status as top-tier world powers.|En julio de 1956, el presidente Gamal Abdel Nasser anunció la nacionalización de la Compañía del Canal de Suez en un discurso ligado a esta vía navegable, lo que desencadenó una breve guerra con Gran Bretaña, Francia e Israel ese mismo año. La crisis terminó con la retirada de las fuerzas invasoras bajo presión internacional, un desenlace visto ampliamente como el fin efectivo del estatus de Gran Bretaña y Francia como potencias mundiales de primer nivel.|En juillet 1956, le président Gamal Abdel Nasser annonça la nationalisation de la Compagnie du canal de Suez dans un discours lié à cette voie d'eau, un geste qui déclencha plus tard cette année-là une brève guerre avec la Grande-Bretagne, la France et Israël. La crise se termina par le retrait des forces envahissantes sous pression internationale, un dénouement largement vu comme marquant la fin effective du statut de la Grande-Bretagne et de la France comme puissances mondiales de tout premier rang.|1956年7月、ガマール・アブドゥル=ナーセル大統領は、この水路にちなんだ演説の中でスエズ運河会社の国有化を発表した。この動きは同年後半、イギリス・フランス・イスラエルとの短い戦争を引き起こした。危機は国際的圧力のもとで侵攻軍が撤退して終わり、この結末はイギリスとフランスが世界一流の大国としての地位を実質的に失った出来事として広く見なされている。",
    [prop("Canal Company Ledger Office|Oficina de registros de la compañía del canal|Bureau des registres de la compagnie du canal|運河会社の記録事務所", 900, 185),
     prop("Waterway Pilot Station|Estación de prácticos del canal|Poste des pilotes du canal|水路案内人の詰所", 480, 99)],
  ),
  ismailia: city(
    "Ismailia|Ismailía|Ismaïlia|イスマイリア",
    32.27, 30.60, "canal", "gardencity", "canalgarden", "r",
    "A garden city, and the labour that dug the water beside it|Una ciudad-jardín, y el trabajo que cavó el agua junto a ella|Une ville-jardin, et le travail qui creusa l'eau à ses côtés|庭園都市と、その傍らで水を掘った労働",
    "The Suez Canal Company built Ismailia from scratch in the 1860s as a purpose-planned headquarters town, its wide tree-lined avenues laid out in a style closer to a French garden suburb than any older Egyptian city. The canal itself was dug largely by Egyptian peasants conscripted under the corvée forced-labour system — more than a million labourers are estimated to have worked on it in stages between 1859 and 1869, with a death toll from disease, exhaustion and accidents that was never precisely counted.|La Compañía del Canal de Suez construyó Ismailía desde cero en la década de 1860 como sede planificada de la empresa, con anchas avenidas arboladas trazadas en un estilo más cercano a un suburbio-jardín francés que a cualquier ciudad egipcia más antigua. El canal en sí fue excavado en gran parte por campesinos egipcios reclutados bajo el sistema de trabajo forzoso de la corvée: se calcula que más de un millón de trabajadores participaron en distintas etapas entre 1859 y 1869, con un número de muertes por enfermedad, agotamiento y accidentes que nunca se contó con precisión.|La Compagnie du canal de Suez bâtit Ismaïlia de toutes pièces dans les années 1860 comme ville-siège planifiée, ses larges avenues bordées d'arbres dessinées dans un style plus proche d'une banlieue-jardin française que de toute ville égyptienne plus ancienne. Le canal lui-même fut creusé en grande partie par des paysans égyptiens réquisitionnés sous le régime de la corvée — plus d'un million de travailleurs auraient œuvré par étapes entre 1859 et 1869, avec un nombre de morts dues à la maladie, à l'épuisement et aux accidents jamais précisément recensé.|スエズ運河会社は1860年代、イスマイリアを本社機能を持つ計画都市としてゼロから築いた。並木の広い大通りは、それまでのどのエジプトの都市よりもフランス風の庭園郊外に近い様式で敷かれた。運河そのものは主に、賦役(コルヴェ)強制労働制度のもとで徴集されたエジプトの農民によって掘られた。1859年から1869年にかけて段階的に働いた労働者は100万人を超えると推定され、病気・過労・事故による死者の数は正確には数えられなかった。",
    [prop("Garden Avenue Villa|Villa de la avenida ajardinada|Villa de l'avenue arborée|並木通りのヴィラ", 980, 202),
     prop("Labourers' Memorial Ground|Terreno del monumento a los trabajadores|Terrain du mémorial des travailleurs|労働者慰霊の広場", 520, 107)],
  ),
  portsaid: city(
    "Port Said|Port Said|Port-Saïd|ポートサイド",
    32.28, 31.26, "canal", "shop", "dutyfreeport", "l",
    "A whole generation's trip for a new television|El viaje de toda una generación por un televisor nuevo|Le voyage de toute une génération pour une nouvelle télévision|新しいテレビを買うためだけの、ある世代の旅",
    "For decades starting in the 1970s, Port Said was designated a duty-free zone, and Egyptians from across the country would travel here specifically to buy imported electronics and appliances at prices unavailable anywhere else. The free-zone status was scaled back in the 2000s, but the city's shopping arcades and the ritual of the trip for a new refrigerator or television are still remembered fondly by an entire generation.|Durante décadas a partir de los setenta, Port Said fue designada zona franca, y egipcios de todo el país viajaban hasta allí específicamente para comprar electrónica y electrodomésticos importados a precios que no se hallaban en ningún otro lugar. El estatus de zona franca se redujo en la década de 2000, pero los pasajes comerciales de la ciudad y el ritual del viaje por un frigorífico o un televisor nuevo siguen recordándose con cariño por toda una generación.|Pendant des décennies à partir des années 1970, Port-Saïd fut désignée zone franche, et des Égyptiens de tout le pays venaient y acheter précisément des appareils électroniques et électroménagers importés à des prix introuvables ailleurs. Le statut de zone franche fut réduit dans les années 2000, mais les galeries marchandes de la ville et le rituel du voyage pour un nouveau réfrigérateur ou une télévision restent fondly rappelés par toute une génération.|1970年代から数十年にわたり、ポートサイドは免税地区に指定されており、エジプトじゅうの人々が、他では手に入らない値段の輸入家電製品を買うためだけにここへ来ていた。免税地区としての扱いは2000年代に縮小されたが、この街のショッピングアーケードと、新しい冷蔵庫やテレビを求めてここへ来るという習わしは、いまもある世代にとって懐かしい記憶である。",
    [prop("Duty-Free Appliance Counter|Mostrador de electrodomésticos libres de impuestos|Comptoir d'électroménager hors taxes|免税の家電売り場", 1050, 216),
     prop("Lighthouse Promenade|Paseo del faro|Promenade du phare|灯台前の遊歩道", 560, 115)],
  ),
  qantara: city(
    "El Qantara|El Qantara|El Qantara|エル・カンタラ",
    32.32, 30.87, "canal", "crossing", "canalcrossing", "r",
    "\"The bridge\" — and a river of soldiers crossing on foot|«El puente», y un río de soldados cruzando a pie|« Le pont », et une rivière de soldats traversant à pied|「橋」という名の町と、徒歩で渡った兵士たちの列",
    "\"Qantara\" means \"the bridge\" or crossing point, and the town has long marked the traditional land route between the Nile Delta and Sinai; a swing bridge and a vehicle ferry still carry traffic across the canal here today. On 6 October 1973, Egyptian forces crossed the canal at several points near here at the start of the October War, an event commemorated annually and taught in schools as the moment Egypt regained a military foothold on the canal's eastern bank.|«Qantara» significa «el puente» o punto de cruce, y la ciudad ha marcado durante mucho tiempo la ruta terrestre tradicional entre el delta del Nilo y el Sinaí; un puente giratorio y un transbordador para vehículos todavía cruzan el tráfico por el canal aquí hoy. El 6 de octubre de 1973, las fuerzas egipcias cruzaron el canal en varios puntos cercanos al inicio de la guerra de Octubre, un hecho conmemorado cada año y enseñado en las escuelas como el momento en que Egipto recuperó una posición militar en la orilla oriental del canal.|« Qantara » signifie « le pont » ou le point de passage, et la ville a longtemps marqué la route terrestre traditionnelle entre le delta du Nil et le Sinaï ; un pont tournant et un bac pour véhicules font encore traverser le trafic ici aujourd'hui. Le 6 octobre 1973, les forces égyptiennes traversèrent le canal en plusieurs points proches d'ici au début de la guerre d'Octobre, un événement commémoré chaque année et enseigné dans les écoles comme le moment où l'Égypte reprit pied militairement sur la rive est du canal.|「カンタラ」は「橋」あるいは渡河点を意味し、この町は長らくナイルデルタとシナイを結ぶ伝統的な陸路の目印だった。可動橋と車両フェリーが、いまもここで運河をまたぐ交通を担っている。1973年10月6日、十月戦争の開戦とともに、エジプト軍はこの付近の複数の地点で運河を渡った。この出来事は毎年記念され、エジプトが運河東岸に軍事的な足がかりを取り戻した瞬間として学校で教えられている。",
    [prop("Swing Bridge Crossing|Cruce del puente giratorio|Passage du pont tournant|可動橋の渡り口", 300, 62),
     prop("October Crossing Memorial|Monumento a la travesía de octubre|Mémorial de la traversée d'octobre|十月渡河の記念碑", 190, 39)],
  ),

  // ---------------------------------------------------------------------
  // medit — 地中海沿岸(西)
  // ---------------------------------------------------------------------
  alexandria: city(
    "Alexandria|Alejandría|Alexandrie|アレクサンドリア",
    29.92, 31.20, "medit", "tram", "cornicheport", "r",
    "Africa's oldest tram, still running along the sea|El tranvía más antiguo de África, aún en marcha junto al mar|Le plus vieux tramway d'Afrique, toujours en service au bord de la mer|いまも海沿いを走る、アフリカ最古の路面電車",
    "Alexandria's tram network opened in 1860, decades before most of the world's cities had one, and double-decker cars introduced in the mid-20th century still rattle along the Mediterranean corniche today, making it one of the oldest continuously operating tram systems anywhere. The city is also losing ground to the sea it faces: parts of the ancient shoreline have already slipped underwater, and engineers now watch the modern corniche for the same slow subsidence that swallowed the old royal quarter centuries ago.|La red de tranvías de Alejandría se inauguró en 1860, décadas antes de que la tuvieran la mayoría de las ciudades del mundo, y los coches de dos pisos introducidos a mediados del siglo XX todavía traquetean hoy por la corniche mediterránea, lo que la convierte en uno de los sistemas de tranvía en funcionamiento continuo más antiguos del planeta. La ciudad también va perdiendo terreno frente al mar al que mira: partes de la costa antigua ya se hundieron bajo el agua, y hoy los ingenieros vigilan la corniche moderna por si sufre el mismo hundimiento lento que se tragó el antiguo barrio real siglos atrás.|Le réseau de tramway d'Alexandrie a ouvert en 1860, des décennies avant la plupart des villes du monde, et des voitures à impériale introduites au milieu du XXe siècle roulent encore aujourd'hui sur la corniche méditerranéenne, ce qui en fait l'un des réseaux de tramway en service continu les plus anciens qui soient. La ville perd aussi du terrain face à la mer qu'elle regarde : des pans du littoral antique ont déjà disparu sous les flots, et les ingénieurs surveillent aujourd'hui la corniche moderne pour le même affaissement lent qui a englouti l'ancien quartier royal il y a des siècles.|アレクサンドリアの路面電車網は1860年に開通した。世界の大半の都市に路面電車が現れるより何十年も早い。20世紀半ばに導入された二階建ての車両は、いまも地中海沿いのコルニッシュをがたごとと走り続けており、現存する路面電車網の中でも指折りの古さを誇る。この街は、向き合う海にじわじわと土地を奪われてもいる。古代の海岸線の一部はすでに水没しており、技術者たちはいま、何世紀も前に旧王宮地区を呑み込んだのと同じゆっくりとした地盤沈下の兆しを、現代のコルニッシュにも探している。",
    [prop("Raml Tram Terminus|Terminal del tranvía de Raml|Terminus du tramway de Raml|ラムル路面電車の終着駅", 1400, 288),
     prop("Corniche Seawall Walk|Paseo del malecón de la Corniche|Promenade du brise-lames de la corniche|コルニッシュの防波堤遊歩道", 700, 144)],
  ),
  eldabaa: city(
    "El Dabaa|El Dabaa|El Dabaa|エル・ダバア",
    28.47, 30.97, "medit", "nuclearplant", "desertcoast", "r",
    "Egypt's first nuclear power plant, rising from the coast|La primera central nuclear de Egipto, alzándose desde la costa|La première centrale nucléaire d'Égypte, sortant de terre sur la côte|海岸に立ち上がる、エジプト初の原子力発電所",
    "Construction began in 2022 on El Dabaa Nuclear Power Plant, Egypt's first, built with Russian technical and financial backing under an intergovernmental agreement signed in 2015; the site was chosen partly because seismic surveys here found some of the most stable bedrock along the entire Mediterranean coast. Before the reactors arrived, this stretch of coast was known mainly for a scatter of small fishing hamlets, a quiet stopover on the long rail and road link between Alexandria and the Libyan border.|La construcción de la central nuclear de El Dabaa, la primera de Egipto, comenzó en 2022 con respaldo técnico y financiero ruso, bajo un acuerdo intergubernamental firmado en 2015; el emplazamiento se eligió en parte porque estudios sísmicos hallaron aquí uno de los lechos rocosos más estables de toda la costa mediterránea. Antes de que llegaran los reactores, este tramo de costa era conocido sobre todo por un puñado de pequeñas aldeas de pescadores, una parada tranquila en el largo enlace ferroviario y por carretera entre Alejandría y la frontera libia.|La construction de la centrale nucléaire d'El Dabaa, la première d'Égypte, débuta en 2022 avec un soutien technique et financier russe, dans le cadre d'un accord intergouvernemental signé en 2015 ; le site fut choisi en partie parce que des études sismiques y trouvèrent l'un des socles rocheux les plus stables de toute la côte méditerranéenne. Avant l'arrivée des réacteurs, ce tronçon de côte était surtout connu pour quelques hameaux de pêcheurs, une halte tranquille sur la longue liaison ferroviaire et routière entre Alexandrie et la frontière libyenne.|エジプト初となるエル・ダバア原子力発電所の建設は2022年に始まった。2015年に結ばれた政府間協定のもと、ロシアの技術と資金の支援を受けている。この場所が選ばれた理由の一つは、地中海沿岸全体でも指折り安定した岩盤が地震調査で見つかったことにある。原子炉がやってくる前、この海岸はもっぱら小さな漁村が点在するだけの土地として知られ、アレクサンドリアとリビア国境を結ぶ長い鉄道・道路の途中の静かな中継地だった。",
    [prop("Reactor Site Overlook|Mirador de la central nuclear|Belvédère du site du réacteur|原子炉建設地の展望台", 600, 124),
     prop("Fishing Hamlet Jetty|Embarcadero de la aldea de pescadores|Jetée du hameau de pêcheurs|漁村の桟橋", 320, 66)],
  ),
  marsamatruh: city(
    "Marsa Matruh|Marsa Matruh|Marsa Matrouh|マルサ・マトルーフ",
    27.24, 31.35, "medit", "railhead", "desertcoast", "l",
    "A wartime railhead that reinvented itself as a beach town|Una cabecera de ferrocarril de guerra que se reinventó como pueblo de playa|Un terminus ferroviaire de guerre reconverti en station balnéaire|戦時の鉄道終着駅から生まれ変わった海辺の町",
    "During the Second World War, the rail line was extended from Alexandria to Marsa Matruh specifically to supply Allied forces fighting Rommel's Afrika Korps in the Western Desert, briefly making a small fishing town one of the most strategically important railheads in North Africa. Decades later the same coast reinvented itself around tourism, and the town's turquoise bays now fill each August with domestic holidaymakers rather than troop convoys.|Durante la Segunda Guerra Mundial, la vía férrea se extendió desde Alejandría hasta Marsa Matruh específicamente para abastecer a las fuerzas aliadas que luchaban contra el Afrika Korps de Rommel en el desierto occidental, y por un tiempo convirtió a un pequeño pueblo pesquero en una de las cabeceras ferroviarias más importantes estratégicamente de todo el norte de África. Décadas después, esa misma costa se reinventó en torno al turismo, y las bahías turquesas del pueblo se llenan hoy cada agosto de veraneantes egipcios en lugar de convoyes militares.|Pendant la Seconde Guerre mondiale, la voie ferrée fut prolongée d'Alexandrie à Marsa Matrouh spécifiquement pour ravitailler les forces alliées combattant l'Afrika Korps de Rommel dans le désert occidental, faisant brièvement d'un petit village de pêcheurs l'un des terminus ferroviaires les plus stratégiques d'Afrique du Nord. Des décennies plus tard, la même côte s'est réinventée autour du tourisme, et les baies turquoise de la ville se remplissent désormais chaque août de vacanciers égyptiens plutôt que de convois militaires.|第二次世界大戦中、鉄道はアレクサンドリアからマルサ・マトルーフまで、西部砂漠でロンメルのアフリカ軍団と戦う連合軍を補給するためだけに延伸され、小さな漁村を一時、北アフリカでも戦略上とりわけ重要な鉄道終着駅に変えた。数十年後、同じ海岸は観光を軸に生まれ変わり、この町のターコイズ色の入江は、いまや毎年8月、軍の車列ではなく国内の海水浴客で埋まっている。",
    [prop("Wartime Railhead Shed|Cobertizo de la cabecera ferroviaria de guerra|Hangar du terminus ferroviaire de guerre|戦時鉄道終着駅の倉庫", 520, 107),
     prop("Turquoise Bay Beach Hut|Cabaña de playa de la bahía turquesa|Cabane de plage de la baie turquoise|ターコイズの入江のビーチ小屋", 280, 58)],
  ),
  elalamein: city(
    "El Alamein|El Alamein|El Alamein|エル・アラメイン",
    28.95, 30.83, "medit", "warcemetery", "desertcoast", "r",
    "A battle fought along a single road because there was no other|Una batalla librada junto a una sola carretera porque no había otra|Une bataille livrée le long d'une unique route car il n'en existait pas d'autre|他に道が無かったため、一本の道に沿って戦われた戦い",
    "The 1942 Battle of El Alamein, fought along the rail line and the single coastal road here because there was effectively no other route through the desert, is widely regarded as the turning point of the North African campaign against Rommel's forces. War cemeteries for thousands of British Commonwealth, German and Italian dead still line the coast near the town, visited today mostly by descendants rather than the crowds drawn to the nearby beach resorts.|La batalla de El Alamein de 1942, librada junto a la vía férrea y la única carretera costera de aquí porque prácticamente no había otra ruta a través del desierto, se considera ampliamente el punto de inflexión de la campaña norteafricana contra las fuerzas de Rommel. Cementerios de guerra con miles de muertos de la Commonwealth británica, alemanes e italianos todavía bordean la costa cerca de la ciudad, visitados hoy sobre todo por descendientes y no por las multitudes que atraen los cercanos complejos de playa.|La bataille d'El Alamein de 1942, livrée le long de la voie ferrée et de l'unique route côtière d'ici parce qu'il n'existait pratiquement aucune autre voie à travers le désert, est largement considérée comme le tournant de la campagne d'Afrique du Nord contre les forces de Rommel. Des cimetières de guerre pour des milliers de morts du Commonwealth britannique, allemands et italiens bordent encore la côte près de la ville, visités aujourd'hui surtout par des descendants plutôt que par les foules attirées par les stations balnéaires voisines.|1942年のエル・アラメインの戦いは、砂漠を抜ける道が事実上ここにしかなかったため、鉄道と唯一の海岸道路に沿って戦われた。ロンメル軍に対する北アフリカ戦線の転換点として広く見なされている。イギリス連邦・ドイツ・イタリアの数千人の戦死者を弔う戦没者墓地がいまも町の近くの海岸沿いに並び、近隣のビーチリゾートに集まる人々というより、いまも遺族が主に訪れる場所である。",
    [prop("Coastal Road Checkpoint|Puesto de control de la carretera costera|Poste de contrôle de la route côtière|海岸道路の検問所", 420, 87),
     prop("War Cemetery Gate|Puerta del cementerio de guerra|Porte du cimetière de guerre|戦没者墓地の門", 220, 45)],
  ),

  // ---------------------------------------------------------------------
  // valley — 中部エジプトのナイル渓谷
  // ---------------------------------------------------------------------
  benisuef: city(
    "Beni Suef|Beni Suef|Beni Souef|ベニ・スエフ",
    31.10, 29.07, "valley", "cementplant", "quarrytown", "l",
    "Limestone hills that fed a construction boom|Colinas calizas que alimentaron un auge de la construcción|Des collines calcaires qui alimentèrent un boom de la construction|建設ブームを支えた石灰岩の丘",
    "The limestone hills flanking Beni Suef made it one of Egypt's biggest cement-producing centres, with several large plants supplying much of the concrete used in the country's construction boom of recent decades. Just west of the city, the ancient Bahr Yussef canal branches off toward the Faiyum depression, an artificial watercourse that has carried irrigation water inland for so long that its exact age is debated by historians.|Las colinas calizas que flanquean Beni Suef la convirtieron en uno de los mayores centros productores de cemento de Egipto, con varias plantas grandes que suministran buena parte del hormigón usado en el auge constructivo del país en las últimas décadas. Justo al oeste de la ciudad, el antiguo canal Bahr Yusef se desvía hacia la depresión de Fayum, un curso de agua artificial que lleva tanto tiempo transportando agua de riego tierra adentro que los historiadores debaten su edad exacta.|Les collines calcaires bordant Beni Souef en firent l'un des plus grands centres producteurs de ciment d'Égypte, avec plusieurs grandes usines fournissant une bonne part du béton utilisé dans le boom de la construction du pays ces dernières décennies. Juste à l'ouest de la ville, l'antique canal du Bahr Youssef bifurque vers la dépression du Fayoum, un cours d'eau artificiel qui achemine l'eau d'irrigation vers l'intérieur des terres depuis si longtemps que les historiens débattent encore de son âge exact.|ベニ・スエフを縁取る石灰岩の丘は、この街をエジプト屈指のセメント生産拠点にした。いくつもの大工場が、近年の建設ブームで使われるコンクリートの多くを供給している。街のすぐ西では、古くからのバハル・ユースフ運河がファイユーム低地へと分かれていく。この人工の水路は、あまりに長く内陸へ灌漑用水を運んできたため、正確な築造年代は歴史家のあいだでも議論が分かれる。",
    [prop("Cement Kiln Yard|Patio del horno de cemento|Cour du four à ciment|セメント窯の作業場", 480, 99),
     prop("Bahr Yussef Canal Bridge|Puente sobre el canal Bahr Yusef|Pont sur le canal Bahr Youssef|バハル・ユースフ運河の橋", 260, 54)],
  ),
  minya: city(
    "Minya|Minya|Minya|ミンヤー",
    30.74, 28.11, "valley", "sugarmill", "agroindustry", "r",
    "A sugar mill from 1881, and a mixed community it still serves|Un ingenio azucarero de 1881, y una comunidad mixta a la que aún sirve|Une sucrerie de 1881, et une communauté mixte qu'elle sert encore|1881年創業の製糖工場と、いまも支える多宗教の町",
    "Minya's sugar factory, founded in 1881, was one of Egypt's earliest large industrial sugar mills, processing cane grown on estates nearby that had shifted from cotton once refining technology made sugar more profitable. The governorate today has one of the country's highest shares of Coptic Christians alongside a Muslim majority, and its rail-served market towns still largely run on the same agricultural rhythm the sugar and cotton economy set more than a century ago.|La fábrica de azúcar de Minya, fundada en 1881, fue uno de los primeros grandes ingenios industriales de Egipto, que procesaba caña cultivada en fincas cercanas que habían pasado del algodón al azúcar cuando la tecnología de refinado lo hizo más rentable. La provincia tiene hoy una de las mayores proporciones de cristianos coptos del país junto a una mayoría musulmana, y sus pueblos mercado, servidos por ferrocarril, siguen funcionando en gran medida con el ritmo agrícola que fijó la economía del azúcar y el algodón hace más de un siglo.|La sucrerie de Minya, fondée en 1881, fut l'une des premières grandes usines sucrières industrielles d'Égypte, traitant la canne cultivée sur des domaines voisins qui étaient passés du coton au sucre lorsque la technologie de raffinage rendit celui-ci plus rentable. La province compte aujourd'hui l'une des plus fortes proportions de chrétiens coptes du pays aux côtés d'une majorité musulmane, et ses villes marchandes desservies par le rail fonctionnent encore largement au rythme agricole fixé par l'économie du sucre et du coton il y a plus d'un siècle.|1881年創業のミンヤーの製糖工場は、エジプト最初期の大規模な工業的製糖所の一つだった。精製技術が砂糖をより儲かる作物にすると、綿花から切り替えた近隣の農園で育てられたサトウキビを加工した。この県はいまもムスリムが多数を占める一方、国内でも指折り高い割合のコプト・キリスト教徒を抱えている。鉄道の通う市場町の多くは、一世紀以上前に砂糖と綿花の経済が定めた農業の季節のリズムのままに動いている。",
    [prop("Sugar Mill Weighing Yard|Patio de pesaje del ingenio azucarero|Cour de pesée de la sucrerie|製糖工場の計量場", 560, 115),
     prop("Market Town Grain Store|Almacén de grano del pueblo mercado|Entrepôt à grain de la ville marchande|市場町の穀物倉庫", 300, 62)],
  ),
  faiyum: city(
    "Faiyum|Fayum|Fayoum|ファイユーム",
    30.84, 29.31, "valley", "lake", "oasisfields", "l",
    "A depression fed by a canal, not the river itself|Una depresión alimentada por un canal, no por el río mismo|Une dépression alimentée par un canal, non par le fleuve lui-même|川そのものではなく運河が満たす窪地",
    "Faiyum sits in a natural depression fed by the Bahr Yussef canal rather than the Nile directly, and one of Egypt's earliest railways, a narrow-gauge line built in 1898, once ran through its fields specifically to move sugarcane to processing mills. At the depression's lowest point, Lake Qarun has shrunk and grown steadily saltier over the past century as more of the water that once reached it was diverted onto farmland instead, a slow change still reshaping the fishing villages along its shore.|Fayum se asienta en una depresión natural alimentada por el canal Bahr Yusef y no directamente por el Nilo, y uno de los primeros ferrocarriles de Egipto, una línea de vía estrecha construida en 1898, cruzaba antaño sus campos específicamente para llevar caña de azúcar a los ingenios. En el punto más bajo de la depresión, el lago Qarun se ha ido reduciendo y volviéndose cada vez más salado en el último siglo, a medida que más agua que antes lo alcanzaba se desviaba hacia los campos de cultivo, un cambio lento que aún transforma los pueblos de pescadores de su orilla.|Le Fayoum occupe une dépression naturelle alimentée par le canal du Bahr Youssef plutôt que directement par le Nil, et l'un des premiers chemins de fer d'Égypte, une ligne à voie étroite construite en 1898, traversait autrefois ses champs spécialement pour acheminer la canne à sucre vers les usines. Au point le plus bas de la dépression, le lac Qaroun a rétréci et est devenu de plus en plus salé au cours du siècle dernier, à mesure qu'une part croissante de l'eau qui l'atteignait autrefois était détournée vers les terres agricoles, un lent changement qui transforme encore les villages de pêcheurs de ses rives.|ファイユームは、ナイル川そのものではなくバハル・ユースフ運河から水を得る自然の窪地に位置する。1898年に敷かれた狭軌線という、エジプト最初期の鉄道の一つは、かつて製糖工場へサトウキビを運ぶためだけにこの地の畑を貫いていた。この窪地の最も低い場所にあるカルーン湖は、かつて湖へ届いていた水の多くが農地へ回されるようになったこの一世紀のあいだ縮み続け、塩分も増し続けている。この緩やかな変化は、いまも湖畔の漁村の姿を変え続けている。",
    [prop("Light Railway Cane Wagon|Vagón de caña del ferrocarril ligero|Wagon à canne du chemin de fer léger|軽便鉄道のサトウキビ貨車", 500, 103),
     prop("Lakeside Fishing Jetty|Embarcadero de pesca junto al lago|Jetée de pêche au bord du lac|湖畔の漁の桟橋", 260, 54)],
  ),
  asyut: city(
    "Asyut|Asiut|Assiout|アシュート",
    31.18, 27.18, "valley", "barrage", "nilebarrage", "r",
    "A barrage older than the dam everyone remembers|Una presa de derivación más vieja que la que todos recuerdan|Un barrage plus vieux que celui dont tout le monde se souvient|皆が思い出すダムより古い堰",
    "The Asyut Barrage, built by British engineers in 1902 across the full width of the Nile, was designed not to hold back water like the dams further south but to raise its level just enough to feed the Ibrahimiya Canal, which still irrigates a large share of the farmland running north through Middle Egypt. The city built around it also holds one of Egypt's largest Coptic Christian communities, and each August the nearby Durunka cave monastery's Feast of the Virgin is said to draw well over a million pilgrims who camp in the surrounding caves and hillside for the week.|La presa de derivación de Asiut, construida por ingenieros británicos en 1902 a todo lo ancho del Nilo, no se diseñó para retener el agua como las presas más al sur, sino para elevar su nivel lo justo para alimentar el canal Ibrahimiya, que todavía riega buena parte de las tierras de cultivo que se extienden hacia el norte por el Egipto Medio. La ciudad construida a su alrededor también alberga una de las mayores comunidades cristianas coptas de Egipto, y cada agosto se dice que la fiesta de la Virgen en el cercano monasterio-cueva de Durunka atrae a más de un millón de peregrinos, que acampan durante la semana en las cuevas y la ladera de alrededor.|Le barrage d'Assiout, construit par des ingénieurs britanniques en 1902 sur toute la largeur du Nil, ne fut pas conçu pour retenir l'eau comme les barrages plus au sud, mais pour en relever le niveau juste assez pour alimenter le canal Ibrahimiya, qui irrigue encore une bonne part des terres agricoles s'étendant vers le nord à travers la Moyenne-Égypte. La ville bâtie autour abrite aussi l'une des plus grandes communautés chrétiennes coptes d'Égypte, et chaque août, la fête de la Vierge au monastère-grotte voisin de Dourounka attirerait plus d'un million de pèlerins, qui campent la semaine durant dans les grottes et sur la colline environnante.|1902年にイギリス人技師団がナイル川の全幅にわたって築いたアシュート堰は、もっと南のダム群のように水を堰き止めるためのものではなく、水位をわずかに上げてイブラヒミーヤ運河へ水を送り込むために造られた。この運河はいまも、中部エジプトを北へ貫く農地の広い範囲を灌漑している。その周りに築かれたこの街は、エジプトでも指折りのコプト・キリスト教徒の共同体を抱えてもいる。毎年8月、近郊のドゥルンカの洞窟修道院で開かれる聖母の祭りには、100万人を超える巡礼者が集まるとされ、一週間にわたって周囲の洞窟や丘の斜面で野営する。",
    [prop("Barrage Control House|Casa de control de la presa|Maison de contrôle du barrage|堰の操作室", 420, 86),
     prop("Durunka Monastery Courtyard|Patio del monasterio de Durunka|Cour du monastère de Dourounka|ドゥルンカ修道院の中庭", 240, 49)],
  ),
  sohag: city(
    "Sohag|Sohag|Sohag|ソハーグ",
    31.70, 26.56, "valley", "migrant", "rivertown", "l",
    "Houses built floor by floor, one remittance at a time|Casas construidas piso a piso, giro a giro|Des maisons bâties étage par étage, virement après virement|送金が届くたびに、一階ずつ積み上がる家",
    "Sohag governorate has long had one of the highest rates of labour emigration in Egypt, with generations of men leaving for jobs in the Gulf states or, earlier still, for factory and service work in Cairo and Alexandria. The money sent home has visibly reshaped villages here, funding houses built in stages over years as remittances arrive, often left with exposed, unplastered brick on the upper floors because the family's earner is still working abroad.|La provincia de Sohag lleva mucho tiempo entre las de mayor emigración laboral de Egipto, con generaciones de hombres que se marchan a trabajar a los estados del Golfo o, antes aún, a fábricas y servicios en El Cairo y Alejandría. El dinero enviado a casa ha remodelado visiblemente los pueblos de aquí, financiando casas construidas por etapas a lo largo de los años a medida que llegan las remesas, a menudo con ladrillo visto y sin enlucir en los pisos superiores porque quien sostiene a la familia todavía trabaja en el extranjero.|La province de Sohag connaît depuis longtemps l'un des taux d'émigration de travail les plus élevés d'Égypte, des générations d'hommes partant pour des emplois dans les États du Golfe ou, plus tôt encore, pour des usines et des services au Caire et à Alexandrie. L'argent envoyé au pays a visiblement remodelé les villages d'ici, finançant des maisons bâties par étapes au fil des années à mesure qu'arrivent les envois de fonds, souvent laissées avec des briques nues et non crépies aux étages supérieurs parce que le soutien de famille travaille encore à l'étranger.|ソハーグ県は長らく、エジプトでも指折り高い労働移民の割合を持つ土地である。何世代もの男たちが、湾岸諸国での仕事へ、あるいはさらに前の時代にはカイロやアレクサンドリアでの工場や接客の仕事へと出ていった。故郷に送られた金は、この土地の村々を目に見える形で作り替えてきた。送金が届くたびに何年もかけて段階的に家を建て増すため、上の階はしばしば漆喰も塗られないむき出しの煉瓦のまま残る。一家の稼ぎ手がまだ海外で働いているからである。",
    [prop("Remittance House, Unfinished Floor|Casa de las remesas, piso sin terminar|Maison des transferts, étage inachevé|出稼ぎ送金の家、未完の階", 440, 91),
     prop("Bus Depot to the Gulf|Depósito de autobuses al Golfo|Dépôt de bus vers le Golfe|湾岸行きバスの発着所", 240, 49)],
  ),
  qena: city(
    "Qena|Qena|Qena|キナー",
    32.72, 26.16, "valley", "pottery", "rivertown", "r",
    "Unglazed jars that keep water cool by letting it leak|Cántaros sin esmaltar que enfrían el agua dejándola rezumar|Des jarres non émaillées qui rafraîchissent l'eau en la laissant suinter|染み出させることで水を冷やす、釉薬のない甕",
    "Qena has been a centre of Nile-water jar pottery for centuries, its distinctive porous, unglazed clay vessels — called qulla — prized across Egypt for keeping drinking water naturally cool through slow evaporation. Workshops along the riverbank still fire the jars much as potters here always have, even as plastic bottles and refrigeration have cut deeply into a trade that once supplied nearly every household in the country.|Qena ha sido un centro de la alfarería de cántaros de agua del Nilo durante siglos; sus característicos recipientes de barro poroso y sin esmaltar, llamados qulla, se aprecian en todo Egipto porque mantienen el agua potable fresca de forma natural mediante una lenta evaporación. Los talleres a orillas del río todavía cuecen los cántaros casi igual que siempre lo han hecho los alfareros de aquí, aunque las botellas de plástico y la refrigeración han recortado con fuerza un oficio que antes abastecía a casi todos los hogares del país.|Qena est depuis des siècles un centre de poterie de jarres à eau du Nil, ses récipients d'argile poreuse et non émaillée, appelés qulla, prisés dans toute l'Égypte pour garder l'eau potable naturellement fraîche par lente évaporation. Les ateliers le long de la berge cuisent encore les jarres à peu près comme l'ont toujours fait les potiers d'ici, même si les bouteilles en plastique et la réfrigération ont profondément entamé un artisanat qui approvisionnait autrefois presque tous les foyers du pays.|キナーは何世紀にもわたり、ナイルの水を入れる甕づくりの中心地だった。クッラと呼ばれる、この地特有の多孔質で釉薬を掛けない粘土の器は、ゆっくりとした蒸発によって飲み水を自然に冷やすとして、エジプトじゅうで重宝されてきた。プラスチックボトルと冷蔵庫がこの土地の商いを大きく削り取ったいまも、川岸の工房はほぼ昔ながらのやり方で甕を焼き続けている。かつては国内のほぼすべての家庭がこれを頼りにしていた。",
    [prop("Riverside Pottery Kiln|Horno de alfarería junto al río|Four de potier au bord du fleuve|川辺の陶器窯", 480, 99),
     prop("Water-Jar Loading Dock|Muelle de carga de cántaros|Quai de chargement des jarres|水甕の積み出し場", 260, 54)],
  ),
  naghammadi: city(
    "Nag Hammadi|Nag Hammadi|Nag Hammadi|ナグ・ハンマディ",
    32.24, 26.05, "valley", "smelter", "industrialtown", "l",
    "An aluminium smelter powered by a dam over a hundred kilometres away|Una fundición de aluminio alimentada por una presa a más de cien kilómetros|Une fonderie d'aluminium alimentée par un barrage à plus de cent kilomètres|百キロ余り離れたダムの電力で動くアルミ精錬所",
    "Nag Hammadi is home to Egypt's largest aluminium smelter, built in the 1970s with Soviet technical assistance and powered by electricity carried from the Aswan High Dam over a hundred kilometres upstream. The plant's alumina and coke shipments still arrive mostly by rail, making the town's small station one of the busiest freight stops on the line despite the town's modest size.|Nag Hammadi alberga la mayor fundición de aluminio de Egipto, construida en los años setenta con asistencia técnica soviética y alimentada por electricidad transportada desde la Presa Alta de Asuán, a más de cien kilómetros río arriba. Los envíos de alúmina y coque de la planta todavía llegan sobre todo por ferrocarril, lo que convierte a la pequeña estación del pueblo en una de las paradas de mercancías más activas de la línea pese al modesto tamaño del pueblo.|Nag Hammadi abrite la plus grande fonderie d'aluminium d'Égypte, construite dans les années 1970 avec une assistance technique soviétique et alimentée en électricité acheminée depuis le barrage d'Assouan, à plus de cent kilomètres en amont. Les livraisons d'alumine et de coke de l'usine arrivent encore surtout par rail, faisant de la petite gare de la ville l'un des arrêts de fret les plus actifs de la ligne malgré la taille modeste de la ville.|ナグ・ハンマディには、エジプト最大のアルミニウム精錬所がある。1970年代にソ連の技術支援で建てられ、100キロメートル余り上流のアスワン・ハイダムから送られる電力で動いている。アルミナとコークスの輸送はいまも大半が鉄道によっており、町の小さな駅は、その規模に似合わず路線でも指折り忙しい貨物停車駅になっている。",
    [prop("Aluminium Smelter Floor|Nave de la fundición de aluminio|Atelier de la fonderie d'aluminium|アルミ精錬所の作業場", 380, 78),
     prop("Freight Sidings|Vías de apartadero de mercancías|Voies de garage du fret|貨物側線", 200, 41)],
  ),
  girga: city(
    "Girga|Girga|Girga|ギルガ",
    31.89, 26.34, "valley", "oldtown", "rivertown", "r",
    "A provincial capital the river slowly ate|Una capital provincial que el río se fue comiendo|Une capitale provinciale que le fleuve a lentement dévorée|川がゆっくり呑み込んでいった州都",
    "Girga was the administrative capital of Upper Egypt for much of the Ottoman period, until repeated Nile floods eroded so much of the riverside old town that the seat of government was eventually moved to Sohag in the 19th century. Much of the old provincial city has since vanished into the river, and today's Girga is a smaller town rebuilt back from the eroded bank, its former importance remembered mainly in the outsized scale of a handful of surviving mosques.|Girga fue la capital administrativa del Alto Egipto durante buena parte del periodo otomano, hasta que las repetidas crecidas del Nilo erosionaron tanto el casco antiguo ribereño que la sede de gobierno acabó trasladándose a Sohag en el siglo XIX. Buena parte de la vieja ciudad provincial ha desaparecido desde entonces en el río, y la Girga actual es un pueblo más pequeño, reconstruido tierra adentro desde la orilla erosionada, cuya antigua importancia se recuerda sobre todo en el tamaño desmesurado de un puñado de mezquitas que sobreviven.|Girga fut la capitale administrative de la Haute-Égypte pendant une bonne partie de la période ottomane, jusqu'à ce que des crues répétées du Nil érodent tant la vieille ville riveraine que le siège du gouvernement finit par être transféré à Sohag au XIXe siècle. Une bonne part de l'ancienne cité provinciale a depuis disparu dans le fleuve, et la Girga d'aujourd'hui est une ville plus petite, rebâtie en retrait de la berge érodée, son importance passée se rappelant surtout dans l'ampleur démesurée de quelques mosquées survivantes.|ギルガはオスマン朝時代の大半を通じて上エジプトの行政上の中心地だったが、繰り返すナイルの洪水が川沿いの旧市街をあまりに大きく浸食したため、19世紀にはついに政庁がソハーグへ移された。かつての州都の多くはその後、川に呑まれて姿を消し、いまのギルガは浸食された岸から後退して建て直された小さな町である。その昔の重要さは、いまも残るいくつかのモスクの不釣り合いに大きな規模に、主に見て取れる。",
    [prop("Eroded Riverbank Mosque|Mezquita del banco erosionado|Mosquée de la berge érodée|浸食された河岸のモスク", 260, 54),
     prop("Old Provincial Archive Room|Sala de archivo de la vieja provincia|Salle des archives de l'ancienne province|旧州庁の文書室", 190, 39)],
  ),

  // ---------------------------------------------------------------------
  // upper — 上エジプト南部
  // ---------------------------------------------------------------------
  luxor: city(
    "Luxor|Luxor|Louxor|ルクソール",
    32.64, 25.69, "upper", "relocation", "westbank", "l",
    "A village demolished because it sat on top of the past|Un pueblo demolido porque estaba encima del pasado|Un village démoli parce qu'il se trouvait sur le passé|過去の上に建っていたために取り壊された村",
    "On Luxor's west bank, the government spent from 2006 to 2009 demolishing the village of Old Gurna, whose mudbrick houses had been built for generations directly on and among ancient tombs, and moved its roughly 3,200 households to a purpose-built settlement called New Gurna. Many residents resisted the move for years, arguing they had effectively become the site's caretakers over generations, but the antiquities authority prevailed on the grounds that the village was damaging what lay beneath it.|En la orilla oeste de Luxor, el gobierno pasó de 2006 a 2009 demoliendo el pueblo de Vieja Gurna, cuyas casas de adobe se habían construido durante generaciones directamente sobre y entre antiguas tumbas, y trasladó a sus cerca de 3.200 familias a un asentamiento construido expresamente llamado Nueva Gurna. Muchos residentes se resistieron al traslado durante años, alegando que se habían convertido de hecho en los guardianes del lugar a lo largo de generaciones, pero la autoridad de antigüedades se impuso alegando que el pueblo dañaba lo que había debajo.|Sur la rive ouest de Louxor, le gouvernement passa de 2006 à 2009 à démolir le village de Vieille Gourna, dont les maisons de brique crue avaient été bâties depuis des générations directement sur et parmi d'anciennes tombes, et relogea ses quelque 3 200 foyers dans une localité bâtie pour l'occasion appelée Nouvelle Gourna. De nombreux habitants résistèrent au déplacement pendant des années, affirmant être devenus de fait les gardiens du site au fil des générations, mais l'autorité des antiquités l'emporta au motif que le village endommageait ce qui se trouvait dessous.|ルクソールの西岸で、政府は2006年から2009年にかけて旧グルナ村を取り壊した。この村の日干し煉瓦の家々は、何世代にもわたり古代の墓の真上や周りに直接建てられていた。およそ3200世帯は、ニュー・グルナと呼ばれる新設の集落へ移された。多くの住民は、自分たちこそ何世代もかけてこの遺跡の実質的な番人になってきたのだと訴え、長年移住に抵抗したが、村がその下にあるものを傷めているという理由で、古美術品当局の側が押し切った。",
    [prop("New Gurna Resettlement House|Casa de reasentamiento de Nueva Gurna|Maison de relogement de New Gurna|ニュー・グルナ移住住宅", 1600, 330),
     prop("West Bank Ferry Landing|Embarcadero del transbordador de la orilla oeste|Débarcadère du bac de la rive ouest|西岸行き渡し船の船着場", 850, 175)],
  ),
  edfu: city(
    "Edfu|Edfu|Edfou|エドフ",
    32.87, 24.98, "upper", "canefield", "agroindustry", "r",
    "A railway that appears only for the harvest|Un ferrocarril que solo aparece en la cosecha|Un chemin de fer qui n'apparaît qu'à la récolte|収穫の季節にだけ現れる鉄道",
    "Edfu is ringed by sugarcane fields serviced by a network of narrow-gauge cane railways, small tracks that during the January–April harvest carry cut cane from the fields directly to the mills rather than by road. The seasonal lines are laid, run hard for a few months and partly lifted again once the harvest ends, so Edfu's rail landscape looks different depending on which month a traveller passes through.|Edfu está rodeada de cañaverales de azúcar servidos por una red de ferrocarriles cañeros de vía estrecha, pequeñas vías que durante la cosecha de enero a abril llevan la caña cortada de los campos directamente a los ingenios en lugar de por carretera. Las líneas estacionales se tienden, se usan intensamente durante unos meses y luego se levantan en parte cuando termina la cosecha, así que el paisaje ferroviario de Edfu se ve distinto según el mes en que pase un viajero.|Edfou est ceinte de champs de canne à sucre desservis par un réseau de chemins de fer canniers à voie étroite, de petites voies qui, pendant la récolte de janvier à avril, acheminent la canne coupée des champs directement aux usines plutôt que par la route. Ces lignes saisonnières sont posées, fortement utilisées quelques mois puis partiellement démontées une fois la récolte finie, si bien que le paysage ferroviaire d'Edfou paraît différent selon le mois où un voyageur y passe.|エドフの周りはサトウキビ畑に囲まれ、狭軌のサトウキビ鉄道網に支えられている。1月から4月の収穫期には、これらの小さな線路が刈り取った茎を道路ではなく直接畑から工場へ運ぶ。この季節限定の線路は敷設されて数か月激しく使われたのち、収穫が終わるとまた一部が撤去される。だから旅人がどの月に訪れるかによって、エドフの鉄道の景色はまるで違って見える。",
    [prop("Cane Railway Siding|Apartadero del ferrocarril cañero|Voie de garage du chemin de fer cannier|サトウキビ列車の側線", 340, 70),
     prop("Harvest Season Weigh Station|Báscula de la temporada de cosecha|Poste de pesée de la récolte|収穫期の計量所", 190, 39)],
  ),
  komombo: city(
    "Kom Ombo|Kom Ombo|Kom Ombo|コムオンボ",
    32.93, 24.45, "upper", "paintedhouse", "nubianvillage", "l",
    "More than forty villages built for people who lost theirs|Más de cuarenta pueblos construidos para gente que perdió el suyo|Plus de quarante villages bâtis pour des gens qui avaient perdu le leur|自分たちの村を失った人々のために建てられた、四十を超える村",
    "The plain around Kom Ombo is now home to more than 40 villages built from the 1960s onward for Nubians displaced by the Aswan High Dam's rising waters, laid out in blocks quite unlike the riverside villages their families had lived in for generations. Many households still paint their houses in the bright colours and geometric patterns of the flooded Nubian homeland, a visible thread of continuity carried from a place that now lies at the bottom of Lake Nasser.|La llanura en torno a Kom Ombo alberga hoy más de 40 pueblos construidos desde los años sesenta para los nubios desplazados por las aguas crecientes de la Presa Alta de Asuán, trazados en manzanas muy distintas de los pueblos ribereños en que sus familias habían vivido durante generaciones. Muchos hogares siguen pintando sus casas con los colores vivos y los patrones geométricos de la tierra nubia inundada, un hilo visible de continuidad llevado desde un lugar que ahora yace en el fondo del lago Nasser.|La plaine autour de Kom Ombo abrite aujourd'hui plus de 40 villages bâtis à partir des années 1960 pour les Nubiens déplacés par la montée des eaux du barrage d'Assouan, disposés en îlots bien différents des villages riverains où leurs familles avaient vécu pendant des générations. De nombreux foyers peignent encore leurs maisons dans les couleurs vives et les motifs géométriques de la terre nubienne engloutie, un fil visible de continuité porté depuis un lieu qui repose désormais au fond du lac Nasser.|コムオンボ周辺の平野には、1960年代以降、アスワン・ハイダムの水位上昇で住む場所を追われたヌビアの人々のために築かれた40を超える村がいまも並ぶ。それらは、彼らの家族が何世代も暮らしてきた川沿いの村とはまるで違う、区画整然とした形に配置されている。多くの家庭は、いまも鮮やかな色と幾何学模様でヌビアの故郷そのままに家を塗る。それはいまナセル湖の底に沈む土地から運ばれてきた、目に見えるつながりの糸である。",
    [prop("Painted House Courtyard|Patio de la casa pintada|Cour de la maison peinte|彩色家屋の中庭", 380, 78),
     prop("Resettlement Grid Street|Calle en cuadrícula del reasentamiento|Rue en damier du relogement|移住地の碁盤目の通り", 200, 41)],
  ),
  esna: city(
    "Esna|Esna|Esna|エスナ",
    32.55, 25.29, "upper", "lock", "rivercrossing", "r",
    "A gate on the river narrow enough to cause a queue|Una compuerta en el río tan estrecha que causa colas|Une porte sur le fleuve si étroite qu'elle cause des files d'attente|行列ができるほど狭い、川の水門",
    "The barrage and lock at Esna, first built in 1906 and entirely rebuilt in the 1990s, regulate the Nile's water level for irrigation while also letting river traffic pass — a chokepoint so narrow that cruise ships heading to or from Luxor sometimes queue for hours to lock through. The lock is one of the few points on the river where a slow line of tourist cruise ships and small motorised feluccas wait to pass through the same narrow gate together, a daily reminder of how differently the same stretch of river gets used.|La presa y esclusa de Esna, construida por primera vez en 1906 y reconstruida por completo en los años noventa, regulan el nivel del agua del Nilo para el riego a la vez que dejan pasar el tráfico fluvial, un cuello de botella tan estrecho que los cruceros que van o vienen de Luxor a veces hacen cola horas para esclusar. La esclusa es uno de los pocos puntos del río donde una lenta fila de cruceros turísticos y pequeñas faluchas motorizadas esperan para pasar juntos por la misma compuerta estrecha, un recordatorio diario de lo diferente que puede ser el uso del mismo tramo de río.|Le barrage et l'écluse d'Esna, construits une première fois en 1906 puis entièrement reconstruits dans les années 1990, régulent le niveau du Nil pour l'irrigation tout en laissant passer le trafic fluvial — un goulet si étroit que les bateaux de croisière en route vers ou depuis Louxor font parfois la queue des heures pour s'éclusa. L'écluse est l'un des rares points du fleuve où une lente file de bateaux de croisière touristiques et de petites felouques motorisées attendent ensemble de franchir la même porte étroite, rappel quotidien de la diversité d'usages d'un même tronçon de fleuve.|1906年に最初に建てられ、1990年代に全面的に建て直されたエスナの堰と閘門は、灌漑のためにナイル川の水位を調整すると同時に、川の交通も通す。あまりに狭い難所のため、ルクソールへ向かう、あるいはそこから来るクルーズ船が閘門を通過するのに何時間も列を作ることがある。この閘門は川の中でも数少ない、観光クルーズ船のゆっくりとした列と小さなモーター付きファルーカが同じ狭い門を一緒に通ろうと待つ場所であり、同じ一区間の川がいかに違う使われ方をしているかを日々見せつけている。",
    [prop("Barrage Lock Gate|Compuerta de la esclusa de la presa|Porte de l'écluse du barrage|堰の水門", 360, 74),
     prop("Felucca Queue Mooring|Amarradero de la cola de faluchas|Mouillage de la file de felouques|ファルーカの順番待ち係留所", 200, 41)],
  ),
  aswan: city(
    "Aswan|Asuán|Assouan|アスワン",
    32.90, 24.09, "upper", "dam", "nubianshore", "l",
    "A dam that moved a people before it moved water|Una presa que desplazó a un pueblo antes que al agua|Un barrage qui a déplacé un peuple avant l'eau|水より先に、人を動かしたダム",
    "When the reservoir behind the Aswan High Dam began filling in the 1960s, it drowned the ancestral Nubian homeland upstream, and an estimated 50,000 or more Egyptian Nubians had to leave villages their families had lived in for generations to be resettled in newly built towns near Kom Ombo, on land that had never been theirs. To save the area's largest monuments from the same rising water, an international UNESCO campaign spent most of that decade cutting temples into numbered blocks and reassembling them higher up the bank — a rescue that saved the buildings but could not save the villages around them.|Cuando el embalse de la Presa Alta de Asuán empezó a llenarse en los años sesenta, anegó la tierra ancestral nubia río arriba, y se calcula que 50.000 nubios egipcios o más tuvieron que abandonar aldeas donde sus familias habían vivido por generaciones para ser reasentados en pueblos de nueva construcción cerca de Kom Ombo, en tierras que nunca habían sido suyas. Para salvar los monumentos más grandes de la zona de la misma crecida, una campaña internacional de la UNESCO pasó casi toda esa década cortando templos en bloques numerados y reconstruyéndolos más arriba en la orilla, un rescate que salvó los edificios pero no pudo salvar las aldeas que los rodeaban.|Quand le réservoir du barrage d'Assouan a commencé à se remplir dans les années 1960, il a englouti la terre ancestrale nubienne en amont, et l'on estime que 50 000 Nubiens égyptiens ou plus ont dû quitter des villages où leurs familles vivaient depuis des générations pour être relogés dans des villes nouvellement construites près de Kom Ombo, sur des terres qui n'avaient jamais été les leurs. Pour sauver les plus grands monuments de la région de la même montée des eaux, une campagne internationale de l'UNESCO a passé presque toute cette décennie à découper des temples en blocs numérotés et à les remonter plus haut sur la rive — un sauvetage qui a préservé les bâtiments mais pas les villages qui les entouraient.|1960年代、アスワン・ハイダムの貯水池が水を溜め始めると、その上流にあったヌビア人の故郷は水底に沈んだ。推定5万人以上のエジプト系ヌビア人が、先祖代々暮らしてきた村を離れ、コムオンボ近郊に新しく建てられた町へ移り住まざるを得なかった。移り住んだ先の土地は、彼らのものだったことは一度もない。同じ水位上昇からこの地域最大級の遺跡を救うため、ユネスコの国際的な救済事業はその十年のほとんどを、神殿を番号付きのブロックに切り分けては岸のより高い場所に組み直す作業に費やした。この救済は建物こそ救ったが、その周りにあった村々までは救えなかった。",
    [prop("High Dam Overlook|Mirador de la Presa Alta|Belvédère du haut barrage|ハイダム展望台", 900, 185),
     prop("New Nubia Guesthouse|Casa de huéspedes de la Nueva Nubia|Maison d'hôtes de la Nouvelle Nubie|ニュー・ヌビアの民宿", 500, 103)],
  ),
  daraw: city(
    "Daraw|Daraw|Daraw|ダラウ",
    32.80, 24.30, "upper", "camelmarket", "desertmarket", "r",
    "The end of a forty-day walk from Sudan|El final de una caminata de cuarenta días desde Sudán|La fin d'une marche de quarante jours depuis le Soudan|スーダンからの四十日の道のりの終着点",
    "Daraw hosts one of Egypt's largest camel markets, the modern terminus of the old Forty Days Road, a desert trade route along which herders once drove camels up from Sudan over roughly forty days to be sold here. Trucks have replaced most of the overland droving in recent decades, but the Tuesday market still draws buyers from across Upper Egypt, and the animals sold here move onward mostly by road rather than the rail line that runs right past the town.|Daraw acoge uno de los mayores mercados de camellos de Egipto, la terminal moderna del antiguo Camino de los Cuarenta Días, una ruta comercial del desierto por la que los pastores solían conducir camellos desde Sudán durante unos cuarenta días para venderlos aquí. Los camiones han sustituido la mayor parte del arreo por tierra en las últimas décadas, pero el mercado de los martes todavía atrae compradores de todo el Alto Egipto, y los animales vendidos aquí siguen su camino sobre todo por carretera y no por la vía férrea que pasa justo junto al pueblo.|Daraw accueille l'un des plus grands marchés aux chameaux d'Égypte, le terminus moderne de l'ancienne route des Quarante Jours, une piste caravanière désertique le long de laquelle des éleveurs menaient autrefois des chameaux depuis le Soudan pendant environ quarante jours pour les vendre ici. Les camions ont remplacé l'essentiel du convoyage terrestre ces dernières décennies, mais le marché du mardi attire encore des acheteurs de toute la Haute-Égypte, et les bêtes vendues ici repartent surtout par la route plutôt que par la voie ferrée qui passe pourtant juste à côté de la ville.|ダラウにはエジプト屈指のラクダ市が立つ。これは、かつて牧夫たちがスーダンからおよそ40日かけてラクダを追い上げてここで売った、古い「四十日路」という砂漠の交易路の現代の終着点である。近年は陸路での追い立てのほとんどがトラックに取って代わられたが、火曜の市はいまも上エジプトじゅうから買い手を集めている。ここで売られる家畜は、町のすぐそばを通る鉄道ではなく、主に道路で運ばれていく。",
    [prop("Tuesday Camel Market Pen|Corral del mercado de camellos de los martes|Enclos du marché aux chameaux du mardi|火曜のラクダ市の囲い", 220, 45),
     prop("Forty Days Road Waystation|Posta del camino de los cuarenta días|Relais de la route des quarante jours|四十日路の宿駅", 190, 39)],
  ),
};

/**
 * 路線(全41都市)。芯のテーマどおり、カイロが1本の幹線に絞られ、
 * デルタへ扇状に、渓谷を南へ、運河沿いに東へ分かれていく形にしてある。
 */
export const EGYPT_EDGES = [
  // cairo 内・周辺
  ["cairo", "giza"],
  ["cairo", "shubraelkheima"],
  ["cairo", "helwan"],
  ["cairo", "newcapital"],
  // cairo → delta(幹線が一本に絞られてから扇状に分かれる)
  ["cairo", "qanater"],
  ["qanater", "banha"],
  ["banha", "zagazig"],
  ["zagazig", "mansoura"],
  ["mansoura", "damietta"],
  ["mansoura", "zefta"],
  ["zefta", "mitghamr"],
  ["mitghamr", "tanta"],
  ["tanta", "mahalla"],
  ["mahalla", "kafrelzayat"],
  ["kafrelzayat", "damanhur"],
  ["damanhur", "kafreldawwar"],
  ["kafreldawwar", "alexandria"],
  ["damanhur", "rosetta"],
  ["tanta", "kafrelsheikh"],
  // cairo → canal(スエズ運河沿い)
  ["cairo", "ismailia"],
  ["ismailia", "qantara"],
  ["qantara", "portsaid"],
  ["ismailia", "suez"],
  // alexandria → medit(西の地中海沿岸)
  ["alexandria", "eldabaa"],
  ["eldabaa", "marsamatruh"],
  ["marsamatruh", "elalamein"],
  // cairo → valley → upper(渓谷を南へ)
  ["cairo", "benisuef"],
  ["benisuef", "faiyum"],
  ["benisuef", "minya"],
  ["minya", "asyut"],
  ["asyut", "sohag"],
  ["sohag", "girga"],
  ["girga", "qena"],
  ["qena", "naghammadi"],
  ["naghammadi", "luxor"],
  ["luxor", "esna"],
  ["esna", "edfu"],
  ["edfu", "komombo"],
  ["komombo", "daraw"],
  ["daraw", "aswan"],
];
